### ISSUE TITLE
(387 != 388) (is True ;-)

### ISSUE THREAD

**Issue by TobiasRzepka** [davidhalter/jedi#1000]
Hello David, this one was harder to catch...
If changing some code I got
```
0.11.1
C:\Python27\lib\site-packages\jedi\evaluate\imports.py:263: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if os.path.basename(path) == self.str_import_path[0]:
Traceback (most recent call last):
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\Test\5. Exception wenn mehrere ─nderungen\jedi_test_exceptions.py", line 21, in <module>
    completions = jedi.Script(source, 366, 45, "cmd").completions()
  File "C:\Python27\lib\site-packages\jedi\api\__init__.py", line 155, in completions
    self._evaluator, self._get_module(), self._code_lines,
  File "C:\Python27\lib\site-packages\jedi\cache.py", line 118, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\jedi\api\__init__.py", line 133, in _get_module
    self._get_module_node(),
  File "C:\Python27\lib\site-packages\jedi\cache.py", line 118, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\jedi\api\__init__.py", line 126, in _get_module_node
    cache_path=settings.cache_directory
  File "C:\Python27\lib\site-packages\parso\grammar.py", line 77, in parse
    return self._parse(code=code, **kwargs)
  File "C:\Python27\lib\site-packages\parso\grammar.py", line 127, in _parse
    new_lines=lines
  File "C:\Python27\lib\site-packages\parso\python\diff.py", line 163, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (387 != 388) with the diff parser. Please report:
---
+++
@@ -384,4 +384,5 @@
             self.__documentationViewer.documentationReady(
                 msg, isDocWarning=True)
         else:
-            self.__documentationViewer.documentationReady(docu)+            self.__documentationViewer.documentationReady(docu)
+
```
Test code and exception message are in the zip file.
[387 not equal 388.zip](https://github.com/davidhalter/jedi/files/1492916/387.not.equal.388.zip)

(I hope this time it suites better, than only adding some files... ?)
Tobias

**Comment by davidhalter** [comment]
Good find. Thanks! To understand a bit better what led to this, can you describe a bit what you did? Can you even reproduce it? I understand that this is probably not easy. But I'm very interested in fixing those parso bugs.

**Comment by TobiasRzepka** [comment]
Hehe, looks like you've overlooked the zip file at the end of my post. Basically I've renamed something and once a time it was gladfully reproducible...

**Comment by davidhalter** [comment]
I've seen the zip file. Thanks for that!

The problem with this bug is basically that it's hard to reproduce. I would have to try around for an hour or so to maybe find it. It's really not that easy ;) So any ideas where you tried to rename something?

**Comment by TobiasRzepka** [comment]
Ok. I've changed "codet" to "coded" in line 366 col. 45. Before and after it was tried to autocomplete the string. If you're running jedi_test_exceptions.py (JediCompleter.py needs to be in the same directory), you should easily get the error.

**Comment by davidhalter** [comment]
Awesome! Thanks so much.

**Comment by davidhalter** [comment]
Fixed in parso.

Thanks so much for this report. That's worth gold :)

**Comment by TobiasRzepka** [comment]
And not so easy to find. After the report I didn't noticed it again.
And I have to thank you for this great tool!
