### ISSUE TITLE
Crash on Win10: "import sy" completion

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1003]
I ll try to make repro script.
Currently i see it in CudaText plugin PythonIntel, Py 3.5.4 x64, Win10, Jedi 0.11.1

new file, I type "import sy" and press Ctrl+Space.
```
Traceback (most recent call last):
  File "C:\cudatext\py\cuda_python_intel\jedi\cache.py", line 116, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\cudatext\py\cuda_python_intel\__init__.py", line 39, in on_complete
    text = handle_autocomplete(*params)
  File "C:\cudatext\py\cuda_python_intel\intel_work.py", line 16, in handle_autocomplete
    if hasattr(c, 'params'):
  File "C:\cudatext\py\cuda_python_intel\jedi\cache.py", line 118, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\jedi\api\classes.py", line 345, in params
    followed = list(self._name.infer())
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 162, in infer
    level=self._level,
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 276, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 383, in _do_import
    module = _load_module(self._evaluator, module_path, code, sys_path, parent_module)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 489, in _load_module
    cache_path=settings.cache_directory)
  File "C:\cudatext\py\cuda_python_intel\parso\grammar.py", line 77, in parse
    return self._parse(code=code, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\parso\grammar.py", line 106, in _parse
    code = python_bytes_to_unicode(code)
  File "C:\cudatext\py\cuda_python_intel\parso\utils.py", line 89, in python_bytes_to_unicode
    return unicode(source, encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 10-11: invalid continuation byte
```

**Comment by Alexey-T** [comment]
It's causes inside "if hasattr(c, 'params')"
and i can rewrite code to hide it.

Now i see the same crash in other place:
```import os
os.pa``` (Ctrl+Space)

```
Python 3.5.4
Loading toolbar config
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\cudatext\py\cuda_python_intel\__init__.py", line 39, in on_complete
    text = handle_autocomplete(*params)
  File "C:\cudatext\py\cuda_python_intel\intel_work.py", line 10, in handle_autocomplete
    completions = script.completions()
  File "C:\cudatext\py\cuda_python_intel\jedi\api\__init__.py", line 158, in completions
    completions = completion.completions()
  File "C:\cudatext\py\cuda_python_intel\jedi\api\completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "C:\cudatext\py\cuda_python_intel\jedi\api\completion.py", line 198, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "C:\cudatext\py\cuda_python_intel\jedi\api\completion.py", line 233, in _trailer_completions
    contexts = evaluate_call_of_leaf(evaluation_context, previous_leaf)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\helpers.py", line 74, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\base_context.py", line 123, in eval_node
    return self.evaluator.eval_element(self, node)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\__init__.py", line 179, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\__init__.py", line 191, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\__init__.py", line 195, in _eval_element_cached
    return eval_node(context, element)
  File "C:\cudatext\py\cuda_python_intel\jedi\debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\syntax_tree.py", line 46, in wrapper
    return func(context, *args, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\syntax_tree.py", line 58, in eval_node
    return eval_atom(context, element)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\syntax_tree.py", line 172, in eval_atom
    search_global=True
  File "C:\cudatext\py\cuda_python_intel\jedi\_compatibility.py", line 204, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\base_context.py", line 140, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "C:\cudatext\py\cuda_python_intel\jedi\debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\finder.py", line 64, in find
    types = self._names_to_types(names, attribute_lookup)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\finder.py", line 157, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "C:\cudatext\py\cuda_python_intel\jedi\common\context.py", line 34, in from_sets
    sets = list(sets)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\finder.py", line 157, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\filters.py", line 100, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\syntax_tree.py", line 485, in tree_name_to_contexts
    types = imports.infer_import(context, tree_name)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 61, in infer_import
    types = importer.follow()
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 276, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 383, in _do_import
    module = _load_module(self._evaluator, module_path, code, sys_path, parent_module)
  File "C:\cudatext\py\cuda_python_intel\jedi\evaluate\imports.py", line 489, in _load_module
    cache_path=settings.cache_directory)
  File "C:\cudatext\py\cuda_python_intel\parso\grammar.py", line 77, in parse
    return self._parse(code=code, **kwargs)
  File "C:\cudatext\py\cuda_python_intel\parso\grammar.py", line 106, in _parse
    code = python_bytes_to_unicode(code)
  File "C:\cudatext\py\cuda_python_intel\parso\utils.py", line 89, in python_bytes_to_unicode
    return unicode(source, encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 17: invalid continuation byte
```

It is some error in caching system? 
I added "print(repr(source))" in parso/utils.py before line 89, and it printed contents of some ZIP file with "PK" at begin. It tries to convert it to Unicode string. And crashes.

**Comment by Alexey-T** [comment]
And it's not visible if I run it in test script (in cmd.exe).

**Comment by davidhalter** [comment]
Hmm we probably need to catch UnicodeDecodeError and just ignore those files.

**Comment by Alexey-T** [comment]
I tested to add "try..except" around 2 "unciode()" calls - where crash. It masked crash, but now Jedi cannot find completions for
```
import os
os.pa
```
This is only inside CudaText Win32, no error in separate py script.

**Comment by davidhalter** [comment]
Is your os.py file utf-8 encoded?

**Comment by Alexey-T** [comment]
os.py? I don't have it- i have portable Python DLL, it is python35.zip, it has os.pyc. It is compiled python code.

**Comment by Alexey-T** [comment]
https://www.python.org/ftp/python/3.5.4/python-3.5.4-embed-amd64.zip

**Comment by Alexey-T** [comment]
And maybe good-
replace in parso/utils.py, line51, `errors='strict'` to `errors='replace'`

**Comment by davidhalter** [comment]
It should be fixed now. I have also tested it. I made it possible to deal with non-unicode encodings (just replaced the characters that were wrong).

**Comment by Alexey-T** [comment]
Thank you for this fixing.
