### ISSUE TITLE
Error when getting the docstring of a parameter from the names method

### ISSUE THREAD

**Issue by micbou** [davidhalter/jedi#1006]
Running the code 
```python
import jedi
jedi.names("def test(param): pass")[1].docstring()
```
raises the following error:
```python
Traceback (most recent call last):
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\cache.py", line 116, in wrapper
    return dct[key]
KeyError: ((), frozenset({('fast', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    jedi.names("def test(param): pass")[1].docstring()
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\api\classes.py", line 257, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\api\classes.py", line 675, in docstring
    for context in self._get_contexts(fast=fast):
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\cache.py", line 118, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\api\classes.py", line 665, in _get_contexts
    return self._name.infer()
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\evaluate\filters.py", line 100, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\evaluate\syntax_tree.py", line 495, in tree_name_to_contexts
    raise ValueError("Should not happen.")
ValueError: Should not happen.
```
Looks like the `param` case is missing in [the `tree_name_to_contexts` function](https://github.com/davidhalter/jedi/blob/6ee361864c6ddb26a2f229b0f69fb0fb14acc6b6/jedi/evaluate/syntax_tree.py#L444).

Configuration:
 - Windows 7 64-bit;
 - Jedi https://github.com/davidhalter/jedi/commit/6ee361864c6ddb26a2f229b0f69fb0fb14acc6b6;
 - Parso https://github.com/davidhalter/parso/commit/0dea94c801a7e135dccb3911a59b8c942641f7ad;
 - Python 2.7.14 and 3.6.2.

**Comment by davidhalter** [comment]
Thank for reporting this issue!
