### ISSUE TITLE
Completion error "No such file 'rb'" in CudaText plugin

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1030]
CudaText plugin-- Python Intel
with updated Jedi 0.12.0 (last on github)
with last Parso (master on github)

I opened py source of "Find in Files" plugin,
cd_fif_api.py:1389

    def is_birary_file(path:str, blocksize=BLOCKSIZE, def_ans=None)->bool:
        if not os.path.isfile(path):    return def_ans
        try:
            block   = open(path, 'br').read(blocksize)
            if not      block:  return False
            if b'\0' in block:  return True
            return bool(block.translate(None, TEXTCHARS)) ##########caret here after "block.tr"
			
I press ctrl+space after "block.tr"

```
Python 3.5.3
Loading toolbar config
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_python_intel/__init__.py", line 39, in on_complete
    text = handle_autocomplete(*params)
  File "/home/user/.cudatext/py/cuda_python_intel/intel_work.py", line 10, in handle_autocomplete
    completions = script.completions()
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/api/__init__.py", line 149, in completions
    completions = completion.completions()
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/api/completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/api/completion.py", line 198, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/api/completion.py", line 233, in _trailer_completions
    contexts = evaluate_call_of_leaf(evaluation_context, previous_leaf)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/helpers.py", line 74, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/base_context.py", line 123, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 181, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 193, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 197, in _eval_element_cached
    return eval_node(context, element)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 46, in wrapper
    return func(context, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 58, in eval_node
    return eval_atom(context, element)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 172, in eval_atom
    search_global=True
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/_compatibility.py", line 194, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/base_context.py", line 140, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/finder.py", line 64, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/finder.py", line 157, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/finder.py", line 157, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/filters.py", line 100, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 479, in tree_name_to_contexts
    types = _remove_statements(evaluator, context, node, tree_name)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 441, in _remove_statements
    return eval_expr_stmt(context, stmt, seek_name=name)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 46, in wrapper
    return func(context, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 225, in eval_expr_stmt
    return _eval_expr_stmt(context, stmt, seek_name)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 241, in _eval_expr_stmt
    context_set = context.eval_node(rhs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/base_context.py", line 123, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 181, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 193, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 197, in _eval_element_cached
    return eval_node(context, element)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 46, in wrapper
    return func(context, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    context_set = eval_atom(context, first_child)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/syntax_tree.py", line 172, in eval_atom
    search_global=True
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/_compatibility.py", line 194, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/base_context.py", line 140, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/finder.py", line 56, in find
    names = self.filter_name(filters)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/finder.py", line 120, in filter_name
    for filter in filters:
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/filters.py", line 424, in get_global_filters
    origin_scope=origin_scope):
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/context/module.py", line 62, in get_filters
    for star_module in self.star_imports():
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/context/module.py", line 74, in star_imports
    new = infer_import(self, name)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/imports.py", line 61, in infer_import
    types = importer.follow()
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/imports.py", line 276, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/imports.py", line 308, in _do_import
    bases = self._do_import(import_path[:-1], sys_path)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/imports.py", line 384, in _do_import
    module = _load_module(self._evaluator, module_path, code, sys_path, parent_module)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/imports.py", line 490, in _load_module
    cache_path=settings.cache_directory)
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 373, in parse
    return self.parse_and_get_code(*args, **kwargs)[0]
  File "/home/user/.cudatext/py/cuda_python_intel/jedi/evaluate/__init__.py", line 366, in parse_and_get_code
    with open('rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'rb'
```

maybe filename missed?

**Comment by davidhalter** [comment]
Yeah sorry. I realized it a few hours ago. It's already fixed. Pushed garbaged to master. A reminder to myself that I should always run the tests.
