### ISSUE TITLE
Jedi healthcheck fails - no attribute sys_path

### ISSUE THREAD

**Issue by aenda** [davidhalter/jedi#1098]
Jedi is working fine for me, but I believe there is an error in the check health function that causes it to incorrectly fail. Using:
```
Neovim version NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
with most recent jedi release on arch and with minimal vimrc (just vim-plug loading jedi).

Output:
```
## jedi
Error detected while processing function health#jedi#check[2]..jedi#debug_info[28]..provider#python3#Call:

line   18:
Traceback (most recent call last):
  File "/home/gmend/.dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 37, in display_debug_
info
    sys_path = script_evaluator.project.sys_path
AttributeError: 'Project' object has no attribute 'sys_path'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/gmend/.dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 39, in display_debug_
info
    sys_path = script_evaluator.sys_path
AttributeError: 'Evaluator' object has no attribute 'sys_path'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gmend/.dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 44, in display_debug_
info
    "{0!r})".format(e))
  File "/home/gmend/.dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 8, in echo
    vim.command('echo {0}'.format(msg))
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 242, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 140, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim(echo):E117: Unknown function: AttributeError'
Error detected while processing function health#jedi#check[2]..jedi#debug_info:
line   28:
E171: Missing :endif
```

**Comment by davidhalter** [comment]
It's fixed in the virtualenv branch. I just have to fix the tests there to get it merged.

**Comment by davidhalter** [comment]
Also this is the wrong issue tracker. This issue would have belonged into the jedi-vim tracker.
