### ISSUE TITLE
During handling of the above exception, another exception occurred: 

### ISSUE THREAD

**Issue by ly973021784** [davidhalter/jedi#1101]
Hello David,
this one is a little special. If you run it on Py 2.7 you got a normal stack trace. But on Py 3.5 you got additionally the "During handling of the above exception, another exception occurred:" message. I know, it doesn't make it easier.

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\absl\flags\_flag.py", line 166, in _parse
    return self.parser.parse(argument)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\absl\flags\_argument_parser.py", line 292, in parse
    raise ValueError('Non-boolean argument to boolean flag', argument)
ValueError: ('Non-boolean argument to boolean flag', 128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\tersonflow\Chinese_rec.py", line 38, in <module>
    tf.app.flags.DEFINE_boolean('batch_size', 128, 'Validation batch size')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\flags.py", line 57, in wrapper
    return original_function(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\absl\flags\_defines.py", line 267, in DEFINE_boolean
    DEFINE_flag(_flag.BooleanFlag(name, default, help, **args),
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\absl\flags\_flag.py", line 293, in __init__
    p, None, name, default, help, short_name, 1, **args)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\absl\flags\_flag.py", line 107, in __init__
    self._set_default(default)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\absl\flags\_flag.py", line 196, in _set_default
    self.default = self._parse(value)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\absl\flags\_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --batch_size=128: ('Non-boolean argument to boolean flag', 128)

**Comment by davidhalter** [comment]
> I know, it doesn't make it easier.

It actually makes it easier if you know what it means :)

This is not a jedi issue. Ther is no jedi in there. This is all about tensorflow or other packages. Sorry cannot help you here :) Just look at the traceback.

**Comment by ly973021784** [comment]
Thank you very much for your help
