### ISSUE TITLE
jedi.create_environment fails when using Anaconda

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#1114]
* Path to anaconda executable = `'C:\ProgramData\Anaconda3\python.exe`
* The following code fails:
```python
import jedi
jedi.create_environment("C:/ProgramData/Anaconda3/python.exe")
```

**Error:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dojayama.REDMOND\.vscode-insiders\extensions\pythonVSCode\pythonFiles\jedi\api\environment.py", line 295, in create_environment
    return Environment(path, _get_executable_path(path, safe=safe))
  File "C:\Users\dojayama.REDMOND\.vscode-insiders\extensions\pythonVSCode\pythonFiles\jedi\api\environment.py", line 308, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: C:/ProgramData/Anaconda3/python.exe\Scripts\python.exe seems to be missing.
```

**Comment by micbou** [comment]
This should work in the latest version of Jedi: the `create_environment` function didn't accept an executable path before PR https://github.com/davidhalter/jedi/pull/1088.

**Comment by davidhalter** [comment]
@DonJayamanne Can you test with latest? I'll reopen if it's still an issue.
