### ISSUE TITLE
Completing f-strings crashes jedi

### ISSUE THREAD

**Issue by fbergroth** [davidhalter/jedi#1141]
```
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.Script("f'xyz'.").completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.6/site-packages/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "venv/lib/python3.6/site-packages/jedi/api/completion.py", line 98, in completions
    completion_names = self._get_context_completions()
  File "venv/lib/python3.6/site-packages/jedi/api/completion.py", line 197, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "venv/lib/python3.6/site-packages/jedi/api/completion.py", line 232, in _trailer_completions
    contexts = evaluate_call_of_leaf(evaluation_context, previous_leaf)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/helpers.py", line 73, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "venv/lib/python3.6/site-packages/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 146, in eval_node
    return eval_or_test(context, element)
  File "venv/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 337, in eval_or_test
    iterator = iter(or_test.children)
AttributeError: 'FStringEnd' object has no attribute 'children'
```

**Comment by davidhalter** [comment]
Thanks for finding this one!
