### ISSUE TITLE
AttributeError: 'PythonNode' object has no attribute 'value'

### ISSUE THREAD

**Issue by TobiasRzepka** [davidhalter/jedi#1146]
Hi, here is another AttributeError when not editing top-down (chars isn't defined at completion call):
`jedi.Script("[','.join(str(x.value) for x in chars]", 1, 37).completions()`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jedi\api\__init__.py", line 174, in completions
    completions = completion.completions()
  File "jedi\api\completion.py", line 98, in completions
    completion_names = self._get_context_completions()
  File "jedi\api\completion.py", line 203, in _get_context_completions
    call_signatures = self._call_signatures_method()
  File "jedi\api\__init__.py", line 279, in call_signatures
    helpers.get_call_signature_details(self._module_node, self._pos)
  File "jedi\api\helpers.py", line 270, in get_call_signature_details
    result = _get_call_signature_details_from_error_node(n, position)
  File "jedi\api\helpers.py", line 243, in _get_call_signature_details_from_error_node
    *_get_index_and_key(children, position)
  File "jedi\api\helpers.py", line 223, in _get_index_and_key
    key_str = last.children[0].value
AttributeError: 'PythonNode' object has no attribute 'value'
```
jedi / parso are the latest snapshots.
Tobias

**Comment by davidhalter** [comment]
Fixed in 8ffdf67
