### ISSUE TITLE
Infinite recursion in jedi.evaluate

### ISSUE THREAD

**Issue by ethframe** [davidhalter/jedi#1173]
This code:

```python
import jedi

jedi.Script("""
class A:
    def a(self, b):
        for i in [self.a(i) for i in b]:
            i.
""", line=5, column=14).completions()
```

raises a `RecursionError` in `jedi.evaluate`:

```
Traceback (most recent call last):
  File "jedi\evaluate\syntax_tree.py", line 543, in tree_name_to_contexts
    types = context.predefined_names[node][tree_name.value]
KeyError: <ForStmt: for i in [s.a(i) for i in b]:             i.@4,8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jedi\evaluate\syntax_tree.py", line 543, in tree_name_to_contexts
    types = context.predefined_names[node][tree_name.value]
KeyError: <CompFor: for i in b@4,25>

...

  File "jedi\evaluate\base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "jedi\evaluate\__init__.py", line 127, in eval_element
    return eval_node(context, element)
  File "jedi\debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "jedi\evaluate\syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "jedi\evaluate\syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "jedi\evaluate\syntax_tree.py", line 202, in eval_atom
    search_global=True
  File "jedi\_compatibility.py", line 263, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
RecursionError: maximum recursion depth exceeded
```
CPython 3.6.3 x64, jedi 0.12.1, parso 0.3.1

**Comment by davidhalter** [comment]
Thanks a lot for the simple reproduction case, usually I just get stack traces. This is obviously a bug.

BTW: I think this is a pretty smart way to trick Jedi into endless recursion :)

**Comment by davidhalter** [comment]
Thank you for the report!
