### ISSUE TITLE
Exception when getting completions for mxnet package

### ISSUE THREAD

**Issue by roxma** [davidhalter/jedi#1194]
Reproducing steps:

`pip3 install --user mxnet`

```python
import jedi
source='from mxnet import '
script = jedi.Script(source, 1, len(source), 'example.py')
[complete.description for complete in script.completions()]
```

```
>>> import jedi
>>> source='from mxnet import '
>>> script = jedi.Script(source, 1, len(source), 'example.py')
>>> [complete.description for complete in script.completions()]
Traceback (most recent call last):
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 210, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/_compatibility.py", line 452, in pickle_load
    return pickle.load(file, encoding='bytes')
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/api/classes.py", line 465, in description
    return Definition.description.__get__(self)
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/api/classes.py", line 520, in description
    typ = self.type
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/api/classes.py", line 146, in type
    for context in self._name.infer():
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 173, in infer
    level=self._level,
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 280, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 368, in _do_import
    safe_module_name=True,
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 503, in _load_module
    module = compiled.load_module(evaluator, path=path, sys_path=sys_path)
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/compiled/__init__.py", line 36, in load_module
    access_path = evaluator.compiled_subprocess.load_module(**kwargs)
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 94, in wrapper
    kwargs=kwargs,
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 166, in run
    return self._send(id(evaluator), function, args, kwargs)
  File "/data/roxma/.local/lib/python3.5/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 221, in _send
    stderr,
jedi.api.exceptions.InternalError: The subprocess /opt/rh/rh-python35/root/usr/bin/python3.5 has crashed (EOFError('Ran out of input',), stderr=b'').
```

My local environment:

```
VM_67_229_centos jedi-vim $ python --version
Python 3.5.1
VM_67_229_centos jedi-vim $ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by davidhalter** [comment]
Too bad. In my case it works, so I cannot reproduce:

```
$ python run.py  # Does essentially wohat you did.
['instance absolute_import', 'module attribute', 'class AttrScope', 'module autograd', 'module base', 'module callback', 'module context', 'class Context', 'module contrib', 'def cpu', 'def current_context', 'module engine', 'module executor', 'module executor_manager', 'module gluon', 'def gpu', 'module image', 'module img', 'module init', 'module initializer', 'module io', 'module kv', 'module kvstore', 'module kvstore_server', 'module libinfo', 'module libmxnet', 'module log', 'module lr_scheduler', 'module metric', 'module misc', 'module mod', 'module model', 'module module', 'module mon', 'module monitor', 'class MXNetError', 'module name', 'module nd', 'module ndarray', 'module ndarray_doc', 'module notebook', 'module operator', 'module optimizer', 'module profiler', 'module random', 'module recordio', 'module registry', 'module rnd', 'module rnn', 'module rtc', 'module sym', 'module symbol', 'module symbol_doc', 'module test_utils', 'module th', 'module tools', 'module torch', 'module visualization', 'module viz', 'module _ctypes', 'module _cy2', 'module _cy3', 'instance __doc__', 'instance __file__', 'instance __name__', 'instance __package__', '__version__ = base.__version__']
```

Hmm. Typically this happens, because something is broken. Could you use the latest master branch and rerun what you just ran?

**Comment by roxma** [comment]
hmm...

I have pushed a docker image for reproducing this issue: https://hub.docker.com/r/roxma/jedi-1194/

```
[root@VM_67_229_centos roxma]# docker run --rm -it -w /root/jedi roxma/jedi-1194  ./run.py
Traceback (most recent call last):
  File "/root/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 241, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "/root/jedi/jedi/_compatibility.py", line 464, in pickle_load
    return pickle.load(file, encoding='bytes')
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run.py", line 5, in <module>
    print([complete.description for complete in script.completions()])
  File "./run.py", line 5, in <listcomp>
    print([complete.description for complete in script.completions()])
  File "/root/jedi/jedi/api/classes.py", line 462, in description
    return Definition.description.__get__(self)
  File "/root/jedi/jedi/api/classes.py", line 517, in description
    typ = self.type
  File "/root/jedi/jedi/api/classes.py", line 146, in type
    for context in self._name.infer():
  File "/root/jedi/jedi/evaluate/imports.py", line 174, in infer
    level=self._level,
  File "/root/jedi/jedi/evaluate/imports.py", line 285, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/root/jedi/jedi/evaluate/imports.py", line 383, in _do_import
    safe_module_name=True,
  File "/root/jedi/jedi/evaluate/imports.py", line 521, in _load_module
    module = compiled.load_module(evaluator, dotted_name=dotted_name, sys_path=sys_path)
  File "/root/jedi/jedi/evaluate/compiled/__init__.py", line 36, in load_module
    access_path = evaluator.compiled_subprocess.load_module(**kwargs)
  File "/root/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 108, in wrapper
    kwargs=kwargs,
  File "/root/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 199, in run
    return self._send(id(evaluator), function, args, kwargs)
  File "/root/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 253, in _send
    stderr,
jedi.api.exceptions.InternalError: The subprocess /usr/bin/python3.6 has crashed (EOFError('Ran out of input',), stderr=<empty/not available (ValueError('I/O operation on closed file',))>).
```

**Comment by roxma** [comment]
Cannot reproduce on my another PC with the same docker image. Closing.

**Comment by Alexey-T** [comment]
Can see same in #1204
