### ISSUE TITLE
'Parser' object has no attribute 'pgen_parser

### ISSUE THREAD

**Issue by Saltychtao** [davidhalter/jedi#1214]
I'm using Emacs lsp-mode to auto complete python code, however it seems something is broken in jedi, which throws an error:`Traceback (most recent call last):
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jedi/api/helpers.py", line 128, in get_stack_at_position
    p.parse(tokens=tokenize_without_endmarker(code))
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/parso/python/parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/parso/parser.py", line 127, in parse
    for token in tokens:
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/parso/python/parser.py", line 198, in _recovery_tokenize
    for token in tokens:
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jedi/api/helpers.py", line 111, in tokenize_without_endmarker
    raise EndMarkerReached()
jedi.api.helpers.get_stack_at_position.<locals>.EndMarkerReached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pyls/python_ls.py", line 257, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pyls/python_ls.py", line 185, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pyls/python_ls.py", line 117, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 10, in pyls_completions
    definitions = document.jedi_script(position).completions()
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 125, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/saltychtao/softwares/anaconda3/lib/python3.6/site-packages/jedi/api/helpers.py", line 130, in get_stack_at_position
    return Stack(p.pgen_parser.stack)
AttributeError: 'Parser' object has no attribute 'pgen_parser'
`

It seems that there is a problem in parso or jedi, but I am not sure.

**Comment by davidhalter** [comment]
This is an issue that I saw coming and almost nobody ran into. When you upgrade Jedi, also upgrade parso. It's unfortunately not possible to force pip to do that. :(

**Comment by bwo** [comment]
```
pip install parso jedi
Looking in indexes: https://registry.affirm-stage.com/artifactory/api/pypi/pypi/simple
Looking in links: /var/cache/pip/wheelhouse
Requirement already satisfied: parso in ./lib/python2.7/site-packages (0.3.1)
Requirement already satisfied: jedi in ./lib/python2.7/site-packages (0.12.0)
```

But I still get this error. What version of parso should one actually upgrade to?

**Comment by davidhalter** [comment]
Can you please try `pip install parso jedi --upgrade`?
