### ISSUE TITLE
Crash on docstring() with complicated class decorators

### ISSUE THREAD

**Issue by reinhrst** [davidhalter/jedi#1222]
The following code makes jedi crash

```
import jedi

script = jedi.Script('''
def dataclass(_cls=None):
    # simplified version of dataclasses backport
    # https://github.com/ericvsmith/dataclasses/blob/master/dataclasses.py
    def wrap(cls):
        return cls

    # See if we're being called as @dataclass or @dataclass().
    if _cls is None:
        # We're called with parens.
        return wrap

    # We're called as @dataclass without parens.
    return wrap(_cls)


def foo(*args, **kwargs):
    def decorator(cls):
        cls = dataclass(_cls=cls, **kwargs)
        return cls
    return decorator


def bar(*args, **kwargs):
    if len(args) == 1 and len(kwargs) == 0 and isinstance(args[0], type):
        # called without arguments
        return bar()(args[0])
    return foo(*args, **{**kwargs, "frozen": True})

@bar
class FooBar:
    pass

FooBa''')

completions = script.completions()
print(completions)
for completion in completions:
    print(completion.name, completion.description)
    print(completion.docstring())
```

This code is distilled down as much as I could, from my tests it looks like all parts are needed. I encountered when making my own wrapper around `dataclasses.dataclass()`. There is quite some "magic" to allow both `@bar` and `@bar()` as class decorator (just as there is in the `@dataclass` decorator itself.

Full error trace:
```
[<Completion: FooBar>]
FooBar class FooBar
Traceback (most recent call last):
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/cache.py", line 140, in wrapper
    return dct[key]
KeyError: ((), frozenset({('fast', False)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 42, in <module>
    print(completion.docstring())
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/api/classes.py", line 456, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/api/classes.py", line 255, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/api/classes.py", line 678, in docstring
    for context in self._get_contexts(fast=fast):
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/cache.py", line 142, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/api/classes.py", line 668, in _get_contexts
    return self._name.infer()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 102, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 562, in tree_name_to_contexts
    types = _apply_decorators(context, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 602, in _apply_decorators
    values = dec_values.execute(arguments.ValuesArguments([values]))
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 65, in mapper
    for context in self._set
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 65, in <genexpr>
    for context in self._set
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 62, in execute
    context_set = func(arguments)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 73, in py__call__
    return self.infer_function_execution(function_execution)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 95, in infer_function_execution
    return function_execution.get_return_values()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/recursion.py", line 87, in wrapper
    result = func(self, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 176, in get_return_values
    context_set |= self.eval_node(children[1])
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 97, in eval_node
    context_set = eval_trailer(context, context_set, trailer)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 183, in eval_trailer
    return base_contexts.execute(args)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 65, in mapper
    for context in self._set
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 65, in <genexpr>
    for context in self._set
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 62, in execute
    context_set = func(arguments)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 73, in py__call__
    return self.infer_function_execution(function_execution)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 95, in infer_function_execution
    return function_execution.get_return_values()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/recursion.py", line 87, in wrapper
    result = func(self, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 176, in get_return_values
    context_set |= self.eval_node(children[1])
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 202, in eval_atom
    search_global=True
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/_compatibility.py", line 274, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 162, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 102, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 554, in tree_name_to_contexts
    types = _remove_statements(evaluator, context, node, tree_name)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 496, in _remove_statements
    return eval_expr_stmt(context, stmt, seek_name=name)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 283, in eval_expr_stmt
    return _eval_expr_stmt(context, stmt, seek_name)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 299, in _eval_expr_stmt
    context_set = context.eval_node(rhs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 97, in eval_node
    context_set = eval_trailer(context, context_set, trailer)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 183, in eval_trailer
    return base_contexts.execute(args)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 65, in mapper
    for context in self._set
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 65, in <genexpr>
    for context in self._set
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 62, in execute
    context_set = func(arguments)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 73, in py__call__
    return self.infer_function_execution(function_execution)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 95, in infer_function_execution
    return function_execution.get_return_values()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/recursion.py", line 87, in wrapper
    result = func(self, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 160, in get_return_values
    check = flow_analysis.reachability_check(self, funcdef, r)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/flow_analysis.py", line 78, in reachability_check
    return _break_check(context, context_scope, first_flow_scope, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/flow_analysis.py", line 93, in _break_check
    reachable = _check_if(context, flow_node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/flow_analysis.py", line 113, in _check_if
    types = context.eval_node(node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 146, in eval_node
    return eval_or_test(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 338, in eval_or_test
    types = context.eval_node(next(iterator))
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 202, in eval_atom
    search_global=True
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/_compatibility.py", line 274, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 162, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 136, in infer
    return self.get_param().infer()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 139, in get_param
    params = self.parent_context.get_executed_params()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 253, in get_executed_params
    return self.var_args.get_executed_params(self)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/arguments.py", line 126, in get_executed_params
    return get_executed_params(execution_context, self)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/param.py", line 52, in get_executed_params
    unpacked_va = list(var_args.unpack(funcdef))
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/arguments.py", line 196, in unpack
    arrays = self.context.eval_node(el)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 202, in eval_atom
    search_global=True
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/_compatibility.py", line 274, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 162, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 136, in infer
    return self.get_param().infer()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 139, in get_param
    params = self.parent_context.get_executed_params()
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 253, in get_executed_params
    return self.var_args.get_executed_params(self)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/arguments.py", line 126, in get_executed_params
    return get_executed_params(execution_context, self)
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/param.py", line 52, in get_executed_params
    unpacked_va = list(var_args.unpack(funcdef))
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/arguments.py", line 198, in unpack
    for key, values in _star_star_dict(self.context, dct, el, funcdef):
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/iterable.py", line 370, in exact_key_items
    for key_node, value in self._items():
  File "/Users/reinoud/Envs/james/lib/python3.6/site-packages/jedi/evaluate/context/iterable.py", line 358, in _items
    assert op == ':'  # A dict.
AssertionError
```

I wouldn't mind spending a couple of hours this weekend trying to squash this, but any pointers would be much appreciated; it's been 2 years since I last worked on the jedi code.

(edited errormessage to use a clean install `pip install git+https://github.com/davidhalter/jedi` of jedi to avoid doubt)

Running python 3.6.5 and jedi master.

**Comment by reinhrst** [comment]
Thanks, this narrows it down a lot!

Don't you mean index `[1]` in your example? Unless `kwargs` is defined above, there is no way to know the type of `[0]`.

I think there are three separate cases that should/could work (although step 1 may just be to stop an error being thrown, actually supporting these cases may be for later):

```
d = {'a': 3, 1.0: list}

# currently fails and returns set()
#? dict()
{**d}

# currently crashes
#? str()
{**d, "b": "b"}["b"]

# currently crashes
#? int()
{**d, "b": 1}["a"]
```

I will take a look if I can get some of these to work!

**Comment by reinhrst** [comment]
Pull request in #1223 . Also fixes the same issue with `{*s}` and `[*s]`. Just ignores any unpacking items in dicts/lists/sets.
