### ISSUE TITLE
Jedi seems unable to handle python 3.6's f-strings (PEP498)

### ISSUE THREAD

**Issue by acetylen** [davidhalter/jedi#1224]
Version of Python: 3.6.3
Version of Jedi: 0.12.1
Editor: Neovim 0.3.1 with deoplete 4.0 and deoplete-jedi

Minimal example of issue:

    f"a"

Adding anything to the string causes jedi to break with the following error:

```
[deoplete] Traceback (most recent call last):
  File "/home/sandbox/.config/nvim/plug/deoplete.nvim/rplugin/python3/deoplete/child.py", line 220, in _gather_results
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 174, in gather_candidates
    completions = self.get_completions(script)
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 129, in get_completions
    return script.completions()
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 98, in completions
    completion_names = self._get_context_completions()
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 126, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/sandbox/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/helpers.py", line 130, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.
Error from jedi: SystemError("This really shouldn't happen. There's a bug in Jedi.",).
```
 
Note that the instance of jedi in the `vendored` directory is a submodule which points to this repository, not an old version.

**Comment by davidhalter** [comment]
Thanks for the report!
