### ISSUE TITLE
Completion crash on global variables

### ISSUE THREAD

**Issue by ppwwyyxx** [davidhalter/jedi#1228]
```python
#File: mymodule.py
def func():
    global a
    a = 1
```
```python
import os
import time
from jedi import Script
source = r"""
#!/usr/bin/env python
import mymodule
mymodule.""".strip()
lines = source.strip().split('\n')

ret = Script(source, len(lines), len(lines[-1]), None).completions()
```

The completion crashes with the error:
```
Traceback (most recent call last):
  File "a.py", line 14, in <module>
    ret = Script(source, len(lines), len(lines[-1]), None).completions()
  File "/home/XXX/.local/lib/python3.6/site-packages/jedi/api/__init__.py", line 182, in completions                                                                                           
    c for c in completions
  File "/home/XXX/.local/lib/python3.6/site-packages/jedi/api/__init__.py", line 184, in <listcomp>                                                                                            
    or c._name.tree_name.get_definition().type in ('import_name', 'import_from')
AttributeError: 'NoneType' object has no attribute 'type'
```

I'm using jedi==0.13.0

**Comment by davidhalter** [comment]
Thanks for finding it. Should be fixed.
