### ISSUE TITLE
completion do not work with pwntools

### ISSUE THREAD

**Issue by iromise** [davidhalter/jedi#1229]
here is an example

```shell
>>> source = '''import pwnlib
... pwnlib.'''
>>> script = jedi.Script(source, 2, len('pwnlib.'), 'example.py')
>>> script.completions()
[]
>>> pwnlib.context.arch='amd64'
>>> print context.arch
amd64

>>> source = '''import Crypto
... Crypto.'''
>>> script = jedi.Script(source, 2, len('Crypto.'), 'example.py')
>>> script.completions()
[<Completion: Cipher>, <Completion: Hash>, <Completion: pct_warnings>, <Completion: Protocol>, <Completion: PublicKey>, <Completion: Random>, <Completion: SelfTest>, <Completion: Signature>, <Completion: Util>, <Completion: version_info>, <Completion: __all__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>, <Completion: __revision__>, <Completion: __version__>]
```

**Comment by iromise** [comment]
Hi, it's very interesting... I install it using pip
```shell
➜  ~ python
Python 2.7.14 (default, Mar 22 2018, 14:43:05)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.set_debug_function()
>>> source = '''import pwnlib
... pwnlib.'''
>>> script = jedi.Script(source, 2, len('pwnlib.'), 'example.py')
speed: init 27.1794679165
speed: parsed 27.1806719303
>>> script.completions()
speed: completions start 10.4135079384
 dbg: eval_node <Name: pwnlib@2,0>@(2, 0)
  dbg: finder.filter_name u'pwnlib' in (<ModuleContext: example@1-2>): [<TreeNameDefinition: pwnlib@(1, 7)>]@(2, 0)
  speed: import (<Name: pwnlib@1,7>,) 10.7254798412
  dbg: search_module u'pwnlib' in '/Users/iromise/example.py'
  warning: /Users/iromise/example.py:1:7: E3 No module named pwnlib
  dbg: finder._names_to_types: [<TreeNameDefinition: pwnlib@(1, 7)>] -> ContextSet()
dbg: trailer completion contexts: ContextSet()
speed: completions end 10.7674820423
[]
>>> import pwnlib
>>> pwnlib.context.arch='amd64'
>>> print pwnlib.context.arch
amd64
```

**Comment by davidhalter** [comment]
`jedi.__version__`?

**Comment by iromise** [comment]
I find my jedi version is a little low(0.12.1). And when I update it to the lastest version `jedi-0.13.1`. It works in the terminal
```shell
➜  ~ python
Python 2.7.14 (default, Mar 22 2018, 14:43:05)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.set_debug_function()
>>> source = '''import pwnlib
... pwnlib.'''
>>> script = jedi.Script(source, 2, len('pwnlib.'), 'example.py')
dbg: Start environment subprocess '/usr/local/opt/python@2/bin/python2.7'
speed: init 25.2653899193
speed: parsed 25.2696218491
>>> script.completions(
... )
speed: completions start 12.5941798687
 dbg: eval_node <Name: pwnlib@2,0>@(2, 0)
  dbg: finder.filter_name u'pwnlib' in (<ModuleContext: example@1-2>): [<TreeNameDefinition: pwnlib@(1, 7)>]@(2, 0)
  speed: import (<Name: pwnlib@1,7>,) 12.5981268883
  dbg: global search_module u'pwnlib' in '/Users/iromise/example.py'
  dbg: after import: ContextSet(<ModuleContext: pwnlib@1-44>)
  dbg: finder._names_to_types: [<TreeNameDefinition: pwnlib@(1, 7)>] -> ContextSet(<ModuleContext: pwnlib@1-44>)
dbg: trailer completion contexts: ContextSet(<ModuleContext: pwnlib@1-44>)
speed: completions end 12.6966028214
[<Completion: abi>, <Completion: absolute_import>, <Completion: adb>, <Completion: args>, <Completion: asm>, <Completion: atexception>, <Completion: atexit>, <Completion: commandline>, <Completion: config>, <Completion: constants>, <Completion: context>, <Completion: data>, <Completion: device>, <Completion: dynelf>, <Completion: elf>, <Completion: encoders>, <Completion: exception>, <Completion: flag>, <Completion: fmtstr>, <Completion: gdb>, <Completion: importlib>, <Completion: internal>, <Completion: lexer>, <Completion: libcdb>, <Completion: log>, <Completion: memleak>, <Completion: module>, <Completion: pep237>, <Completion: protocols>, <Completion: qemu>, <Completion: regsort>, <Completion: replacements>, <Completion: rop>, <Completion: runner>, <Completion: shellcraft>, <Completion: term>, <Completion: testexample>, <Completion: timeout>, <Completion: tubes>, <Completion: ui>, <Completion: update>, <Completion: useragents>, <Completion: util>, <Completion: version>, <Completion: __all__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>, <Completion: __version__>]
>>> source = '''from pwn import *
... context.'''
>>> script = jedi.Script(source, 2, len('context.'), 'example.py')
dbg: Start environment subprocess '/usr/local/opt/python@2/bin/python2.7'
speed: init 60.356595993
speed: parsed 60.3577678204
>>> script.completions()
speed: completions start 5.93840694427
 dbg: eval_node <Name: context@2,0>@(2, 0)
  speed: import (<Name: pwn@1,5>,) 5.94116401672
  dbg: global search_module u'pwn' in '/Users/iromise/example.py'
  dbg: after import: ContextSet(<ModuleContext: pwn@2-21>)
  speed: import (<Name: pwn@4,5>, <Name: toplevel@4,9>) 6.01799798012
  dbg: search_module u'pwn.toplevel' in paths [u'/usr/local/lib/python2.7/site-packages/pwn']
  dbg: after import: ContextSet(<ModuleContext: toplevel@2-86>)
  speed: import (<Name: pwnlib@21,5>,) 6.03692317009
  dbg: global search_module u'pwnlib' in u'/usr/local/lib/python2.7/site-packages/pwn/toplevel.py'
  dbg: after import: ContextSet(<ModuleContext: pwnlib@1-44>)
  speed: import (<Name: pwnlib@22,5>, <Name: asm@22,12>) 6.03894209862
  dbg: search_module u'pwnlib.asm' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: after import: ContextSet(<ModuleContext: asm@2-820>)
  speed: import (<Name: pwnlib@26,5>, <Name: encoders@26,12>) 6.17053103447
  dbg: search_module u'pwnlib.encoders' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: after import: ContextSet(<ModuleContext: encoders@2-18>)
  speed: import (<Name: pwnlib@29,5>, <Name: encoders@29,12>) 6.17503595352
  dbg: after import: ContextSet(<ModuleContext: encoders@2-18>)
  speed: import (<Name: pwnlib@32,5>, <Name: flag@32,12>) 6.17532610893
  dbg: search_module u'pwnlib.flag' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: after import: ContextSet(<ModuleContext: flag@1-8>)
  speed: import (<Name: pwnlib@36,5>, <Name: regsort@36,12>) 6.1785030365
  dbg: search_module u'pwnlib.regsort' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: after import: ContextSet(<ModuleContext: regsort@2-424>)
  speed: import (<Name: pwnlib@37,5>, <Name: replacements@37,12>) 6.2496919632
  dbg: search_module u'pwnlib.replacements' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: after import: ContextSet(<ModuleContext: replacements@1-21>)
  speed: import (<Name: pwnlib@40,5>, <Name: runner@40,12>) 6.25504207611
  dbg: search_module u'pwnlib.runner' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: after import: ContextSet(<ModuleContext: runner@1-93>)
  speed: import (<Name: pwnlib@49,5>, <Name: ui@49,12>) 6.26484203339
  dbg: search_module u'pwnlib.ui' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: after import: ContextSet(<ModuleContext: ui@1-193>)
  speed: import (<Name: pwnlib@56,5>, <Name: util@56,12>, <Name: cyclic@56,17>) 6.32787704468
  dbg: search_module u'pwnlib.util' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
  dbg: search_module u'pwnlib.util.cyclic' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: cyclic@1-337>)
  speed: import (<Name: pwnlib@57,5>, <Name: util@57,12>, <Name: fiddling@57,17>) 6.37230300903
  dbg: search_module u'pwnlib.util.fiddling' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: fiddling@2-925>)
  speed: import (<Name: pwnlib@58,5>, <Name: util@58,12>, <Name: getdents@58,17>) 6.51190805435
  dbg: search_module u'pwnlib.util.getdents' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: getdents@1-62>)
  speed: import (<Name: pwnlib@59,5>, <Name: util@59,12>, <Name: hashes@59,17>) 6.52335906029
  dbg: search_module u'pwnlib.util.hashes' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: hashes@1-34>)
  speed: import (<Name: pwnlib@60,5>, <Name: util@60,12>, <Name: lists@60,17>) 6.5410759449
  dbg: search_module u'pwnlib.util.lists' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: lists@1-209>)
  speed: import (<Name: pwnlib@61,5>, <Name: util@61,12>, <Name: misc@61,17>) 6.58009409904
  dbg: search_module u'pwnlib.util.misc' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: misc@1-367>)
  speed: import (<Name: pwnlib@62,5>, <Name: util@62,12>, <Name: packing@62,17>) 6.64784002304
  dbg: search_module u'pwnlib.util.packing' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: packing@2-862>)
  speed: import (<Name: pwnlib@65,5>, <Name: util@65,12>, <Name: splash@65,17>) 6.86059999466
  dbg: search_module u'pwnlib.util.splash' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: splash@1-72>)
  speed: import (<Name: pwnlib@66,5>, <Name: util@66,12>, <Name: web@66,17>) 6.88276815414
  dbg: search_module u'pwnlib.util.web' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib/util']
  dbg: after import: ContextSet(<ModuleContext: web@2-79>)
  dbg: finder.filter_name u'context' in (<ModuleContext: example@1-2>): [<TreeNameDefinition: context@(61, 27)>]@(2, 0)
  speed: import (<Name: pwnlib@61,5>, <Name: context@61,12>) 6.91711115837
  dbg: search_module u'pwnlib.context' in paths [u'/usr/local/lib/python2.7/site-packages/pwnlib']
   dbg: finder.filter_name u'context' in (<ModuleContext: context@3-1419>): [<TreeNameDefinition: context@(1364, 0)>]@None
    dbg: eval_expr_stmt <ExprStmt: #: Global :class:`.ContextType` object, used to store commonly-used pwntools settings. #: #: In most cases, the context is used to infer default variables values. #: For example, :func:`.asm` can take an ``arch`` parameter as a #: keyword argument. #: #: If it is not supplied, the ``arch`` specified by ``context`` is used instead. #: #: Consider it a shorthand to passing ``os=`` and ``arch=`` to every single #: function call. context = ContextType()@1364,0> (<Name: context@1364,0>)
     dbg: eval_node PythonNode(power, [<Name: ContextType@1364,10>, PythonNode(trailer, [<Operator: (>, <Operator: )>])])@(1364, 10)
      dbg: finder.filter_name u'ContextType' in (<ModuleContext: context@3-1419>): [<TreeNameDefinition: ContextType@(266, 6)>]@(1364, 0)
      dbg: finder._names_to_types: [<TreeNameDefinition: ContextType@(266, 6)>] -> ContextSet(<ClassContext: <Class: ContextType@266-1352>>)
     dbg: eval_trailer: PythonNode(trailer, [<Operator: (>, <Operator: )>]) in ContextSet(<ClassContext: <Class: ContextType@266-1352>>)
      dbg: execute: <ClassContext: <Class: ContextType@266-1352>> <TreeArguments: None>
      dbg: execute result: ContextSet(<TreeInstance of <ClassContext: <Class: ContextType@266-1352>>(<TreeArguments: None>)>) in <ClassContext: <Class: ContextType@266-1352>>
    dbg: eval_expr_stmt result ContextSet(<TreeInstance of <ClassContext: <Class: ContextType@266-1352>>(<TreeArguments: None>)>)
   dbg: finder._names_to_types: [<TreeNameDefinition: context@(1364, 0)>] -> ContextSet(<TreeInstance of <ClassContext: <Class: ContextType@266-1352>>(<TreeArguments: None>)>)
  dbg: after import: ContextSet(<TreeInstance of <ClassContext: <Class: ContextType@266-1352>>(<TreeArguments: None>)>)
  dbg: finder._names_to_types: [<TreeNameDefinition: context@(61, 27)>] -> ContextSet(<TreeInstance of <ClassContext: <Class: ContextType@266-1352>>(<TreeArguments: None>)>)
dbg: trailer completion contexts: ContextSet(<TreeInstance of <ClassContext: <Class: ContextType@266-1352>>(<TreeArguments: None>)>)
 dbg: eval_node <Name: object@266,18>@(266, 18)
  dbg: finder.filter_name u'object' in (<ModuleContext: context@3-1419>): [<CompiledName: (<CompiledContextName: builtins>).object>]@(266, 18)
  dbg: finder._names_to_types: [<CompiledName: (<CompiledContextName: builtins>).object>] -> ContextSet(<CompiledObject: <class 'future.types.newobject.newobject'>>)
speed: completions end 7.2251200676
[<Completion: abi>, <Completion: adb>, <Completion: adb_host>, <Completion: adb_port>, <Completion: arch>, <Completion: architectures>, <Completion: aslr>, <Completion: big_32>, <Completion: big_64>, <Completion: binary>, <Completion: bits>, <Completion: buffer_size>, <Completion: bytes>, <Completion: cache_dir>, <Completion: clear>, <Completion: copy>, <Completion: cyclic_alphabet>, <Completion: cyclic_size>, <Completion: defaults>, <Completion: delete_corefiles>, <Completion: device>, <Completion: endian>, <Completion: endianness>, <Completion: endiannesses>, <Completion: gdbinit>, <Completion: kernel>, <Completion: little_16>, <Completion: little_32>, <Completion: little_64>, <Completion: little_8>, <Completion: local>, <Completion: log_console>, <Completion: log_file>, <Completion: log_level>, <Completion: mask>, <Completion: native>, <Completion: next>, <Completion: noptrace>, <Completion: os>, <Completion: oses>, <Completion: proxy>, <Completion: quiet>, <Completion: quietfunc>, <Completion: randomize>, <Completion: rename_corefiles>, <Completion: reset_local>, <Completion: sign>, <Completion: signed>, <Completion: signedness>, <Completion: signednesses>, <Completion: silent>, <Completion: socket>, <Completion: terminal>, <Completion: Thread>, <Completion: timeout>, <Completion: update>, <Completion: valid_signed>, <Completion: verbose>, <Completion: word_size>, <Completion: _tls>, <Completion: __call__>, <Completion: __class__>, <Completion: __delattr__>, <Completion: __dict__>, <Completion: __doc__>, <Completion: __format__>, <Completion: __getattribute__>, <Completion: __hash__>, <Completion: __init__>, <Completion: __long__>, <Completion: __module__>, <Completion: __native__>, <Completion: __new__>, <Completion: __nonzero__>, <Completion: __reduce__>, <Completion: __reduce_ex__>, <Completion: __repr__>, <Completion: __setattr__>, <Completion: __sizeof__>, <Completion: __slots__>, <Completion: __str__>, <Completion: __subclasshook__>, <Completion: __unicode__>, <Completion: __weakref__>]
```

Actually, I want to use it in emacs, and I am using spacemacs with lsp-python enabled, I meet this error

```
InvalidPythonEnvironment: Could not get version information for '/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python': OSError(24, 'Too many open files')
2018-10-03 08:53:40,878 UTC - ERROR - jsonrpc.endpoint - Failed to handle request 145
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/local/lib/python2.7/site-packages/jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/local/lib/python2.7/site-packages/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/local/lib/python2.7/site-packages/pyls/python_ls.py", line 257, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/usr/local/lib/python2.7/site-packages/pyls/python_ls.py", line 185, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/usr/local/lib/python2.7/site-packages/pyls/python_ls.py", line 117, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/site-packages/pyls/plugins/jedi_completion.py", line 10, in pyls_completions
    definitions = document.jedi_script(position).completions()
  File "/usr/local/lib/python2.7/site-packages/pyls/workspace.py", line 209, in jedi_script
    'sys_path': self.sys_path()
  File "/usr/local/lib/python2.7/site-packages/pyls/workspace.py", line 222, in sys_path
    path.extend(environment.get_sys_path())
  File "/usr/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jedi/api/environment.py", line 128, in get_sys_path
    return self._get_subprocess().get_sys_path()
  File "/usr/local/lib/python2.7/site-packages/jedi/api/environment.py", line 79, in _get_subprocess
    exc))
```

I think the error is  mainly because ```OSError(24, 'Too many open files')```. but I just open one file

```
from pwn import *

p = remote('127.0.0.1', 12345)

```

**Comment by davidhalter** [comment]
I think for your issue with spacemacs you have to open a different issue.

If it works in 0.13.1 I feel like there were just issues with open files in 0.12 that have been fixed. Is everything working in 0.13?

**Comment by galeo** [comment]
I've met the same problem that it reports the error `OSError(24, 'Too many open files')`. I use the latest **0.13.1** version.

**Comment by iromise** [comment]
@davidhalter  it works. But i think the following is worth to read..

@galeo it is because that the limited file number is two small, for mac

```shell
launchctl limit maxfiles
```
default is 256..
I change it to a little large
```shell
➜  ~ launchctl limit maxfiles
	maxfiles    64000          524288
```
Then it works.

But I think may be there is a lot of opened files that jedi do not close..
And I find it's slow for jedi to complete pwntools related symbol. @davidhalter

**Comment by davidhalter** [comment]
Ok. IMO there's one or two places where we maybe keep open files. Generally we don't do that though and are closing everything. It's a bug if that's not the case.

**Comment by davidhalter** [comment]
Is this still an issue? I doubt that Jedi is at fault here.

**Comment by davidhalter** [comment]
Closing due to inactivity.
