### ISSUE TITLE
completion do not work with 'from . import *'

### ISSUE THREAD

**Issue by doszik** [davidhalter/jedi#1235]
here is an example
```
import jedi

source = """
from . import *
furl.c
"""
script = jedi.Script(source,3,len("furl.c"), 'export.py')

completions = script.completions()
```
```
'Traceback (most recent call last):
  File "1.py", line 11, in <module>
    completions = script.completions()
  File "/home/user/.local/lib/python3.5/site-packages/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/home/user/.local/lib/python3.5/site-packages/jedi/api/completion.py", line 98, in completions
    completion_names = self._get_context_completions()
  File "/home/user/.local/lib/python3.5/site-packages/jedi/api/completion.py", line 198, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "/home/user/.local/lib/python3.5/site-packages/jedi/api/completion.py", line 234, in _trailer_completions
    contexts = evaluate_call_of_leaf(evaluation_context, previous_leaf)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/helpers.py", line 77, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/syntax_tree.py", line 202, in eval_atom
    search_global=True
  File "/home/user/.local/lib/python3.5/site-packages/jedi/_compatibility.py", line 274, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/base_context.py", line 162, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 56, in find
    names = self.filter_name(filters)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 141, in filter_name
    for filter in filters:
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/filters.py", line 482, in get_global_filters
    origin_scope=origin_scope):
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/context/module.py", line 66, in get_filters
    for star_module in self.star_imports():
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/context/module.py", line 77, in star_imports
    name = i.get_paths()[-1][-1]
IndexError: list index out of range```

**Comment by davidhalter** [comment]
Thanks for the report!
