### ISSUE TITLE
CPython installed via pyenv is deemed unsafe

### ISSUE THREAD

**Issue by jschwinger23** [davidhalter/jedi#1239]
## Versions

1\. jedi version

```
In [3]: jedi.__version__
Out[3]: '0.12.1'
```

2\. vim version

```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 27 2018 18:08:08)
macOS version
Included patches: 1-400
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cindent           +cursorshape       +file_in_path      +jumplist          +mksession         +mouse_xterm       +printer           +startuptime       +termresponse      +viminfo           -xterm_clipboard
+arabic            -clientserver      +dialog_con        +find_in_path      +keymap            +modify_fname      +multi_byte        +profile           +statusline        +textobjects       +vreplace          -xterm_save
+autocmd           +clipboard         +diff              +float             +lambda            +mouse             +multi_lang        -python            -sun_workshop      +timers            +wildignore
+autochdir         +cmdline_compl     +digraphs          +folding           +langmap           -mouseshape        -mzscheme          +python3           +syntax            +title             +wildmenu
-autoservername    +cmdline_hist      -dnd               -footer            +libcall           +mouse_dec         +netbeans_intg     +quickfix          +tag_binary        -toolbar           +windows
-balloon_eval      +cmdline_info      -ebcdic            +fork()            +linebreak         -mouse_gpm         +num64             +reltime           +tag_old_static    +user_commands     +writebackup
+balloon_eval_term +comments          +emacs_tags        -gettext           +lispindent        -mouse_jsbterm     +packages          +rightleft         -tag_any_white     +vartabs           -X11
-browse            +conceal           +eval              -hangul_input      +listcmds          +mouse_netterm     +path_extra        +ruby              -tcl               +vertsplit         -xfontset
++builtin_terms    +cryptv            +ex_extra          +iconv             +localmap          +mouse_sgr         +perl              +scrollbind        +termguicolors     +virtualedit       -xim
+byte_offset       +cscope            +extra_search      +insert_expand     -lua               -mouse_sysmouse    +persistent_undo   +signs             +terminal          +visual            -xpm
+channel           +cursorbind        +farsi             +job               +menu              +mouse_urxvt       +postscript        +smartindent       +terminfo          +visualextra       -xsmp
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.
13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.
7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

3\. pyenv version

```
$ pyenv --version
pyenv 1.2.7
```

## Steps

1\. install CPython 3.6.6 via [pyenv](https://github.com/pyenv/pyenv): 

```
$ pyenv install 3.6.6
```

2\. create virtualenv 3_6_6 via [pyenv-virtual](https://github.com/pyenv/pyenv-virtualenv)

```
$ pyenv virtualenv 3.6.6 3_6_6 && pyenv activate 3_6_6
```

3\. check environments: 

```
$ echo $VIRTUAL_ENV
/Users/zc/.pyenv/versions/3.6.6/envs/3_6_6
```

4\. open IPython and try `jedi.create_environment`:

```
In [1]: import jedi

In [2]: jedi.create_environment('/Users/zc/.pyenv/versions/3.6.6/envs/3_6_6')
---------------------------------------------------------------------------
InvalidPythonEnvironment                  Traceback (most recent call last)
<ipython-input-2-c5267e185398> in <module>
----> 1 jedi.create_environment('/Users/zc/.pyenv/versions/3.6.6/envs/3_6_6')

~/.pyenv/versions/3.6.6/envs/3_6_6/lib/python3.6/site-packages/jedi/api/environment.py in create_environment(path, safe)
    297         _assert_safe(path, safe)
    298         return Environment(_get_python_prefix(path), path)
--> 299     return Environment(path, _get_executable_path(path, safe=safe))
    300
    301

~/.pyenv/versions/3.6.6/envs/3_6_6/lib/python3.6/site-packages/jedi/api/environment.py in _get_executable_path(path, safe)
    312         raise InvalidPythonEnvironment("%s seems to be missing." % python)
    313
--> 314     _assert_safe(python, safe)
    315     return python
    316

~/.pyenv/versions/3.6.6/envs/3_6_6/lib/python3.6/site-packages/jedi/api/environment.py in _assert_safe(executable_path, safe)
    346     if safe and not _is_safe(executable_path):
    347         raise InvalidPythonEnvironment(
--> 348             "The python binary is potentially unsafe.")
    349
    350

InvalidPythonEnvironment: The python binary is potentially unsafe.
```

5\. check Python binary info

```
$ /Users/zc/.pyenv/versions/3.6.6/envs/3_6_6/bin/python --version
Python 3.6.6
$ ls -l /Users/zc/.pyenv/versions/3.6.6/envs/3_6_6/bin/python
lrwxr-xr-x  1 zc  1032302077  54 Sep 27 18:44 /Users/zc/.pyenv/versions/3.6.6/envs/3_6_6/bin/python -> /Users/zc/.pyenv/versions/3.6.6/bin/python
$ ls -l /Users/zc/.pyenv/versions/3.6.6/bin/python
lrwxr-xr-x  1 zc  1032302077  9 Sep 27 18:04 /Users/zc/.pyenv/versions/3.6.6/bin/python -> python3.6
```

And that's where is problematic, which results in crash in vim-jedi under the situation of pyenv-virtualenv activated when calling `:jedi#goto()`:

```
Traceback (most recent call last):
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/cache.py", line 140, in wrapper
    return dct[key]
KeyError: ((), frozenset())
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 302, in goto
    definitions = script.goto_assignments(follow_imports=True)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 226, in goto_assignments
    context = self._evaluator.create_context(self._get_module(), tree_name)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 147, in _get_module
    n = dotted_path_in_sys_path(self._evaluator.get_sys_path(), self.path)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 123, in get_sys_path
    return self.project._get_sys_path(self, environment=self.environment)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/project.py", line 104, in _get_sys_path
    sys_path = list(self._get_base_sys_path(environment))
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/project.py", line 88, in _get_base_sys_path
    sys_path = environment.get_sys_path()
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/cache.py", line 142, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 116, in get_sys_path
    return self._get_subprocess().get_sys_path()
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 169, in get_sys_path
    return self._send(None, functions.get_sys_path, (), {})
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 210, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "/Users/zc/.vim/plugged/jedi-vim/pythonx/jedi/jedi/_compatibility.py", line 452, in pickle_load
    return pickle.load(file, encoding='bytes')
_pickle.UnpicklingError: invalid load key, '\x1b'.
```

The exception above is confusing, firstly I suspected encoding for a while as there are multiple versions of CPython existing and what if jedi running by Python3 analysis Python2 code? But after digging into source code with enormous `print` inserted, it turns out `jedi.create_environment` failure is the root cause, and so that fallback to `find_system_environments`, also fails and fallback to `SameEnvironment`, whose executable is `/usr/local/bin/vim`, and that's what we have above.

It's time consuming to find out what's underneath..

## Proposition

Maybe some variable like `permit_unsafe_binary` to be configurable by user?

**Comment by davidhalter** [comment]
Can you please upgrade to Jedi 0.13? We changed some things about environments and it might work now.

**Comment by jschwinger23** [comment]
Works very fine, thank you very much. @davidhalter
