### ISSUE TITLE
Exception: There's an issue (45 != 43) with the diff parser.

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1245]
There is an issue with the diff parser I've been asked to report:

> Exception: There's an issue (45 != 43) with the diff parser. Please report:

```
Traceback (most recent call last):                                                                                                                                                                            
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 220, in get_script
    environment=get_environment(),
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 118, in __init__
    cache_path=settings.cache_directory,
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 388, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "/home/user/.vim/plugged/jedi-vim/pythonx/parso/parso/grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/parso/parso/grammar.py", line 126, in _parse
    new_lines=lines
  File "/home/user/.vim/plugged/jedi-vim/pythonx/parso/parso/python/diff.py", line 170, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (45 != 43) with the diff parser. Please report:
---
+++
@@ -37,8 +37,7 @@
                                       ('Content-Length', str(len(body)))])
             __import__('pdb').set_trace()
             return [body]
-    class FormApplication(object):
-        def __call__(self, environ, start_response):
-            body = b"<html><body><form></form></body></html>"

-    +    app = TestApp(SlowConsumer())
+    res = app.get('/', params={'a': ['1', '2']})
+    form = res.forms[0]
Traceback (most recent call last):
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 302, in goto
    definitions = script.goto_assignments(follow_imports=True)
AttributeError: 'NoneType' object has no attribute 'goto_assignments'
```

It was fixed after restarting Neovim (using jedi-vim).

**Comment by davidhalter** [comment]
Not really. However I'll try to play around with it. The current implementation of the diff parser is just too susceptible for such issues, because of its mutability. I have plans to change that in the future, but I have to find the time.

**Comment by davidhalter** [comment]
What was the parso version you were using? (`import parso; print(parso.__version__)`)

**Comment by blueyed** [comment]
Awesome, thanks!
