### ISSUE TITLE
Unable to complete MySQL.

### ISSUE THREAD

**Issue by hifall** [davidhalter/jedi#1246]
I have a Python 3 snippet like this:

```
import mysql.connector

mydb = mysql.connector.connect(
  host="1.1.1.1",
  user="user",
  passwd="password"
)

mycursor = mydb.cursor()
mydb.
```

In the snippet above, when I try to invoke completion by `mydb.`, nothing pops up. And the language server gives:

```
2018-10-30 23:27:22,710 UTC - WARNING - jsonrpc.endpoint - Received cancel notification for unknown message id 27

2018-10-30 23:27:24,270 UTC - ERROR - jsonrpc.endpoint - Failed to handle request 30
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/local/lib/python2.7/dist-packages/jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/local/lib/python2.7/dist-packages/pyls/python_ls.py", line 257, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/usr/local/lib/python2.7/dist-packages/pyls/python_ls.py", line 185, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/usr/local/lib/python2.7/dist-packages/pyls/python_ls.py", line 117, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/_tracing.py", line 80, in __call__
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/_tracing.py", line 78, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/pyls/plugins/jedi_completion.py", line 18, in pyls_completions
    } for d in definitions] or None
  File "/usr/local/lib/python2.7/dist-packages/pyls/plugins/jedi_completion.py", line 23, in _label
    params = ', '.join(param.name for param in definition.params)
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 345, in params
    raise AttributeError('There are no params defined on this.')
AttributeError: There are no params defined on this.
```

Ideas? Thanks!

**Comment by MarTango** [comment]
That code snippet works fine for me, using jedi via [anaconda-mode](https://github.com/proofit404/anaconda-mode) on emacs, with python3.6.

Might be an issue with pyls? Doesn't look like it's an issue with jedi.

**Comment by davidhalter** [comment]
Please check the typeshed branch. I think it should work there, now.

**Comment by hifall** [comment]
Hi @davidhalter, has the fix been ported to the main branch? Thanks!

**Comment by davidhalter** [comment]
As I said, please check the typeshed branch. It probably won't get merged for another 1-3 months.
