### ISSUE TITLE
Jedi crashes on completion with a KeyError on SequenceLiteralContext.mapping

### ISSUE THREAD

**Issue by adefossez** [davidhalter/jedi#1273]
When trying to complete the following file, called `source.py`:

```python
import other
import numpy as np
spec = np.zeros((12, 2))
result = other.power(spec)
result.
```

where `other.py` is defined as

```python
def power(spectrogram):
    return spectrogram[..., 0]**2 + spectrogram[..., 1]**2
```

using the following code:
```python
import jedi

source = open("source.py", "r").read()
line = 5
col = 7
filename = "source.py"
environment = None

script = jedi.Script(source, line, col, filename, environment)
script.completions()
```

When running this code against master, I get a `KeyError` on `SequenceLiteralContext.mapping`. It looks like the key is the token for `spectrogram` and not one of `[`, `(`, `{` like this code would expect. It seems that some code in `syntax_tree.py` wrongly considers that this expression is a list, dict or tuple literal. I included the full traceback hereafter.
Let me know if you need anymore information.
Cheers

Full traceback:
```
Traceback (most recent call last):
  File "bug.py", line 10, in <module>
    script.completions()
  File "/Users/defossez/tmp/jedi/jedi/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/Users/defossez/tmp/jedi/jedi/jedi/api/completion.py", line 98, in completions
    completion_names = self._get_context_completions()
  File "/Users/defossez/tmp/jedi/jedi/jedi/api/completion.py", line 198, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "/Users/defossez/tmp/jedi/jedi/jedi/api/completion.py", line 234, in _trailer_completions
    contexts = evaluate_call_of_leaf(evaluation_context, previous_leaf)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/helpers.py", line 77, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 202, in eval_atom
    search_global=True
  File "/Users/defossez/tmp/jedi/jedi/jedi/_compatibility.py", line 274, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/base_context.py", line 162, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/defossez/tmp/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/defossez/tmp/jedi/jedi/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/filters.py", line 102, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 555, in tree_name_to_contexts
    types = _remove_statements(evaluator, context, node, tree_name)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 497, in _remove_statements
    return eval_expr_stmt(context, stmt, seek_name=name)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 284, in eval_expr_stmt
    return _eval_expr_stmt(context, stmt, seek_name)
  File "/Users/defossez/tmp/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 300, in _eval_expr_stmt
    context_set = context.eval_node(rhs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 97, in eval_node
    context_set = eval_trailer(context, context_set, trailer)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 183, in eval_trailer
    return base_contexts.execute(args)
  File "/Users/defossez/tmp/jedi/jedi/jedi/common/context.py", line 65, in mapper
    for context in self._set
  File "/Users/defossez/tmp/jedi/jedi/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/defossez/tmp/jedi/jedi/jedi/common/context.py", line 65, in <genexpr>
    for context in self._set
  File "/Users/defossez/tmp/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/base_context.py", line 62, in execute
    context_set = func(arguments)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/context/function.py", line 73, in py__call__
    return self.infer_function_execution(function_execution)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/context/function.py", line 95, in infer_function_execution
    return function_execution.get_return_values()
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/recursion.py", line 87, in wrapper
    result = func(self, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/context/function.py", line 176, in get_return_values
    context_set |= self.eval_node(children[1])
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 146, in eval_node
    return eval_or_test(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 339, in eval_or_test
    types = context.eval_node(next(iterator))
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/base_context.py", line 145, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 200, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 212, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/__init__.py", line 216, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/defossez/tmp/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 85, in eval_node
    context_set = eval_atom(context, first_child)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/syntax_tree.py", line 262, in eval_atom
    context = iterable.SequenceLiteralContext(context.evaluator, context, atom)
  File "/Users/defossez/tmp/jedi/jedi/jedi/evaluate/context/iterable.py", line 293, in __init__
    self.array_type = SequenceLiteralContext.mapping[atom.children[0]]
KeyError: <Name: spectrogram@2,11>
```

**Comment by davidhalter** [comment]
Jedi version? I might have fixed this. Please upgrade to latest.

**Comment by adefossez** [comment]
As of commit `e33da2bab4174d47111c036d5a26e60a749776d3` the bug is still here. I have a fix and will open a pull request.

**Comment by davidhalter** [comment]
As I wrote in the other issue, please check the typeshed branch, I'm pretty sure there was a fix for this or something similar.

**Comment by adefossez** [comment]
I've tried, the bug is fixed in typeshed :) When will this land in master ?
Closing the issue and pull request.
Cheers

**Comment by davidhalter** [comment]
I'm trying as hard as possible to make typeshed stable. The tests are all passing, but a few other things need a bit help and I need to test a lot. Almost everything has changed...

**Comment by adefossez** [comment]
No worries, it's not really a blocking bug. I might just try the typeshed branch if it is stable enough. Thanks a lot for the work you put into this anyway.
