### ISSUE TITLE
Error in Jedi while editing a file with deoplete-jedi

### ISSUE THREAD

**Issue by kef95** [davidhalter/jedi#1279]
I was editing a file with neovim and this error popped up while I was typing an f-string. I can't reproduce it anywhere else.
I'd be glad to provide any further info

Error:
```
[deoplete] Traceback (most recent call last):
  File "/home/ubuntu/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 179, in _gather_results
    result = self._get_result(context, source)
  File "/home/ubuntu/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 234, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 170, in gather_candidates
    completions = self.get_completions(script)
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 123, in get_completions
    return script.completions()
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 179, in completions

    completions = completion.completions()
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 98, in completion
s
    completion_names = self._get_context_completions()
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 126, in _get_cont
ext_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/ubuntu/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/helpers.py", line 133, in get_stack_at
_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.
Error from jedi: SystemError("This really shouldn't happen. There's a bug in Jedi.",).  Use :messages / see above for error details.
```

**Comment by Shougo** [comment]
deoplete-jedi is updated recently.
It is the latest version?

https://github.com/deoplete-plugins/deoplete-jedi/pull/217

**Comment by kef95** [comment]
Yeah I have the latest update, and just to make sure I did `:PlugUpdate` right now and gave it a try again. Same error arises

**Comment by kef95** [comment]
I'd also like to mention that I manually implemented Jedi outside of neovim and tried to get completions inside the string. Same error popped up at https://github.com/davidhalter/jedi/blob/9617d4527de583b0b900166e4430a8964ee67dc6/jedi/api/helpers.py#L133

**Comment by Shougo** [comment]
Hm.  If so, it seems jedi's problem.

**Comment by kef95** [comment]
@davidhalter any update on this bug? It's definitely an issue with f-strings

**Comment by davidhalter** [comment]
Please upgrade to latest parso and retry. I fixed some of these. Also if you have a reproduction case - that would help. I won't be able to fix the bug like this.

**Comment by davidhalter** [comment]
I also just pushed a commit that will make error messages clearer, so if you could try it with that specific commit that would probably also help me. Even more improtant: Upgrade parso to latest.

**Comment by Shougo** [comment]
@kef95 I have updated deoplete-jedi submodule to the latest version.
Please update.

**Comment by kef95** [comment]
@davidhalter @Shougo that did it! Thank you both for working on the fix, and sorry for the late response.
