### ISSUE TITLE
names() with references raises ValueError when getting parameters of a definition

### ISSUE THREAD

**Issue by micbou** [davidhalter/jedi#1286]
The code
```python
import jedi
jedi.names(source = 'foo', references = True)[0].params
```
raises the following exception:
```python
Traceback (most recent call last):
  File "C:\Users\micbou\tests\jedi-names\jedi\jedi\cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 11, in <module>
    jedi.names(source = 'foo', references = True)[0].params
  File "jedi\cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "jedi\api\classes.py", line 324, in params
    for context in self._name.infer():
  File "jedi\evaluate\filters.py", line 102, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "jedi\evaluate\syntax_tree.py", line 575, in tree_name_to_contexts
    raise ValueError("Should not happen. type: %s", node.type)
ValueError: ('Should not happen. type: %s', 'file_input')
```
This occurs on Python 2.7.15 and 3.7.1 with the latest versions of Parso (https://github.com/davidhalter/parso/commit/acccb4f28d6d57f4ad4c882f3408136ee8f50ff5) and Jedi on both master and typeshed branches (2f86f549f5ec908c996f09e351164192df7aead8 and e3d5ee8332eeae1e19346dc2d81ad57f7c98da74 respectively).

**Comment by davidhalter** [comment]
Thanks for the report!
