### ISSUE TITLE
'from sys import path' crashes Jedi

### ISSUE THREAD

**Issue by ollenorelius** [davidhalter/jedi#1298]
Autocompleting the following code at the end, trying to get docstring, gives a strange error:

```
from sys import path
path
```

> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset({('fast', False)}))
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/jedi/api/classes.py", line 456, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/usr/local/lib/python3.5/dist-packages/jedi/api/classes.py", line 255, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/jedi/api/classes.py", line 678, in docstring
    for context in self._get_contexts(fast=fast):
  File "/usr/local/lib/python3.5/dist-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jedi/api/classes.py", line 668, in _get_contexts
    return self._name.infer()
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/filters.py", line 102, in infer
    return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/syntax_tree.py", line 561, in tree_name_to_contexts
    types = imports.infer_import(context, tree_name)
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/imports.py", line 79, in infer_import
    types = importer.follow()
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/imports.py", line 284, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/imports.py", line 270, in sys_path_with_modifications
    + sys_path.check_sys_path_modifications(self.module_context)
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/sys_path.py", line 119, in check_sys_path_modifications
    for name, power in get_sys_path_powers(possible_names):
  File "/usr/local/lib/python3.5/dist-packages/jedi/evaluate/sys_path.py", line 102, in get_sys_path_powers
    if power.type in ('power', 'atom_expr'):
AttributeError: 'NoneType' object has no attribute 'type'
```

Minimal code example: 
```
import jedi
s = jedi.Interpreter("from sys import path\npath", line=2, column=4, namespaces = [locals()])
s.completions()[0].docstring()
```

**Comment by davidhalter** [comment]
I can reproduce. Thanks for the report!

**Comment by davidhalter** [comment]
Fixed on master.
