### ISSUE TITLE
'bool' object has no attribute 'get_api_type'

### ISSUE THREAD

**Issue by felixhao28** [davidhalter/jedi#1333]
I am using Jedi 0.13.3, sometimes I see `'bool' object has no attribute 'get_api_type'`.

```
Traceback (most recent call last):
  File "main.py", line 146, in work
    completions = get_completions(source, projID, path)
  File "main.py", line 140, in get_completions
    return s.completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 103, in completions
    return sorted(completions, key=lambda x: (x.name.startswith('__'),
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 43, in filter_names
    k = (new.name, new.complete)  # key
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/classes.py", line 434, in complete
    return self._complete(True)
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/classes.py", line 403, in _complete
    if self._name.api_type == 'param' and self._stack is not None:
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/context.py", line 237, in api_type
    return next(iter(self.infer())).api_type
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/context.py", line 128, in api_type
    return self.access_handle.get_api_type()
AttributeError: 'bool' object has no attribute 'get_api_type'

'bool' object has no attribute 'get_api_type'
object of type 'NoneType' has no len()
```

And sometimes I see `'str' object has no attribute 'get_api_type'`.

```
Traceback (most recent call last):
  File "main.py", line 146, in work
    completions = get_completions(source, projID, path)
  File "main.py", line 140, in get_completions
    return s.completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 103, in completions
    return sorted(completions, key=lambda x: (x.name.startswith('__'),
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 43, in filter_names
    k = (new.name, new.complete)  # key
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/classes.py", line 434, in complete
    return self._complete(True)
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/classes.py", line 403, in _complete
    if self._name.api_type == 'param' and self._stack is not None:
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/context.py", line 237, in api_type
    return next(iter(self.infer())).api_type
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/context.py", line 128, in api_type
    return self.access_handle.get_api_type()
AttributeError: 'str' object has no attribute 'get_api_type'

'str' object has no attribute 'get_api_type'
object of type 'NoneType' has no len()
```

And sometimes this:

```
Traceback (most recent call last):
  File "main.py", line 146, in work
    completions = get_completions(source, projID, path)
  File "main.py", line 139, in get_completions
    s = jedi.Script(source + "\n", len(lines), len(lines[-1]), full_file_path)
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 118, in __init__
    cache_path=settings.cache_directory,
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 388, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "/home/user/anaconda3/lib/python3.6/site-packages/parso/grammar.py", line 77, in parse
    return self._parse(code=code, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/parso/grammar.py", line 131, in _parse
    new_lines=lines
  File "/home/user/anaconda3/lib/python3.6/site-packages/parso/python/diff.py", line 236, in update
    self._copy_from_old_parser(line_offset, i2, j2)
  File "/home/user/anaconda3/lib/python3.6/site-packages/parso/python/diff.py", line 275, in _copy_from_old_parser
    line_stmt = self._get_old_line_stmt(parsed_until_line_old + 1)
  File "/home/user/anaconda3/lib/python3.6/site-packages/parso/python/diff.py", line 310, in _get_old_line_stmt
    leaf = self._module.get_leaf_for_position((old_line, 0), include_prefixes=True)
  File "/home/user/anaconda3/lib/python3.6/site-packages/parso/tree.py", line 312, in get_leaf_for_position
    raise ValueError('Please provide a position that exists within this node.')
ValueError: Please provide a position that exists within this node.

Please provide a position that exists within this node.
object of type 'NoneType' has no len()
```

Sometimes this:

```
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 126, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/helpers.py", line 121, in get_stack_at_position
    code = dedent(_get_code_for_stack(code_lines, module_node, pos))
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/helpers.py", line 79, in _get_code_for_stack
    raise OnErrorLeaf(leaf)
jedi.api.helpers.OnErrorLeaf: <PythonErrorLeaf: OP:';', (38, 4)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 146, in work
    completions = get_completions(source, projID, path)
  File "main.py", line 140, in get_completions
    return s.completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 98, in completions
    completion_names = self._get_context_completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 136, in _get_context_completions
    return self._global_completions()
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/api/completion.py", line 225, in _global_completions
    for filter in filters:
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 491, in get_global_filters
    for filter in evaluator.builtins_module.get_filters(search_global=True):
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 118, in builtins_module
    return compiled.get_special_object(self, u'BUILTINS')
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/__init__.py", line 27, in get_special_object
    evaluator.compiled_subprocess.get_special_object(identifier)
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 108, in wrapper
    kwargs=kwargs,
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 199, in run
    return self._send(id(evaluator), function, args, kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 242, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "/home/user/anaconda3/lib/python3.6/site-packages/jedi/_compatibility.py", line 469, in pickle_load
    return pickle.load(file, encoding='bytes')
_pickle.UnpicklingError: invalid load key, '='.

invalid load key, '='.
object of type 'NoneType' has no len()
```

The real problem is I can only see these in our server's log. When I try to reproduce these issues offline single-threaded, they go away. Do you have any guesses on the cause of these issues?

**Comment by felixhao28** [comment]
I switched from ThreadPoolExecutor to ProcessPoolExecutor and all the issues seems gone. Apparently jedi is not thread safe.

**Comment by davidhalter** [comment]
Yes, Jedi is not thread safe.
