### ISSUE TITLE
UnboundLocalError: local variable 'builtin_func' referenced before assignment

### ISSUE THREAD

**Issue by aste4** [davidhalter/jedi#1337]
Hello, 

I am using YouCompleteMe and I am getting this error with when I try to autocomplete functions from the following snippet. Please let me know if this is not the right place to post this and whether I need to post this on YCM. 

```
my_list = [1,2,3]
my_iter = iter(my_list)
my_iter.   <---- 
```

I get `UnboundLocalError: local variable 'builtin_func' referenced before assignment` when using python 3. The only information I found on this was this issue https://github.com/davidhalter/jedi/issues/1255.  

I am using python3 (version 3.5.2) as the default python interpreter (i.e python points to python3) I set this up using python virtualenv. `virtualenv -p python3 my_env`. Using the latest full installation of ycm

However, the same example works fine when I use the default python in my PATH (i.e no virtualenv and python 2.7.12). I see the correct available completions. 

It should be hopefully easily reproduced. If you cant reproduce this and need more information, please let me know.

Environment: Stock Ubuntu 16.04

When it does not work
```
Printing YouCompleteMe debug information...                                                                            
-- Server Python interpreter: /usr/bin/python                                   
-- Server Python version: 2.7.12        
-- Server has Clang support compiled in: True                                   
-- Clang version: clang version 8.0.0 (tags/RELEASE_800/final)                  
...                                                 
--   Python version: 3.5.2              
--   Jedi version: 0.13.3               
--   Parso version: 0.3.4 
```              

When it works
```
Printing YouCompleteMe debug information...                                                                                                                                                     
-- Server Python interpreter: /usr/bin/python                                  
-- Server Python version: 2.7.12       
-- Server has Clang support compiled in: True                                  
-- Clang version: clang version 8.0.0 (tags/RELEASE_800/final)                 
-- Extra configuration file found and loaded                                                  
...                                 
--   Python version: 2.7.12            
--   Jedi version: 0.13.3              
--   Parso version: 0.3.4       
```

**Comment by aste4** [comment]
Nevermind, it seems that python 3 does not actually support that syntax - so there is an error on my part. However, I would still expect auto completion to work for some of the __ methods i.e` __next__ `

https://stackoverflow.com/questions/1073396/is-generator-next-visible-in-python-3-0

The correct way to get the next item from an iterator is to use 

`next(my_iter)`

**Comment by davidhalter** [comment]
Can you please give me a traceback? Without it, it's kind of hard to debug.

**Comment by aste4** [comment]
```
Traceback (most recent call last):                                  
  File "/root/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/handlers.py", line 100, in GetCompletions                                  
    .ComputeCandidates( request_data ) )                            
  File "/root/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/completers/completer.py", line 238, in ComputeCandidates                   
    return self.DetailCandidates( request_data, candidates )        
  File "/root/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/completers/python/python_completer.py", line 205, in DetailCandidates      
    candidate[ 'extra_menu_info' ] = self._BuildTypeInfo( completion )                                                                   
  File "/root/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/completers/python/python_completer.py", line 266, in _BuildTypeInfo        
    [ param.description[ 6: ] for param in definition.params ] ) + ')'                                                                   
  File "/root/.vim/bundle/youcompleteme/third_party/ycmd/third_party/jedi_deps/jedi/jedi/cache.py", line 143, in wrapper                 
    result = method(self, *args, **kwargs)                          
  File "/root/.vim/bundle/youcompleteme/third_party/ycmd/third_party/jedi_deps/jedi/jedi/api/classes.py", line 343, in params            
    followed = list(self._name.infer())                             
  File "/root/.vim/bundle/youcompleteme/third_party/ycmd/third_party/jedi_deps/jedi/jedi/evaluate/filters.py", line 357, in infer        
    _BuiltinMappedMethod(self.parent_context, self._callable, builtin_func)                                                              
UnboundLocalError: local variable 'builtin_func' referenced before assignment  
```
If it is easier, here is a quick and minimal Dockerfile that reproduces the issue:

```
FROM ubuntu:16.04                 

RUN apt-get update && apt-get install -y git cmake make g++ python-dev python3-dev curl vim                                             

RUN git clone https://github.com/Valloric/YouCompleteMe.git         
RUN cd YouCompleteMe &&  git submodule update --init --recursive && ./install.py                                                        

RUN mkdir -p ~/.vim/autoload /roo/.vim/bundle && \                  
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim                                                                 

RUN mkdir -p /root/.vim/bundle/youcompleteme                        
RUN cp -r YouCompleteMe/* /root/.vim/bundle/youcompleteme           
RUN echo "execute pathogen#infect()" >> ~/.vimrc                    
RUN echo "set encoding=utf-8" >> ~/.vimrc                           

RUN apt-get -y install virtualenv 
RUN virtualenv -p python3 test_virtual_env                          

RUN echo "my_list = [1,2,3]" >> test.py                             
RUN echo "my_iter = iter(my_list)" >> test.py  
```

```
$ docker build -t repro .
$ docker run -t -i repro # launches bash inside container

inside the container
$ source test_virtual_env/bin/activate
$ vim test.py
at the end of the file, enter `my_iter.` (and wait)
To see the logs in /tmp, exit insert mode suspend vim process via Ctrl-Z
```

The same steps without the line `source test_virtual_env/bin/activate` (python 2.7.12) yields correct auto completions

**Comment by davidhalter** [comment]
Can you retry on current master? So many things have changed and I don't really care anymore about 0.13.3. Make sure to checkout submodules.

**Comment by aste4** [comment]
If if update **both**
- /third_party/ycmd/third_party/jedi_deps/jedi
- /third_party/ycmd/third_party/jedi_deps/parso

Then it seems to work

**Comment by davidhalter** [comment]
Oh yeah, of course I mean both. I guess I'll close. Wait for next release and if it's an issue at that point, I will reopen.

Thanks for reporting!
