### ISSUE TITLE
"TypeError: values() missing 1 required positional argument: 'name'" with completions for typing

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1339]
Using the following script results in a TypeError:
```
import jedi
script = jedi.Script("import typing; typing.")
print(script.completions())
```
```
Traceback (most recent call last):
  File "t-typing.py", line 7, in <module>
    print(script.completions())
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 215, in completions
    completions = completion.completions()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 199, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 242, in _trailer_completions
    completion_names += filter.values()
TypeError: values() missing 1 required positional argument: 'name'
```

(I wanted to create a script to reproduce not getting completions for `typing.` - not sure if that's the reason (I do not get any error with jedi-vim))

However `script = jedi.Script("import os; os.")` works, so this is likely related.

Jedi f7076da, davidhalter/parso@a9b6114

**Comment by davidhalter** [comment]
sith.py found this as well 5 minutes ago, haha. Thanks!
