### ISSUE TITLE
Traceback for tab completion on windows 10 in REPL and sys module 

### ISSUE THREAD

**Issue by jmfrank63** [davidhalter/jedi#1354]
jedi==0.14.0
parso==0.5.0
pyreadline==2.1

python version 3.7.3

On windows 10 REPL completion works if you resolve $(python -m jedi repl) and put the resolved replstartup.py in your PYTHONPATH. e.g. C:\Users\jmfra\scoop\apps\python\3.7.3\Lib\site-packages\jedi\api\replstartup.py

The following works fine:

import os

os.<tab>

However with the sys module jedi crashes:

```
 15:46:11  ~  $ python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.14.0
>>> import sys
>>> sys.ERROR:root:REPL Completion error:
Traceback (most recent call last):
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\utils.py", line 97, in complete
    completions = interpreter.completions()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\__init__.py", line 216, in completions
    return completion.completions()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\completion.py", line 204, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\completion.py", line 249, in _trailer_completions
    python_contexts = convert_contexts(contexts)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 159, in convert_contexts
    for stub_context in contexts
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\common\context.py", line 32, in from_sets
    for set_ in sets:
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 159, in <genexpr>
    for stub_context in contexts
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 28, in _stub_to_python_context_set
    contexts = _infer_from_stub(stub_module, qualified_names, ignore_compiled)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 43, in _infer_from_stub
    assert isinstance(stub_module, StubModuleContext), stub_module
AssertionError: <MixedObject: <module 'sys' (built-in)>>

Readline internal error
Traceback (most recent call last):
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\rlmain.py", line 571, in readline
    self._readline_from_keyboard()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\rlmain.py", line 536, in _readline_from_keyboard
    if self._readline_from_keyboard_poll():
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\rlmain.py", line 556, in _readline_from_keyboard_poll
    result = self.mode.process_keyevent(event.keyinfo)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\modes\emacs.py", line 243, in process_keyevent
    r = self.process_keyevent_queue[-1](keyinfo)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\modes\emacs.py", line 286, in _process_keyevent
    r = dispatch_func(keyinfo)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\modes\basemode.py", line 257, in complete
    completions = self._get_completions()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\pyreadline\modes\basemode.py", line 200, in _get_completions
    r = self.completer(ensure_unicode(text), i)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\utils.py", line 97, in complete
    completions = interpreter.completions()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\__init__.py", line 216, in completions
    return completion.completions()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\completion.py", line 204, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\api\completion.py", line 249, in _trailer_completions
    python_contexts = convert_contexts(contexts)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 159, in convert_contexts
    for stub_context in contexts
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\common\context.py", line 32, in from_sets
    for set_ in sets:
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 159, in <genexpr>
    for stub_context in contexts
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 28, in _stub_to_python_context_set
    contexts = _infer_from_stub(stub_module, qualified_names, ignore_compiled)
  File "C:\Users\jmfra\scoop\apps\python\current\lib\site-packages\jedi\evaluate\gradual\conversion.py", line 43, in _infer_from_stub
    assert isinstance(stub_module, StubModuleContext), stub_module
AssertionError: <MixedObject: <module 'sys' (built-in)>>
>>>
```

A comparison with ipython shows that os works fine as well but sys just doesn't do anything.

Let me know if additional information is required.

**Comment by jmfrank63** [comment]
I did some further research. Builtin modules fail while modules read from disk work.

Here is a list of the failing modules (from sys.builtin_module_names)
```
('_abc', '_ast', '_bisect', '_blake2', '_codecs', '_codecs_cn', '_codecs_hk', '_codecs_iso2022', '_codecs_jp', '_codecs_kr', '_codecs_tw', '_collections', '_contextvars', '_csv', '_datetime', '_functools', '_heapq', '_imp', '_io', '_json', '_locale', '_lsprof', '_md5', '_multibytecodec', '_opcode', '_operator', '_pickle', '_random', '_sha1', '_sha256', '_sha3', '_sha512', '_signal', '_sre', '_stat', '_string', '_struct', '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', '_winapi', 'array', 'atexit', 'audioop', 'binascii', 'builtins', 'cmath', 'errno', 'faulthandler', 'gc', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'parser', 'sys', 'time', 'winreg', 'xxsubtype', 'zipimport', 'zlib')
```

The difference seems to start at line 9 of `conversion.py`
`stub_module = stub_context.get_root_context()`

A module loaded from disk resolves to `<StubModuleContext: os@4-723 is_stub=True>`
while a builtin module stays a `<MixedObject: <module 'sys' (built-in)>>`.

This is very deep into the implementation I am not sure if I can continue from here.

**Comment by jmfrank63** [comment]
Found a temporary fix.
 ```
from jedi import evaluate
assert isinstance(stub_module, StubModuleContext) or isinstance(stub_module, evaluate.compiled.mixed.MixedObject) , stub_module
```
Don't know if amending the assert this way is valid. If so I'd do a PR.

**Comment by davidhalter** [comment]
Not sure if that's intended. I will check that. Thanks for looking into it. Your fix might be correct.

**Comment by davidhalter** [comment]
I'm pretty sure that your solution is the right one. Please add a failing test to it (probably under `test/test_api/test_interpreter.py`) and you probably can use the import directly. Thanks for your investigation!

The thing is that in case no `.py` file is found, stub files are tried - so a stub file can actually be a mixed module. Mixed objects are a way of connection shell objects to Python code.

**Comment by davidhalter** [comment]
ping, if you don't do it I will :)

**Comment by jmfrank63** [comment]
Hi David, sorry, got caught up on work, will do start today. The strange
import by the way was to avoid circular imports. I will look into this as
well.

Thanks for the reminder.

Johannes

**Comment by davidhalter** [comment]
You're probably right about the import, I just realized.
