### ISSUE TITLE
Python container type annotations confuse hints

### ISSUE THREAD

**Issue by verschmelzen** [davidhalter/jedi#1377]
YCM debug information:
```
Printing YouCompleteMe debug information...
-- Client logfile: /tmp/ycm_xvoj4zco.log
-- Server Python interpreter: /usr/bin/python
-- Server Python version: 3.7.3
-- Server has Clang support compiled in: False
-- Clang version: None
-- Extra configuration file found and loaded
-- Extra configuration path: /home/archer/.vim/.ycm_extra_conf.py
-- Python completer debug information:
--   Python interpreter: /usr/bin/python
--   Python path: ['/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home
/archer/.local/lib/python3.7/site-packages', '/usr/lib/python3.7/site-packages']
--   Python version: 3.7.3
--   Jedi version: 0.13.3
--   Parso version: 0.3.4
-- Server running at: http://127.0.0.1:41217
-- Server process ID: 3394
-- Server logfiles:
--   /tmp/ycmd_41217_stdout_s5hh8jr0.log
--   /tmp/ycmd_41217_stderr_xym_8bs0.log
```

Works correctly for in this case
```
def foo(a: Set):
    a.|                    <---- checks type and autocompletes
```

But fails to check type here
```
def foo(a: Set[int]):
    a
```

YCMD logs when running `:YcmCompleter GetType` on `a`:
```
2019-07-25 09:31:11,984 - INFO - Received command request
Traceback (most recent call last):
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 82, in RunCompleterCommand
    request_data ) )
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/ycmd/completers/completer.py", line 350, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/ycmd/completers/python/python_completer.py", line 242, in <lambda>
    self._GetType( request_data ) ),
  File "/home/archer/.vim/plug/YouCompleteMe/third_party/ycmd/ycmd/completers/python/python_completer.py", line 349, in _GetType
    raise RuntimeError( 'No type information available.' )
RuntimeError: No type information available.
```

**Comment by davidhalter** [comment]
0.13.3 didn't support typing properly, please upgrade Jedi.
