### ISSUE TITLE
AssertionError with goto in stub file (.pyi)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1397]
Given `t.py`:
```python
class Foo(str):
    pass
```

Using `goto` on the class results in an AssertionError:

```
Traceback (most recent call last):
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 313, in goto
    definitions = script.goto_assignments(follow_imports=True)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 277, in goto_assignments
    return self._goto_assignments(follow_imports, follow_builtin_imports, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 312, in _goto_assignments
    prefer_stubs=prefer_stubs,
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/gradual/conversion.py", line 145, in convert_names
    return _try_stub_to_python_names(names, prefer_stub_to_compiled=True)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/gradual/conversion.py", line 69, in _try_stub_to_python_names
    ignore_compiled=prefer_stub_to_compiled,
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/gradual/conversion.py", line 45, in _infer_from_stub
    assert isinstance(stub_module, (StubModuleValue, MixedObject)), stub_module_context
AssertionError: ModuleContext(<ModuleValue: t@1-2 is_stub=True>)

```

Happens on v0.15.1 and master (66022ed).

**Comment by davidhalter** [comment]
Hmm strange, this seems such a simple one. I cannot reproduce it. Is there something special in your environment? Also Python version?

**Comment by blueyed** [comment]
Might be fixed already, closing for now.

**Comment by davidhalter** [comment]
It's just strange, because I was also not able to reproduce it on the commit you mentioned (and the changes since then have been quite minimal).

**Comment by blueyed** [comment]
I see.
Will provide more information the next time, and/or try it in a clean venv etc.
