### ISSUE TITLE
os.DirEntry docstring __init__ is_bound assert failed

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1414]
#### Envirment
Windows 7
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit(Intel)] on win32
jedi master last commit
parso master last commit
typeshed master last commit, python official repo 

#### reproduct code
```
import jedi
completions = jedi.Script("import os;os.").completions()
for c in completions:
    print(c)
    c.docstring()
```
#### output
```
<Completion: abc>
<Completion: abort>
<Completion: access>
<Completion: altsep>
<Completion: chdir>
<Completion: chflags>
<Completion: chmod>
<Completion: chown>
<Completion: chroot>
<Completion: CLD_CONTINUED>
<Completion: CLD_DUMPED>
<Completion: CLD_EXITED>
<Completion: CLD_TRAPPED>
<Completion: close>
<Completion: closerange>
<Completion: confstr>
<Completion: confstr_names>
<Completion: cpu_count>
<Completion: ctermid>
<Completion: curdir>
<Completion: defpath>
<Completion: device_encoding>
<Completion: devnull>
<Completion: DirEntry>
Traceback (most recent call last):
  File "1.py", line 5, in <module>
    c.docstring()
  File "E:\Downloads\test\jedi\api\classes.py", line 477, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "E:\Downloads\test\jedi\api\classes.py", line 240, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "E:\Downloads\test\jedi\api\classes.py", line 754, in docstring
    signature_text = _format_signatures(value)
  File "E:\Downloads\test\jedi\api\classes.py", line 713, in _format_signatures
    for signature in value.get_signatures()
  File "E:\Downloads\test\jedi\inference\value\klass.py", line 231, in get_signatures
    return [sig.bind(self) for sig in init_funcs.get_signatures()]
  File "E:\Downloads\test\jedi\inference\value\klass.py", line 231, in <listcomp>
    return [sig.bind(self) for sig in init_funcs.get_signatures()]
  File "E:\Downloads\test\jedi\inference\signature.py", line 131, in bind
    assert not self.is_bound
AssertionError
```
#### check infomation

Append print code in `jedi\inference\signature.py`  line 130:
```
    def bind(self, value):
        print(self, value)
        assert not self.is_bound
        return BuiltinSignature(value, self._return_string, is_bound=True)
```
last output:
```
<BuiltinSignature: <CompiledObject: <slot wrapper '__init__' of 'object' objects>>> CompiledBoundMethod(<CompiledObject: <slot wrapper '__init__' of 'object' objects>>)
<BuiltinSignature: CompiledBoundMethod(<CompiledObject: <slot wrapper '__init__' of 'object' objects>>)> <ClassValue: <Class: DirEntry@243-256>>
```
find out `jedi\third_party\typeshed\stdlib\3\os\__init__.pyi` line 243:
```
if sys.version_info >= (3, 6):
    class DirEntry(PathLike[AnyStr]):
        # This is what the scandir interator yields
        # The constructor is hidden

        name: AnyStr
        path: AnyStr
```

Add such as `def __init__(self) -> None: ...`,  the problem will disappear.

I think `The constructor is hidden` is important with this issue.

**Comment by davidhalter** [comment]
Thanks for the detailed report!

**Comment by mchoji** [comment]
I'm getting similar errors on Linux, although a bit different from above.

Running this code throws no error.
> import jedi
> completions = jedi.Script("import os;os.").completions()
> for c in completions:
>     print(c)
>     c.docstring()

If I try completions on `pandas` instead:
```python
import pandas
import jedi

completions = jedi.Script("import pandas;pandas.").completions()
for c in completions:
    print(c)
    c.docstring()
```
I get:
```
<Completion: api>
<Completion: array>
<Completion: arrays>
<Completion: bdate_range>
<Completion: Categorical>
<Completion: CategoricalDtype>
<Completion: CategoricalIndex>
<Completion: compat>
<Completion: concat>
<Completion: conftest>
<Completion: core>
<Completion: crosstab>
<Completion: cut>
<Completion: DataFrame>
<Completion: date_range>
<Completion: DateOffset>
<Completion: datetime>
<Completion: DatetimeIndex>
<Completion: DatetimeTZDtype>
<Completion: dependency>
<Completion: describe_option>
<Completion: e>
<Completion: errors>
<Completion: eval>
<Completion: ExcelFile>
<Completion: ExcelWriter>
<Completion: factorize>
<Completion: Float64Index>
<Completion: get_dummies>
<Completion: get_option>
<Completion: get_versions>
<Completion: Grouper>
<Completion: hard_dependencies>
<Completion: HDFStore>
<Completion: Index>
<Completion: IndexSlice>
<Completion: infer_freq>
<Completion: Int16Dtype>
<Completion: Int32Dtype>
<Completion: Int64Dtype>
<Completion: Int64Index>
<Completion: Int8Dtype>
<Completion: Interval>
<Completion: interval_range>
<Completion: IntervalDtype>
<Completion: IntervalIndex>
<BuiltinSignature: <CompiledObject: <slot wrapper '__init__' of 'object' objects>>, <CompiledObject: <slot wrapper '__init__' of 'object' objects>>> CompiledBoundMethod(<CompiledObject: <slot wrapper '__init__' of 'object' objects>>)
<BuiltinSignature: CompiledBoundMethod(<CompiledObject: <slot wrapper '__init__' of 'object' objects>>), CompiledBoundMethod(<CompiledObject: <slot wrapper '__init__' of 'object' objects>>)> <ClassContext: <Class: IntervalIndex@201-1292>>
Traceback (most recent call last):
  File "/tmp/lsp/hello.py", line 9, in <module>
    c.docstring()
  File "/tmp/lsp/.venv/lib/python3.8/site-packages/jedi/api/classes.py", line 479, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/tmp/lsp/.venv/lib/python3.8/site-packages/jedi/api/classes.py", line 242, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "/tmp/lsp/.venv/lib/python3.8/site-packages/jedi/api/classes.py", line 756, in docstring
    signature_text = _format_signatures(context)
  File "/tmp/lsp/.venv/lib/python3.8/site-packages/jedi/api/classes.py", line 715, in _format_signatures
    for signature in context.get_signatures()
  File "/tmp/lsp/.venv/lib/python3.8/site-packages/jedi/evaluate/context/klass.py", line 229, in get_signatures
    return [sig.bind(self) for sig in init_funcs.get_signatures()]
  File "/tmp/lsp/.venv/lib/python3.8/site-packages/jedi/evaluate/context/klass.py", line 229, in <listcomp>
    return [sig.bind(self) for sig in init_funcs.get_signatures()]
  File "/tmp/lsp/.venv/lib/python3.8/site-packages/jedi/evaluate/signature.py", line 108, in bind
    assert not self.is_bound
AssertionError
```
Quite similar unless by the module in a different path (jed/evaluate instead of jedi/inference). I am commenting in here mostly because I am not sure if it corresponds to the same module or not, so maybe this could helps.

### Workaround
Following the suggestion from @bstaint and modifying the offending class (in this case class `IntervalIndex` in pandas/core/indexes/interval.py) made the error stop.

### Environment
I'm using Linux with Python 3.8 with following packages versions:
```
jedi==0.15.1
numpy==1.17.4
pandas==0.25.3
parso==0.5.1
python-dateutil==2.8.1
pytz==2019.3
six==1.13.0
```

**Comment by davidhalter** [comment]
Should be working now, I realized that the assert was not really necessary.
