### ISSUE TITLE
jedi.api.exceptions.InternalError: The subprocess(python-language-server)

### ISSUE THREAD

**Issue by 1123852253** [davidhalter/jedi#1418]
```
code:
import imgui
imgui.

imgui-1.0.0 python-language-server-0.28.3
linuxmint 19.1

astroid-2.3.1 autopep8-1.4.4 future-0.17.1 importlib-metadata-0.23 isort-4.3.21 jedi-0.14.1 lazy-object-proxy-1.4.2 mccabe-0.6.1 more-itertools-7.2.0 parso-0.5.1 pluggy-0.13.0 pycodestyle-2.5.0 pydocstyle-4.0.1 pyflakes-2.1.1 pylint-2.4.2 python-jsonrpc-server-0.2.0 python-language-server-0.28.3 rope-0.14.0 six-1.12.0 snowballstemmer-1.9.1 typed-ast-1.4.0 wrapt-1.11.2 yapf-0.28.0 zipp-0.6.0


error log:
[12:15:56:045 DBG] [Main] [pyls] Starting...
[12:15:56:045 DBG] [Main] [pyls] Command: [/home/mx/.local/bin/pyls]
[12:15:56:045 DBG] [Main] [pyls] Root folder: /home/mx/testpyls
[12:15:56:045 DBG] [Main] [pyls] Language: python
[12:15:56:064 DBG] [Main] [pyls] Sending initialize request...
[12:15:56:064 DBG] [Main] LSPNetworkSTDIO:
Content-Length: 145

{"jsonrpc":"2.0","method":"initialize","id":30,"params":{"processId":2539,"rootUri":"file:/home/mx/testpyls","capabilities":{"textDocument":{}}}}
[12:15:56:064 DBG] Wrote message of size: 168
[12:15:56:588 DBG] [Main] [pyls] Content-Length: 758
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "id": 30, "result": {"capabilities": {"codeActionProvider": true, "codeLensProvider": {"resolveProvider": false}, "completionProvider": {"resolveProvider": false, "triggerCharacters": ["."]}, "documentFormattingProvider": true, "documentHighlightProvider": true, "documentRangeFormattingProvider": true, "documentSymbolProvider": true, "definitionProvider": true, "executeCommandProvider": {"commands": []}, "hoverProvider": true, "referencesProvider": true, "renameProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ",", "="]}, "textDocumentSync": {"change": 2, "save": {"includeText": true}, "openClose": true}, "workspace": {"workspaceFolders": {"supported": true, "changeNotifications": true}}, "experimental": {}}}}
[12:15:56:589 DBG] [Main] [pyls] initialization completed
[12:15:57:814 DBG] [Main] OpenEditor->SendOpenRequest called for: test.py
[12:15:57:815 DBG] [Main] LSPNetworkSTDIO:
Content-Length: 180

{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:/home/mx/testpyls/test.py","languageId":"python","version":1,"text":"import imgui\nimgui."}}}
[12:15:57:815 DBG] Wrote message of size: 203
[12:15:58:780 DBG] [Main] [pyls] Content-Length: 684
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:/home/mx/testpyls/test.py", "diagnostics": [{"source": "pylint", "range": {"start": {"line": 1, "character": 7}, "end": {"line": 1, "character": 6}}, "message": "[syntax-error] invalid syntax (<unknown>, line 2)", "severity": 1, "code": "E0001"}, {"source": "pyflakes", "range": {"start": {"line": 1, "character": 7}, "end": {"line": 1, "character": 14}}, "message": "invalid syntax", "severity": 1}, {"source": "pycodestyle", "range": {"start": {"line": 1, "character": 6}, "end": {"line": 1, "character": 6}}, "message": "W292 no newline at end of file", "code": "W292", "severity": 2}]}}
[12:15:58:780 DBG] [Main] [pyls] Received diagnostic message
[12:15:58:989 DBG] [Main] LSPNetworkSTDIO:
Content-Length: 180

{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:/home/mx/testpyls/test.py","languageId":"python","version":1,"text":"import imgui\nimgui."}}}
[12:15:58:989 DBG] Wrote message of size: 203
[12:15:58:990 DBG] [Main] LSPNetworkSTDIO:
Content-Length: 163

{"jsonrpc":"2.0","method":"textDocument/completion","params":{"textDocument":{"uri":"file:/home/mx/testpyls/test.py"},"position":{"line":1,"character":6}},"id":31}
[12:15:58:990 DBG] Wrote message of size: 186
[12:15:59:427 DBG] [Main] 2021-10-03 12:15:59,424 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 31
Traceback (most recent call last):
File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 141, in wrapper
return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 141, in wrapper
return dct[key]
KeyError: (('get_signature_params',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 251, in _send
is_exception, traceback, result = pickle_load(self._get_process().stdout)
File "/home/mx/.local/lib/python3.6/site-packages/jedi/_compatibility.py", line 478, in pickle_load
return pickle.load(file, encoding='bytes')
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
self._handle_request(message['id'], message['method'], message.get('params'))
File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
handler_result = handler(params)
File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
return method(**(params or {}))
File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 295, in m_text_document__completion
return self.completions(textDocument['uri'], position)
File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 216, in completions
completions = self._hook('pyls_completions', doc_uri, position=position)
File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 132, in _hook
return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in call
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 335, in traced_hookexec
return outcome.get_result()
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
raise ex[1].with_traceback(ex[2])
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 52, in from_call
result = func()
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 333, in
outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 86, in
firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
return outcome.get_result()
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
raise ex[1].with_traceback(ex[2])
File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
res = hook_impl.function(*args)
File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 54, in pyls_completions
return [_format_completion(d, snippet_support and should_include_params) for d in definitions] or None
File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 54, in
return [_format_completion(d, snippet_support and should_include_params) for d in definitions] or None
File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 59, in _format_completion
'label': _label(d),
File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 84, in _label
if definition.type in ('function', 'method') and hasattr(definition, 'params'):
File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 143, in wrapper
result = method(self, *args, **kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/jedi/api/classes.py", line 340, in params
return [Definition(self._evaluator, n) for n in signature.get_param_names()]
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/signature.py", line 49, in get_param_names
param_names = self._function_context.get_param_names()
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/utils.py", line 20, in wrapper
return list(func(*args, **kwargs))
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/context.py", line 127, in get_param_names
signature_params = self.access_handle.get_signature_params()
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 398, in _workaround
return self._cached_results(name, *args, **kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 143, in wrapper
result = method(self, *args, **kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 406, in _cached_results
return self._subprocess.get_compiled_method_return(self.id, name, *args, **kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 122, in wrapper
kwargs=kwargs,
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 219, in run
return self._send(id(evaluator), function, args, kwargs)
File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 263, in _send
stderr,
jedi.api.exceptions.InternalError: The subprocess /usr/bin/python3 has crashed (EOFError('Ran out of input',), stderr=).

[12:15:59:427 DBG] [Main] [pyls] Content-Length: 5408
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "id": 31, "error": {"code": -32602, "message": "jedi.api.exceptions.InternalError: The subprocess /usr/bin/python3 has crashed (EOFError('Ran out of input',), stderr=).", "data": {"traceback": [" File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume\n self._handle_request(message['id'], message['method'], message.get('params'))\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request\n handler_result = handler(params)\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler\n return method(**(params or {}))\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 295, in m_text_document__completion\n return self.completions(textDocument['uri'], position)\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 216, in completions\n completions = self._hook('pyls_completions', doc_uri, position=position)\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 132, in _hook\n return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in call\n return self._hookexec(self, self.get_hookimpls(), kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec\n return self._inner_hookexec(hook, methods, kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 335, in traced_hookexec\n return outcome.get_result()\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result\n raise ex[1].with_traceback(ex[2])\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 52, in from_call\n result = func()\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 333, in \n outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 86, in \n firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall\n return outcome.get_result()\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result\n raise ex[1].with_traceback(ex[2])\n", " File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall\n res = hook_impl.function(*args)\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 54, in pyls_completions\n return [_format_completion(d, snippet_support and should_include_params) for d in definitions] or None\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 54, in \n return [_format_completion(d, snippet_support and should_include_params) for d in definitions] or None\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 59, in _format_completion\n 'label': _label(d),\n", " File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 84, in _label\n if definition.type in ('function', 'method') and hasattr(definition, 'params'):\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 143, in wrapper\n result = method(self, *args, **kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/api/classes.py", line 340, in params\n return [Definition(self._evaluator, n) for n in signature.get_param_names()]\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/signature.py", line 49, in get_param_names\n param_names = self._function_context.get_param_names()\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/utils.py", line 20, in wrapper\n return list(func(*args, **kwargs))\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/context.py", line 127, in get_param_names\n signature_params = self.access_handle.get_signature_params()\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 398, in _workaround\n return self._cached_results(name, *args, **kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 143, in wrapper\n result = method(self, *args, **kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 406, in _cached_results\n return self._subprocess.get_compiled_method_return(self.id, name, *args, **kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 122, in wrapper\n kwargs=kwargs,\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 219, in run\n return self._send(id(evaluator), function, args, kwargs)\n", " File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 263, in _send\n stderr,\n"]}}}
[12:15:59:428 DBG] [Main] [pyls] received an error message
[12:15:59:428 DBG] [Main] [pyls] LanguageServerProtocol::FileClosed(): file /home/mx/testpyls/test.py is not opened
[12:15:59:428 DBG] [Main] OpenEditor->SendOpenRequest called for: test.py
[12:15:59:428 DBG] [Main] LSPNetworkSTDIO:
Content-Length: 180

{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:/home/mx/testpyls/test.py","languageId":"python","version":1,"text":"import imgui\nimgui."}}}
[12:15:59:428 DBG] Wrote message of size: 203
[12:16:00:417 DBG] [Main] [pyls] Content-Length: 684
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:/home/mx/testpyls/test.py", "diagnostics": [{"source": "pylint", "range": {"start": {"line": 1, "character": 7}, "end": {"line": 1, "character": 6}}, "message": "[syntax-error] invalid syntax (<unknown>, line 2)", "severity": 1, "code": "E0001"}, {"source": "pyflakes", "range": {"start": {"line": 1, "character": 7}, "end": {"line": 1, "character": 14}}, "message": "invalid syntax", "severity": 1}, {"source": "pycodestyle", "range": {"start": {"line": 1, "character": 6}, "end": {"line": 1, "character": 6}}, "message": "W292 no newline at end of file", "code": "W292", "severity": 2}]}}
[12:16:00:418 DBG] [Main] [pyls] Received diagnostic message
```

**Comment by davidhalter** [comment]
Typically there is a stderr somewhere, I need that to debug this. Also if you want to help me fix this, just start it with Jedi directly.

`imgui` probably is buggy in a place and that's why Jedi crashes.

**Comment by 1123852253** [comment]
I didn't find more error messages.
I found that 'jedi' work independently is no problem.
But it has problems in python-language-server
The problem trigger function is imgui.begin_child

**Comment by davidhalter** [comment]
Please try playing with the language server. Use `environment=InterpreterEnvironment()` in the `Script` call and report back what happens.

I'm pretty sure this is not a Jedi issue.

**Comment by 1123852253** [comment]
2019-10-16 20:11:12,386 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 12
Traceback (most recent call last):
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: (('get_signature_params',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 251, in _send
    is_exception, traceback, result = pickle_load(self._get_process().stdout)
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/_compatibility.py", line 478, in pickle_load
    return pickle.load(file, encoding='bytes')
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/mx/.local/lib/python3.6/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 305, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 226, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/home/mx/.local/lib/python3.6/site-packages/pyls/python_ls.py", line 143, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 335, in traced_hookexec
    return outcome.get_result()
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 333, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mx/.local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 54, in pyls_completions
    return [_format_completion(d, snippet_support and should_include_params) for d in definitions] or None
  File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 54, in <listcomp>
    return [_format_completion(d, snippet_support and should_include_params) for d in definitions] or None
  File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 59, in _format_completion
    'label': _label(d),
  File "/home/mx/.local/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 84, in _label
    if definition.type in ('function', 'method') and hasattr(definition, 'params'):
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/api/classes.py", line 350, in params
    for n in signature.get_param_names(resolve_stars=True)
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/signature.py", line 49, in get_param_names
    param_names = self._function_context.get_param_names()
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/context.py", line 127, in get_param_names
    signature_params = self.access_handle.get_signature_params()
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 398, in _workaround
    return self._cached_results(name, *args, **kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 406, in _cached_results
    return self._subprocess.get_compiled_method_return(self.id, name, *args, **kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 122, in wrapper
    kwargs=kwargs,
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 219, in run
    return self._send(id(evaluator), function, args, kwargs)
  File "/home/mx/.local/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 263, in _send
    stderr,
jedi.api.exceptions.InternalError: The subprocess /usr/bin/python3.6 has crashed (EOFError('Ran out of input',), stderr=).

**Comment by 1123852253** [comment]
Python2 does not have this problem

**Comment by davidhalter** [comment]
Please try to eliminate the language server from the equation and use Jedi directly instead.

Then do what I asked you to do above. I'm pretty sure it's a problem with the library you're working with.

**Comment by davidhalter** [comment]
Closing, because no feedback. I'm pretty sure this is an issue with the library in question.
