### ISSUE TITLE
error with docstring: 'BuiltinSignature' object has no attribute 'matches_signature'

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1426]
```python
import jedi
source = '''
import numpy
numpy.'''

script = jedi.Script(source, 3, len('numpy.'), '')
completions = script.completions()

for x in completions:
    try:
        doc = x.docstring()
    except Exception as exc:
        print(x, exc)
```

Prints:
```
<Completion: chararray> 'BuiltinSignature' object has no attribute 'matches_signature'
<Completion: matrix> 'BuiltinSignature' object has no attribute 'matches_signature'
<Completion: memmap> 'BuiltinSignature' object has no attribute 'matches_signature'
<Completion: recarray> 'BuiltinSignature' object has no attribute 'matches_signature'
```

```
Traceback (most recent call last):
  File "t-948.py", line 10, in <module>
    doc = x.docstring()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 477, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 240, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 754, in docstring
    signature_text = _format_signatures(value)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 713, in _format_signatures
    for signature in value.get_signatures()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/klass.py", line 230, in get_signatures
    init_funcs = self.py__call__().py__getattribute__('__init__')
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 381, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 381, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/finder.py", line 36, in filter_name
    for filter in filters:
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 154, in get_filters
    class_value = self.get_annotated_class_object()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 339, in get_annotated_class_object
    return self._get_annotated_class_object() or self.class_value
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 323, in _get_annotated_class_object
    if not signature.matches_signature(args):
AttributeError: 'BuiltinSignature' object has no attribute 'matches_signature'
```
Via https://github.com/davidhalter/jedi-vim/issues/948.

```
+a6fcf779d41862de50d25cbe964c64831c7d64bc pythonx/jedi (v0.15.1-203-ga6fcf779)
+ee2995c1108028cd8c6d56df3a00170c93dc9ce6 pythonx/parso (v0.5.1-8-gee2995c)
```

**Comment by davidhalter** [comment]
Thanks! There's definitely still a few bugs on current master, I have refactored a lot of things.

**Comment by davidhalter** [comment]
Should be working now, assert is not really needed.
