### ISSUE TITLE
goto_assignments: NotImplementedError: Not all values need to be converted to contexts

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1427]
Given `t.py`:
```python
import pytest


@pytest.mark.xfail()
def test():
    pass
```

Using `goto_assignments` on `xfail` results in:
```
Traceback (most recent call last):
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 358, in goto
    definitions = script.goto_assignments()
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 277, in goto_assignments
    return self._goto_assignments(follow_imports, follow_builtin_imports, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 305, in _goto_assignments
    names = list(name.goto())
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/names.py", line 169, in goto
    for value in values
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/utils.py", line 26, in unite
    return set(typ for types in iterable for typ in types)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/utils.py", line 26, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/names.py", line 169, in <genexpr>
    for value in values
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 138, in as_context
    return self._as_context(*args, **kwargs)
  File "/home/user/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 251, in _as_context
    raise NotImplementedError('Not all values need to be converted to contexts')
NotImplementedError: Not all values need to be converted to contexts
```

**Comment by davidhalter** [comment]
Thanks for finding this one. It was wrong for years, just surfaced now, because of code changes. (only happened with decorators).
