### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1432]
Python 3.7.5

code:
```
import jedi
script = jedi.Script("")

for c in script.completions():
    c.docstring()
```

traceback
```
Traceback (most recent call last):
  File "E:\Downloads\opencv\jedi\inference\value\klass.py", line 227, in get_filters
    yield next(instance_filters)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "3.py", line 6, in <module>
    c.docstring()
  File "E:\Downloads\opencv\jedi\api\classes.py", line 477, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "E:\Downloads\opencv\jedi\api\classes.py", line 240, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "E:\Downloads\opencv\jedi\api\classes.py", line 754, in docstring
    signature_text = _format_signatures(value)
  File "E:\Downloads\opencv\jedi\api\classes.py", line 713, in _format_signatures
    for signature in value.get_signatures()
  File "E:\Downloads\opencv\jedi\inference\value\klass.py", line 230, in get_signatures
    init_funcs = self.py__call__().py__getattribute__('__init__')
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 381, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "E:\Downloads\opencv\jedi\common\value.py", line 32, in from_sets
    for set_ in sets:
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 381, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "E:\Downloads\opencv\jedi\inference\finder.py", line 36, in filter_name
    for filter in filters:
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
  File "E:\Downloads\opencv\jedi\inference\value\instance.py", line 154, in get_filters
    class_value = self.get_annotated_class_object()
  File "E:\Downloads\opencv\jedi\inference\value\instance.py", line 339, in get_annotated_class_object
    return self._get_annotated_class_object() or self.class_value
  File "E:\Downloads\opencv\jedi\inference\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "E:\Downloads\opencv\jedi\inference\value\instance.py", line 320, in _get_annotated_class_object
    for signature in self.class_value.py__getattribute__('__init__').get_signatures():
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "E:\Downloads\opencv\jedi\inference\finder.py", line 36, in filter_name
    for filter in filters:
  File "E:\Downloads\opencv\jedi\inference\base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
RuntimeError: generator raised StopIteration
```

**Comment by davidhalter** [comment]
Can you please try again on master? I don't see it there. Ok actually I also don't see it on 0.15.3.

**Comment by bstaint** [comment]
git clone master

Linux (Python 3.7.4 ) and Windows (Python 3.7.5) all can reproduct.

under linux Traceback

```
Traceback (most recent call last):
  File "/srv/http/test/jedi/inference/value/klass.py", line 227, in get_filters
    yield next(instance_filters)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "1.py", line 5, in <module>
    c.docstring()
  File "/srv/http/test/jedi/api/classes.py", line 477, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/srv/http/test/jedi/api/classes.py", line 240, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "/srv/http/test/jedi/api/classes.py", line 754, in docstring
    signature_text = _format_signatures(value)
  File "/srv/http/test/jedi/api/classes.py", line 713, in _format_signatures

  File "/srv/http/test/jedi/inference/base_value.py", line 381, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/srv/http/test/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/srv/http/test/jedi/inference/base_value.py", line 381, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/srv/http/test/jedi/inference/base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "/srv/http/test/jedi/inference/base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "/srv/http/test/jedi/inference/finder.py", line 36, in filter_name
    for filter in filters:
  File "/srv/http/test/jedi/inference/base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
  File "/srv/http/test/jedi/inference/value/instance.py", line 154, in get_filters
    class_value = self.get_annotated_class_object()
  File "/srv/http/test/jedi/inference/value/instance.py", line 339, in get_annotated_class_object
    return self._get_annotated_class_object() or self.class_value
  File "/srv/http/test/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/test/jedi/inference/value/instance.py", line 320, in _get_annotated_class_object
    for signature in self.class_value.py__getattribute__('__init__').get_signatures():
  File "/srv/http/test/jedi/inference/base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "/srv/http/test/jedi/inference/base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "/srv/http/test/jedi/inference/finder.py", line 36, in filter_name
    for filter in filters:
  File "/srv/http/test/jedi/inference/base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
RuntimeError: generator raised StopIteration
```

**Comment by bstaint** [comment]
last print(c)  `<Completion: SyntaxWarning>`

**Comment by bstaint** [comment]
`git checkout 18ecb5a74` don't raise RuntimeError.

`git diff  18ecb5a74 066b189bf`

**Comment by davidhalter** [comment]
I can finally reproduce on 3.8.

**Comment by davidhalter** [comment]
Thanks again for the report!
