### ISSUE TITLE
python2.7 numpy context error

### ISSUE THREAD

**Issue by stu105502** [davidhalter/jedi#1442]
Hello,

I have following problem but I can't solve it on my own. When I try to generate the docstring of a very specific context - namely `numpy.char` -, I receive an assertion error in python2.7 when it processes the context `numpy.chararray`. This error does not occur with python3.6. I'm not sure if this error result from a different structure of numpy for python3.6 and python2.7 but I'm quite sure to understand why this error results but not how it can be fixed. The point I observe is that the type's of context that jedi internally processes are different and signature can not be processed with one type:

Python2.7 seems to be incapable to process the signature because the context is from type `Decoratee(<ClassContext: <Class: chararray@1825-2632>>)`. This decoratee seems to be already bound and thereby I receive the assertion error you can see below. On side of python3.6 I can process the code without problems because there the context is of type `<ClassContext: <Class: chararray@1811-2616>>.` I don't understand the jedi-library well enough to find the error but I hope you can help me on this.

by the way: The code works when I use the optional parameter raw=True. So the problem is realy only related to signatures.

### Code

```
import jedi
jedi.settings.call_signatures_validity = 20
source = '''
import numpy as np
np.char'''
script = jedi.Script(source, 3, len('np.char'), 'example.py')
completions = script.completions()
# script.call_signatures()
for completion in completions:
    completion.docstring()
```

### Output

```
File "jedi_test.py", line 14, in <module>
    completion.docstring()
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 479, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 242, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 757, in docstring
    signature_text = _format_signatures(context)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 715, in _format_signatures
    for signature in context.get_signatures()
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/evaluate/context/klass.py", line 229, in get_signatures
    return [sig.bind(self) for sig in init_funcs.get_signatures()]
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/evaluate/signature.py", line 107, in bind
    assert not self.is_bound
AssertionError

```

**Comment by davidhalter** [comment]
There was a major rework of signatures. Please try on master. If it works there I will close this.

On master there are now definitely other bugs that would need fixing.

**Comment by stu105502** [comment]
Thank you,
but right now I receive a complete different error. I will just attach the error message if you guys are interested in fixing in. To be honest, solving this is at the moment not my priority. I would ask you kindly to close the issue but also to read the text below. Could be interesting for you guys. 

I had tried to solve the error in the v0.15.1. I wasn't successful but found something that could probably solve one or two problems on your master-branch: 
The point is if you have defined an `__eq__`-function you can use the `==`-operator but not the `!=`-operator. To actually apply the `!=`-operator on object of a class you have to define the `__ne__`-function for this class. Here is a small [link](https://stackoverflow.com/questions/4352244/python-should-i-implement-ne-operator-based-on-eq) to the topic.
For example, I would advice you to write a `__ne__`-function for the `jedi/common/value.BaseValueSet` class. Maybe you don't have the problem anymore but this solved at least the Decoratee-problem I had.


### New Error

```
Traceback (most recent call last):
  File "jedi_test.py", line 7, in <module>
    completions = script.completions()
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 217, in completions
    return completion.completions()
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/completion.py", line 99, in completions
    completion_names = self._get_value_completions(leaf)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/completion.py", line 208, in _get_value_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/api/completion.py", line 241, in _trailer_completions
    values = infer_call_of_leaf(inferred_context, previous_leaf)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/helpers.py", line 77, in infer_call_of_leaf
    return context.infer_node(leaf)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/context.py", line 210, in infer_node
    return infer_node(self, node)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/syntax_tree.py", line 139, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/syntax_tree.py", line 152, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/syntax_tree.py", line 157, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/syntax_tree.py", line 53, in wrapper
    return func(context, *args, **kwargs)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/syntax_tree.py", line 167, in _infer_node
    return infer_atom(context, element)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/syntax_tree.py", line 292, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/context.py", line 43, in py__getattribute__
    names = self.goto(name_or_str, position)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/context.py", line 32, in goto
    names = finder.filter_name(filters, name_or_str)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/finder.py", line 37, in filter_name
    names = filter.get(string_name)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/filters.py", line 240, in get
    return [n for filter in self._filters for n in filter.get(name)]
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/filters.py", line 82, in get
    _get_definition_names(self._used_names, name),
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/filters.py", line 66, in _get_definition_names
    name for name in names if name.is_definition(include_setitem=True)
  File "/home/ofi/.local/lib/python2.7/site-packages/jedi/inference/filters.py", line 66, in <genexpr>
    name for name in names if name.is_definition(include_setitem=True)
TypeError: is_definition() got an unexpected keyword argument 'include_setitem'
```

**Comment by davidhalter** [comment]
Oh fuck. This is related to parso. You need to get latest parso master as well. Sorry for that.

**Comment by davidhalter** [comment]
> The point is if you have defined an __eq__-function you can use the ==-operator but not the !=-operator.

I actually know about that stuff. It probably just got forgotten. Thanks for finding it! Python 2 has been low priority for a while now. I just fixed it.

**Comment by davidhalter** [comment]
AFAIK this is fixed. Please let me know if that's not the case. If you guys test it, you need both jedi and parso on master branch.
