### ISSUE TITLE
 'list' object has no attribute 'get_signatures'

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1477]
code:
```
import jedi

s = jedi.Script("""
import sys

sys.""")

for c in s.completions():
    print(c)
    c.docstring()
```

output
```
<Completion: tracebacklimit>
<Completion: version>
<Completion: version_info>
Traceback (most recent call last):
  File "9.py", line 10, in <module>
    c.docstring()
  File "E:\Downloads\test\jedi\api\classes.py", line 592, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "E:\Downloads\test\jedi\api\classes.py", line 250, in docstring
    signature_text = self._get_docstring_signature()
  File "E:\Downloads\test\jedi\api\classes.py", line 610, in _get_docstring_sign
ature
    return super(Completion, self)._get_docstring_signature()
  File "E:\Downloads\test\jedi\api\classes.py", line 262, in _get_docstring_sign
ature
    for signature in self._get_signatures(for_docstring=True)
  File "E:\Downloads\test\jedi\api\classes.py", line 505, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
  File "E:\Downloads\test\jedi\api\classes.py", line 505, in <listcomp>
    return [sig for name in names for sig in name.infer().get_signatures()]
AttributeError: 'list' object has no attribute 'get_signatures'
```

**Comment by davidhalter** [comment]
You really find everything :) Thanks!
