### ISSUE TITLE
Completion errors with jedi/lsp/emacs

### ISSUE THREAD

**Issue by SreenivasVRao** [davidhalter/jedi#1484]
Thanks a lot for this really nice package! :)  I'm running into an issue which seems related to #1003... 
```
import numpy as np
x = np.
```
pressing TAB for completion causes this crash to occur:

```
2020-01-28 18:54:40,422 UTC - WARNING - pyls_jsonrpc.endpoint - Received cancel notification for unknown message id 13
2020-01-28 18:54:41,251 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 26
Traceback (most recent call last):
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls/python_ls.py", line 321, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls/python_ls.py", line 239, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls/python_ls.py", line 155, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls/plugins/jedi_completion.py", line 68, in pyls_completions
    return [_format_completion(d, include_params) for d in definitions] or None
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls/plugins/jedi_completion.py", line 68, in <listcomp>
    return [_format_completion(d, include_params) for d in definitions] or None
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/pyls/plugins/jedi_completion.py", line 103, in _format_completion
    if include_params and hasattr(d, 'params') and d.params:
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/jedi/api/classes.py", line 344, in params
    for value in self._name.infer():
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/jedi/inference/names.py", line 237, in infer
    self.tree_name
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[name](*args, **kwargs)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/jedi/plugins/stdlib.py", line 827, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/sreenivas/.envs/py3_ssm/lib/python3.5/site-packages/jedi/inference/syntax_tree.py", line 744, in tree_name_to_values
    raise ValueError("Should not happen. type: %s" % typ)
ValueError: Should not happen. type: del_stmt

```

**Comment by davidhalter** [comment]
I'm pretty sure this is a parso/jedi mismatch. You probably have latest parso, but older jedi.

This is also due to Jedi not pinning parso. I was adviced not to pin it anymore by some people. So Just upgrade Jedi and you'll probably be fine. :)

Closing, because I really think this is a version mismatch, but if you tell me you use both latest jedi and parso, I'm happy to reopen. :)

**Comment by twlz0ne** [comment]
If you're using [pyls](https://github.com/palantir/python-language-server), you should **downgrade** the Jedi to '0.15.2' and the Parso to '0.5.2', because pyls is **incompatible** with the last version of Jedi:

<pre>
⋊> pip install --upgrade jedi
Collecting jedi
  Using cached jedi-0.16.0-py2.py3-none-any.whl (1.1 MB)
Requirement already satisfied, skipping upgrade: parso>=0.5.2 in ~/.pyenv/versions/3.6.6/lib/python3.6/site-packages (from jedi) (0.6.0)
<b>ERROR: python-language-server 0.31.7 has requirement jedi<0.16,>=0.14.1, but you'll have jedi 0.16.0 which is incompatible.</b>
......
</pre>

CC @palantir

**Comment by davidhalter** [comment]
It's actually not incompatible. It's just the way how they set it up. If you can dodge that error, pretty much everything should work fine.
