### ISSUE TITLE
RecursionError with `import pdb; pdb = pdb`

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1504]
The following script causes a recursion error:
```python
import jedi
source = """
import pdb
pdb = pdb  # type: pdb
class MyPdb(pdb.Pdb):
    ...
"""

script = jedi.Script(source, 4, 14, '')
completions = script.completions()
out = [x.complete for x in completions]
print(out)
```

I've noticed this with pdbpp when giving a type hint to https://github.com/pdbpp/pdbpp/blob/cb56e1b6126bb87597684d01af6f18c873be85ee/src/pdbpp.py#L85.

(mypy appears to handle it as expected.)

```
Traceback (most recent call last):
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/gradual/annotation.py", line 54, in _infer_annotation_string
    value_set = context.infer_node(node)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 216, in infer_node
    return infer_node(self, node)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 220, in _infer_node
    return context.infer_node(element.children[0])
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 216, in infer_node
    return infer_node(self, node)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  …
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 165, in _infer_node
    return infer_atom(context, element)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 283, in infer_atom
    if _is_annotation_name(atom):
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 519, in _is_annotation_name
    ancestor = tree.search_ancestor(name, 'param', 'funcdef', 'expr_stmt')
  File "…/vim/plugged/jedi-vim/pythonx/jedi/.venv/lib/python3.8/site-packages/parso/tree.py", line 18, in search_ancestor
    if node is None or node.type in node_types:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by davidhalter** [comment]
Why would you ever write code like this, hahaha :D

**Comment by blueyed** [comment]
> Why would you ever write code like this, hahaha :D

:)
It's from/via pdb++ (https://github.com/pdbpp/pdbpp), which by default hijacks/replaces the real "pdb", so that it gets picked up with regulard `import pdb; pdb.set_trace()` already.

Thanks for fixing it!
