### ISSUE TITLE
completion broken for pyvista under ipython

### ISSUE THREAD

**Issue by jfmoulin** [davidhalter/jedi#1517]
Hello,

Under IPython I get autocompletion for the pyvista package but not for objects it creates:

    In [1]: import pyvista, pylab                                                         
    In [2]: import jedi, sys                                                
    In [3]: import IPython                                                         
    In [4]: ipy = IPython.get_ipython()                                            
    In [5]: data = pylab.rand(10,3)                                                    
    In [6]: mesh = pyvista.PolyData(data)                                          
    In [7]: ipy.Completer.all_completions("mesh.")                                 
    Out[7]: []
    In [8]: ipy.Completer.all_completions("pyvista.")                              
    Out[8]: 
    ['pyvista.appdirs',
     'pyvista.Arrow',
     'pyvista.assert_empty_kwargs',
     'pyvista.BackgroundPlotter',.....

 
If I run the same code in IPython after deactivating Jedi, completion works both for the package and the objects it creates:
    
    In [1]: import IPython                                                         
    In [2]: import pyvista, pylab                                                  
    In [3]: ipy = IPython.get_ipython()                                            
    In [4]: data = p.rand(10,3)                                                    
    In [5]: mesh = pyvista.PolyData(data)                                          
    In [6]: ipy.Completer.all_completions("mesh.")                                 
    Out[6]: 
    ['mesh.ALL_PIECES_EXTENT',
     'mesh.AddCellReference',
     'mesh.AddObserver',
     'mesh.AddReferenceToCell',

The issue https://github.com/davidhalter/jedi/issues/1415 seems very similar to this one but is not fixed for  

    In [9]: jedi.__version__                                                       
    Out[9]: '0.16.0'
    In [10]: IPython.__version__                                                   
    Out[10]: '7.13.0'

**Comment by davidhalter** [comment]
Strange. Thanks for this report! What usually helps me is the debug info. Not sure that works with IPython. But can you try `import jedi; jedi.set_debug_function()`?

**Comment by davidhalter** [comment]
What's `dir(mesh)`?

**Comment by davidhalter** [comment]
This helped:

```
>>> jedi.Interpreter([globals()], 'mesh.')
Traceback (most recent call last):
  File "/home/dave/source/jedi/jedi/api/__init__.py", line 679, in __init__
    namespaces = [dict(n) for n in namespaces]
  File "/home/dave/source/jedi/jedi/api/__init__.py", line 679, in <listcomp>
    namespaces = [dict(n) for n in namespaces]
ValueError: dictionary update sequence element #0 has length 1; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dave/source/jedi/jedi/api/__init__.py", line 681, in __init__
    raise TypeError("namespaces must be a non-empty list of dicts.")
TypeError: namespaces must be a non-empty list of dicts.
>>> jedi.Interpreter('mesh.', [globals()])
<Interpreter: None <jedi.api.environment.InterpreterEnvironment object at 0x7f77ae02a160>>
>>> jedi.Interpreter('mesh.', [globals()]).completions()
Traceback (most recent call last):
  File "/home/dave/source/jedi/jedi/cache.py", line 109, in wrapper
    return dct[key]
KeyError: (('get_dir_infos',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dave/source/jedi/jedi/api/__init__.py", line 231, in completions
    return self.complete(*self._pos, fuzzy=fuzzy)
  File "/home/dave/source/jedi/jedi/api/helpers.py", line 463, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/dave/source/jedi/jedi/api/__init__.py", line 219, in complete
    return self._complete(line, column, **kwargs)
  File "/home/dave/source/jedi/jedi/api/__init__.py", line 227, in _complete
    return completion.complete()
  File "/home/dave/source/jedi/jedi/api/completion.py", line 145, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/home/dave/source/jedi/jedi/api/completion.py", line 262, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "/home/dave/source/jedi/jedi/api/completion.py", line 355, in _complete_trailer
    return cached_name, self._complete_trailer_for_values(values)
  File "/home/dave/source/jedi/jedi/api/completion.py", line 360, in _complete_trailer_for_values
    return complete_trailer(user_context, values)
  File "/home/dave/source/jedi/jedi/api/completion.py", line 504, in complete_trailer
    completion_names += filter.values()
  File "/home/dave/source/jedi/jedi/inference/compiled/value.py", line 490, in values
    needs_type_completions, dir_infos = self.compiled_value.access_handle.get_dir_infos()
  File "/home/dave/source/jedi/jedi/inference/compiled/subprocess/__init__.py", line 398, in _workaround
    return self._cached_results(name, *args, **kwargs)
  File "/home/dave/source/jedi/jedi/cache.py", line 111, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/dave/source/jedi/jedi/inference/compiled/subprocess/__init__.py", line 402, in _cached_results
    return self._subprocess.get_compiled_method_return(self.id, name, *args, **kwargs)
  File "/home/dave/source/jedi/jedi/inference/compiled/subprocess/functions.py", line 21, in get_compiled_method_return
    return getattr(handle.access, attribute)(*args, **kwargs)
  File "/home/dave/source/jedi/jedi/inference/compiled/access.py", line 545, in get_dir_infos
    for name in self.dir()
  File "/home/dave/source/jedi/jedi/inference/compiled/access.py", line 545, in <genexpr>
    for name in self.dir()
  File "/home/dave/source/jedi/jedi/inference/compiled/access.py", line 343, in is_allowed_getattr
    attr, is_get_descriptor = getattr_static(self._obj, name)
  File "/home/dave/source/jedi/jedi/inference/compiled/getattr_static.py", line 164, in getattr_static
    return klass_result, _safe_hasattr(klass_result, '__get__')
  File "/home/dave/source/jedi/jedi/inference/compiled/getattr_static.py", line 123, in _safe_hasattr
    return _check_class(_get_type(obj), name) is not _sentinel
  File "/home/dave/source/jedi/jedi/inference/compiled/getattr_static.py", line 24, in _check_class
    for entry in _static_getmro(klass):
TypeError: 'NoneType' object is not iterable
```

**Comment by davidhalter** [comment]
I guess the tracebacks are ignored in IPython and we cannot see what's happening there. The random exception crashes Jedi.

This is obviously a bug. If you want to work on this, just try to modify the `getattr_static` file.

**Comment by davidhalter** [comment]
Just fixed this, but couldn't find a good test for it. So it's unfortunately untested, because I cannot reproduce it with pure Python.

**Comment by jfmoulin** [comment]
Hey! Thanks a bunch for the fast reaction. Will test and have a look at getattr_static.py.

**Comment by jfmoulin** [comment]
So, with the same code, I used pudb.set_trace() inside the last function ( _check_class),
this is the trace:
any use ?
```
Traceback (most recent call last):                                                                                                           
│  File "/usr/local/lib/python3.6/dist-packages/jedi/cache.py", line 109, in wrapper                                                          │
│    return dct[key]                                                                                                                                         │
│KeyError: (('get_dir_infos',), frozenset())                                                                                                                 │
│                                                                                                                                                            │
│During handling of the above exception, another exception occurred:                                                                                         │
│                                                                                                                                                            │
│Traceback (most recent call last):                                                                                                                          │
│  File "/usr/local/lib/python3.6/dist-packages/jedi/inference/compiled/getattr_static.py", line 29, in │
│    return entry.__dict__[attr]                                                                                                                             │
│KeyError: 'ALL_PIECES_EXTENT
```

**Comment by davidhalter** [comment]
As I said, I already fixed it, but thanks anyway :)

I ended up installing pyvista.
