### ISSUE TITLE
Jedi crashes on pandas.NamedAgg

### ISSUE THREAD

**Issue by Foxboron** [davidhalter/jedi#1529]
Seems like there is something the typshed integration doesn't like about [pandas.NamedAgg](https://github.com/pandas-dev/pandas/blob/v1.0.3/pandas/core/groupby/generic.py#L80). The error is confusing and It's unclear to me where the problem is.

```python
py3.8 >>> import jedi
py3.8 >>> jedi.Script("import pandas as pd; pd.Named").complete()[0].get_signatures()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/api/classes.py", line 510, in get_signatures
    for s in self._get_signatures()
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/api/classes.py", line 504, in _get_signatures
    names = convert_names([self._name], prefer_stubs=True)
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/conversion.py", line 138, in convert_names
    return _python_to_stub_names(names, fallback_to_python=prefer_stubs)
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/conversion.py", line 106, in _python_to_stub_names
    values = convert_values(n.infer(), only_stubs=True)
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/conversion.py", line 148, in convert_values
    return ValueSet.from_sets(
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/conversion.py", line 149, in <genexpr>
    to_stub(value)
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/conversion.py", line 170, in to_stub
    stub_module = _load_stub_module(value.get_root_context().get_value())
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/conversion.py", line 85, in _load_stub_module
    return _try_to_load_stub_cached(
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/typeshed.py", line 141, in _try_to_load_stub_cached
    _try_to_load_stub(inference_state, import_names, *args, **kwargs)
  File "/home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/jedi/inference/gradual/typeshed.py", line 153, in _try_to_load_stub
    if parent_module_value is None and len(import_names) > 1:
TypeError: object of type 'NoneType' has no len()
```

```shell
(.venv) λ python-language-server develop» pip list 
Package                Version                 Location                                                                                                                                         
---------------------- ----------------------- -------------------------------------------------------------------------------------------------------------------------------------------------
astroid                2.3.3                   
attrs                  19.3.0                  
autopep8               1.5                     
coverage               5.0.4                   
cycler                 0.10.0                  
isort                  4.3.21                  
jedi                   0.16.0                  
kiwisolver             1.1.0                   
lazy-object-proxy      1.4.3                   
matplotlib             3.2.1                   
mccabe                 0.6.1                   
mock                   4.0.2                   
more-itertools         8.2.0                   
mypy                   0.770                   
mypy-extensions        0.4.3                   
numpy                  1.18.2                  
packaging              20.3                    
pandas                 1.0.3                   
parso                  0.6.2                   
pip                    19.2.3                  
pluggy                 0.13.1                  
py                     1.8.1                   
pycodestyle            2.5.0                   
pydocstyle             5.0.2                   
pyflakes               2.1.1                   
pylint                 2.4.4                   
pyparsing              2.4.6                   
PyQt5                  5.14.1                  
PyQt5-sip              12.7.1                  
pytest                 5.4.1                   
pytest-cov             2.8.1                   
python-dateutil        2.8.1                   
python-jsonrpc-server  0.3.4                   
python-language-server 0.31.9+0.g21833ea.dirty /home/fox/Git/prosjekter/Python/python-language-server/.venv/lib/python3.8/site-packages/python_language_server-0.31.9+0.g21833ea.dirty-py3.8.egg
pytz                   2019.3                  
rope                   0.16.0                  
setuptools             41.2.0                  
six                    1.14.0                  
snowballstemmer        2.0.0                   
typed-ast              1.4.1                   
typing-extensions      3.7.4.1                 
ujson                  1.35                    
versioneer             0.18                    
wcwidth                0.1.9                   
wrapt                  1.11.2                  
yapf                   0.29.0                  
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by stonebig** [comment]
may it be related to the vendored version of typeshed being too old (may 2019) ?

**Comment by davidhalter** [comment]
It's definitely a Jedi issue. Jedi tries to load stubs if possible, but that's not the issue.  The question is just if it was fixed in master (I doubt it). The question is: Why is import_names ever None at this point. This shouldn't be the case.

**Comment by FFY00** [comment]
This was fixed in d574162da32052ca378cf08b3429eef2fd11100d.

**Comment by davidhalter** [comment]
@FFY00 Thanks a lot for looking this up!

@Foxboron Could you try to verify with the latest master? https://jedi.readthedocs.io/en/latest/docs/installation.html#manual-installation-from-github

**Comment by stonebig** [comment]
Would it be possible Jeid leaves a wheel artifact in one of the Appveyor build ? It would make things easier to check with jedi-master.

**Comment by davidhalter** [comment]
Why is this not good enough: `sudo pip install -e git://github.com/davidhalter/jedi.git#egg=jedi`?

**Comment by stonebig** [comment]
hi sorry, it's indeed good enough, no need for artifact

**Comment by Foxboron** [comment]
This is indeed fixed with master. Would it be possible with a patch release as this break the API?

**Comment by davidhalter** [comment]
No, sorry. I'll try to make a new release soon. I'm only trying to fix stuff in parso, now.

**Comment by FFY00** [comment]
@davidhalter btw, the value comes from `ModuleValue` which is optional https://github.com/davidhalter/jedi/blob/604029568c532f8fe3013d4637157515315ca757/jedi/inference/value/module.py#L152.

**Comment by davidhalter** [comment]
@FFY00 How do you know that? I have never seen you contribute here :) Did you just look that up? :) 

Happy to see you contribute in the future ;-)

**Comment by FFY00** [comment]
I just saw the issue and decided to look into it. I am not really a jedi user.
