### ISSUE TITLE
Using astropy.units.quantity_input decorator on __init__ crashes completition

### ISSUE THREAD

**Issue by noc0lour** [davidhalter/jedi#1550]
I'm using jedi inside of `anaconda-mode` in Emacs for autocompletion and if a class in a module uses [`astropy.units.quantity_input`](https://github.com/astropy/astropy/blob/d91f4441ee45f406efa3a470fa092392b806190d/astropy/units/decorators.py#L243) as decorator I get following traceback:
```
Traceback (most recent call last):
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
  File "<string>", line 126, in company_complete
  File "<string>", line 128, in <listcomp>
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/api/classes.py", line 592, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/api/classes.py", line 250, in docstring
    signature_text = self._get_docstring_signature()
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/api/classes.py", line 610, in _get_docstring_signature
    return super(Completion, self)._get_docstring_signature()
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/api/classes.py", line 262, in _get_docstring_signature
    for signature in self._get_signatures(for_docstring=True)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/api/classes.py", line 505, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/api/classes.py", line 505, in <listcomp>
    return [sig for name in names for sig in name.infer().get_signatures()]
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/base_value.py", line 415, in get_signatures
    return [sig for c in self._set for sig in c.get_signatures()]
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/base_value.py", line 415, in <listcomp>
    return [sig for c in self._set for sig in c.get_signatures()]
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/value/klass.py", line 218, in get_signatures
    init_funcs = self.py__call__(args).py__getattribute__('__init__')
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/base_value.py", line 395, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/base_value.py", line 395, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/finder.py", line 35, in filter_name
    for filter in filters:
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/value/instance.py", line 176, in get_filters
    class_value = self.get_annotated_class_object()
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/value/instance.py", line 350, in get_annotated_class_object
    return self._get_annotated_class_object() or self.class_value
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/value/instance.py", line 339, in _get_annotated_class_object
    all_annotations = py__annotations__(signature.value.tree_node)
  File "/home/andrej/.emacs.d/.cache/anaconda-mode/0.1.13/jedi-0.16.0-py3.8.egg/jedi/inference/gradual/annotation.py", line 189, in py__annotations__
    for function_param in funcdef.get_params():
AttributeError: 'Class' object has no attribute 'get_params'
```

I've tried to look into how to reproduce/create simple test case for this but somehow it escapes me how to do this.
I've tested with anaconda-mode on two files:
`test.py`
```
import astropy.units as u

class my_class:
    @u.quantity_input
    def __init__(self):
        print("foo")

    def foo():
        print("bar")
```

`test2.py`
```
import test

import astropy.units as u

test.my_class
```
If I try to auto-complete inside `test2.py` with the decorator on `__init__` I get the traceback & crash with other decorators it works fine. 
Maybe you have a pointer what is the special case for this decorator? As other decorators work fine on `__init__`.

**Comment by davidhalter** [comment]
> I've tried to look into how to reproduce/create simple test case for this but somehow it escapes me how to do this.

Yeah, this is very hard to reproduce. In general with these kind of issues I find/fix the issue in a few minutes and then I use `git stash` and try to find a reproduction case. In this case Jedi probably thought that the decorator returned some class or maybe instance.

Thanks a lot for the detailed report and for trying to reproduce this!

**Comment by noc0lour** [comment]
Thanks a lot! Surprisingly quick fix :+1:
