### ISSUE TITLE
Script('\n').help(1, 0): 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by muffinmad** [davidhalter/jedi#1556]
With Jedi 0.17.0/latest master:

```
Python 3.7.4 (default, Sep 28 2019, 16:39:19) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jedi import Script
>>> Script('\n').help(1, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mad/.virtualenvs/jedi/lib/python3.7/site-packages/jedi/api/helpers.py", line 482, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/Users/mad/.virtualenvs/jedi/lib/python3.7/site-packages/jedi/api/__init__.py", line 475, in help
    if leaf.type in ('keyword', 'operator', 'error_leaf'):
AttributeError: 'NoneType' object has no attribute 'type'
```

Thanks!

**Comment by davidhalter** [comment]
Thanks for finding this one!
