### ISSUE TITLE
crash on Python 3.7

### ISSUE THREAD

**Issue by Akuli** [davidhalter/jedi#1563]
```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.__version__
'0.15.2'
>>> jedi.Script('import os\nos.').completions()
Traceback (most recent call last):
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/api/__init__.py", line 217, in completions
    return completion.completions(fuzzy)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/api/completion.py", line 94, in completions
    return self._completions(fuzzy, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/api/completion.py", line 109, in _completions
    completion_names = self._get_value_completions(leaf)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/api/completion.py", line 218, in _get_value_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/api/completion.py", line 270, in _trailer_completions
    completion_names += filter.values()
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 243, in values
    return [n for filter in self._filters for n in filter.values()]
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 243, in <listcomp>
    return [n for filter in self._filters for n in filter.values()]
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 92, in values
    for name_key in self._used_names
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 87, in _convert_names
    return [self.name_class(self.parent_context, name) for name in names]
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 87, in <listcomp>
    return [self.name_class(self.parent_context, name) for name in names]
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 95, in <genexpr>
    **filter_kwargs
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 122, in _filter
    return list(self._check_flows(names))
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/filters.py", line 137, in _check_flows
    origin_scope=self._origin_scope
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/flow_analysis.py", line 78, in reachability_check
    return _break_check(context, value_scope, first_flow_scope, node)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/flow_analysis.py", line 93, in _break_check
    reachable = _check_if(context, flow_node)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/flow_analysis.py", line 113, in _check_if
    types = context.infer_node(node)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/context.py", line 210, in infer_node
    return infer_node(self, node)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 148, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 161, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 166, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 62, in wrapper
    return func(context, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 248, in _infer_node
    return infer_or_test(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 453, in infer_or_test
    types = context.infer_node(next(iterator))
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/context.py", line 210, in infer_node
    return infer_node(self, node)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 148, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 161, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 166, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 62, in wrapper
    return func(context, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 248, in _infer_node
    return infer_or_test(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 471, in infer_or_test
    context.infer_node(right))
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 524, in _infer_comparison
    for left in left_values
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 525, in <genexpr>
    for right in right_values
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 601, in _infer_comparison_part
    if left.is_compiled() and right.is_compiled():
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/base_value.py", line 287, in __getattr__
    return getattr(self._wrapped_value, name)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/utils.py", line 75, in wrapper
    return func(*args, **kwds)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/base_value.py", line 295, in _wrapped_value
    return self._get_wrapped_value()
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/value/iterable.py", line 202, in _get_wrapped_value
    TupleGenericManager(self._get_generics())
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/value/iterable.py", line 194, in _get_generics
    return (self.merge_types_of_iterate().py__class__(),)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/base_value.py", line 58, in merge_types_of_iterate
    for lazy_value in self.iterate(contextualized_node, is_async)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/base_value.py", line 57, in <genexpr>
    lazy_value.infer()
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/value/iterable.py", line 346, in py__iter__
    for addition in check_array_additions(self._defining_context, self):
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/value/dynamic_arrays.py", line 40, in check_array_additions
    return _internal_check_array_additions(context, sequence)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/value/dynamic_arrays.py", line 110, in _internal_check_array_additions
    cut_own_trailer=True
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/helpers.py", line 106, in infer_call_of_leaf
    values = context.infer_node(base)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/context.py", line 210, in infer_node
    return infer_node(self, node)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 148, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 161, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 166, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 62, in wrapper
    return func(context, *args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 176, in _infer_node
    return infer_atom(context, element)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 301, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/names.py", line 237, in infer
    self.tree_name
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[name](*args, **kwargs)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 827, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/akuli/porcu/env/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 744, in tree_name_to_values
    raise ValueError("Should not happen. type: %s" % typ)
ValueError: Should not happen. type: del_stmt
>>> 
```

**Comment by davidhalter** [comment]
Please upgrade your Jedi/parso versions. They are quite old. I'm pretty sure this was fixed a while ago.

**Comment by Akuli** [comment]
This doesn't happen with latest jedi
