### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'iter_return_stmts'

### ISSUE THREAD

**Issue by d-ryzhikov** [davidhalter/jedi#1573]
Discovered while using with deoplete-jedi in vim.

Stacktrace:
```
[deoplete] Traceback (most recent call last):
  File "/home/dmitry/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 194, in _gather_results
    result = self._get_result(context, source)
  File "/home/dmitry/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 254, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 189, in gather_candidates
    completions = self.get_completions(script)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 137, in get_completions
    return script.completions()
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 291, in completions
    return self.complete(*self._pos, fuzzy=fuzzy)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/helpers.py", line 465, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 275, in complete
    return self._complete(line, column, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 283, in _complete
    return completion.complete()
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 145, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 262, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 355, in _complete_trailer
    return cached_name, self._complete_trailer_for_values(values)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 360, in _complete_trailer_for_values
    return complete_trailer(user_context, values)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 509, in complete_trailer
    completion_names += _complete_getattr(user_context, value)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 547, in _complete_getattr
    for return_stmt in tree_node.iter_return_stmts():
AttributeError: 'NoneType' object has no attribute 'iter_return_stmts'
```

**Comment by davidhalter** [comment]
Thanks for the report.

Just fixed this. It was of course a bug - but a very obscure one. I'm still wondering what code exactly caused it, because my reproduction case looks very strange :).

**Comment by d-ryzhikov** [comment]
Thanks for the fix. Gonna try this out.
I noticed that it happens when I work with [pydantic](https://github.com/samuelcolvin/pydantic)'s `BaseModel`s after putting a dot after BaseModel instance (which I assume triggers attribute lookup).

**Comment by d-ryzhikov** [comment]
I pulled the latest master and unfortunately a new error occurs.
```
[deoplete] Traceback (most recent call last):                                                                                                                                                  
  File "/home/dmitry/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 194, in _gather_results
    result = self._get_result(context, source)
  File "/home/dmitry/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 254, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 189, in gather_candidates
    completions = self.get_completions(script)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 137, in get_completions
    return script.completions()
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 291, in completions
    return self.complete(*self._pos, fuzzy=fuzzy)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/helpers.py", line 482, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 275, in complete
    return self._complete(line, column, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 283, in _complete
    return completion.complete()
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 172, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 284, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 397, in _complete_trailer
    return cached_name, self._complete_trailer_for_values(values)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 402, in _complete_trailer_for_values
    return complete_trailer(user_context, values)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 551, in complete_trailer
    completion_names += _complete_getattr(user_context, value)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 589, in _complete_getattr
    if tree_node.type != 'funcdef':
AttributeError: 'NoneType' object has no attribute 'type'
Error from jedi: 'NoneType' object has no attribute 'type'.  Use :messages / see above for error details.
```

**Comment by davidhalter** [comment]
Try again, should be good now. Turns out I probably understand now why this has happened.

**Comment by d-ryzhikov** [comment]
Tried reproducing with pydantic model - it works now. Thanks! 🎉
