### ISSUE TITLE
error on "extract variable" action - it's ok?

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1583]
![Screenshot from 2020-05-14 18-32-18](https://user-images.githubusercontent.com/4154978/81954211-41286c00-9611-11ea-8f6e-833ded80e960.png)

```
Python 3.8
Init: cuda_project_man
Startup: 860ms, plugins: 30ms (project_man 31ms)
Init: cuda_addonman
Init: cuda_hilite_occurrences
Init: cuda_python_intel
Python IntelliSense:  <Python 3.8.2 in /usr>
Goto "/home/user/.config/cudatext/py/cuda_ext/cd_ext_tabs.py", Line 305
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_python_intel/__init__.py", line 338, in refactoring_extract_variable
    item = self.app.script.extract_variable(
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/api/__init__.py", line 62, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/api/__init__.py", line 715, in extract_variable
    return self._extract_variable(line, column, **kwargs)  # Python 2...
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/api/helpers.py", line 465, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/api/__init__.py", line 727, in _extract_variable
    return extract_variable(
  File "/home/user/.config/cudatext/py/cuda_python_intel/jedi/api/refactoring/extract.py", line 25, in extract_variable
    raise RefactoringError(message)
jedi.api.exceptions.RefactoringError: Cannot extract a "trailer"
```

is this ok? selection has incorrect ) char.

**Comment by Alexey-T** [comment]
@OlehL FYI

**Comment by davidhalter** [comment]
This is IMO expected. You are selecting the `)` that is part of `int(...)`. Jedi then assumes that you want to extract everything after int, which is simply not possible. Just don't select that character and you don't get that error.
