### ISSUE TITLE
Error during editing doctest

### ISSUE THREAD

**Issue by d-ryzhikov** [davidhalter/jedi#1585]
I use jedi via nvim deoplete-jedi. The error occurs when I edit doctest.
Traceback:
```
[deoplete] Traceback (most recent call last):                                                                                                                                                
  File "/home/dmitry/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 194, in _gather_results
    result = self._get_result(context, source)
  File "/home/dmitry/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 254, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 189, in gather_candidates
    completions = self.get_completions(script)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 137, in get_completions
    return script.completions()
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 291, in completions
    return self.complete(*self._pos, fuzzy=fuzzy)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/helpers.py", line 482, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 275, in complete
    return self._complete(line, column, **kwargs)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 283, in _complete
    return completion.complete()
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 169, in complete
    prefixed_completions = self._complete_in_string(start_leaf, string)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 460, in _complete_in_string
    return self._complete_code_lines(relevant_code_lines)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 474, in _complete_code_lines
    return Completion(
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 172, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/home/dmitry/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 259, in _complete_python
    current_line = self._code_lines[self._position[0] - 1][:self._position[1]]
IndexError: list index out of range
```

**Comment by davidhalter** [comment]
Can you give us the code that causes this?

**Comment by d-ryzhikov** [comment]
```python
from typing import Mapping

ProductAmounts = Mapping[str, int]

def get_remainder(a: ProductAmounts, b: ProductAmounts):
    """Subtract product amounts `b` from `a` and return the remainder.

    >>> a = {"foo": 13, "bar": 37, "spam": 42}
    >>> b = {"foo": 3, "bar": 30, "spam": 42}
    >>> get_remainder(a, b) == {
    ...     "foo": 10, "bar": 7
    ... }
    True
    >>> get_remainder({"foo": 32}, {"foo": 32}) == {}
    True
    """
    res = {}
    for code, amount in a.items():
        remainder = amount - b.get(code, 0)
        if remainder > 0:
            res[code] = remainder
    return res
```

**Comment by davidhalter** [comment]
Where do you have your cursor?

**Comment by d-ryzhikov** [comment]
On `get_remainder` call definition in the doctest.

**Comment by davidhalter** [comment]
I tried to reproduce, but your description is still to vague. Can you tell me the exact position where you completed?

It would be even better to have direct `jedi.Script` calls.

**Comment by d-ryzhikov** [comment]
I'm not sure what you mean by `jedi.Script` calls.
The error happens right after I type `>>> ` and start typing the `get_remainder` function name, on the 2nd character in function name.

**Comment by davidhalter** [comment]
This is still completely unclear, because you have two get_remainder calls.

**Comment by d-ryzhikov** [comment]
This happens on both calls. You can reproduce it removing the docstring completely and starting to write it from the start. As soon as you start writing a doctest with `>>> ` and start writing a function name, the error is thrown.

**Comment by davidhalter** [comment]
What I mean by `jedi.Script` calls is that you write a reproduction with `jedi`. This could look like this:

```
code = '''\
# your code here
'''
jedi.Script(code).complete(line, column)
```

If you can reproduce an error this way, I have an easier time to reproduce usually.

**Comment by davidhalter** [comment]
For whatever reason, I can reproduce now:

```
import jedi

code = '''\
from typing import Mapping

ProductAmounts = Mapping[str, int]

def get_remainder(a: ProductAmounts, b: ProductAmounts):
    """Subtract product amounts `b` from `a` and return the remainder.

    >>> a = {"foo": 13, "bar": 37, "spam": 42}
    >>> b = {"foo": 3, "bar": 30, "spam": 42}
    >>> get_remainder(a, b) == {
    ...     "foo": 10, "bar": 7
    ... }
    True
    >>> get_remainder({"foo": 32}, {"foo": 32}) == {}
    True
    """
    res = {}
    for code, amount in a.items():
        remainder = amount - b.get(code, 0)
        if remainder > 0:
            res[code] = remainder
    return res
'''

jedi.Script(code).complete(10, 8)
```

**Comment by hwalinga** [comment]
Maybe you can create a github issue template that explains the `jedi.Script(code).complete(line, column)` part so that people more often will provide you with easier ways to reproduce issues. 

And thank you for the fix btw.

**Comment by davidhalter** [comment]
Yeah, might be an option in the future :) It's just that most of the time I can reproduce if people give me the exact position, so it's usually not that important. It's just nice if I don't even have to write the test, but can copy it :).
