### ISSUE TITLE
jedi infer() does not work with my custom AWS S3-based Python importer

### ISSUE THREAD

**Issue by asterkin** [davidhalter/jedi#1591]
I get a ValueError: not enough values to unpack (expected 1, got 0) exception when I'm trying to run jedi inside of AWS Lambda powered with my S3-based Python importer. I manged to make parso and jedi working with two small Python standard compliant patches, but with this one I feel clueless. Here is the stack trace, debug output and the test function code. It works locally. Any ideas where to look at would be highly appreciated. The ultimate goal is to explore possibilities of having a completely serverless Python IDE.

1. Debug output and Stack trace:

```
dbg: Start: infer
dbg: infer_node <Name: variable@16,4>@(16, 4) in MixedModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: context.goto <Name: variable@16,4> in (MixedModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)): [<TreeNameDefinition: string_name=variable start_pos=(15, 4)>]
dbg: global search_module 'builtins': <CompiledModule: <module 'builtins' (built-in)>>
dbg: infer_node PythonNode(atom, [<Operator: [>, PythonNode(testlist_comp, [<Name: keyword@15,17>, <Operator: ,>, <Name: f@15,26>, <Operator: ,>, <Name: C@15,29>, <Operator: ,>, <Name: x@15,32>]), <Operator: ]>])@(15, 16) in ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: iterate <SequenceLiteralValue of PythonNode(atom, [<Operator: [>, PythonNode(testlist_comp, [<Name: keyword@15,17>, <Operator: ,>, <Name: f@15,26>, <Operator: ,>, <Name: C@15,29>, <Operator: ,>, <Name: x@15,32>]), <Operator: ]>])>
dbg: infer_node <Name: keyword@15,17>@(15, 17) in ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: context.goto <Name: keyword@15,17> in (ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)): [<TreeNameDefinition: string_name=keyword start_pos=(2, 7)>]
dbg: global search_module 'keyword': <ModuleValue: keyword@3-95 is_stub=False>
dbg: after import: S{<ModuleValue: keyword@3-95 is_stub=False>}
dbg: context.names_to_types: [<TreeNameDefinition: string_name=keyword start_pos=(2, 7)>] -> S{<ModuleValue: keyword@3-95 is_stub=False>}
dbg: infer_node <Name: f@15,26>@(15, 26) in ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: context.goto <Name: f@15,26> in (ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)): [<TreeNameDefinition: string_name=f start_pos=(12, 4)>]
dbg: context.names_to_types: [<TreeNameDefinition: string_name=f start_pos=(12, 4)>] -> S{<FunctionValue: <Function: f@12-14>>}
dbg: infer_node <Name: C@15,29>@(15, 29) in ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: context.goto <Name: C@15,29> in (ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)): [<TreeNameDefinition: string_name=C start_pos=(4, 6)>]
dbg: context.names_to_types: [<TreeNameDefinition: string_name=C start_pos=(4, 6)>] -> S{<ClassValue: <Class: C@4-6>>}
dbg: infer_node <Name: x@15,32>@(15, 32) in ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: context.goto <Name: x@15,32> in (ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)): [<TreeNameDefinition: string_name=x start_pos=(10, 0)>]
dbg: infer_expr_stmt <ExprStmt: x = D()@10,0> (<Name: x@10,0>)
dbg: infer_node PythonNode(atom_expr, [<Name: D@10,4>, PythonNode(trailer, [<Operator: (>, <Operator: )>])])@(10, 4) in ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: infer_node <Name: D@10,4>@(10, 4) in ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
dbg: context.goto <Name: D@10,4> in (ModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)): [<TreeNameDefinition: string_name=D start_pos=(7, 6)>]
dbg: context.names_to_types: [<TreeNameDefinition: string_name=D start_pos=(7, 6)>] -> S{<ClassValue: <Class: D@7-9>>}
dbg: infer_trailer: PythonNode(trailer, [<Operator: (>, <Operator: )>]) in S{<ClassValue: <Class: D@7-9>>}
dbg: execute: <ClassValue: <Class: D@7-9>> <TreeArguments: None>
dbg: context.goto 'object' in (<CompiledModule: <module 'builtins' (built-in)>>): [<CompiledName: (<CompiledValueName: string_name=builtins>).object>]
dbg: context.names_to_types: [<CompiledName: (<CompiledValueName: string_name=builtins>).object>] -> S{<CompiledValue: <class 'object'>>}
dbg: execute result: S{<TreeInstance of <ClassValue: <Class: D@7-9>>(<TreeArguments: None>)>} in <ClassValue: <Class: D@7-9>>
dbg: infer_expr_stmt result S{<TreeInstance of <ClassValue: <Class: D@7-9>>(<TreeArguments: None>)>}
dbg: context.names_to_types: [<TreeNameDefinition: string_name=x start_pos=(10, 0)>] -> S{<TreeInstance of <ClassValue: <Class: D@7-9>>(<TreeArguments: None>)>}
dbg: Dynamic array search for <SequenceLiteralValue of PythonNode(atom, [<Operator: [>, PythonNode(testlist_comp, [<Name: keyword@15,17>, <Operator: ,>, <Name: f@15,26>, <Operator: ,>, <Name: C@15,29>, <Operator: ,>, <Name: x@15,32>]), <Operator: ]>])>
dbg: Start: Resolve lazy value wrapper
dbg: iterate <SequenceLiteralValue of PythonNode(atom, [<Operator: [>, PythonNode(testlist_comp, [<Name: keyword@15,17>, <Operator: ,>, <Name: f@15,26>, <Operator: ,>, <Name: C@15,29>, <Operator: ,>, <Name: x@15,32>]), <Operator: ]>])>
dbg: global search_module 'types': <ModuleValue: types@1-267 is_stub=False>
Module: S{<ModuleValue: types@1-267 is_stub=False>}
dbg: context.goto 'FunctionType' in (<ModuleValue: types@1-267 is_stub=False>): [<TreeNameDefinition: string_name=FunctionType start_pos=(12, 0)>]
dbg: infer_expr_stmt <ExprStmt: FunctionType = type(_f)@12,0> (<Name: FunctionType@12,0>)
dbg: infer_node PythonNode(atom_expr, [<Name: type@12,15>, PythonNode(trailer, [<Operator: (>, <Name: _f@12,20>, <Operator: )>])])@(12, 15) in ModuleContext(<ModuleValue: types@1-267 is_stub=False>)
dbg: infer_node <Name: type@12,15>@(12, 15) in ModuleContext(<ModuleValue: types@1-267 is_stub=False>)
dbg: context.goto <Name: type@12,15> in (ModuleContext(<ModuleValue: types@1-267 is_stub=False>)): [<CompiledName: (<CompiledValueName: string_name=builtins>).type>]
dbg: context.names_to_types: [<CompiledName: (<CompiledValueName: string_name=builtins>).type>] -> S{<CompiledValue: <class 'type'>>}
dbg: infer_trailer: PythonNode(trailer, [<Operator: (>, <Name: _f@12,20>, <Operator: )>]) in S{<CompiledValue: <class 'type'>>}
dbg: infer_node <Name: _f@12,20>@(12, 20) in ModuleContext(<ModuleValue: types@1-267 is_stub=False>)
dbg: context.goto <Name: _f@12,20> in (ModuleContext(<ModuleValue: types@1-267 is_stub=False>)): [<TreeNameDefinition: string_name=_f start_pos=(11, 4)>]
dbg: context.names_to_types: [<TreeNameDefinition: string_name=_f start_pos=(11, 4)>] -> S{<FunctionValue: <Function: _f@11-12>>}
dbg: builtin start <CompiledValue: <class 'type'>>
Module: S{<ModuleValue: types@1-267 is_stub=False>}
dbg: context.goto 'FunctionType' in (<ModuleValue: types@1-267 is_stub=False>): [<TreeNameDefinition: string_name=FunctionType start_pos=(12, 0)>]
warning: catched stmt recursion: <ExprStmt: FunctionType = type(_f)@12,0> @(12, 0)
dbg: context.names_to_types: [<TreeNameDefinition: string_name=FunctionType start_pos=(12, 0)>] -> S{}
Name: S{}
dbg: End: Resolve lazy value wrapper
dbg: End: infer
not enough values to unpack (expected 1, got 0): ValueError
Traceback (most recent call last):
  File "/var/task/index.py", line 17, in handle_event
    return _test_infer_type()
  File "./service/python/_test_infer_type.py", line 34, in _test_infer_type
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/api/helpers.py", line 482, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/api/__init__.py", line 311, in infer
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/api/__init__.py", line 331, in _infer
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/api/helpers.py", line 164, in infer
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/__init__.py", line 179, in infer
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/helpers.py", line 80, in infer_call_of_leaf
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/context.py", line 222, in infer_node
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 156, in infer_node
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/cache.py", line 44, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/debug.py", line 82, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 82, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 184, in _infer_node
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 309, in infer_atom
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/context.py", line 75, in py__getattribute__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 414, in from_sets
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/context.py", line 75, in <genexpr>
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/names.py", line 282, in infer
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/__init__.py", line 21, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/stdlib.py", line 844, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 741, in tree_name_to_values
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 298, in iterate_values
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 414, in from_sets
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 297, in <genexpr>
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 466, in iterate
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/iterable.py", line 361, in py__iter__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/dynamic_arrays.py", line 40, in check_array_additions
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/cache.py", line 44, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/debug.py", line 82, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/dynamic_arrays.py", line 76, in _internal_check_array_additions
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/iterable.py", line 190, in name
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/compiled/value.py", line 423, in __init__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 320, in __getattr__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/utils.py", line 75, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/cache.py", line 111, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 328, in _wrapped_value
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/iterable.py", line 205, in _get_wrapped_value
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/cache.py", line 44, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/iterable.py", line 197, in _cached_generics
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/iterable.py", line 338, in _get_generics
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/iterable.py", line 193, in _get_generics
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 461, in py__class__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 398, in __init__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 461, in <genexpr>
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/function.py", line 164, in py__class__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/helpers.py", line 198, in values_from_qualified_names
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 481, in py__getattribute__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 414, in from_sets
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 481, in <genexpr>
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 81, in py__getattribute__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 414, in from_sets
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 81, in <genexpr>
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/names.py", line 282, in infer
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/__init__.py", line 21, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/stdlib.py", line 844, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 746, in tree_name_to_values
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 82, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 384, in infer_expr_stmt
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/debug.py", line 82, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 417, in _infer_expr_stmt
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/context.py", line 222, in infer_node
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 156, in infer_node
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/cache.py", line 44, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/debug.py", line 82, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 82, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 208, in _infer_node
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/syntax_tree.py", line 280, in infer_trailer
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 472, in execute
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 414, in from_sets
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 472, in <genexpr>
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/__init__.py", line 21, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/stdlib.py", line 131, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/stdlib.py", line 173, in wrapper
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/plugins/stdlib.py", line 219, in builtins_type
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 461, in py__class__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 398, in __init__
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/base_value.py", line 461, in <genexpr>
  File "/tmp/tmp9_1lc7fp/lib/python/jedi/inference/value/function.py", line 164, in py__class__
ValueError: not enough values to unpack (expected 1, got 0)
```

 2. Test Function Code:

```
 from jedi import settings, Interpreter, debug

settings.cache_directory = '/tmp'
debug.debug_function = debug.print_to_stdout
debug.enable_warning = True
debug.enable_notice = True
namespaces = [locals()]

source_1 = '''
import keyword

class C:
    pass

class D:
    pass

x = D()

def f():
    pass

for variable in [keyword, f, C, x]:
    variable'''

source_2 = '''
import json
json.lo'''


def _test_infer_type():
    '''test type inference'''
    script = Interpreter(source_1, namespaces)
    defs = sorted(script.infer(), key=lambda d: d.line)
    types = [str(d.type) for d in defs]
    assert(['module', 'class', 'instance', 'function'] == types)

    return 'OK'
```

**Comment by davidhalter** [comment]
BTW: You can use ` ``` ` to format your code. You can also click the <> icon when you select some text to do the same.

**Comment by davidhalter** [comment]
Have you tried the master branch?

**Comment by asterkin** [comment]
Hi, Dave!

thanks for coming to me back. Will use ``` in the future (know Markdown
fairly well, just forgot it's relevant for issue report). Here is what I
did in my Makefile:

clone:
rm -fR ./$(library)
git clone --recurse-submodules https://github.com/davidhalter/jedi
(cd ./$(library); git apply ../patch)

I assume it picked up the last stable version. The patch is below. It does
the same, just in a more portable way. Ignore the helpers part, I just
injected some debugging printouts. I will remove it.

diff --git a/jedi/inference/gradual/typeshed.py
b/jedi/inference/gradual/typeshed.py
index bcf839a0..57c88126 100644
--- a/jedi/inference/gradual/typeshed.py
+++ b/jedi/inference/gradual/typeshed.py
@@ -54,12 +54,14 @@ def _create_stub_map(directory):
     # Create a dictionary from the tuple generator.
     return dict(generate())

+import pkgutil

 def _get_typeshed_directories(version_info):
     check_version_list = ['2and3', str(version_info.major)]
     for base in ['stdlib', 'third_party']:
         base = os.path.join(TYPESHED_PATH, base)
-        base_list = os.listdir(base)
+        # base_list = os.listdir(base)
+        base_list = pkgutil.iter_modules(base)
         for base_list_entry in base_list:
             match = re.match(r'(\d+)\.(\d+)$', base_list_entry)
             if match is not None:
diff --git a/jedi/inference/helpers.py b/jedi/inference/helpers.py
index 3e4d3952..0b6b2e6c 100644
--- a/jedi/inference/helpers.py
+++ b/jedi/inference/helpers.py
@@ -193,7 +193,11 @@ def parse_dotted_names(nodes, is_import_from,
until_node=None):


 def values_from_qualified_names(inference_state, *names):
-    return
inference_state.import_module(names[:-1]).py__getattribute__(names[-1])
+    m = inference_state.import_module(names[:-1])
+    print(f'Module: {m}')
+    n = m.py__getattribute__(names[-1])
+    print(f'Name: {n}')
+    return n


 def is_big_annoying_library(context):

**Comment by davidhalter** [comment]
You seem to be patching something. I'm interested in a pure Jedi run without any shenanigans and a clear statement which commit you are using.

**Comment by asterkin** [comment]
I'm using the master branch. Without patching shenanigans it fails (error
trace is below). Please, notice, jedi, as well as parso is imported from S3
using my custom Importer and listdir will not work. The change is safe and
simple - use pkgutil.iter_modules instead. We patched 10s of Open Source
libraries this way. Let me know if I'm still doing something wrong.

dbg: Start: infer
  dbg: infer_node <Name: variable@16,4>@(16, 4) in
MixedModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)
  dbg: context.goto <Name: variable@16,4> in
(MixedModuleContext(<ModuleValue: __main__@2-16 is_stub=False>)):
[<TreeNameDefinition: string_name=variable start_pos=(15, 4)>]
   dbg: global search_module 'builtins': <CompiledModule: <module
'builtins' (built-in)>>
dbg: End: infer
[Errno 2] No such file or directory:
'/var/task/s3:/caios-shelf-asher/caios-py-jedi/jedi/third_party/typeshed/stdlib':
FileNotFoundError
Traceback (most recent call last):
  File "/var/task/index.py", line 17, in handle_event
    return _test_infer_type()
  File "./service/python/_test_infer_type.py", line 34, in _test_infer_type
  File "/tmp/tmptat3q0c2/lib/python/jedi/api/helpers.py", line 482, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/api/__init__.py", line 311, in
infer
  File "/tmp/tmptat3q0c2/lib/python/jedi/api/__init__.py", line 331, in
_infer
  File "/tmp/tmptat3q0c2/lib/python/jedi/api/helpers.py", line 164, in infer
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/__init__.py", line 179,
in infer
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/helpers.py", line 80, in
infer_call_of_leaf
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/context.py", line 222,
in infer_node
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
156, in infer_node
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
169, in _infer_node_if_inferred
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/cache.py", line 44, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
174, in _infer_node_cached
  File "/tmp/tmptat3q0c2/lib/python/jedi/debug.py", line 82, in wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
82, in wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
184, in _infer_node
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
309, in infer_atom
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/context.py", line 75, in
py__getattribute__
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/base_value.py", line
414, in from_sets
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/context.py", line 75, in
<genexpr>
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/names.py", line 282, in
infer
  File "/tmp/tmptat3q0c2/lib/python/jedi/plugins/__init__.py", line 21, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/plugins/stdlib.py", line 844, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
739, in tree_name_to_values
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/base_value.py", line
363, in infer
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/context.py", line 222,
in infer_node
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
156, in infer_node
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
169, in _infer_node_if_inferred
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/cache.py", line 44, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
174, in _infer_node_cached
  File "/tmp/tmptat3q0c2/lib/python/jedi/debug.py", line 82, in wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/syntax_tree.py", line
70, in wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/cache.py", line 44, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/__init__.py", line 129,
in builtins_module
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/__init__.py", line 112,
in import_module
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/imports.py", line 347,
in import_module_by_names
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/imports.py", line 347,
in <listcomp>
  File "/tmp/tmptat3q0c2/lib/python/jedi/plugins/__init__.py", line 21, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/plugins/flask.py", line 20, in
wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/gradual/typeshed.py",
line 123, in wrapper
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/gradual/typeshed.py",
line 144, in try_to_load_stub_cached
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/gradual/typeshed.py",
line 212, in _try_to_load_stub
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/gradual/typeshed.py",
line 245, in _load_from_typeshed
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/gradual/typeshed.py",
line 90, in _cache_stub_file_map
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/gradual/typeshed.py",
line 26, in _merge_create_stub_map
  File "/tmp/tmptat3q0c2/lib/python/jedi/inference/gradual/typeshed.py",
line 62, in _get_typeshed_directories
FileNotFoundError: [Errno 2] No such file or directory:
'/var/task/s3:/caios-shelf-asher/caios-py-jedi/jedi/third_party/typeshed/stdlib'

**Comment by davidhalter** [comment]
There's a FileNotFoundError in there. You probably messed something up with the installation.

> Please, notice, jedi, as well as parso is imported from S3
using my custom Importer and listdir will not work

I'm sorry to say it, but that's a terrible idea (I'm not exaggerating). If Jedi doesn't work with it, I pretty much don't care.

I'm closing, because this is really not something I ever want to support. If there's an actual error, please install Jedi normally.

**Comment by asterkin** [comment]
You do not have to agree with this particular way of cloud innovation.
Thanks for your support.

Best regards,
Asher

**Comment by davidhalter** [comment]
Let's call it innovation :)

I work in a cloud company. It is our business to run an S3. It's not like I'm against cloud innovation at all, but a lot of the stuff people are pushing is just a bad idea.

**Comment by asterkin** [comment]
Of course it's a bad idea!
But this bad idea helps me with putting almost any monstrous ML library
into Lambda thus bypassing the 250MB disk space limitation. And it works
exceptionally well via S3 mount on Cloud9. Cloud9 has an outdated version
of jedi, btw.
I have no conceptual barrier for maintaining complete meta-database in
DynamoDB for all onboarded libraries (about 50 today) - just a mater of
some effort to implement it. I could implement Python import (or any other
language) on the top of Dynamo if I need better performance.  The list of
extremely bad ideas is pretty long.

Not sure you really want to continue this debate, just in case the general
direction is outlined in:
https://medium.com/analytics-vidhya/if-your-computer-is-cloud-how-its-operating-system-should-look-like-24f62e274a95
.
I tried to fined your profile without success. Mine are here:

   -

   Medium <https://medium.com/@asher.sterkin>
   -

   Slideshare <https://www.slideshare.net/AsherSterkin/presentations>
   -

   Linkedin <https://www.linkedin.com/in/asher-sterkin-10a1063/>
   -

   Twitter <https://twitter.com/asterkin?lang=en>
   -



It was a pleasure to e-meet you, and thanks again for your valuable
comments.

Best regards,
Asher

**Comment by PeterJCLaw** [comment]
@asterkin a couple of quick thoughts, though I agree with @davidhalter that this doesn't look like an issue on Jedi's side:
- `pkgutil.iter_modules` has different behaviour to `os.listdir` (notably it returns no matches when scanning a directory containing only directories, which is what it's doing in the case you've patched)
- the error you got without the patch (`FileNotFoundError` around `.../jedi/third_party/typeshed/stdlib`) looks very much like the error you get if you run `jedi` without the submodules present. While your post (https://github.com/davidhalter/jedi/issues/1591#issuecomment-632668088) about how the patch works showed you recursing submodules on clone, maybe check that that is also happening correctly in your real S3 backend?

**Comment by davidhalter** [comment]
You can find me on twitter: twitter.com/jedidjah_ch, but I'm not very active.

> But this bad idea helps me with putting almost any monstrous ML library
into Lambda thus bypassing the 250MB disk space limitation. And it works
exceptionally well via S3 mount on Cloud9. Cloud9 has an outdated version
of jedi, btw.

Yeah, I guess that's just where I would stop. Not saying that there is never a reason to do it... If your already in deep troubles you might just need to commit to it, because your company forces you to :). But in any case I would probably set up normal instances, do some sort of load balancing/auto scaling. It's probably cheaper both financially and in maintenance. You might not even need auto scaling, if there's not big shifts in traffic. Deploy all that with ansible/whatever and have infrastructure that is more "reasonable". In that case you also have less of a vendor lock-in.
