### ISSUE TITLE
Non-graceful handling of cache permission errors

### ISSUE THREAD

**Issue by nitrocalcite** [davidhalter/jedi#1615]
For legacy reasons, sometimes I need to run `ipython` with `sudo`.  Later, I run `ipython` without `sudo`.  Trying to autocomplete will then occasionally cause this rather verbose stack trace (below) to come out of `jedi`.  

It looks like there's a `PermissionError` trying to open root-owned pickles in `~/.cache/jedi/`, which isn't caught anywhere.  Purging the cache by deleting the `~/.cache/jedi` seems to fix the problem, although it's a bit hard to tell (because I don't know what kinds of operations will trigger a call to read cached pickles, so I just have to try autocompleting until it fails).

Anyway, this isn't immediately obvious from the stack trace, because it's huge, and the underlying `PermissionError` is not the last exception (there's a chain of 4).  Any chance that this could be handled more gracefully, perhaps catching the exception, ignoring the pickle, and raising a warning instead?

I'm running `jedi 0.17.0` on Ubuntu 16.04, if that helps.  Thanks!

```
Traceback (most recent call last):
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/cache.py", line 109, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/cache.py", line 109, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 126, in _get_completions
    for c in completions:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/core/completer.py", line 1875, in _completions
    signature = _make_signature(jm)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/core/completer.py", line 991, in _make_signature
    return '(%s)'% ', '.join([f for f in (_formatparamchildren(p) for p in completion.params) if f])
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/cache.py", line 111, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/api/classes.py", line 479, in params
    for signature in self._get_signatures():
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/api/classes.py", line 561, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/api/classes.py", line 561, in <listcomp>
    return [sig for name in names for sig in name.infer().get_signatures()]
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/cache.py", line 111, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/compiled/mixed.py", line 124, in infer
    tree_values = tree_value.py__getattribute__(self.string_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 90, in py__getattribute__
    values = self.py__getattribute__alternatives(n)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/instance.py", line 239, in py__getattribute__alternatives
    return self.execute_function_slots(names, name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/instance.py", line 130, in execute_function_slots
    for name in names
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/instance.py", line 130, in <genexpr>
    for name in names
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 390, in execute_with_values
    return ValueSet.from_sets(c.execute_with_values(*args, **kwargs) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 390, in <genexpr>
    return ValueSet.from_sets(c.execute_with_values(*args, **kwargs) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 47, in execute_with_values
    return self.inference_state.execute(self, arguments)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 123, in wrapper
    return call()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 107, in call
    return callback(value, arguments=arguments)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/pytest.py", line 25, in wrapper
    return callback(value, arguments)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/__init__.py", line 119, in execute
    value_set = value.py__call__(arguments=arguments)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/instance.py", line 480, in py__call__
    return function_execution.infer()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/function.py", line 360, in infer
    return self.get_return_values()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/recursion.py", line 87, in wrapper
    result = func(self, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/function.py", line 234, in get_return_values
    check = flow_analysis.reachability_check(self, funcdef, r)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/flow_analysis.py", line 83, in reachability_check
    return _break_check(context, value_scope, first_flow_scope, node)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/flow_analysis.py", line 98, in _break_check
    reachable = _check_if(context, flow_node)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/flow_analysis.py", line 118, in _check_if
    types = context.infer_node(node)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/context.py", line 222, in infer_node
    return infer_node(self, node)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 237, in _infer_node
    return infer_or_test(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 467, in infer_or_test
    context.infer_node(right))
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/context.py", line 222, in infer_node
    return infer_node(self, node)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 189, in _infer_node
    value_set = infer_trailer(context, value_set, trailer)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 256, in infer_trailer
    name_or_str=node
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 396, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 396, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 87, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 87, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/names.py", line 282, in infer
    self.tree_name
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 842, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 709, in tree_name_to_values
    types = infer_expr_stmt(context, node, tree_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 365, in infer_expr_stmt
    return _infer_expr_stmt(context, stmt, seek_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 398, in _infer_expr_stmt
    value_set = context.infer_node(rhs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/context.py", line 222, in infer_node
    return infer_node(self, node)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 189, in _infer_node
    value_set = infer_trailer(context, value_set, trailer)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 261, in infer_trailer
    return atom_values.execute(args)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 387, in execute
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 387, in <genexpr>
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 132, in wrapper
    return call()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 107, in call
    return callback(value, arguments=arguments)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/pytest.py", line 25, in wrapper
    return callback(value, arguments)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/__init__.py", line 119, in execute
    value_set = value.py__call__(arguments=arguments)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/klass.py", line 142, in py__call__
    if self.is_typeddict():
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/klass.py", line 265, in is_typeddict
    if method():
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/value/klass.py", line 254, in is_typeddict
    for cls in lazy_cls.infer():
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/lazy_value.py", line 48, in infer
    return self.context.infer_node(self.data)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/context.py", line 222, in infer_node
    return infer_node(self, node)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 165, in _infer_node
    return infer_atom(context, element)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 290, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/names.py", line 282, in infer
    self.tree_name
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 842, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 715, in tree_name_to_values
    types = imports.infer_import(context, tree_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 62, in infer_import
    analysis_errors=False
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 396, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 396, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 87, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/base_value.py", line 87, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/names.py", line 282, in infer
    self.tree_name
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 842, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 715, in tree_name_to_values
    types = imports.infer_import(context, tree_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 55, in infer_import
    _prepare_infer_import(module_context, tree_name)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 118, in _prepare_infer_import
    return from_import_name, tuple(import_path), import_node.level, importer.follow()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 261, in follow
    self._inference_state, self.import_path, sys_path, self._module_context
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 347, in import_module_by_names
    ) for parent_module_value in value_set
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 347, in <listcomp>
    ) for parent_module_value in value_set
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/plugins/flask.py", line 20, in wrapper
    return callback(inference_state, import_names, module_context, *args, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/gradual/typeshed.py", line 113, in wrapper
    for p in parent_module_values
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/common/value.py", line 69, in from_sets
    for set_ in sets:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/gradual/typeshed.py", line 113, in <genexpr>
    for p in parent_module_values
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 420, in import_module
    is_package=is_pkg,
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/imports.py", line 436, in _load_python_module
    cache_path=settings.cache_directory,
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/__init__.py", line 197, in parse
    return self.parse_and_get_code(*args, **kwargs)[0]
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/jedi/inference/__init__.py", line 194, in parse_and_get_code
    return grammar.parse(code=code, path=path, file_io=file_io, **kwargs), code
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/parso/grammar.py", line 79, in parse
    return self._parse(code=code, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/parso/grammar.py", line 154, in _parse
    cache_path=cache_path)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/parso/cache.py", line 174, in save_module
    _save_to_file_system(hashed_grammar, path, item, cache_path=cache_path)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/parso/cache.py", line 178, in _save_to_file_system
    with open(_get_hashed_path(hashed_grammar, path, cache_path=cache_path), 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/home/empad/.cache/jedi/CPython-37-33/593d51111df2a7984c5d14ec09b1fb4e1c5fa86889ca077d5efe8caf989e2ebc-6487045d9c44b10d4917e4901fe3a8778f99fc867eb78979b28be5589cd71f13.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 546, in interact
    code = self.prompt_for_code()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 474, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 778, in run_async
    return await _run_async2()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 766, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 867, in cancel_and_wait_for_background_tasks
    await task
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1684, in async_completer
    document, complete_event
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 270, in get_completions_async
    document, complete_event
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    print_tb(e)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/traceback.py", line 344, in extract
    for f, lineno in frame_gen:
  File "/home/empad/miniconda3/envs/PyX/lib/python3.7/traceback.py", line 309, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'PermissionError' object has no attribute 'tb_frame'

If you suspect this is an IPython 7.15.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by davidhalter** [comment]
@isidentical What do you think about this? This might look like a Jedi issue, but it's very much related to parso. IMO this should probably be a Jedi fix, where Jedi ignores PermissionErrors.

**Comment by isidentical** [comment]
Well, in either case, it would require a minimal amount of work and since we suppress `OSError`/`FileNotFoundError` in a bunch of places we can just do the same thing for this. It's your call.
