### ISSUE TITLE
Error from jedi: Should not happen

### ISSUE THREAD

**Issue by Nudin** [davidhalter/jedi#1647]
Using jedi via deoplete, I sometimes get errors with very long stack trace.
```
Muster nicht gefunden 
[deoplete] Traceback (most recent call last): 
  File "/home/michi/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 194, in _gather_results  
    result = self._get_result(context, source)
  File "/home/michi/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 254, in _get_result      
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/michi/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper   
    return func(self, *args, **kwargs)   
  File "/home/michi/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 200, in gather_candidates 
    completions = self.get_completions(script)
  File "/home/michi/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper   
    return func(self, *args, **kwargs)   
  File "/home/michi/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 145, in get_completions   
    return script.completions()   
  File "/usr/lib/python3.8/site-packages/jedi/api/__init__.py", line 291, in completions 
    return self.complete(*self._pos, fuzzy=fuzzy)    
  File "/usr/lib/python3.8/site-packages/jedi/api/helpers.py", line 465, in wrapper      
    return func(self, line, column, *args, **kwargs) 
  File "/usr/lib/python3.8/site-packages/jedi/api/__init__.py", line 275, in complete    
    return self._complete(line, column, **kwargs)    
  File "/usr/lib/python3.8/site-packages/jedi/api/__init__.py", line 283, in _complete   
    return completion.complete()  
  File "/usr/lib/python3.8/site-packages/jedi/api/completion.py", line 123, in complete  
    prefixed_completions = complete_dict(
  File "/usr/lib/python3.8/site-packages/jedi/api/strings.py", line 42, in complete_dict 
    values = infer_call_of_leaf(context, before_bracket_leaf)    
  File "/usr/lib/python3.8/site-packages/jedi/inference/helpers.py", line 80, in infer_call_of_leaf  
    return context.infer_node(leaf)      
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 222, in infer_node  
    return infer_node(self, node) 
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 137, in infer_node     
    return _infer_node_if_inferred(context, element) 
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred    
    return _infer_node_cached(context, element)      
  File "/usr/lib/python3.8/site-packages/jedi/inference/cache.py", line 43, in wrapper   
    rv = function(obj, *args, **kwargs)  
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached  
    return _infer_node(context, element) 
  File "/usr/lib/python3.8/site-packages/jedi/debug.py", line 82, in wrapper 
    return func(*args, **kwargs)  
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper  
    return func(context, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 165, in _infer_node    
    return infer_atom(context, element)  
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 290, in infer_atom     
    return context.py__getattribute__(atom, position=position)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in py__getattribute__  
    values = ValueSet.from_sets(name.infer() for name in names)  
  File "/usr/lib/python3.8/site-packages/jedi/common/value.py", line 69, in from_sets    
    for set_ in sets: 
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in <genexpr>    
    values = ValueSet.from_sets(name.infer() for name in names)  
  File "/usr/lib/python3.8/site-packages/jedi/inference/names.py", line 279, in infer    
    return tree_name_to_values(   
  File "/usr/lib/python3.8/site-packages/jedi/plugins/__init__.py", line 21, in wrapper  
    return built_functions[public_name](*args, **kwargs)
      File "/usr/lib/python3.8/site-packages/jedi/inference/cache.py", line 43, in wrapper     
    rv = function(obj, *args, **kwargs)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached 
    return _infer_node(context, element)  
  File "/usr/lib/python3.8/site-packages/jedi/debug.py", line 82, in wrapper 
    return func(*args, **kwargs)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper      
    return func(context, *args, **kwargs) 
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 165, in _infer_node 
    return infer_atom(context, element)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 290, in infer_atom  
    return context.py__getattribute__(atom, position=position) 
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in py__getattribute__      
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/common/value.py", line 69, in from_sets      
    for set_ in sets:
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in <genexpr> 
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/inference/names.py", line 279, in infer      
    return tree_name_to_values(    
  File "/usr/lib/python3.8/site-packages/jedi/plugins/__init__.py", line 21, in wrapper    
    return built_functions[public_name](*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/plugins/stdlib.py", line 842, in wrapper     
    return func(inference_state, context, tree_name)    
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 709, in tree_name_to_values
    types = infer_expr_stmt(context, node, tree_name)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper      
    return func(context, *args, **kwargs) 
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 365, in infer_expr_stmt    
    return _infer_expr_stmt(context, stmt, seek_name)   
  File "/usr/lib/python3.8/site-packages/jedi/debug.py", line 82, in wrapper 
    return func(*args, **kwargs)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 410, in _infer_expr_stmt   
    left_values = context.py__getattribute__(name, position=stmt.start_pos)  
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in py__getattribute__      
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/common/value.py", line 69, in from_sets      
    for set_ in sets:
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in <genexpr> 
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/inference/names.py", line 279, in infer      
    return tree_name_to_values(    
  File "/usr/lib/python3.8/site-packages/jedi/plugins/__init__.py", line 21, in wrapper    
    return built_functions[public_name](*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/plugins/stdlib.py", line 842, in wrapper     
    return func(inference_state, context, tree_name)    
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 709, in tree_name_to_values
    types = infer_expr_stmt(context, node, tree_name)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper      
    return func(context, *args, **kwargs) 
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 365, in infer_expr_stmt    
    return _infer_expr_stmt(context, stmt, seek_name)   
  File "/usr/lib/python3.8/site-packages/jedi/debug.py", line 82, in wrapper 
    return func(*args, **kwargs)
      File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 410, in _infer_expr_stmt   
    left_values = context.py__getattribute__(name, position=stmt.start_pos)  
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in py__getattribute__      
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/common/value.py", line 69, in from_sets      
    for set_ in sets:
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in <genexpr> 
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/inference/names.py", line 279, in infer      
    return tree_name_to_values(    
  File "/usr/lib/python3.8/site-packages/jedi/plugins/__init__.py", line 21, in wrapper    
    return built_functions[public_name](*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/plugins/stdlib.py", line 842, in wrapper     
    return func(inference_state, context, tree_name)    
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 709, in tree_name_to_values
    types = infer_expr_stmt(context, node, tree_name)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 63, in wrapper      
    return func(context, *args, **kwargs) 
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 365, in infer_expr_stmt    
    return _infer_expr_stmt(context, stmt, seek_name)   
  File "/usr/lib/python3.8/site-packages/jedi/debug.py", line 82, in wrapper 
    return func(*args, **kwargs)   
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 410, in _infer_expr_stmt   
    left_values = context.py__getattribute__(name, position=stmt.start_pos)  
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in py__getattribute__      
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/common/value.py", line 69, in from_sets      
    for set_ in sets:
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in <genexpr> 
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/inference/names.py", line 279, in infer      
    return tree_name_to_values(    
  File "/usr/lib/python3.8/site-packages/jedi/plugins/__init__.py", line 21, in wrapper    
    return built_functions[public_name](*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/plugins/stdlib.py", line 842, in wrapper     
    return func(inference_state, context, tree_name)    
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 729, in tree_name_to_values
    raise ValueError("Should not happen. type: %s" % typ)      
ValueError: Should not happen. type: name 
Error from jedi: Should not happen. type: name.  Use :messages / see above for error details.
```

**Comment by Nudin** [comment]
Please tell me if/what I should do to help to debug this.

**Comment by davidhalter** [comment]
Is there a way you could provide me with the code that led to this? I'm not sure I will be able to debug this. Also what are your Jedi/Parso versions?

**Comment by Nudin** [comment]
- python-parso: 0.7.1
- python-jedi: 0.17.0
- The source code is [here](https://github.com/Nudin/mpv-script-directory/blob/a643f3e370ea71e9dd9c4b0b54d6bd6e1983c68b/querystars.py#L68), I can reproduce the error while changing the key (not just the string) in Line 68 by two letters. Here is an screencast:
![Peek 2020-08-04 00-59](https://user-images.githubusercontent.com/509205/89235598-c3ac4080-d5ee-11ea-84c0-b8c0e4529068.gif)

**Comment by davidhalter** [comment]
Can you upgrade to latest Jedi and retest please?

**Comment by Nudin** [comment]
> Can you upgrade to latest Jedi and retest please?

No difference with jedi-0.17.2-py2.py3-none-any.whl

**Comment by davidhalter** [comment]
Great, I can reproduce. Thanks! (And also WTF why does this happen)

**Comment by davidhalter** [comment]
I just realized that I had never properly implemented the walrus operator. So all of this should now work.
