### ISSUE TITLE
atom / autocomplete-python & args completion : No such file or directory (parser/grammar3.8.txt)

### ISSUE THREAD

**Issue by msharp1** [davidhalter/jedi#1668]
autocomplete-python 1.16.0 package in Atom 1.51.0

As asked in the debug error message below, I'm reporting the issue here.
The issue prevents completion of arguments to work when triggered with opening parenthesis.

Ubuntu 20.04.1
```
$ python --version
Python 3.8.2
```

(In a yellow warning box after activating debug in autocomplete-python package configuration)
> Looks like this error originated from Jedi. Please do not report such issues in autocomplete-python issue tracker. Report them directly to Jedi. Turn off outputProviderErrors setting to hide such errors in future. Traceback output:

```
Traceback (most recent call last):
  File "/home/martin/.atom/packages/autocomplete-python/lib/jedi/parser/__init__.py", line 56, in load_grammar
    return _loaded_grammars[path]
KeyError: '/home/martin/.atom/packages/autocomplete-python/lib/jedi/parser/grammar3.8.txt'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/martin/.atom/packages/autocomplete-python/lib/completion.py", line 376, in watch
    self._process_request(request)
  File "/home/martin/.atom/packages/autocomplete-python/lib/completion.py", line 338, in _process_request
    script = jedi.api.Script(
  File "/home/martin/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 126, in __init__
    self._grammar = load_grammar(version='%s.%s' % sys.version_info[:2])
  File "/home/martin/.atom/packages/autocomplete-python/lib/jedi/parser/__init__.py", line 58, in load_grammar
    return _loaded_grammars.setdefault(path, generate_grammar(path))
  File "/home/martin/.atom/packages/autocomplete-python/lib/jedi/parser/pgen2/pgen.py", line 393, in generate_grammar
    p = ParserGenerator(filename)
  File "/home/martin/.atom/packages/autocomplete-python/lib/jedi/parser/pgen2/pgen.py", line 18, in __init__
    stream = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/martin/.atom/packages/autocomplete-python/lib/jedi/parser/grammar3.8.txt'
```

**Comment by keisuke-nakata** [comment]
This error is actually due to autocomplete-python. (It misses `grammar3.8.txt` file as you noticed.)

See https://github.com/autocomplete-python/autocomplete-python/pull/436

**Comment by davidhalter** [comment]
It's probably an outdated parso version.
