### ISSUE TITLE
Getting ValueError: Should not happen. type: name when I type an opening paren on a Python `re` function call

### ISSUE THREAD

**Issue by malan88** [davidhalter/jedi#1673]
Complete Traceback:
```
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "completion.py", line 670, in watch
    response = self._process_request(rq)
  File "completion.py", line 640, in _process_request
    return self._serialize_arguments(script, line, column, request["id"])
  File "completion.py", line 309, in _serialize_arguments
    "results": self._get_call_signatures_with_args(script, line, column),
  File "completion.py", line 148, in _get_call_signatures_with_args
    call_signatures = script.get_signatures(line, column)
  File "/usr/lib/python3.8/site-packages/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/api/__init__.py", line 562, in get_signatures
    definitions = helpers.cache_signatures(
  File "/usr/lib/python3.8/site-packages/jedi/cache.py", line 69, in wrapper
    value = next(generator)
  File "/usr/lib/python3.8/site-packages/jedi/api/helpers.py", line 461, in cache_signatures
    yield infer(
  File "/usr/lib/python3.8/site-packages/jedi/api/helpers.py", line 164, in infer
    return inference_state.infer(context, leaf)
  File "/usr/lib/python3.8/site-packages/jedi/inference/__init__.py", line 179, in infer
    return helpers.infer_call_of_leaf(context, name)
  File "/usr/lib/python3.8/site-packages/jedi/inference/helpers.py", line 105, in infer_call_of_leaf
    values = context.infer_node(base)
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 222, in infer_node
    return infer_node(self, node)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 157, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 170, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/usr/lib/python3.8/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 175, in _infer_node_cached
    return _infer_node(context, element)
  File "/usr/lib/python3.8/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 83, in wrapper
    return func(context, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 185, in _infer_node
    return infer_atom(context, element)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 310, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/inference/base_value.py", line 427, in from_sets
    for set_ in sets:
  File "/usr/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/usr/lib/python3.8/site-packages/jedi/inference/names.py", line 279, in infer
    return tree_name_to_values(
  File "/usr/lib/python3.8/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jedi/plugins/stdlib.py", line 862, in wrapper
    return func(inference_state, context, tree_name)
  File "/usr/lib/python3.8/site-packages/jedi/plugins/django.py", line 176, in wrapper
    result = func(inference_state, context, tree_name)
  File "/usr/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 767, in tree_name_to_values
    raise ValueError("Should not happen. type: %s" % typ)
ValueError: Should not happen. type: name
```

I'm using Neovim with coc. I am not sure what other settings you need to know about, my vimrc is rather large and modularized in about 10-12 files. If there is output command that you'd like please let me know.

Happens when I type `re.search(`.

**Comment by davidhalter** [comment]
Jedi/Parso versions?

**Comment by malan88** [comment]
jedi==0.17.2
parso==0.7.1

**Comment by davidhalter** [comment]
I can not reproduce this, so it's going to be hard to fix :-/

**Comment by malan88** [comment]
Okay, so it's not just on re.search(.

Some further testing revealed that it's only within a loop that starts like this:

```
while m := re.search(regex, text[i:]):
```
And it only happens on certain function calls on objects:

- `re.search(`
- `m.group(`
- `payload = TAGS[match].copy(`

It doesn't happen on `test.test(` or `test.copy(`, so it seems to rely on an actual assigned variable first. `m.yo(` triggered it.

I'm sorry I haven't been more helpful. The PKGBUILD specified a commit from Jul 17 (I guess that's your latest release). I'm not quite sure how to install from master, I'm assuming I write a PKGBUILD and install that via pacman, but there's a dependency with ipython and I guess it will take some time to figure out. I also tried setting an interpreter to a new venv and now I get just a very terse error.

**Comment by malan88** [comment]
In case you'd like to try it out with the file I'm currently finding it in, here it is: https://github.com/Anno-Wiki/icc2-formatter/blob/master/format.py

Entering `m.group(` after line 71 should trigger it.

**Comment by malan88** [comment]
I'll add a minimal reproducible example (finally). Sorry it took so long:

Opened a new file

```
while m := s.index('_'):
    m.group(
```
Error. It clearly has to do with the walrus operator.

**Comment by astier** [comment]
Usually you would post a minimal vimrc. People will not debug your vimrc for you.

**Comment by malan88** [comment]
@astier 
```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
let g:coc_global_extensions = [
    \ 'coc-python',
    \ ]
```

**Comment by puremourning** [comment]
@astier this does not repro in jedi master:

```
(jedi-env) ben@BenMBP Development % python
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> s = jedi.Script("""
... while m := s.index('_'):
...     m.group(""" )
>>> s.complete(3,9)
[]
>>>
```

bit does ion the latest version on pypy:

```
(jedi-env) ben@BenMBP ~ % python
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> s = jedi.Script( """
... while m := s.index('_'):
...     m.group(""" )
>>> s
<Script: None <SameEnvironment: 3.8.5 in /Users/ben/jedi-env>>
>>> s.complete( 3, 9 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/api/__init__.py", line 275, in complete
    return self._complete(line, column, **kwargs)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/api/__init__.py", line 283, in _complete
    return completion.complete()
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/api/completion.py", line 172, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/api/completion.py", line 283, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/api/completion.py", line 384, in _complete_trailer
    values = infer_call_of_leaf(inferred_context, previous_leaf)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/helpers.py", line 80, in infer_call_of_leaf
    return context.infer_node(leaf)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/context.py", line 222, in infer_node
    return infer_node(self, node)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 157, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 170, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 175, in _infer_node_cached
    return _infer_node(context, element)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 83, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 185, in _infer_node
    return infer_atom(context, element)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 310, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/base_value.py", line 427, in from_sets
    for set_ in sets:
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/names.py", line 279, in infer
    return tree_name_to_values(
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/plugins/stdlib.py", line 862, in wrapper
    return func(inference_state, context, tree_name)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/plugins/django.py", line 176, in wrapper
    result = func(inference_state, context, tree_name)
  File "/Users/ben/jedi-env/lib/python3.8/site-packages/jedi/inference/syntax_tree.py", line 767, in tree_name_to_values
    raise ValueError("Should not happen. type: %s" % typ)
ValueError: Should not happen. type: name
>>> exit()

```

**Comment by davidhalter** [comment]
@malan88 Are you using pypy?

**Comment by malan88** [comment]
@davidhalter 

I am not. I am using coc which is installing via pip (from pypi). I managed to install via source per a command suggestion via coc (kind of fortuitous luck there, earlier in the day coc suggested a command because my pip was out of date so I just copied the command which showed where the interpreter was).

I had been mistaken about the package being installed via pacman. The problem is now fixed for me by installing from master. I apologize for taking so long to try that, I had been under the mistaken assumption that I would have to write a PKGBUILD to install via master and I had delayed on that for a long time.

**Comment by puremourning** [comment]
@davidhalter apologies, I tyop'd - pypy -> py**pi**

**Comment by davidhalter** [comment]
Ok @puremourning: Can you upgrade parso to 0.8.0 and use Jedi master and retry?

**Comment by puremourning** [comment]
@davidhalter yeah  it works [fine in master](https://github.com/davidhalter/jedi/issues/1673#issuecomment-709538698) with `pip install -e /path/to/jedi-HEAD`, which IIRC did install parso 0.8.0.

**Comment by davidhalter** [comment]
In that case I'm closing. Trying to make a new release now.
