### ISSUE TITLE
No completion if class inherit from QtWidgets

### ISSUE THREAD

**Issue by Nathoufresh** [davidhalter/jedi#1678]
I use emacs-lsp with pyls.

If I have file similar to this:

```
from PyQt5 import QtCore, QtWidgets, QtGui

class MainWindow(QtWidgets.QMainWindow):
    self __init__(self):
        self.label = QtWidgets.QLabel()
        self....
```
if I try to complete after inserting `self. ` I get an emacs error `not enough value to unpack expected  1 got 0`.

But with a `class thread(threading.Thread):` completion works well.

Not sure if it's a jedi related issue..

**Comment by davidhalter** [comment]
Sorry, but I'm going to need a traceback. Without a traceback I cannot do anything here. Jedi/parso versions are usually also interesting.

**Comment by Nathoufresh** [comment]
[Traceback](https://pastebin.com/KSU3rFvc)

python-jedi 0.17.2
python-parso 1:0.7.1

**Comment by davidhalter** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/lib/python3.8/site-packages/pyls/python_ls.py", line 322, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/usr/lib/python3.8/site-packages/pyls/python_ls.py", line 240, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/usr/lib/python3.8/site-packages/pyls/python_ls.py", line 156, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/pyls/plugins/jedi_completion.py", line 74, in pyls_completions
    ready_completions = [
  File "/usr/lib/python3.8/site-packages/pyls/plugins/jedi_completion.py", line 75, in <listcomp>
    _format_completion(c, include_params)
  File "/usr/lib/python3.8/site-packages/pyls/plugins/jedi_completion.py", line 145, in _format_completion
    'documentation': _utils.format_docstring(d.docstring()),
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 719, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 300, in docstring
    doc = self._get_docstring()
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 728, in _get_docstring
    return super(Completion, self)._get_docstring()
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 311, in _get_docstring
    return self._name.py__doc__()
  File "/usr/lib/python3.8/site-packages/jedi/inference/compiled/value.py", line 329, in py__doc__
    value, = self.infer()
ValueError: not enough values to unpack (expected 1, got 0)
2020-10-05 13:36:58,216 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 90
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/lib/python3.8/site-packages/pyls/python_ls.py", line 322, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/usr/lib/python3.8/site-packages/pyls/python_ls.py", line 240, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/usr/lib/python3.8/site-packages/pyls/python_ls.py", line 156, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/pyls/plugins/jedi_completion.py", line 74, in pyls_completions
    ready_completions = [
  File "/usr/lib/python3.8/site-packages/pyls/plugins/jedi_completion.py", line 75, in <listcomp>
    _format_completion(c, include_params)
  File "/usr/lib/python3.8/site-packages/pyls/plugins/jedi_completion.py", line 145, in _format_completion
    'documentation': _utils.format_docstring(d.docstring()),
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 719, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 300, in docstring
    doc = self._get_docstring()
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 728, in _get_docstring
    return super(Completion, self)._get_docstring()
  File "/usr/lib/python3.8/site-packages/jedi/api/classes.py", line 311, in _get_docstring
    return self._name.py__doc__()
  File "/usr/lib/python3.8/site-packages/jedi/inference/compiled/value.py", line 329, in py__doc__
    value, = self.infer()
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by davidhalter** [comment]
I'm not 100% sure now how to fix this, but I'm pretty sure that this is related to `CompiledInstanceName` being a subclass of CompiledName, which might not be correct.

**Comment by Nathoufresh** [comment]
Can I provide logs (how?) or test stuff to help you find out?

**Comment by davidhalter** [comment]
I think this should be fixed now. Please test (you also need lastest parso).

**Comment by Nathoufresh** [comment]
It's working. Thank you for your time and great work.
