### ISSUE TITLE
jedi make ipython3 crash 

### ISSUE THREAD

**Issue by Havivw** [davidhalter/jedi#1736]
File "/home/user/.local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/user/.local/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/user/.local/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/user/.local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 558, in mainloop
    self.interact()
  File "/home/user/.local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 541, in interact
    code = self.prompt_for_code()
  File "/home/user/.local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 467, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 825, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 792, in run_async
    return await _run_async2()
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 780, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 881, in cancel_and_wait_for_background_tasks
    await task
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1738, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/home/user/.local/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/user/.local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 92, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/user/.local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 102, in _get_completions
    for c in completions:
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/completer.py", line 1819, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/completer.py", line 1862, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/completer.py", line 2030, in _complete
    completions = self._jedi_matches(
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/home/user/.local/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

**Comment by RecNes** [comment]
Same here:

```$ ipython 
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os
Traceback (most recent call last):
  File ".Env/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File ".Env/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 126, in _get_completions
    for c in completions:
  File ".Env/lib/python3.6/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File ".Env/lib/python3.6/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File ".Env/lib/python3.6/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File ".Env/lib/python3.6/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File ".Env/lib/python3.6/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File ".Env/lib/python3.6/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".Env/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File ".Env/lib/python3.6/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File ".Env/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File ".Env/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File ".Env/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File ".Env/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 546, in interact
    code = self.prompt_for_code()
  File ".Env/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 474, in prompt_for_code
    **self._extra_prompt_options())
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1021, in prompt
    set_exception_handler=set_exception_handler, in_thread=in_thread
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 888, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 798, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 945, in cancel_and_wait_for_background_tasks
    await task
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1739, in async_completer
    document, complete_event
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 272, in get_completions_async
    document, complete_event
  File ".Env/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 198, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File ".Env/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    print_tb(e)
  File "/usr/lib/python3.6/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/usr/lib/python3.6/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/usr/lib/python3.6/traceback.py", line 345, in extract
    for f, lineno in frame_gen:
  File "/usr/lib/python3.6/traceback.py", line 310, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'TypeError' object has no attribute 'tb_frame'

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by PeterJCLaw** [comment]
For others who end up here -- this is a duplicate of #1714.
