### ISSUE TITLE
crashes when using Jedi Language Server from JupyterLab

### ISSUE THREAD

**Issue by dpriedel** [davidhalter/jedi#1742]
I don't know whether or not this is a Jedi problem or the problem is elsewhere.

Running:
- JupyterLab 3.0.6
- JupyterLab-LSP 3.3.0
- Jedi 0.18
- Jedi Language Server 0.23
- Manjaro Linux

To create the problem:

- open a Jupyter notebook in JupyterLab with JupyterLab-LSP and Jedi Language Server
`import pandas as pd`
`df = pd.DataFrame()`
`df.`
- typing the dot to get member completions yields the following stack trace

Failed to handle request 9 textDocument/completion Object(textDocument=Object(uri='file:///home/dpriedel/projects/Jupyter/.virtual_documents/blood_pressure/bloodpressure.ipynb'), position=Object(line=31, character=9), context=Object(triggerKind=2, triggerCharacter='.'))
Traceback (most recent call last):
  File "/usr/local/python-3.9/lib/python3.9/site-packages/pygls/protocol.py", line 324, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/usr/local/python-3.9/lib/python3.9/site-packages/pygls/protocol.py", line 249, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/usr/local/python-3.9/lib/python3.9/site-packages/jedi_language_server/server.py", line 183, in completion
    completion_items = [
  File "/usr/local/python-3.9/lib/python3.9/site-packages/jedi_language_server/server.py", line 184, in <listcomp>
    jedi_utils.lsp_completion_item(
  File "/usr/local/python-3.9/lib/python3.9/site-packages/jedi_language_server/jedi_utils.py", line 345, in lsp_completion_item
    lsp_type = get_lsp_completion_type(completion.type)
  File "/usr/local/python-3.9/lib/python3.9/site-packages/jedi/api/classes.py", line 719, in type
    return super().type
  File "/usr/local/python-3.9/lib/python3.9/site-packages/jedi/api/classes.py", line 189, in type
    return self._name.api_type
  File "/usr/local/python-3.9/lib/python3.9/site-packages/jedi/inference/names.py", line 620, in __getattr__
    return getattr(self._wrapped_name, name)
  File "/usr/local/python-3.9/lib/python3.9/site-packages/jedi/inference/value/klass.py", line 81, in api_type
    if definition.type == 'funcdef':
AttributeError: 'NoneType' object has no attribute 'type'

changing the code in klass.py from: 
```python
@property
    def api_type(self):
        if self.tree_name is not None:
            definition = self.tree_name.get_definition()
            if definition.type == 'funcdef':
                if function_is_property(definition):
                    # This essentially checks if there is an @property before
                    # the function. @property could be something different, but
                    # any programmer that redefines property as something that
                    # is not really a property anymore, should be shot. (i.e.
                    # this is a heuristic).
                    return 'property'
        return super().api_type
```
to:
```python
    @property
    def api_type(self):
        if self.tree_name is not None:
            definition = self.tree_name.get_definition()
            if definition is not None:
                if definition.type == 'funcdef':
                    if function_is_property(definition):
                        # This essentially checks if there is an @property before
                        # the function. @property could be something different, but
                        # any programmer that redefines property as something that
                        # is not really a property anymore, should be shot. (i.e.
                        # this is a heuristic).
                        return 'property'
        return super().api_type


```

works but I don't know if this is a correct fix or not.

**Comment by davidhalter** [comment]
I'm pretty sure this was fixed in 04c1c0f871c35751e9dd5bc85f53a65f510a8962. Please try master. Thanks!
