### ISSUE TITLE
Name.defined_names() on statements sometimes raises NotImplementedError

### ISSUE THREAD

**Issue by dmcooke** [davidhalter/jedi#1744]
(Python 3.9, latest jedi from git)

For the code snippet `x = (1,2)`, called `defined_names` on the results of `Script.get_names()` raises a `NotImplementedError`.
I expected an empty list.

Specifically,
```
import jedi
sc = jedi.Script(`x = (1, 2)')
for name in sc.get_names():
    print(name)   # So we know what name the next line fails on
    print(name.defined_names())
```
results in this output:
```
<Name full_name='__main__.x', description='x = (1,2)'>
Traceback (most recent call last):
  File "<redacted>/jedi/jedi/cache.py", line 110, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<redacted>/jedi/jedi/cache.py", line 110, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "<redacted>/jedi/jedi/cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "<redacted>/jedi/jedi/api/classes.py", line 762, in defined_names
    unite(defined_names(self._inference_state, d.as_context()) for d in defs),
  File "<redacted>/jedi/jedi/inference/utils.py", line 28, in unite
    return set(typ for types in iterable for typ in types)
  File "<redacted>/jedi/jedi/inference/utils.py", line 28, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "<redacted>/jedi/jedi/api/classes.py", line 762, in <genexpr>
    unite(defined_names(self._inference_state, d.as_context()) for d in defs),
  File "<redacted>/jedi/jedi/cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "<redacted>/jedi/jedi/inference/base_value.py", line 136, in as_context
    return self._as_context(*args, **kwargs)
  File "<redacted>/jedi/jedi/inference/base_value.py", line 264, in _as_context
    raise NotImplementedError('Not all values need to be converted to contexts: %s', self)
NotImplementedError: ('Not all values need to be converted to contexts: %s', <TreeInstance of <GenericClass: <ClassValue: <Class: tuple@671-695>>[S{<ClassValue: <Class: int@164-240>>}, S{<ClassValue: <Class: int@164-240>>}]>(<ValuesArguments: []>)>)
```

I get the same error (for the name 'x') for other code snippets, like
```
# snippet 1
class C: pass
x = C()
# snippet 2
def f():
    return ()
x = f()
# snippet 3
def f(y=2):
    return y
x = f(1)
# snippet 4
import datetime
x = datetime.datetime.now()
```

but not for these similar snippets, where `defined_names()` returns an empty list:
```
# snippet 5
class C: pass
x = C
# snippet 6
def f():
    return None
x = f()
# snippet 7
def f(y=2):
    return y
x = f(True)
# snippet 8
import module
x = module.foo()
```

In all these cases, the `Name` object for `x` has `.type = "statement"`, so I would expect an empty list for all of them.

**Comment by davidhalter** [comment]
Will be part of the next release in the next few days
