### ISSUE TITLE
Name.defined_names() for  'typing.Any` raises NotImplementedError.

### ISSUE THREAD

**Issue by dmcooke** [davidhalter/jedi#1745]
(Python 3.9, latest jedi from git).

This is similar to #1744, but seems to be limited to the 'special' names in the `typing` module, so I suspect it has a different cause.

This is my test code, for various values of `code`:
```
for name in jedi.Script('from typing import Any').get_names():
    print(name)
    print(name.defined_names())
```
The output is
```
<Name full_name='typing.Any', description='class Any'> class
Traceback (most recent call last):
  File "<redacted>/jedi/jedi/cache.py", line 110, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<redacted>/jedi/jedi/cache.py", line 110, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in show_names
  File "<redacted>/jedi/jedi/cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "<redacted>/jedi/jedi/api/classes.py", line 762, in defined_names
    unite(defined_names(self._inference_state, d.as_context()) for d in defs),
  File "<redacted>/jedi/jedi/inference/utils.py", line 28, in unite
    return set(typ for types in iterable for typ in types)
  File "<redacted>/jedi/jedi/inference/utils.py", line 28, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "<redacted>/jedi/jedi/api/classes.py", line 762, in <genexpr>
    unite(defined_names(self._inference_state, d.as_context()) for d in defs),
  File "<redacted>/jedi/jedi/cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "<redacted>/jedi/jedi/inference/base_value.py", line 136, in as_context
    return self._as_context(*args, **kwargs)
  File "<redacted>/jedi/jedi/inference/base_value.py", line 264, in _as_context
    raise NotImplementedError('Not all values need to be converted to contexts: %s', self)
NotImplementedError: ('Not all values need to be converted to contexts: %s', _PseudoTreeNameClass(Any))
```

Note that the `Name` object for `Any` has `.type = "class"`. You can replace `Any` with `NoReturn`, `ClassVar`, or `Union`,
amongst others. These all have `.type` of "class". The `Final` value from `typing` also causes the same error (albeit with a different object in the error message) ,but it's `Name` object has a `.type` of "instance".

If these objects aren't directly imported, no error is raised. The following is fine:
```
import typing
x: typing.Any = 1
```

**Comment by davidhalter** [comment]
Definitely bugs.

**Comment by davidhalter** [comment]
Will be part of the next release in the next few days
