### ISSUE TITLE
ValueError when prompted for PyQt5 completions

### ISSUE THREAD

**Issue by Jajafarov** [davidhalter/jedi#1754]
**Issue:**
`jedi` (through `pyls`) is throwing an error when prompted for completions for the following piece of code:
```
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QWidget
import sys

app = QApplication(sys.argv)

window = QWidget()

window. <--- Problem occurs
```

The completion choices never show up and `pyls` spits out the following error:
```
2021-02-22 16:48:46,891 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 283
Traceback (most recent call last):
  File "/home/jafarov/.local/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/jafarov/.local/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/jafarov/.local/lib/python3.9/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/lib/python3.9/site-packages/pyls/python_ls.py", line 322, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/usr/lib/python3.9/site-packages/pyls/python_ls.py", line 240, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/usr/lib/python3.9/site-packages/pyls/python_ls.py", line 156, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jafarov/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/pyls/plugins/jedi_completion.py", line 74, in pyls_completions
    ready_completions = [
  File "/usr/lib/python3.9/site-packages/pyls/plugins/jedi_completion.py", line 75, in <listcomp>
    _format_completion(c, include_params)
  File "/usr/lib/python3.9/site-packages/pyls/plugins/jedi_completion.py", line 145, in _format_completion
    'documentation': _utils.format_docstring(d.docstring()),
  File "/home/jafarov/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 719, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/home/jafarov/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 300, in docstring
    doc = self._get_docstring()
  File "/home/jafarov/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 728, in _get_docstring
    return super(Completion, self)._get_docstring()
  File "/home/jafarov/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 311, in _get_docstring
    return self._name.py__doc__()
  File "/home/jafarov/.local/lib/python3.9/site-packages/jedi/inference/compiled/value.py", line 329, in py__doc__
    value, = self.infer()
ValueError: not enough values to unpack (expected 1, got 0)
```

This problem does not happen when asking for completion for `sys.` or even for `Gtk.` I have tried other packages as well (`numpy` for example), `jedi` behaves as usual for them as well. This might simply be me installing `pyls/jedi` incorrectly, version problems or `jedi` being unable to find the `PyQt5` folder (although `PyQt5` was installed through the exact same methods as the other packages).

**System:**
```
Arch Linux
python 3.9.1-2
pyls installed from package manager or pip (tried both) ver. 0.36.2-1
python-jsonrpc-server 0.4.0-3
jedi installed from package manager or pip (tried both) ver. 0.17.2 (have also tried 0.18.0 and 0.15.2)
parso installed from package manager or pip (tried both) ver. 0.7.1 (have also tried 0.8.0 and 0.5.2)
Using pyls in Emacs with company
```

**Similar Issues:**
#1484 Similar but the solution (as I understood it) did not seem to apply.

**Note:**
I opened an issue on the `pyls` repository and was directed to this repository instead as the issue is more related to `jedi`. See palantir/python-language-server#912.

**Comment by davidhalter** [comment]
Please try it with Jedi 0.18.0 I'm not sure this is still an issue. Similar things have been fixed.

**Comment by Jajafarov** [comment]
Thank you! Oddly this seems to have fixed it. I tried this previously but I think `pyls` did not allow for `jedi 0.18.0` and was therefore throwing version errors.
