### ISSUE TITLE
AttributeError: type object 'Script' has no attribute 'goto_assignments'

### ISSUE THREAD

**Issue by max0x7ba** [davidhalter/jedi#1760]
Just installed `jedi-0.18.0` using [jedi:install-server](https://tkf.github.io/emacs-jedi/latest/) and get following errors:

```
41501
ERROR:epc:TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given')
ERROR:epc:AttributeError("type object 'Script' has no attribute 'goto_assignments'")
ERROR:epc:TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given')
ERROR:epc:TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given')
ERROR:epc:AttributeError("type object 'Script' has no attribute 'goto_assignments'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/jediepcserver.py", line 263, in goto
    return self._goto(jedi.Script.goto_assignments, *args)
AttributeError: type object 'Script' has no attribute 'goto_assignments'
ERROR:epc:TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/jediepcserver.py", line 227, in get_in_function_call
    sig = self.jedi_script(*args).call_signatures()
  File "/home/max/.emacs.d/.python-environments/default/lib/python3.8/site-packages/jediepcserver.py", line 201, in jedi_script
    return jedi.Script(
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given
```

The OS is Ubuntu-20.04 LTS, Python 3.8.5.

**Comment by max0x7ba** [comment]
I switched to `elpy` trying to fix the problem without luck - `xref-find-definitions` function didn't find any definitions.

Downgrading `jedi-0.18.0` to `jedi-0.17.2` fixed the problem, `xref-find-definitions` now finds definitions.

**Comment by davidhalter** [comment]
This is definitely not a Jedi issue. The API deprecations where removed in `0.18.0`. This is something that you need to report to your plugin provider.
