### ISSUE TITLE
jedi#goto_definitions raise a AttributeError: 'str' object has on attribute 'exists'

### ISSUE THREAD

**Issue by WorldObserver** [davidhalter/jedi#1770]
When i use <leader>d to use jedi#goto_definitions,this happening:

Traceback (most recent call last):
  File "/home/deepin/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi_vim.py", line 196, in wrapper
    return func(*args, **kwargs)
  File "/home/deepin/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi_vim.py", line 415, in goto
    _goto_specific_name(n)
  File "/home/deepin/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi_vim.py", line 438, in _goto_specific_name
    n.module_path.exists()):
AttributeError: 'str' object has no attribute 'exists'

So, how do I solve this problem?

**Comment by davidhalter** [comment]
I'm pretty sure your Jedi version is too old. Simply upgrade it. For jedi-vim you probably need to upgrade submodules.

**Comment by whatupmiked** [comment]
I hit this same issue with jedi-vim the fix was to update the submodules in the cloned git repo.
`cd .vim/pack/foobar/opt/jedi-vim`
`git submodule update --init --recursive`
After that goto definition worked.
