### ISSUE TITLE
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

### ISSUE THREAD

**Issue by Nikratio** [davidhalter/jedi#1802]
I'm getting the following traceback when trying to use jedi:

```
ERROR:epc:TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "/usr/lib/python3/dist-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/usr/lib/python3/dist-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/home/nikratio/.emacs.d/elpa/jedi-core-0.2.8/jediepcserver.py", line 227, in get_in_function_call
    sig = self.jedi_script(*args).call_signatures()
  File "/home/nikratio/.emacs.d/elpa/jedi-core-0.2.8/jediepcserver.py", line 201, in jedi_script
    return jedi.Script(
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given
```

`jedi:show-setup-info` says:

```
;; Emacs Lisp version:
(:emacs-version "27.1" :jedi-version "0.2.8" :python-environment-version "0.0.2alpha0")
;; Python version:
((:name "sys" :file nil :version "3.9.2 (default, Feb 28 2021, 17:03:44) \n[GCC 10.2.1 20210110]")
 (:name "jedi" :file "/usr/lib/python3/dist-packages/jedi/__init__.py" :version "0.18.0")
 (:name "epc" :file "/usr/lib/python3/dist-packages/epc/__init__.py" :version "0.0.5")
 (:name "sexpdata" :file "/usr/lib/python3/dist-packages/sexpdata.py" :version "0.0.3"))
;; Command line:
(:virtualenv "/usr/bin/virtualenv" :virtualenv-version "virtualenv 20.4.0+ds from /usr/lib/python3/dist-packages/virtualenv/__init__.py\n")
;; Customization:
((jedi:complete-on-dot)
 (jedi:doc-display-buffer . display-buffer)
 (jedi:doc-hook view-mode)
 (jedi:doc-mode . rst-mode)
 (jedi:environment-root)
 (jedi:environment-virtualenv)
 (jedi:get-in-function-call-delay . 1000)
 (jedi:get-in-function-call-timeout . 3000)
 (jedi:goto-definition-config
  (nil nil nil)
  (t nil nil)
  (nil definition nil)
  (t definition nil)
  (nil nil t)
  (t nil t)
  (nil definition t)
  (t definition t))
 (jedi:goto-definition-hook)
 (jedi:goto-definition-marker-ring-length . 16)
 (jedi:imenu-create-index-function . jedi:create-nested-imenu-index)
 (jedi:import-python-el-settings . t)
 (jedi:install-imenu)
 (jedi:install-python-jedi-dev-command "pip" "install" "--upgrade" "git+https://github.com/davidhalter/jedi.git@master#egg=jedi")
 (jedi:key-complete .
                    [C-tab])
 (jedi:key-goto-definition .
                           [67108910])
 (jedi:key-goto-definition-pop-marker .
                                      [67108908])
 (jedi:key-related-names . "r")
 (jedi:key-show-doc . "d")
 (jedi:server-args "--log-traceback")
 (jedi:server-command "python3" "/home/nikratio/.emacs.d/elpa/jedi-core-0.2.8/jediepcserver.py")
 (jedi:setup-keys)
 (jedi:tooltip-method pos-tip popup)
 (jedi:use-shortcuts)
 (python-environment-default-root-name . "default")
 (python-environment-directory . "~/.emacs.d/.python-environments")
 (python-environment-virtualenv "virtualenv" "--system-site-packages" "--quiet"))

```

**Comment by davidhalter** [comment]
This is a mismatch of the Jedi version and your emacs plugin version. You should probably report that to the maintainers of the emacs plugin. You could probably also downgrade Jedi to 0.17.2 and be fine.

**Comment by mortlind** [comment]
How long do we need to keep python3-jedi on version 0.17.2?

**Comment by davidhalter** [comment]
This is not a Jedi issue. Talk to the maintainers of - I guess elpa?
