### ISSUE TITLE
Flaky parso cache on Windows?

### ISSUE THREAD

**Issue by krassowski** [davidhalter/jedi#1807]
With `python-lsp-server`, I see a test randomly fail on Windows, but once it does it fails quite persistently (it happens once a few runs on CI, but if it does the subsequent attempts on the same runner fail too). The sequence of the failing test is:

- enter an editor, automatically request references using `jedi.Script(...).get_references(**code_position)`
- request completions using `jedi.Script(...).complete(**code_position)`
- immediately switch to a different place in editor to test that the completions will be discarded upon cursor movement
- the movement automatically invokes references request with `jedi.Script(...).get_references(**different_code_position)`

(`python-lsp-server` wraps the jedi operations in a lock to prevent common issues, but maybe this is not sufficient here)

Within 5 seconds the (below) traceback appears. If I interpret it correctly it looks that the cache pickle is empty. Could it be that there is a race condition which causes jedi/parso to abort writing the pickle, or not flushing it on disk in Windows-specific manner?

Would you have any advice on how to proceed debugging this one? It only happens on Windows builds, Ubuntu and Mac are not affected.

```python
Traceback (most recent call last):
  File "C:\Miniconda3\envs\test\lib\site-packages\parso\cache.py", line 122, in load_module
    module_cache_item = parser_cache[hashed_grammar][file_io.path]
KeyError: WindowsPath('C:/Miniconda3/envs/test/lib/site-packages/jedi/third_party/typeshed/stdlib/2/__builtin__.pyi')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  [...]
  File "C:\Miniconda3\envs\test\lib\site-packages\pylsp\plugins\highlight.py", line 13, in pylsp_document_highlight
    usages = document.jedi_script().get_references(**code_position)
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\api\helpers.py", line 488, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\api\__init__.py", line 417, in get_references
    return _references(**kwargs)
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\api\__init__.py", line 411, in _references
    names = find_references(self._get_module_context(), tree_name, scope == 'file')
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\references.py", line 145, in find_references
    for module_context in potential_modules:
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\references.py", line 273, in get_module_contexts_containing_name
    yield from search_in_file_ios(inference_state, file_io_iterator, name,
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\references.py", line 285, in search_in_file_ios
    m = _check_fs(inference_state, file_io, regex)
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\references.py", line 177, in _check_fs
    m = load_module_from_path(inference_state, new_file_io)
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\imports.py", line 537, in load_module_from_path
    parse_stub_module(inference_state, file_io), file_io, import_names
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\gradual\typeshed.py", line 288, in parse_stub_module
    return inference_state.parse(
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\__init__.py", line 200, in parse
    return self.parse_and_get_code(*args, **kwargs)[0]
  File "C:\Miniconda3\envs\test\lib\site-packages\jedi\inference\__init__.py", line 197, in parse_and_get_code
    return grammar.parse(code=code, path=path, file_io=file_io, **kwargs), code
  File "C:\Miniconda3\envs\test\lib\site-packages\parso\grammar.py", line 114, in parse
    module_node = load_module(self._hashed, file_io, cache_path=cache_path)
  File "C:\Miniconda3\envs\test\lib\site-packages\parso\cache.py", line 127, in load_module
    return _load_from_file_system(
  File "C:\Miniconda3\envs\test\lib\site-packages\parso\cache.py", line 145, in _load_from_file_system
    module_cache_item = pickle.load(f)
EOFError: Ran out of input
```

Packages:
- jedi                      0.18.0           py39hcbf5309_2    conda-forge
- parso                     0.8.2              pyhd8ed1ab_0    conda-forge
- python                    3.9.7           h7840368_3_cpython    conda-forge

**Comment by davidhalter** [comment]
Are you testing in parallel?

**Comment by krassowski** [comment]
Sorry, I don't remember which test suite this came from. I have not seen this one in a while. Feel free to close and I will reopen if I see it again and get an answer.
