### ISSUE TITLE
Error on getting completions

### ISSUE THREAD

**Issue by rchl** [davidhalter/jedi#1822]
I'm using this project through `pylsp`	through `LSP-pylsp` so I'm reporting this issue from the context of those. Sorry but I don't know how to use this project in standalone way and how to test that way.

I'm coming here from https://github.com/python-lsp/python-lsp-server/issues/121 where triggering completions in a document:

```py
import c
```

(after the `c`) triggers an error in jedi:

```
LSP-pylsp: 2021-11-25 11:14:53,289 CET - ERROR - pylsp_jsonrpc.endpoint - Failed to handle request 43
LSP-pylsp: Traceback (most recent call last):
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/pylsp/plugins/jedi_completion.py", line 311, in resolve_label
LSP-pylsp:     sig = completion.get_signatures()
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/api/classes.py", line 582, in get_signatures
LSP-pylsp:     for s in self._get_signatures()
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/api/classes.py", line 570, in _get_signatures
LSP-pylsp:     names = convert_names([self._name], prefer_stubs=True)
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/gradual/conversion.py", line 152, in convert_names
LSP-pylsp:     return _python_to_stub_names(names, fallback_to_python=prefer_stubs)
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
LSP-pylsp:     return list(func(*args, **kwargs))
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/gradual/conversion.py", line 126, in _python_to_stub_names
LSP-pylsp:     for x in _python_to_stub_names([n], fallback_to_python=fallback_to_python):
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
LSP-pylsp:     return list(func(*args, **kwargs))
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/gradual/conversion.py", line 132, in _python_to_stub_names
LSP-pylsp:     v = name.get_defining_qualified_value()
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/names.py", line 251, in get_defining_qualified_value
LSP-pylsp:     if context.is_module() or context.is_class():
LSP-pylsp: AttributeError: 'NoneType' object has no attribute 'is_module'
```

Used Jedi 0.18.1 here.

**Comment by rchl** [comment]
Looks like it turned out to be a language server issue: https://github.com/python-lsp/python-lsp-server/issues/121#issuecomment-979344262

**Comment by davidhalter** [comment]
This is a bug.
