### ISSUE TITLE
Function parameters completions is not the same if the module is imported in the context

### ISSUE THREAD

**Issue by Morikko** [davidhalter/jedi#1857]
```python
import jedi
assert jedi.__version__ == '0.18.1'

def filter_function_params(completions):
    return [c for c in completions if c.complete.endswith("=")]

def get_code_function_params_completion(code_to_complete):
    return filter_function_params(
        jedi.Script(code_to_complete).complete()
    )

def get_function_function_params_completion(func):
    return filter_function_params(
        jedi.Interpreter(
            f"{func.__name__}(",
            [
                {
                    func.__name__: f,
                }
            ],
        ).complete()
    )

import logging

logging.log?
# Signature: logging.log(level, msg, *args, **kwargs)

# 1. Only the function
get_function_function_params_completion(logging.log)
# [<Completion: level=>, <Completion: msg=>]

# 2. Function with import
python_function = 'import logging; logging.log('
get_code_function_params_completion(python_function)
# [<Completion: exc_info=>,
#  <Completion: extra=>,
#  <Completion: level=>,
#  <Completion: msg=>,
#  <Completion: stack_info=>]

# Another example with a numpy function

# OK

get_function_function_params_completion(np.linspace)
# [<Completion: axis=>,
#  <Completion: dtype=>,
#  <Completion: endpoint=>,
#  <Completion: num=>,
#  <Completion: retstep=>,
#  <Completion: start=>,
#  <Completion: stop=>]

get_code_function_params_completion("import numpy as np;np.linspace(")
# [<Completion: axis=>,
#  <Completion: dtype=>,
#  <Completion: endpoint=>,
#  <Completion: num=>,
#  <Completion: retstep=>,
#  <Completion: start=>,
#  <Completion: stop=>]

# NOK

get_code_function_params_completion('import numpy as np; np.random.uniform(')
# [<Completion: high=>, <Completion: low=>, <Completion: size=>]

get_function_function_params_completion(np.random.uniform)
# []
```

The same phenomenon is visible with IPython. The case 1. corresponds to the completions visible in a cell only calling the `logging.log(` function. While the completions are like in the 2nd case when the `import logging` is also present in the same cell.

Expected results: It would be better to have the same exhaustive completions when the module is not imported in the same "context".

**Comment by davidhalter** [comment]
This is originally a numpy issue (though Jedi could do a bit better):

```
>>> import inspect
>>> inspect.signature(np.random.uniform)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/inspect.py", line 3105, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.8/inspect.py", line 2854, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.8/inspect.py", line 2308, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/usr/lib/python3.8/inspect.py", line 2119, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in method uniform of numpy.random.mtrand.RandomState object at 0x7f2c7cc1bc40>
```

The static analysis uses the docstring while the runtime analysis uses only `inspect.signature`. `uniform(low=0.0, high=1.0, size=None)` is part of the `numpy.random.uniform.__doc__`.

IMO Jedi could just use the docstring in both cases, although I still think that numpy should just use proper signatures.
