### ISSUE TITLE
Pickle data was truncated when using Django

### ISSUE THREAD

**Issue by hwalinga** [davidhalter/jedi#1891]
When working on a file that imports Django models I sometimes get a `_pickle.UnpicklingError: pickle data was truncated` error. 

Here a minimal reproducible example:

```
from django.contrib.auth.models import User

cr = CustomRes
```

Full trace:

```
[deoplete] Traceback (most recent call last):                                                                                                                                                  
  File "/home/hielke/.local/lib/python3.9/site-packages/parso/cache.py", line 122, in load_module                                                                                              
    module_cache_item = parser_cache[hashed_grammar][file_io.path]                                                                                                                             
KeyError: PosixPath('/home/hielke/.cache/pypoetry/virtualenvs/demap-kqoNszLJ-py3.10/lib/python3.10/site-packages/django/contrib/auth/models.py')                                               
During handling of the above exception, another exception occurred:                                                                                                                            
Traceback (most recent call last):                                                                                                                                                             
  File "/home/hielke/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 203, in _gather_results                                                                                
    result = self._get_result(context, source)                                                                                                                                                 
  File "/home/hielke/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 267, in _get_result                                                                                    
    ctx['candidates'] = source.gather_candidates(ctx)                                                                                                                                          
  File "/home/hielke/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper                                                                
    return func(self, *args, **kwargs)                                                                                                                                                         
  File "/home/hielke/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 204, in gather_candidates                                                              
    return self.finalize_completions(completions)                                                                                                                                              
  File "/home/hielke/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper                                                                
    return func(self, *args, **kwargs)                                                                                                                                                         
  File "/home/hielke/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 151, in finalize_completions                                                           
    out.append(self.parse_completion(c, tmp_filecache))                                                                                                                                        
  File "/home/hielke/.vim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 320, in parse_completion                                                               
    type_ = comp.type                                                                                                                                                                          
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 725, in type                                                                                                
    return super().type                                                                                                                                                                        
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 191, in type                                                                                                
    for value in self._name.infer():                                                                                                                                                           
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/names.py", line 281, in infer                                                                                           
    return tree_name_to_values(                                                                                                                                                                
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper                                                                                         
    return built_functions[public_name](*args, **kwargs)                                                                                                                                       
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/plugins/stdlib.py", line 867, in wrapper                                                                                          
    return func(inference_state, context, tree_name)                                                                                                                                           
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/plugins/django.py", line 177, in wrapper                                                                                          
    result = func(inference_state, context, tree_name)                                                                                                                                         
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/syntax_tree.py", line 751, in tree_name_to_values                                                                       
    types = imports.infer_import(context, tree_name)                                                                                                                                           
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/cache.py", line 44, in wrapper                                                                                          
    rv = function(obj, *args, **kwargs)                                                                                                                                                        
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/imports.py", line 53, in infer_import                                                                                   
    _prepare_infer_import(module_context, tree_name)                                                                                                                                           
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/imports.py", line 116, in _prepare_infer_import                                                                         
    return from_import_name, tuple(import_path), import_node.level, importer.follow()                                                                                                          
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/imports.py", line 296, in follow                                                                                        
    return import_module_by_names(                                                                                                                                                             
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/imports.py", line 376, in import_module_by_names                                                                        
    value_set = ValueSet.from_sets([                                                                                                                                                           
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/imports.py", line 377, in <listcomp>                                                                                    
    import_module(                                                                                                                                                                             
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/plugins/__init__.py", line 21, in wrapper                                                                                         
    return built_functions[public_name](*args, **kwargs)                                                                                                                                       
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/plugins/flask.py", line 20, in wrapper                                                                                            
    return callback(inference_state, import_names, module_context, *args, **kwargs)                                                                                                            
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/gradual/typeshed.py", line 115, in wrapper                                                                              
    python_value_set = ValueSet.from_sets(                                                                                                                                                     
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/base_value.py", line 430, in from_sets                                                                                  
    for set_ in sets:                                                                                                                                                                          
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/gradual/typeshed.py", line 116, in <genexpr>                                                                            
    func(inference_state, import_names, p, sys_path,)                                                                                                                                          
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/imports.py", line 446, in import_module                                                                                 
    module = _load_python_module(                                                                                                                                                            
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/imports.py", line 461, in _load_python_module                                                                           
    module_node = inference_state.parse(                                                                                                                                                       
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/__init__.py", line 198, in parse                                                                                        
    return self.parse_and_get_code(*args, **kwargs)[0]                                                                                                                                         
  File "/home/hielke/.local/lib/python3.9/site-packages/jedi/inference/__init__.py", line 195, in parse_and_get_code                                                                           
    return grammar.parse(code=code, path=path, file_io=file_io, **kwargs), code                                                                                                                
  File "/home/hielke/.local/lib/python3.9/site-packages/parso/grammar.py", line 114, in parse                                                                                                  
    module_node = load_module(self._hashed, file_io, cache_path=cache_path)                                                                                                                    
  File "/home/hielke/.local/lib/python3.9/site-packages/parso/cache.py", line 127, in load_module                                                                                              
    return _load_from_file_system(                                                                                                                                                             
  File "/home/hielke/.local/lib/python3.9/site-packages/parso/cache.py", line 145, in _load_from_file_system                                                                                   
    module_cache_item = pickle.load(f)                                                                                                                                                         
_pickle.UnpicklingError: pickle data was truncated                                                                                                                                             
Error from jedi: pickle data was truncated  Use :messages / see above for error details.    
```

Tested on jedi master.
Neovim on v0.9.0-dev-136-gfad558b6a
All vim plugins on recent versions.

**Comment by davidhalter** [comment]
I feel like the cache is corrupted, no idea how this happened. But please try to remove the jedi caches (probably at `~/.cache/jedi`) and let me now if the issue persists.

**Comment by davidhalter** [comment]
> but shall I put FAQ entry in the README about corrupted cache?

No, I feel like this is something that hasn't happened before for other people (it's the first such bug report in years) and I'd like to get such reports if there are any. Because the cache is versioned and shouldn't actually cause this.
