### ISSUE TITLE
sys.path gets replaced by tuple which causes sys.path.insert(0, "") to fail

### ISSUE THREAD

**Issue by ghrist8p** [davidhalter/jedi#1909]
```
Traceback (most recent call last):
  File ".../.venv/lib/pypy3.9/site-packages/ptpython-3.0.22-py3.9.egg/ptpython/repl.py", line 98, in run_and_show_expression
    result = self.eval(expression)
  File ".../.venv/lib/pypy3.9/site-packages/ptpython-3.0.22-py3.9.egg/ptpython/repl.py", line 229, in eval
    sys.path.insert(0, "")
AttributeError: 'tuple' object has no attribute 'insert'. Did you mean: index?
```
This is an intermittent issue. I am creating a REPL with `ptpython.repl.embed(globals, configure = ptpython.repl.run_config)`. After a while of using the REPL I might get the above exception out of the blue just as I am typing and waiting for an auto complete. I may have identified the issue to originate from jedi/inference/__init__.py line 128: `builtins_module, = self.import_module((module_name,), sys_path=())` where an empty set of parentheses get passed as the `sys_path` argument.

**Comment by ghrist8p** [comment]
I tried to identify the issue by finding all the places where sys.path gets set by jedi and I found two places:
.../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/compiled/subprocess/functions.py line 39
.../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/compiled/access.py line 118
I then modified the functions that change sys.path to include the following code:
```
if type(sys_path) is tuple:
    import traceback
    traceback.print_stack()
```

This produced the following stack trace:
```
  File "/snap/pypy3/116/lib/pypy3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/snap/pypy3/116/lib/pypy3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/snap/pypy3/116/lib/pypy3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/snap/pypy3/116/lib/pypy3.9/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/snap/pypy3/116/lib/pypy3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/pypy3/116/lib/pypy3.9/_contextvars.py", line 44, in run
    return callable(*args, **kwargs)
  File ".../.venv/lib/pypy3.9/site-packages/prompt_toolkit-3.0.36-py3.9.egg/prompt_toolkit/eventloop/async_generator.py", line 92, in runner
    for item in get_iterable():
  File ".../.venv/lib/pypy3.9/site-packages/prompt_toolkit-3.0.36-py3.9.egg/prompt_toolkit/completion/base.py", line 281, in <lambda>
    lambda: self.completer.get_completions(document, complete_event)
  File ".../.venv/lib/pypy3.9/site-packages/ptpython-3.0.22-py3.9.egg/ptpython/completer.py", line 621, in get_completions
    completions = list(self.completer.get_completions(document, complete_event))
  File ".../.venv/lib/pypy3.9/site-packages/prompt_toolkit-3.0.36-py3.9.egg/prompt_toolkit/completion/deduplicate.py", line 28, in get_completions
    for completion in self.completer.get_completions(document, complete_event):
  File ".../.venv/lib/pypy3.9/site-packages/prompt_toolkit-3.0.36-py3.9.egg/prompt_toolkit/completion/base.py", line 384, in get_completions
    yield from completer.get_completions(document, complete_event)
  File ".../.venv/lib/pypy3.9/site-packages/ptpython-3.0.22-py3.9.egg/ptpython/completer.py", line 194, in get_completions
    yield from self._jedi_completer.get_completions(
  File ".../.venv/lib/pypy3.9/site-packages/ptpython-3.0.22-py3.9.egg/ptpython/completer.py", line 223, in get_completions
    jedi_completions = script.complete(
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/api/__init__.py", line 214, in complete
    return completion.complete()
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/api/completion.py", line 170, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/api/completion.py", line 314, in _complete_python
    completion_names += self._complete_global_scope()
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/api/completion.py", line 379, in _complete_global_scope
    for filter in filters:
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/context.py", line 496, in get_global_filters
    b = next(base_context.inference_state.builtins_module.get_filters(), None)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/__init__.py", line 128, in builtins_module
    builtins_module, = self.import_module((module_name,), sys_path=())
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/__init__.py", line 111, in import_module
    return imports.import_module_by_names(
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/imports.py", line 376, in import_module_by_names
    value_set = ValueSet.from_sets([
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/imports.py", line 377, in <listcomp>
    import_module(
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/plugins/flask.py", line 20, in wrapper
    return callback(inference_state, import_names, module_context, *args, **kwargs)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/gradual/typeshed.py", line 115, in wrapper
    python_value_set = ValueSet.from_sets(
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/gradual/typeshed.py", line 116, in <genexpr>
    func(inference_state, import_names, p, sys_path,)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/imports.py", line 411, in import_module
    file_io_or_ns, is_pkg = inference_state.compiled_subprocess.get_module_info(
  File "/snap/pypy3/116/lib/pypy3.9/functools.py", line 302, in __call__
    return self.func(*self.args, *args, **keywords)
  File ".../.venv/lib/pypy3.9/site-packages/jedi-0.18.2-py3.9.egg/jedi/inference/compiled/subprocess/functions.py", line 38, in get_module_info
    traceback.print_stack()
```

This id how I found the offending line jedi/inference/\_\_init\_\_.py line 128

**Comment by davidhalter** [comment]
Can you send a PR over? I'm happy to merge. Thanks for the investigation!
