### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by schlamar** [davidhalter/jedi#251]
I use SublimeJEDI and noticed that auto-complete doesn't work anymore, so I am not sure which part of my code base caused this crash:

```
Traceback (most recent call last):
  File "jedi_daemon.py", line 292, in <module>
    process_line(line)
  File "jedi_daemon.py", line 231, in process_line
    action_type: JediFacade(**data).get(action_type)
  File "jedi_daemon.py", line 111, in get
    return getattr(self, 'get_' + action)()
  File "jedi_daemon.py", line 127, in get_autocomplete
    data = self._parameters_for_completion() or []
  File "jedi_daemon.py", line 138, in _parameters_for_completion
    in_call = self.script.call_signatures()[0]
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\api_classes.py", line 44, in wrapper
    result = func(*args, **kwds)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\api.py", line 448, in call_signatures
    call, index = self._func_call_and_param_index()
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\api.py", line 464, in _func_call_and_param_index
    user_stmt = self._parser.user_stmt
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\api.py", line 75, in _parser
    return self._module.parser
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\modules.py", line 116, in parser
    self.position)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\fast_parser.py", line 73, in __call__
    p.update(source, user_position)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\fast_parser.py", line 224, in update
    self._parse(code)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\fast_parser.py", line 333, in _parse
    line_offset, nodes, not is_first)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\fast_parser.py", line 396, in _get_parser
    no_docstr=no_docstr)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\parsing.py", line 68, in __init__
    self._parse()
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\parsing.py", line 671, in _parse
    stmt, tok = self._parse_statement(self.current)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\parsing.py", line 366, in _parse_statement
    n, token_type, tok = self._parse_dot_name(self.current)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\parsing.py", line 151, in _parse_dot_name
    n = pr.Name(self.module, names, first_pos, self.end_pos) if names \
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\parsing_representation.py", line 1344, in __init__
    NamePart(n[0], self, n[1]) for n in names)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\parsing_representation.py", line 1344, in <genexpr>
    NamePart(n[0], self, n[1]) for n in names)
  File "C:\Users\schlaich\Sublime Text 3\Data\Packages\SublimeJEDI\jedi\parsing_representation.py", line 1314, in __new__
    self = super(NamePart, cls).__new__(cls, s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
```

**Comment by Becivells** [comment]
编辑 completion.py 
import os
import io
import re
import sys
import json
import traceback
sys.path.append(os.path.dirname(__file__))
import jedi
# remove jedi from path after we import it so it will not be completed
sys.path.pop(0)

#在此处增加即可解决多语言乱码
reload(sys)
sys.setdefaultencoding('utf-8')
