### ISSUE TITLE
Linter crash

### ISSUE THREAD

**Issue by mriehl** [davidhalter/jedi#457]
As an experiment I added jedi as a [pybuilder plugin](https://github.com/pybuilder/pybuilder/blob/master/src/main/python/pybuilder/plugins/python/jedi_linter_plugin.py) and ran it on several of my projects. It performs surprisingly well!

I have identified a crash. If you need more information I can try to identify the script causing the crash, but the exception looks quite straightforward to me.

```
[DEBUG] Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 596, in _analysis
    nested_resolve=True).follow()
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 181, in follow
    star_imports = remove_star_imports(self._evaluator, module)
  File "/venv/local/lib/python2.7/site-packages/jedi/cache.py", line 171, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 500, in remove_star_imports
    modules = follow_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 347, in follow_file_system
    sys_path_mod = list(self.sys_path_with_modifications())
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 335, in sys_path_with_modifications
    return in_path + sys_path_with_modifications(self._evaluator, self.module)
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/sys_path.py", line 131, in sys_path_with_modifications
    result = _check_module(module)
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/sys_path.py", line 111, in _check_module
    _paths_from_call_expression(module.path, expressions[0]) or [])
  File "/venv/local/lib/python2.7/site-packages/jedi/evaluate/sys_path.py", line 97, in _paths_from_call_expression
    return path and [path] or []
UnboundLocalError: local variable 'path' referenced before assignment
```

**Comment by davidhalter** [comment]
Thanks for testing again :-)
