### ISSUE TITLE
linter crashes on PEP 3132 Extended Iterable Unpacking

### ISSUE THREAD

**Issue by encukou** [davidhalter/jedi#462]
When linting this code:

    first, *rest = stuff
    use(first)

I get a scary traceback:

    Traceback (most recent call last):
    File "/home/petr/programs/Python-3.4.0/__installed__/lib/python3.4/runpy.py", line 171, in _run_module_as_main
        "__main__", mod_spec)
    File "/home/petr/programs/Python-3.4.0/__installed__/lib/python3.4/runpy.py", line 86, in _run_code
        exec(code, run_globals)
    File "/home/petr/dev/jedi/jedi/__main__.py", line 36, in <module>
        for error in jedi.Script(path=path)._analysis():
    File "/home/petr/dev/jedi/jedi/api/__init__.py", line 602, in _analysis
        self._evaluator.eval_statement(stmt)
    File "/home/petr/dev/jedi/jedi/evaluate/cache.py", line 39, in wrapper
        rv = function(obj, *args, **kwargs)
    File "/home/petr/dev/jedi/jedi/evaluate/recursion.py", line 24, in run
        result = func(evaluator, stmt, *args, **kwargs)
    File "/home/petr/dev/jedi/jedi/debug.py", line 51, in wrapper
        result = func(*args, **kwargs)
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 132, in eval_statement
        result = self.eval_expression_list(expression_list)
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 170, in eval_expression_list
        return self.process_precedence_element(p) or []
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 180, in process_precedence_element
        return self.eval_statement_element(el)
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 215, in eval_statement_element
        return self.eval_call(element)
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 226, in eval_call
        return self.eval_call_path(path, par, s.start_pos)
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 240, in eval_call_path
        search_global=True)
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 113, in find_types
        return f.find(scopes, resolve_decorator, search_global)
    File "/home/petr/dev/jedi/jedi/debug.py", line 51, in wrapper
        result = func(*args, **kwargs)
    File "/home/petr/dev/jedi/jedi/evaluate/finder.py", line 47, in find
        types = self._names_to_types(names, resolve_decorator)
    File "/home/petr/dev/jedi/jedi/evaluate/finder.py", line 222, in _names_to_types
        types += self._remove_statements(typ, name)
    File "/home/petr/dev/jedi/jedi/evaluate/finder.py", line 260, in _remove_statements
        types += evaluator.eval_statement(stmt, seek_name=unicode(self.name_str))
    File "/home/petr/dev/jedi/jedi/evaluate/cache.py", line 39, in wrapper
        rv = function(obj, *args, **kwargs)
    File "/home/petr/dev/jedi/jedi/evaluate/recursion.py", line 24, in run
        result = func(evaluator, stmt, *args, **kwargs)
    File "/home/petr/dev/jedi/jedi/debug.py", line 51, in wrapper
        result = func(*args, **kwargs)
    File "/home/petr/dev/jedi/jedi/evaluate/__init__.py", line 158, in eval_statement
        new_result += finder.find_assignments(ass_expression_list[0], result, seek_name)
    File "/home/petr/dev/jedi/jedi/evaluate/finder.py", line 563, in find_assignments
        return _assign_tuples(lhs, results, seek_name)
    File "/home/petr/dev/jedi/jedi/evaluate/finder.py", line 544, in _assign_tuples
        result += find_assignments(command, r, seek_name)
    File "/home/petr/dev/jedi/jedi/evaluate/finder.py", line 564, in find_assignments
        elif unicode(lhs.name.names[-1]) == seek_name:
    AttributeError: 'Operator' object has no attribute 'name'

**Comment by davidhalter** [comment]
Doesn't crash anymore. But note that I'm currently not actively working on the linter (but this issue was fixed).
