### ISSUE TITLE
SyntaxError: encoding declaration in Unicode string

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#465]
Jedi apparently can get confused about coding system declarations within strings within source fragments. E.g.:

```Python
lit = """\
# -*- coding: utf-8 -*-
"""
```

Also if the source is further down the file.

Reproduction:

```Python
source = u'lit = """\\\n# -*- coding: utf-8 -*-\n"""\n'
script = jedi.Script(column=3, source=source, line=2, encoding='utf-8')
script.call_signatures()
```

Results in this backtrace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 558, in call_signatures
    call, index = search_call_signatures(user_stmt, self._pos)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 122, in search_call_signatures
    user_stmt = fast_parent_copy(user_stmt)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 61, in fast_parent_copy
    return recursion(obj)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 18, in recursion
    obj.get_defined_names()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 960, in get_defined_names
    for calls, operation in self.assignment_details:
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 984, in assignment_details
    self.expression_list()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 1183, in expression_list
    call = cls(self._sub_module, tok_str, tok.start_pos, tok.end_pos, self)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 1339, in __init__
    self.value = literal_eval(literal)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/_compatibility.py", line 193, in literal_eval
    return ast.literal_eval(string)
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
SyntaxError: encoding declaration in Unicode string
```

This could very well be a bug in Python's `ast` module:

```Python
>>> s = u'"""\\\n# -*- coding: utf-8 -*-\n"""'
>>> print s
"""\
# -*- coding: utf-8 -*-
"""
>>> ast.literal_eval(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
SyntaxError: encoding declaration in Unicode string
>>> ast.literal_eval("\n" + s)
'# -*- coding: utf-8 -*-\n'
```

**Comment by davidhalter** [comment]
Thanks for reporting it upstream. I'm closing it, since it has been fixed upstream and I don't want to hack around it here.
