### ISSUE TITLE
ImportError during call_signatures

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#471]
A user of Elpy reports in jorgenschaefer/elpy#337

> I have some projects that use fortran and c accelerated routines. It appears that when Jedi tries to look at these while editing code, the elpy bug report keeps popping up.

```
Traceback (most recent call last):
  File "/home/user/.emacs.d/elpa/elpy-20140810.7/elpy/jedibackend.py", line 235, in run_with_debug
    return getattr(script, name)()
  File "/home/user/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 574, in call_signatures
    self._pos, user_stmt)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/cache.py", line 90, in wrapper
    value = optional_callable()
  File "/home/user/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 572, in <lambda>
    _callable = lambda: self._evaluator.eval_call(stmt_el)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 244, in eval_call_path
    types = imports.follow_imports(self, types)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 469, in _follow_sys_path
    return _load_module(path, source, sys_path=sys_path), rest
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 527, in _load_module
    return load(source) if cached is None else cached.module
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 520, in load
    return compiled.load_module(path, name)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 288, in load_module
    __import__(dotted_path)
ImportError: No module named f2pymodule

Jedi Debug Information

[N] dbg: finder.filter_name "f2pymodule" in (<Function: routine@752-790>-<ModuleWrapper: <fast.Module: mainpymodule@1-4752>>): [<Name: f2pymodule@23,7>]@(771, 8)
[N] dbg: finder._names_to_types: [<Name: f2pymodule@23,7>] -> [<Import: import f2pymodule @23,0>]
[N] dbg: follow_module None f2pymodule
[N] dbg: search_module /home/usr/lib/python
```

Lacking the self-written modules, I can't provide reproduction steps I'm afraid.

**Comment by davidhalter** [comment]
Fixed in  https://github.com/davidhalter/jedi/commit/eb146adcc1f035f1272105349c4d261f648c9a14.

We just catch such errors now (and issue a warning).
