### ISSUE TITLE
jedi fails when pkg.__init__ is an extension module

### ISSUE THREAD

**Issue by mustrumr** [davidhalter/jedi#472]
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "jedi/api/__init__.py", line 157, in completions
    completions = get_completions(user_stmt, b)
  File "jedi/api/__init__.py", line 136, in get_completions
    return self._simple_complete(path, like)
  File "jedi/api/__init__.py", line 203, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "jedi/api/__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "jedi/evaluate/__init__.py", line 244, in eval_call_path
    types = imports.follow_imports(self, types)
  File "jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "jedi/evaluate/imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "jedi/evaluate/imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "jedi/evaluate/imports.py", line 464, in _follow_sys_path
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.4/site-packages/pkg/__init__.py'
```

**Comment by davidhalter** [comment]
I'm just not sure how to deal with this. Is there an open source pkg that does this? Or could you provide a test case?

**Comment by mustrumr** [comment]
asdf.c:
```c
#include "Python.h"
static struct PyModuleDef asdfmodule = {
   PyModuleDef_HEAD_INIT,
   "asdf",
   NULL,
   -1,
   NULL
};
PyMODINIT_FUNC
PyInit_asdf(void)
{
    PyObject *m;

    m = PyModule_Create(&asdfmodule);
    if (m == NULL)
        return NULL;

    PyModule_AddObject(m, "asdf", Py_None);
    return m;
}
```

setup.py
```py
from distutils.core import setup, Extension
setup(name = 'asdf',
      version='0.0',
      description='',
      ext_modules=[
          Extension('asdf.__init__', sources = ['asdf.c'])
      ]
)
```

test.py
```py
import jedi
sc=jedi.Script('import asdf\nasdf.', 2, 5)
print(sc.completions())
```

**Comment by davidhalter** [comment]
Thanks for the test and good description!
