### ISSUE TITLE
AttributeError in python2 unicode.isinstance

### ISSUE THREAD

**Issue by dimaqq** [davidhalter/jedi#474]
When ran under CPython 2.7 I get AttributeError for many complex source files.
Same succeeds if ran under CPython 3.4.1

```
(plc)[dima@bmg 18src]$ python -m jedi linter utils/file_utils.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/__main__.py", line 36, in <module>
    for error in jedi.Script(path=path)._analysis():
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/api/__init__.py", line 602, in _analysis
    self._evaluator.eval_statement(stmt)
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/evaluate/__init__.py", line 152, in eval_statement
    result = precedence.calculate(self, left, operator, result)
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/evaluate/precedence.py", line 228, in calculate
    result += _element_calculate(evaluator, left, operator, right)
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/evaluate/precedence.py", line 295, in _element_calculate
    message % (left, right))
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/evaluate/analysis.py", line 77, in add
    if _check_for_exception_catch(evaluator, jedi_obj, exception, payload):
  File "/dima/plc/lib/python2.7/site-packages/jedi-0.8.1_final0-py2.7.egg/jedi/evaluate/analysis.py", line 179, in _check_for_exception_catch
    while obj is not None and not obj.isinstance(pr.Function, pr.Class):
AttributeError: 'unicode' object has no attribute 'isinstance'


(plc)[dima@bmg 18src]$ python
Python 2.7.8 (default, Jul  1 2014, 17:30:21) 
[GCC 4.9.0 20140604 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by davidhalter** [comment]
Can you try again? Same error?

**Comment by dimaqq** [comment]
There's a different error now with github master:

```sh
(env-red)air:~ dima$ pip install git+https://github.com/davidhalter/jedi
...
(env-red)air:~ dima$ python -m jedi linter 18src/utils/file_utils.py
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/__main__.py", line 36, in <module>
    for error in jedi.Script(path=path)._analysis():
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/api/__init__.py", line 533, in _analysis
    analysis.get_module_statements(self._parser.module())
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/user_context.py", line 332, in module
    return self._parser().module
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/user_context.py", line 277, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/fast.py", line 106, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/fast.py", line 243, in __init__
    self.update(source)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'timeit'
```

**Comment by dimaqq** [comment]
I've narrowed down the error I'm seeing and I'll open a new issue for that.

**Comment by davidhalter** [comment]
Well I have actually not tested the linter at all since the rewrite, so there might still be quite a few bus. It doesn't look like the old one though.

**Comment by dimaqq** [comment]
OK, I removed octal numbers, now I get this error:

```py
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/__main__.py", line 36, in <module>
    for error in jedi.Script(path=path)._analysis():
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/api/__init__.py", line 538, in _analysis
    check_types(self._evaluator.eval_element(node))
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 157, in eval_element
    return [compiled.builtin.get_by_name(element.value)]
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/cache.py", line 160, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 457, in get_by_name
    return self.names_dict[name][0].parent
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/cache.py", line 160, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/dima/env-red/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 260, in __getitem__
    raise KeyError('%s in %s not found.' % (name, self._compiled_obj))
KeyError: u"assert in <Builtin: <module '__builtin__' (built-in)>> not found."
```

Btw., `__builtin__` is not referenced in this file.

**Comment by davidhalter** [comment]
This code is all different now and the linter hasn't made progress in years. In fact it will be rewritten if anything at some point. Closing this, because the linter never left alpha and the current version is being dicontinued.
