### ISSUE TITLE
UnicodeEncodeError with unicode in strings

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#482]
Traceback:

```
Traceback (most recent call last):
  File "foo.py", line 13, in <module>
    script.call_signatures()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 574, in call_signatures
    self._pos, user_stmt)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/cache.py", line 90, in wrapper
    value = optional_callable()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 572, in <lambda>
    _callable = lambda: self._evaluator.eval_call(stmt_el)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 57, in find
    message)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/analysis.py", line 82, in add
    debug.warning(str(instance))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab' in position 40: ordinal not in range(128)
```

Reproduction:

```Python
source = '''\                                                                   
# coding: utf-8                                                                 
                                                                                
logging.info(u"Saving «{}»...".format(title))                                   
requests.get(u"https://web.archive.org/save/{}".format(url))                    
'''

script = jedi.Script(column=40, source=source, line=3, encoding='utf-8')
script.call_signatures()
```

(Originally reported as jorgenschaefer/elpy#358)

**Comment by davidhalter** [comment]
Tested it with both Python 2 and 3. Seems to work now. So much got change, that this might not be an issue anymore.
