### ISSUE TITLE
ValueError: invalid \x escape

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#485]
When Jedi sees a `'\x'` in a string, it throws an error; this can easily happen while the user is entering a hex escape sequence.

Traceback:

```
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    script.call_signatures()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 558, in call_signatures
    call, index = search_call_signatures(user_stmt, self._pos)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 122, in search_call_signatures
    user_stmt = fast_parent_copy(user_stmt)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 61, in fast_parent_copy
    return recursion(obj)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 18, in recursion
    obj.get_defined_names()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 960, in get_defined_names
    for calls, operation in self.assignment_details:
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 984, in assignment_details
    self.expression_list()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 1183, in expression_list
    call = cls(self._sub_module, tok_str, tok.start_pos, tok.end_pos, self)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/representation.py", line 1339, in __init__
    self.value = literal_eval(literal)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/_compatibility.py", line 193, in literal_eval
    return ast.literal_eval(string)
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
ValueError: invalid \x escape
```

Reproduction:

```Python
import jedi

script = jedi.Script(line=1, column=8, source=r"v = '\x'")
script.call_signatures()
```

(Originally reported as jorgenschaefer/elpy#360)

**Comment by davidhalter** [comment]
Did I fix this? I don't seem to be able to reproduce it anymore. Can you check with the latest dev branch?

**Comment by jorgenschaefer** [comment]
Seems not to happen anymore. Thank you!
