### ISSUE TITLE
AttributeError: 'LazyName' object has no attribute '_parent' in ``get_completions``.

### ISSUE THREAD

**Issue by jonathanslenders** [davidhalter/jedi#487]
```python
Traceback (most recent call last):
  File "/home/jonathan/env/tulip-test2/lib/python3.3/site-packages/jedi/cache.py", line 137, in wrapper
    return getattr(self, name)
AttributeError: 'LazyName' object has no attribute '_parent'
```

this error happened during the handling of the following error:
```python
  File "/Library/Python/2.7/site-packages/prompt_toolkit/contrib/python_input.py", line 449, in get_completions
    for c in script.completions():
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 161, in completions
    for call_sig in self.call_signatures():
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 574, in call_signatures
    self._pos, user_stmt)
  File "/Library/Python/2.7/site-packages/jedi/cache.py", line 90, in wrapper
    value = optional_callable()
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 572, in <lambda>
    _callable = lambda: self._evaluator.eval_call(stmt_el)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/Library/Python/2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 46, in find
    names = self.filter_name(scopes)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 89, in filter_name
    scope = name.parent.parent
  File "/Library/Python/2.7/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/Library/Python/2.7/site-packages/jedi/api/interpreter.py", line 69, in parent
    module = __import__(module_name)
TypeError: __import__() argument 1 must be string, not None
```

See: https://github.com/jonathanslenders/python-prompt-toolkit/issues/19

**Comment by davidhalter** [comment]
Still happening? Pretty sure this is fixed.

**Comment by davidhalter** [comment]
Fixed.
