### ISSUE TITLE
ValueError: __loader__ is None

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#491]
Apparently, `importlib.find_loader` can throw a `ValueError` when a given module has a `__loader__` that is `None`. Should Jedi catch this error and ignore it? I'm not sure if this is a bug in the `smc` library (whatever that is), but this might happen during development, too, I guess?

```
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\elpy\jedibackend.py", line 199, in run_with_debug
    return getattr(script, name)()
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 157, in completions
    completions = get_completions(user_stmt, b)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 136, in get_completions
    return self._simple_complete(path, like)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 203, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 244, in eval_call_path
    types = imports.follow_imports(self, types)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 430, in _follow_sys_path
    current_namespace = follow_str(current_namespace[1], unicode(s))
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 419, in follow_str
    importing = find_module(string)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\_compatibility.py", line 23, in find_module_py33
    loader = importlib.find_loader(string)
  File "c:\python34\lib\importlib\__init__.py", line 70, in find_loader
    raise ValueError('{}.__loader__ is None'.format(name))
ValueError: smc.__loader__ is None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\elpy\jedibackend.py", line 235, in run_with_debug
    return getattr(script, name)()
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 157, in completions
    completions = get_completions(user_stmt, b)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 136, in get_completions
    return self._simple_complete(path, like)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 203, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\api\__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\__init__.py", line 244, in eval_call_path
    types = imports.follow_imports(self, types)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 430, in _follow_sys_path
    current_namespace = follow_str(current_namespace[1], unicode(s))
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\evaluate\imports.py", line 419, in follow_str
    importing = find_module(string)
  File "c:\python34\lib\site-packages\jedi-0.8.1_final0-py3.4.egg\jedi\_compatibility.py", line 23, in find_module_py33
    loader = importlib.find_loader(string)
  File "c:\python34\lib\importlib\__init__.py", line 70, in find_loader
    raise ValueError('{}.__loader__ is None'.format(name))
ValueError: smc.__loader__ is None

Jedi Debug Information

[W] warning: No statement under the cursor.
[N] dbg: start: fi in <Function: nef_to_tif@26-37>
[N] dbg: eval_statement <Statement: fi @28,7> (None)
[N] dbg: eval_expression_list: [<Call: fi>]
[N]  dbg: finder.filter_name "fi" in (<Function: nef_to_tif@26-37>): [<Name: fi@27,28>]@(28, 7)
[N]  dbg: finder._names_to_types: [<Name: fi@27,28>] -> [<Import: import smc.freeimage as fi @27,4>]
[N] dbg: follow_module None smc
[N] dbg: search_module smc c:\Users\zyuan\projects
```

Originally reported as jorgenschaefer/elpy#366

**Comment by davidhalter** [comment]
Hmm is `importlib.find_loader` actually importing modules?

**Comment by jorgenschaefer** [comment]
Nope, but it re-uses loaders of loaded modules:

```Python
        loader = sys.modules[name].__loader__
        if loader is None:
            raise ValueError('{}.__loader__ is None'.format(name))
        else:
            return loader
```

I do not know what this `smc` module is, but it seems it does something unusual there.

**Comment by davidhalter** [comment]
I just make an ImportError from those ValueErrors now, which is probably going to work. Let me know if it doesn't!
