### ISSUE TITLE
UnicodeDecodeError on OpenBSD.

### ISSUE THREAD

**Issue by jonathanslenders** [davidhalter/jedi#495]
On openBSD, when calling `script.completions`, we get a `UnicodeDecodeError`.

``` python
In [1]: import sException in thread Thread-8:
Traceback (most recent call last):
...
  File "/home/edd/.local/lib/python2.7/site-packages/prompt_toolkit/contrib/pyts
    completions = script.completions()
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", lins
    completions = get_completions(user_stmt, b)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", lins
    return self._simple_complete(path, like)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line
    return super(Interpreter, self)._simple_complete(path, like)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line
    names = s.get_defined_names(on_import_stmt=True)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py",s
    names += self._get_module_names([path])
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py",s
    for module_loader, name, is_pkg in pkgutil.iter_modules(search_path):
  File "/usr/local/lib/python2.7/pkgutil.py", line 147, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "/usr/local/lib/python2.7/pkgutil.py", line 202, in iter_modules
    filenames.sort()  # handle packages before same-named modules
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 25: ordina)
```

See: https://github.com/jonathanslenders/python-prompt-toolkit/issues/43

**Comment by davidhalter** [comment]
If you can, please check the output of `pkgutil.iter_modules(search_path)` or play around with it, so we can check what's wrong with it.

**Comment by davidhalter** [comment]
Is this still happening in latest jedi dev?

**Comment by jonathanslenders** [comment]
Hi David,

Honestly, I have no idea how to reproduce it. Back then, it wasn't on my system, but maybe @can help. For me, if you think it's fixed, we can probably close it. (Then we'll open a new issue if ever this happens again.)

**Comment by jonathanslenders** [comment]
@cc: vext01

**Comment by jonathanslenders** [comment]
Hi David,

Honestly, I have no idea how to reproduce it. Back then, it wasn't on my system, but maybe @vext01 can help. For me, if you think it's fixed, we can probably close it. (Then we'll open a new issue if ever this happens again.)

**Comment by davidhalter** [comment]
Since everything was rewritten in parso I just suppose this one was fixed. Otherwise just open an issue in the parso tracker :)
