### ISSUE TITLE
Jedi cannot be installed (and totally borks SublimePythonIDE)

### ISSUE THREAD

**Issue by benjolitz** [davidhalter/jedi#499]
Python 2.7, OSX
```
(cpython27) bjolit@BJOLIT1013mac:[ZSyncer]$ pip install -U jedi
Downloading/unpacking jedi
  Downloading jedi-0.8.1-final0.tar.gz (298kB): 298kB downloaded
  Running setup.py (path:/Users/bjolit/.virtualenvs/cpython27/build/jedi/setup.py) egg_info for package jedi
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/bjolit/.virtualenvs/cpython27/build/jedi/setup.py", line 15, in <module>
        import jedi
      File "jedi/__init__.py", line 39, in <module>
        from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
      File "jedi/api/__init__.py", line 26, in <module>
        from jedi.api import keywords
      File "jedi/api/keywords.py", line 6, in <module>
        from jedi.evaluate import compiled
      File "jedi/evaluate/__init__.py", line 78, in <module>
        from jedi.evaluate import representation as er
      File "jedi/evaluate/representation.py", line 23, in <module>
        from jedi.evaluate import compiled
      File "jedi/evaluate/compiled/__init__.py", line 399, in <module>
        type_names = builtin.get_by_name('type').get_defined_names()
      File "jedi/cache.py", line 157, in wrapper
        result = func(*args, **kwargs)
      File "jedi/evaluate/compiled/__init__.py", line 368, in get_by_name
        item = [n for n in self.get_defined_names() if n.get_code() == name][0]
    IndexError: list index out of range
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/bjolit/.virtualenvs/cpython27/build/jedi/setup.py", line 15, in <module>

    import jedi

  File "jedi/__init__.py", line 39, in <module>

    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function

  File "jedi/api/__init__.py", line 26, in <module>

    from jedi.api import keywords

  File "jedi/api/keywords.py", line 6, in <module>

    from jedi.evaluate import compiled

  File "jedi/evaluate/__init__.py", line 78, in <module>

    from jedi.evaluate import representation as er

  File "jedi/evaluate/representation.py", line 23, in <module>

    from jedi.evaluate import compiled

  File "jedi/evaluate/compiled/__init__.py", line 399, in <module>

    type_names = builtin.get_by_name('type').get_defined_names()

  File "jedi/cache.py", line 157, in wrapper

    result = func(*args, **kwargs)

  File "jedi/evaluate/compiled/__init__.py", line 368, in get_by_name

    item = [n for n in self.get_defined_names() if n.get_code() == name][0]

IndexError: list index out of range

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/bjolit/.virtualenvs/cpython27/build/jedi
Storing debug log for failure in /Users/bjolit/.pip/pip.log
```

**Comment by davidhalter** [comment]
ping

**Comment by davidhalter** [comment]
Closing, no answer.
