### ISSUE TITLE
IndexError when creating jedi.Interpreter.

### ISSUE THREAD

**Issue by jonathanslenders** [davidhalter/jedi#514]
Not sure what the input was, but probably something like:
```python
open('file', '
```

```python
Traceback (most recent call last):
  File "/home/jonathan/git/prompt_toolkit/prompt_toolkit/contrib/python_input.py", line 458, in get_jedi_script_from_document
    namespaces=[locals, globals])
  File "/home/jonathan/env/mobilevikings/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 642, in __init__
    interpreter.create(self._evaluator, namespaces[0], self._parser.module())
  File "/home/jonathan/env/mobilevikings/local/lib/python2.7/site-packages/jedi/api/interpreter.py", line 107, in create
    for something in getattr(parser_module, attr_name):
  File "/home/jonathan/env/mobilevikings/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 38, in __getattr__
    return getattr(self.parsers[0].module, name)
IndexError: list index out of range
```

**Comment by davidhalter** [comment]
Probably fixed? Since you're not sure what the input was, I will just close it.

I have rewritten the interpreter completion completely. It should work much better with fewer exceptions.
