### ISSUE TITLE
Unguarded __getattr__ causes exception

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#529]
A user received the following error in some non-open source code (hence no clear reproduction case). I hope the backtrace is helpful nonetheless.

Originally reported as jorgenschaefer/elpy#441

```
Error Message

Instance <eInstance of <eClass of <Class: Tool@49-185>> (var_args: 0)>: Don't touch this (is_generated)!

Configuration

Virtualenv........: None
RPC Python........: 2.7.9 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 25.0.50.1
Elpy..............: 1.6.1
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Importmagic.......: 0.1.0
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/elpy/jedibackend.py", line 286, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib64/python2.7/site-packages/jedi/api/__init__.py", line 157, in completions
    completions = get_completions(user_stmt, b)
  File "/usr/lib64/python2.7/site-packages/jedi/api/__init__.py", line 136, in get_completions
    return self._simple_complete(path, like)
  File "/usr/lib64/python2.7/site-packages/jedi/api/__init__.py", line 203, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/usr/lib64/python2.7/site-packages/jedi/api/__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 47, in find
    types = self._names_to_types(names, resolve_decorator)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 216, in _names_to_types
    types += self._eval_param(typ)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 294, in _eval_param
    for inst in evaluator.execute(er.Class(evaluator, cls)):
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 332, in execute
    return [er.Instance(self, obj, params)]
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 54, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/representation.py", line 63, in __init__
    self.execute_subscope_by_name('__init__', self.var_args)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/representation.py", line 133, in execute_subscope_by_name
    return self._evaluator.execute(method, args)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 336, in execute
    stmts = er.FunctionExecution(self, obj, params).get_return_types(evaluate_generator)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/recursion.py", line 108, in run
    result = func(execution, evaluate_generator)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/representation.py", line 437, in get_return_types
    stmts += self._evaluator.eval_statement(r)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 177, in process_precedence_element
    return self._eval_precedence(el)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 184, in _eval_precedence
    right = self.process_precedence_element(_precedence.right)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 177, in process_precedence_element
    return self._eval_precedence(el)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 184, in _eval_precedence
    right = self.process_precedence_element(_precedence.right)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 47, in find
    types = self._names_to_types(names, resolve_decorator)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 216, in _names_to_types
    types += self._eval_param(typ)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 302, in _eval_param
    and func.instance.is_generated and str(func.name) == '__init__':
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/representation.py", line 181, in __getattr__
    % (self, name))
AttributeError: Instance <eInstance of <eClass of <Class: BugreportTool@49-185>> (var_args: 0)>: Don't touch this (is_generated)!
```

**Comment by davidhalter** [comment]
I don't see how `is_generated` cannot be defined on an Instance.

Since this is 0.8.1 and not 0.9.0 (where about > 50% of the code base has changed), I think he should try to test again with Jedi's master branch.

**Comment by jorgenschaefer** [comment]
Thanks. Forwarded to the user; will let you know if I hear more. Always tricky to deal with bug reports without a reproduction step.

**Comment by jorgenschaefer** [comment]
No updates from the user, so I closed the Elpy bug, and I guess we can just assume this is fixed.
