### ISSUE TITLE
[parser] ValueError from Django not caught for many-to-many relationship

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#538]
I've seen the following error during completion in Django's shell (using shell_plus / ptipython):

    Traceback (most recent call last):
      File "…/pyenv/2.7.8/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "…/pyenv/2.7.8/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "…/pyenv/project/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 466, in run
        CompleteEvent(text_inserted=True)))
      File "…/pyenv/project/lib/python2.7/site-packages/prompt_toolkit/contrib/ipython.py", line 69, in get_completions
        for c in super(IPythonCompleter, self).get_completions(document, complete_event):
      File "…/pyenv/project/lib/python2.7/site-packages/prompt_toolkit/contrib/python_input.py", line 573, in get_completions
        completions = script.completions()
      File "…/vim/neobundles/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/api/__init__.py", line 183, in completions
        completion_names = get_completions(user_stmt, b)
      File "…/vim/neobundles/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/api/__init__.py", line 169, in get_completions
        completion_names += self._simple_complete(path, dot, like)
      File "…/vim/neobundles/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/api/__init__.py", line 612, in _simple_complete
        namespaces.append(getattr(n, p))
      File "…/django-1.7.x/django/db/models/fields/related.py", line 1175, in __get__
        through=self.field.rel.through,
      File "…/django-1.7.x/django/db/models/fields/related.py", line 831, in __init__
        (instance, source_field_name))
    ValueError: "<Collection: >" needs to have a value for field "collection" before this many-to-many relationship can be used.

Also catching ValueError here (in jedi/api/__init__.py", line 612) fixed it, in the sense that no traceback was thrown in ptipython.

**Comment by davidhalter** [comment]
What branch are you on?
