### ISSUE TITLE
KeyError: u'u' in tokenize.generate_tokens

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#548]
A user using Jedi 0.8.1 got the following message:

```
Traceback

Traceback (most recent call last):
  File "/home/bersace/.emacs.d/elpa/elpy-20150206.1012/elpy/jedibackend.py", line 300, in run_with_debug
    return getattr(script, name)()
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/__init__.py", line 557, in call_signatures
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 226, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 216, in user_stmt
    module = self.module()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 255, in module
    return self._parser().module
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 209, in _parser
    parser = FastParser(self._source, self._path)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 65, in __call__
    p = super(CachedFastParser, self).__call__(source, module_path)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 199, in __init__
    self._parse(code)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 302, in _parse
    line_offset, nodes, not is_first)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 367, in _get_parser
    top_module=self.module, no_docstr=no_docstr)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 59, in __init__
    self._parse()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 604, in _parse
    stmt, tok = self._parse_statement(self._gen.current)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 360, in _parse_statement
    tok = next(self._gen)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 627, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 634, in __next__
    self.current = next(self._tokenizer)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 399, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 405, in __next__
    current = next(self.gen)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/tokenize.py", line 285, in generate_tokens
    endprog = (endprogs[initial] or endprogs[token[1]] or
KeyError: u'u'

Jedi Debug Information

Jedi did not emit any debug info.
```

Sadly, the user can not provide the source file that lead to this error, so I can't provide a reproduction case. If there is anything we can do to help figuring out what is happening here, let us know :-)

Reported as jorgenschaefer/elpy#500

**Comment by davidhalter** [comment]
Sure this isn't fixed in the current master branch? I think I have seen this before.

**Comment by jorgenschaefer** [comment]
Not sure at all, I asked the user if they can test it :-)

**Comment by bersace** [comment]
Yep, fixed in master. Thanks :)

**Comment by jorgenschaefer** [comment]
Great, thank you!
