### ISSUE TITLE
AttributeError: 'Operator' object has no attribute 'get_definition'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#573]
Python 3.4.2, Jedi 0.9.0:

```Python
>>> import jedi
>>> s = jedi.Script("import threading\nthreading.Thread(foo()", line=2, column=22)
>>> s.call_signatures()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/api/classes.py", line 693, in __repr__
    self.index)
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/home/forcer/.virtualenvs/elpy3/lib/python3.4/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
```

**Comment by cpdean** [comment]
This appears to be yet another python3 specific error, since this works on python2:
```
Python 2.7.10 (default, Jul 13 2015, 12:18:59)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from __future__ import print_function

In [2]: import jedi


In [3]:

In [3]:     src = "\n".join(
   ...:         ("import threading",
   ...:          "threading.Thread(foo()")
   ...:     )

In [4]:     s = jedi.Script(source=src, line=2, column=22)
    signatures = s.call_signatures()


In [5]:     signatures = s.call_signatures()

In [6]:

In [6]:     assert len(signatures) > 0

In [7]:

In [7]:     print(signatures)
[<CallSignature: Thread index 0>]
```

**Comment by davidhalter** [comment]
I think this is probably a Python 2 bug as well, but since the code changed behind `threading.Thread`, this works in Python 2 only.

As a solution for this, I would probably search for the actual cause, which is probably something very simple. With the traceback I would suspect a signature like `def x(a, *, b=3):` being the cause, because I think I have not handled the new syntax of `*` as a param yet.

**Comment by davidhalter** [comment]
It's working now!

```
>>> s = jedi.Script("import threading\nthreading.Thread(foo()", line=2, column=22)
>>> s.call_signatures()
[<CallSignature: Thread index 0>]
```
