### ISSUE TITLE
Python 3.3: 'NoneType' object has no attribute 'names_dicts'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#575]
Not sure if Jedi supports Python 3.3, but in case it does:

```
Python 3.3.6 (default, Feb 10 2015, 12:57:54)
[GCC 4.7.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.__version__
'0.9.0'
>>> s = jedi.Script("from .. import foo", line=1, column=18, path="foo.py")
>>> s.usages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forcer/Programs/jedi/jedi/api/__init__.py", line 464, in usages
    definitions = self._goto(add_import_name=True)
  File "/home/forcer/Programs/jedi/jedi/api/__init__.py", line 434, in _goto
    definitions = self._evaluator.goto(name)
  File "/home/forcer/Programs/jedi/jedi/evaluate/__init__.py", line 354, in goto
    modules = imports.ImportWrapper(self, name).follow(is_goto=True)
  File "/home/forcer/Programs/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/forcer/Programs/jedi/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/home/forcer/Programs/jedi/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/home/forcer/Programs/jedi/jedi/evaluate/__init__.py", line 117, in find_types
    scopes = f.scopes(search_global)
  File "/home/forcer/Programs/jedi/jedi/evaluate/finder.py", line 109, in scopes
    return ((n, None) for n in self.scope.names_dicts(search_global))
AttributeError: 'NoneType' object has no attribute 'names_dicts'
```

**Comment by davidhalter** [comment]
it does.

**Comment by cperezabo** [comment]
Please, I am having the same problem. Autocompletion is not working with PyQt5. It is working with the rest of installed modules

**Comment by davidhalter** [comment]
Is working now, please retest. Probably related to #577.

@cperezabo I'm not this fixes your issues. You can open a new issue if you want, but there's probably quite a few issues with PyQt5 since it's not just Python code.
