### ISSUE TITLE
Python 3.3: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#576]
Again not sure if Python 3.3 is supported, but (Jedi 0.9.0):

```
>>> import jedi
>>> s = jedi.Script("from .. import foo", line=1, column=18, path="foo.py")
>>> s.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forcer/Programs/jedi/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/forcer/Programs/jedi/jedi/api/__init__.py", line 165, in get_completions
    user_stmt, self._pos)
  File "/home/forcer/Programs/jedi/jedi/evaluate/imports.py", line 58, in completion_names
    return importer.completion_names(evaluator, only_modules)
  File "/home/forcer/Programs/jedi/jedi/evaluate/imports.py", line 396, in completion_names
    if not scope.type == 'file_input':  # not a module
AttributeError: 'NoneType' object has no attribute 'type'
```

**Comment by davidhalter** [comment]
Guys, I think this one was fixed along the lines as well. I don't know how, but if you could test?

I will reopen if it's still an issue. Just let me know.
