### ISSUE TITLE
Error when no path is given to Script

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#577]
Any Python, Jedi 0.9.0:

```
>>> import jedi
>>> s = jedi.Script("from .. import foo", line=1, column=18)
>>> s.completions()                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forcer/Programs/jedi/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/forcer/Programs/jedi/jedi/api/__init__.py", line 165, in get_completions
    user_stmt, self._pos)
  File "/home/forcer/Programs/jedi/jedi/evaluate/imports.py", line 52, in completion_names
    importer = Importer(evaluator, tuple(import_path), module, level)
  File "/home/forcer/Programs/jedi/jedi/evaluate/imports.py", line 199, in __init__
    base = module.py__package__().split('.')
  File "/home/forcer/Programs/jedi/jedi/evaluate/representation.py", line 782, in py__package__
    if self._get_init_directory() is None:
  File "/home/forcer/Programs/jedi/jedi/evaluate/representation.py", line 760, in _get_init_directory
    if self.py__file__().endswith(ending):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

If `path` is required, a more readable error might be preferable :-)

**Comment by davidhalter** [comment]
It's not.

**Comment by davidhalter** [comment]
Fixed it!
