### ISSUE TITLE
KeyError for lambda expressions with re-used arguments

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#579]
```
>>> import jedi
>>> s = jedi.Script("class C(object):\n  def m(self):\n    self.x = lambda self:", line=3, column=24)
>>> s.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 106, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 243, in __init__
    self.update(source)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'x'
```

**Comment by jorgenschaefer** [comment]
Seems to be more general (reported as jorgenschaefer/elpy#561):

```
import jedi

source = '''\                                                                   
max(hash_table., key=lambda)                                                    
'''

script = jedi.Script(column=15, source=source, line=1)
script.completions()
```

**Comment by davidhalter** [comment]
It seems to be working with the test above!
