### ISSUE TITLE
Jedi crashes on superscript

### ISSUE THREAD

**Issue by tinloaf** [davidhalter/jedi#587]
Hi, 

I just got this backtrace from my Jedi after typing a "¹":

```
Traceback (most recent call last):
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/jedi-cmd.py", line 63, in _process_line
    completions = script.completions()
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/api/__init__.py", line 180, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/user_context.py", line 300, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/user_context.py", line 290, in user_stmt
    module = self.module()
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/user_context.py", line 336, in module
    return self._parser().module
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/user_context.py", line 281, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/pgen2/parse.py", line 105, in parse
    for type, value, prefix, start_pos in tokenizer:
  File "/mnt/data/home/tinloaf/src/acp-python-jedi/lib/python_packages/jedi/parser/__init__.py", line 343, in _tokenize
    typ = token.opmap[value]
KeyError: '¹'
```

Don't worry about the strange path where Jedi lives, that's just how I ship it with my autocomplete plugin. Jedi is currently shipped with commit 1e623509cdf3276181204d5c525fe4ffd97e7f59 (10.4.2015), so fairly recent. I'm running Python 3.4.1 here.

**Comment by davidhalter** [comment]
Fixed, thanks!
