### ISSUE TITLE
KeyError: 'pytest'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#590]
A user reported another issue. The KeyError seems very similar to #579, but I am not sure if it's the same problem.

Originally reported as jorgenschaefer/elpy#564

```
Jedi..............: 0.9.0

Traceback

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
AttributeError: 'Name' object has no attribute 'children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 216, in run_with_debug
    return getattr(script, name)()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 397, in _parse
    line_offset, nodes)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: 'pytest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
AttributeError: 'Name' object has no attribute 'children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flub/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/flub/Abilisoft/topoenv/envs/topology/lib/python3.4/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: 'pytest'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
import pytest


@pytest.fixture
def'''

script = jedi.Script(path='/tmp/sandbox/test_foo.py', column=3, line=5, encoding='utf-8', source=source)
script.completions()
```

**Comment by yejianye** [comment]
This error could also be reproduced with a simple '@property' decorator

```python
import jedi

source = '''\
class foo(object):
    @property
    def bar(gook):
'''
script  = jedi.Script(column=16, source=source, line=3)
script.completions()
```
I'm using jedi with anaconda-mode in emacs. This bug is causing emacs super laggy when completing decorated functions.
