### ISSUE TITLE
KeyError during creation of jedi.Interpreter

### ISSUE THREAD

**Issue by jonathanslenders** [davidhalter/jedi#594]
When typing the following string in the ptpython REPL:
```python
lambda a, b: a if a > b else b
```
It crashes at the point when the repl is completing:
```python
lambda a, b: a i
```

Traceback.
```python
Traceback (most recent call last):      
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()                          
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jonathan/git/python-prompt-toolkit/prompt_toolkit/interface.py", line 479, in run                                                                                                                                                      [F2] Sidebar - CPython 2.7.6 
    CompleteEvent(text_inserted=True)))
  File "/home/jonathan/git/ptpython/ptpython/completer.py", line 104, in get_completions
    script = get_jedi_script_from_document(document, self.get_locals(), self.get_globals())
  File "/home/jonathan/git/ptpython/ptpython/utils.py", line 50, in get_jedi_script_from_document
    namespaces=[locals, globals])
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 598, in __init__
    self._parser.module())
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 287, in _parser
    parser = Parser(self._grammar, self._source, self._path)
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/jonathan/.virtualenvs/env/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'a'
```

See also: https://github.com/jonathanslenders/ptpython/issues/44

Thanks for having a look a this and keep up the good work!

Jonathan

**Comment by davidhalter** [comment]
May be related to #590 and 579.
