### ISSUE TITLE
Errors when editing a file whose path contains a non-ascii character

### ISSUE THREAD

**Issue by njsmith** [davidhalter/jedi#595]
On linux using elpy with python 2.7, jedi 0.9.0 installed via pip, I try:
```
$ mkdir project-with-stéfan
$ cd project-with-stéfan
$ emacs test.py
```
and now while editing the file, I get a constant stream of error messages:
```
error in process filter: Error from RPC: "'ascii' codec can't encode character u'\\xe9' in position 37: ordinal not in range(128)"
```
Running `elpy-rpc-traceback` suggests that the problem is inside `jedi`:
```
Traceback (most recent call last):
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/elpy/rpc.py", line 103, in handle_request
    if request_id is not None:
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/elpy/server.py", line 52, in handle
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/elpy/backends/jedibackend.py", line 85, in rpc_get_calltip
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api.py", line 293, in get_in_function_call
    return self.function_definition()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api.py", line 302, in function_definition
    sig = self.call_signatures()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api_classes.py", line 44, in wrapper
    result = func(*args, **kwds)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api.py", line 500, in call_signatures
    call, index = self._func_call_and_param_index()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api.py", line 517, in _func_call_and_param_index
    user_stmt = self._user_stmt()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api.py", line 198, in _user_stmt
    user_stmt = self._parser.user_stmt
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api.py", line 96, in _parser
    return self._module.parser
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/modules.py", line 116, in parser
    self.position)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/fast_parser.py", line 70, in __call__
    user_position)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/fast_parser.py", line 196, in __init__
    self._parse(code)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/fast_parser.py", line 344, in _parse
    line_offset, nodes, not is_first)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/fast_parser.py", line 407, in _get_parser
    no_docstr=no_docstr)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parsing.py", line 68, in __init__
    self._parse()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parsing.py", line 472, in _parse
    for token_type, tok in self.iterator:
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parsing.py", line 418, in next
    return self.__next__()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parsing.py", line 448, in __next__
    (self.parserline.replace('\n', ''), repr(self._scope)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)
```

**Comment by davidhalter** [comment]
Can you post the content of `test.py`?

**Comment by njsmith** [comment]
It's an empty file I created to check that this minimal reproduction
worked. I just opened it and started typing a few characters... I think I
typed "class foo" or something like that, but in my experience it doesn't
matter at all -- start doing anything with such a file and every few
seconds you start getting errors to the minibuffer. If you're having
trouble reproducing let me know and I'll provide more detailed
instructions...

**Comment by davidhalter** [comment]
It looks like an old version of Jedi, could you please upgrade to Jedi 0.9.0?

**Comment by njsmith** [comment]
Ah-hah, right, I upgraded jedi to make sure the bug was still there before reporting, but forgot to `M-x elpy-rpc-restart`... after having done that I'm not seeming to tickle the bug in some quick tests, so hopefully it's sorted, and I'll re-open if not. Sorry for the bother, and thanks!
