### ISSUE TITLE
Exception when trying to display documentation for a Python C extension

### ISSUE THREAD

**Issue by lesbeben** [davidhalter/jedi#596]
Hi,

I'm getting an exception whenever I try to display documentation for my module.
Pydoc generates it correctly, but in vim when pressing shift+K on my module name, I get:
```
Exception, this shouldn't happen.
Traceback (most recent call last):
  File "/home/beben/.vim/bundle/jedi-vim/jedi_vim.py", line 268, in show_documentation
    definitions = script.goto_definitions()
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 365, in goto_definitions
    names = [s.name for s in definitions]
AttributeError: 'NoneType' object has no attribute 'name'
No documentation found for that.
```

Thanks for your help.

For reference: http://stackoverflow.com/questions/30644539/how-to-make-jedi-recognize-a-python-c-extension

**Comment by davidhalter** [comment]
One of the definitions is `None`. This should never happen.

**Comment by lesbeben** [comment]
Maybe it's because I did not set something on my side? 
I was reluctant to post here at first because I thought there was something missing from my module. 
When I try to display documentation for a funciton, I get:
```
Exception, this shouldn't happen.
Traceback (most recent call last):
  File "/home/beben/.vim/bundle/jedi-vim/jedi_vim.py", line 268, in show_documentation
    definitions = script.goto_definitions()
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 362, in goto_definitions
    definitions = set(self._prepare_goto(goto_path))
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 257, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 117, in find_types
    scopes = f.scopes(search_global)
  File "/home/beben/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 109, in scopes
    return ((n, None) for n in self.scope.names_dicts(search_global))
AttributeError: 'NoneType' object has no attribute 'names_dicts'
No documentation found for that.
```

**Comment by davidhalter** [comment]
Well, I know what you mean, but Jedi should catch exactly those cases. If you have a "bad" module, Jedi shouldn't crash, IMO.

**Comment by lesbeben** [comment]
I'm pretty sure I have a "bad" module :laughing: 
It's my first time coding a C extension for Python, I followed the documentation closely, but I'm bound to have made some mistakes here and there...
I mean, it's running perfectly and it never crashed, but I wouldn't be surprised if I forgot something "seemingly unimportant" somewhere :stuck_out_tongue:

**Comment by davidhalter** [comment]
Can you retry? I'm pretty sure I fixed something similar.

**Comment by davidhalter** [comment]
I'm closing, let me know if this bug still exists and I'll reopen.
