### ISSUE TITLE
KeyError: <Name: deprecate@244,11>

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#601]
In Jedi 0.9.0, a user was trying to get the completions of `plt` from matplotlib:

```Python
import numpy as np
import matplotlib.pyplot as plt
fig,  ax =  plt.
```

This caused the following error:

```
Traceback (most recent call last):
  File "c:\Users\admin\GoogleDrive\Git\Configurations\Emacs\.emacs.d\elpa\elpy-1.8.0\elpy\rpc.py", line 100, in handle_request
    result = method(*params)
  File "c:\Users\admin\GoogleDrive\Git\Configurations\Emacs\.emacs.d\elpa\elpy-1.8.0\elpy\server.py", line 93, in rpc_get_completions
    get_source(source), offset)
  File "c:\Users\admin\GoogleDrive\Git\Configurations\Emacs\.emacs.d\elpa\elpy-1.8.0\elpy\server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "c:\Users\admin\GoogleDrive\Git\Configurations\Emacs\.emacs.d\elpa\elpy-1.8.0\elpy\jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "c:\Users\admin\GoogleDrive\Git\Configurations\Emacs\.emacs.d\elpa\elpy-1.8.0\elpy\jedibackend.py", line 45, in <listcomp>
    for proposal in proposals]
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 470, in type
    followed = self.follow_definition()
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\imports.py", line 103, in follow
    for t in types))
  File "c:\Python34\lib\site-packages\jedi\evaluate\imports.py", line 103, in <genexpr>
    for t in types))
  File "c:\Python34\lib\site-packages\jedi\evaluate\__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "c:\Python34\lib\site-packages\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "c:\Python34\lib\site-packages\jedi\evaluate\finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "c:\Python34\lib\site-packages\jedi\evaluate\finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "c:\Python34\lib\site-packages\jedi\evaluate\__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "c:\Python34\lib\site-packages\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\__init__.py", line 299, in execute
    types = func(self, arguments)
  File "c:\Python34\lib\site-packages\jedi\_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "c:\Python34\lib\site-packages\jedi\evaluate\representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "c:\Python34\lib\site-packages\jedi\evaluate\helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "c:\Python34\lib\site-packages\jedi\evaluate\helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "c:\Python34\lib\site-packages\jedi\evaluate\helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "c:\Python34\lib\site-packages\jedi\evaluate\helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "c:\Python34\lib\site-packages\jedi\evaluate\helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
  File "c:\Python34\lib\site-packages\jedi\evaluate\helpers.py", line 55, in <listcomp>
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: <Name: deprecate@244,11>
```

Originally reported as jorgenschaefer/elpy#597

**Comment by davidhalter** [comment]
It seems to work now. I cannot reproduce it anymore.
