### ISSUE TITLE
AttributeError: 'list' object has no attribute 'isinstance'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#625]
Using Python 2.7.0, Jedi 0.9.0, a user reported receiving the following error. (Originally reported as jorgenschaefer/elpy#669)

```
Traceback

Traceback (most recent call last):
  File "/home/mje/.emacs.d/elpa/elpy-20150830.510/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/mje/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/home/mje/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/mje/.emacs.d/elpa/elpy-20150830.510/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 300, in _name_to_types
    typ = typ.get_decorated_func()
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 533, in get_decorated_func
    wrappers = self._evaluator.execute_evaluated(decorator, old_func)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 275, in execute_evaluated
    return self.execute(obj, args)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 167, in names_dict_lookup
    return [get_param(name_scope, n) for n in last_names]
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 114, in get_param
    return scope.param_by_name(str(el))
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 644, in param_by_name
    return [n for n in self._get_params() if str(n) == name][0]
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 641, in _get_params
    return param.get_params(self._evaluator, self.base, self.var_args)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/param.py", line 295, in get_params
    calling_va, message=m)
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/analysis.py", line 83, in add
    if _check_for_exception_catch(evaluator, jedi_obj, exception, payload):
  File "/home/mje/Toolboxes/anaconda/lib/python2.7/site-packages/jedi/evaluate/analysis.py", line 199, in _check_for_exception_catch
    while obj is not None and not obj.isinstance(tree.Function, tree.Class):
AttributeError: 'list' object has no attribute 'isinstance'
```

**Comment by davidhalter** [comment]
If this issue still exists, let me know. However the traceback is not meaningful at all in this case. You would need to provide some way of reproducing it (or at least hints).
