### ISSUE TITLE
'Lambda' object has no attribute 'get_subscope_by_name'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#628]
Jedi 0.9.0, Python 2.7.3

Reproduction:

```Python
import jedi

script = """\                                                                   
my_lambda = lambda x: x+1                                                       
my_lambda(1)                                                                    
"""

sigs = jedi.Script(script, line=2, column=11).call_signatures()
print sigs[0].index
```

Traceback:

```
Traceback (most recent call last):
  File "/home/forcer/Projects/elpy/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/forcer/Projects/elpy/elpy/server.py", line 87, in rpc_get_calltip
    get_source(source), offset)
  File "/home/forcer/Projects/elpy/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/forcer/Projects/elpy/elpy/jedibackend.py", line 129, in rpc_get_calltip
    "index": call.index,
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 563, in __getattr__
    return getattr(self.base_func, name)
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'
```

**Comment by kelleyk** [comment]
I can confirm that this happens in Python 3.5.0, too.

**Comment by kelleyk** [comment]
Oops!  Some whitespace snuck in when I was saving @jorgenschaefer's reproduction case to a file.  I am now seeing the same stack trace under both versions of Python and both versions of `jedi`.

**Comment by davidhalter** [comment]
This is working now!
