### ISSUE TITLE
'Class' object has no attribute 'is_generator'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#642]
With Jedi 0.9.0 on Python 3.4.3, a user reported the following error:

```
Traceback (most recent call last):
  File "/home/jose/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 216, in run_with_debug
    return getattr(script, name)()
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 276, in _name_to_types
    types += _eval_param(evaluator, typ, scope)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 367, in _eval_param
    res_new += dynamic.search_params(evaluator, param)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/dynamic.py", line 63, in search_params
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/dynamic.py", line 63, in <genexpr>
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/param.py", line 174, in eval
    types += evaluator.eval_element(v)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/usr/local/lib/python3.4/dist-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/usr/local/lib/python3.4/dist-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 200, in eval_element
    return (self.eval_element(element.children[0]) +
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/usr/local/lib/python3.4/dist-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 557, in py__call__
    if self.base.is_generator():
AttributeError: 'Class' object has no attribute 'is_generator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jose/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 276, in _name_to_types
    types += _eval_param(evaluator, typ, scope)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/finder.py", line 367, in _eval_param
    res_new += dynamic.search_params(evaluator, param)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/dynamic.py", line 63, in search_params
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/dynamic.py", line 63, in <genexpr>
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/param.py", line 174, in eval
    types += evaluator.eval_element(v)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/usr/local/lib/python3.4/dist-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/usr/local/lib/python3.4/dist-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 200, in eval_element
    return (self.eval_element(element.children[0]) +
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/local/lib/python3.4/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/usr/local/lib/python3.4/dist-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/representation.py", line 557, in py__call__
    if self.base.is_generator():
AttributeError: 'Class' object has no attribute 'is_generator'

Jedi Debug Information

[N] dbg: While parsing '/home/jose/Desktop/Python_Libraries/data_structures/expression_tree.py', line 34 slowed down the fast parser.
[N] dbg: Parsed /home/jose/Desktop/Python_Libraries/data_structures/expression_tree.py, with 1 parsers in 7 splits.
[W] warning: No statement under the cursor.
[N] dbg: start: 'p' in <IfStmt:         if self.is_leaf(p):             return float(p.element())                         # we assume element is numeric         else: @60,8>
[N] dbg: eval_element <Name: p@63,19>@(63, 19)
[N] dbg: finder.filter_name "<Name: p@63,19>" in (<eFunction of <Function: _evaluate_recur@58-64>>): '[<Name: p@58,30>]'@(63, 19)
[N]  dbg: Dynamic param search for <Param: p> in '_evaluate_recur'.
[N]  dbg: eval_element Node(power, [<Name: self@56,15>, Node(trailer, [<Operator: .>, <Name: _evaluate_recur@56,20>])])@(56, 15)
[N]   dbg: finder.filter_name "<Name: self@56,15>" in (<eFunction of <Function: evaluate@54-58>>): '[<Name: self@54,17>]'@(56, 15)
[N]   dbg: finder._names_to_types: [<Name: self@54,17>] -> [<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>]
[N]  dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: _evaluate_recur@56,20>]) in scope <eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>
[N]  dbg: eval_element <Name: LinkedBinaryTree@13,21>@(13, 21)
[N]   dbg: finder.filter_name "<Name: LinkedBinaryTree@13,21>" in (<eClass of <Class: ExpressionTree@13-64>>): '[<Name: LinkedBinaryTree@11,31>]'@(13, 21)
[N]   dbg: search_module 'linked_binary_tree' in '/home/jose/Desktop/Python_Libraries/data_structures/expression_tree.py'
[N]    dbg: finder.filter_name "'LinkedBinaryTree'" in (<ModuleWrapper: <fast.FastModule: linked_binary_tree@12-17>>): '[<Name: LinkedBinaryTree@14,6>]'@None
[N]    dbg: finder._names_to_types: [<FakeName: LinkedBinaryTree@14,6>] -> [<eClass of <Class: LinkedBinaryTree@14-183>>]
[N]   dbg: after import: [<eClass of <Class: LinkedBinaryTree@14-183>>]
[N]   dbg: finder._names_to_types: [<Name: LinkedBinaryTree@11,31>] -> [<eClass of <Class: LinkedBinaryTree@14-183>>]
[N]  dbg: eval_element <Name: BinaryTree@14,23>@(14, 23)
[N]   dbg: finder.filter_name "<Name: BinaryTree@14,23>" in (<eClass of <Class: LinkedBinaryTree@14-183>>): '[<Name: BinaryTree@12,28>]'@(14, 23)
[N]   dbg: search_module 'binary_tree_ADT' in '/home/jose/Desktop/Python_Libraries/data_structures/linked_binary_tree.py'
[N]    dbg: finder.filter_name "'BinaryTree'" in (<ModuleWrapper: <fast.FastModule: binary_tree_ADT@12-18>>): '[<Name: BinaryTree@14,6>]'@None
[N]    dbg: finder._names_to_types: [<FakeName: BinaryTree@14,6>] -> [<eClass of <Class: BinaryTree@14-73>>]
[N]   dbg: after import: [<eClass of <Class: BinaryTree@14-73>>]
[N]   dbg: finder._names_to_types: [<Name: BinaryTree@12,28>] -> [<eClass of <Class: BinaryTree@14-73>>]
[N]  dbg: eval_element <Name: Tree@14,17>@(14, 17)
[N]   dbg: finder.filter_name "<Name: Tree@14,17>" in (<eClass of <Class: BinaryTree@14-73>>): '[<Name: Tree@12,21>]'@(14, 17)
[N]   dbg: search_module 'tree_ADT' in '/home/jose/Desktop/Python_Libraries/data_structures/binary_tree_ADT.py'
[N]    dbg: finder.filter_name "'Tree'" in (<ModuleWrapper: <fast.FastModule: tree_ADT@11-17>>): '[<Name: Tree@13,6>]'@None
[N]    dbg: finder._names_to_types: [<FakeName: Tree@13,6>] -> [<eClass of <Class: Tree@13-147>>]
[N]   dbg: after import: [<eClass of <Class: Tree@13-147>>]
[N]   dbg: finder._names_to_types: [<Name: Tree@12,21>] -> [<eClass of <Class: Tree@13-147>>]
[N]   dbg: execute: <eClass of <Class: LinkedBinaryTree@14-183>> <Arguments: ()>
[N]    dbg: execute: <InstanceElement of <eFunction of <Function: __init__@46-53>>> <Arguments: ()>
[N]    dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@46-53>>>
[N]   dbg: execute result: [<eInstance of <eClass of <Class: LinkedBinaryTree@14-183>>(<Arguments: ()>)>] in <eClass of <Class: LinkedBinaryTree@14-183>>
[N]   dbg: execute: <eClass of <Class: BinaryTree@14-73>> <Arguments: ()>
[N]   dbg: execute result: [<eInstance of <eClass of <Class: BinaryTree@14-73>>(<Arguments: ()>)>] in <eClass of <Class: BinaryTree@14-73>>
[N]   dbg: execute: <eClass of <Class: Tree@13-147>> <Arguments: ()>
[N]   dbg: execute result: [<eInstance of <eClass of <Class: Tree@13-147>>(<Arguments: ()>)>] in <eClass of <Class: Tree@13-147>>
[N]   dbg: finder.filter_name "<Name: _evaluate_recur@56,20>" in (<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>): '[<InstanceName: _evaluate_recur@58,8>]'@None
[N]   dbg: finder._names_to_types: [<InstanceName: _evaluate_recur@58,8>] -> [<InstanceElement of <eFunction of <Function: _evaluate_recur@58-64>>>]
[N]  dbg: eval_trailer: Node(trailer, [<Operator: (>, Node(power, [<Name: self@56,36>, Node(trailer, [<Operator: .>, <Name: root@56,41>]), Node(trailer, [<Operator: (>, <Operator: )>])]), <Operator: )>]) in scope <InstanceElement of <eFunction of <Function: _evaluate_recur@58-64>>>
[N]   dbg: execute: <InstanceElement of <eFunction of <Function: _evaluate_recur@58-64>>> <Arguments: Node(power, [<Name: self@56,36>, Node(trailer, [<Operator: .>, <Name: root@56,41>]), Node(trailer, [<Operator: (>, <Operator: )>])])>
[N]   dbg: execute result: [] in <InstanceElement of <eFunction of <Function: _evaluate_recur@58-64>>>
[N]  dbg: eval_element Node(power, [<Name: self@56,36>, Node(trailer, [<Operator: .>, <Name: root@56,41>]), Node(trailer, [<Operator: (>, <Operator: )>])])@(56, 36)
[N]   dbg: finder.filter_name "<Name: self@56,36>" in (<eFunction of <Function: evaluate@54-58>>): '[<Name: self@54,17>]'@(56, 36)
[N]   dbg: finder._names_to_types: [<Name: self@54,17>] -> [<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>]
[N]  dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: root@56,41>]) in scope <eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>
[N]   dbg: finder.filter_name "<Name: root@56,41>" in (<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>): '[<InstanceName: root@155,8>]'@None
[N]   dbg: finder._names_to_types: [<InstanceName: root@155,8>] -> [<InstanceElement of <eFunction of <Function: root@155-159>>>]
[N]  dbg: eval_trailer: Node(trailer, [<Operator: (>, <Operator: )>]) in scope <InstanceElement of <eFunction of <Function: root@155-159>>>
[N]   dbg: execute: <InstanceElement of <eFunction of <Function: root@155-159>>> <Arguments: ()>
[N]   dbg: eval_element Node(power, [<Name: self@157,15>, Node(trailer, [<Operator: .>, <Name: _make_position@157,20>]), Node(trailer, [<Operator: (>, Node(power, [<Name: self@157,35>, Node(trailer, [<Operator: .>, <Name: _root@157,40>])]), <Operator: )>])])@(157, 15)
[N]    dbg: finder.filter_name "<Name: self@157,15>" in (<FunctionExecution of <InstanceElement of <eFunction of <Function: root@155-159>>>>): '[<FakeName: self@155,13>]'@(157, 15)
[N]    dbg: finder._names_to_types: [<FakeName: self@155,13>] -> [<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>]
[N]   dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: _make_position@157,20>]) in scope <eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>
[N]    dbg: finder.filter_name "<Name: _make_position@157,20>" in (<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>): '[<InstanceName: _make_position@63,8>]'@None
[N]    dbg: finder._names_to_types: [<InstanceName: _make_position@63,8>] -> [<InstanceElement of <eFunction of <Function: _make_position@63-67>>>]
[N]   dbg: eval_trailer: Node(trailer, [<Operator: (>, Node(power, [<Name: self@157,35>, Node(trailer, [<Operator: .>, <Name: _root@157,40>])]), <Operator: )>]) in scope <InstanceElement of <eFunction of <Function: _make_position@63-67>>>
[N]    dbg: execute: <InstanceElement of <eFunction of <Function: _make_position@63-67>>> <Arguments: Node(power, [<Name: self@157,35>, Node(trailer, [<Operator: .>, <Name: _root@157,40>])])>
[N]    dbg: eval_element Node(test, [Node(power, [<Name: self@65,15>, Node(trailer, [<Operator: .>, <Name: Position@65,20>]), Node(trailer, [<Operator: (>, Node(arglist, [<Name: self@65,29>, <Operator: ,>, <Name: node@65,35>]), <Operator: )>])]), <Keyword: if>, Node(comparison, [<Name: node@65,44>, Node(comp_op, [<Keyword: is>, <Keyword: not>]), <Keyword: None>]), <Keyword: else>, <Keyword: None>])@(65, 15)
[N]    dbg: eval_element Node(power, [<Name: self@65,15>, Node(trailer, [<Operator: .>, <Name: Position@65,20>]), Node(trailer, [<Operator: (>, Node(arglist, [<Name: self@65,29>, <Operator: ,>, <Name: node@65,35>]), <Operator: )>])])@(65, 15)
[N]     dbg: finder.filter_name "<Name: self@65,15>" in (<FunctionExecution of <InstanceElement of <eFunction of <Function: _make_position@63-67>>>>): '[<FakeName: self@63,23>]'@(65, 15)
[N]     dbg: finder._names_to_types: [<FakeName: self@63,23>] -> [<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>]
[N]    dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: Position@65,20>]) in scope <eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>
[N]     dbg: finder.filter_name "<Name: Position@65,20>" in (<eInstance of <eClass of <Class: ExpressionTree@13-64>>(<Arguments: ()>)>): '[<InstanceName: Position@28,10>]'@None
[N]     dbg: finder._names_to_types: [<InstanceName: Position@28,10>] -> [<InstanceElement of <eClass of <Class: Position@28-46>>>]
[N]    dbg: eval_trailer: Node(trailer, [<Operator: (>, Node(arglist, [<Name: self@65,29>, <Operator: ,>, <Name: node@65,35>]), <Operator: )>]) in scope <InstanceElement of <eClass of <Class: Position@28-46>>>
[N]     dbg: execute: <InstanceElement of <eClass of <Class: Position@28-46>>> <Arguments: Node(arglist, [<Name: self@65,29>, <Operator: ,>, <Name: node@65,35>])>
```

The reproduction case is incomplete, so I'll leave that out. Is the above sufficient to identify the problem or should I ask the user to provide more of the code?

Originally reported as jorgenschaefer/elpy#698

**Comment by kootenpv** [comment]
Elpy (because of Jedi) was constantly crashing today. Until it becomes official, I was able to use:

    pip install https://github.com/davidhalter/jedi/archive/dev.zip

to install from Jedi's dev branch.

So far no issues yet.

**Comment by davidhalter** [comment]
Do you have a reproduction case for it?

**Comment by kootenpv** [comment]
I'm thinking it might have to do with `namedtuple`.
