### ISSUE TITLE
StopIteration in `call_signatures`

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#647]
Hello there. Another weird problem with Python 3.5, apparently – does not happen with earlier versions of Python.

Jedi 0.9.0, Python 3.5.

Reproduction:

```Python
import jedi

source = '''\
import os
import fnmatch


def all_files():
    base = '/projects/DATASETS/nsidc0051_gsfc_nasateam_seaice/final-gsfc/'
    filelist = []
    for root, dirs, files in os.walk(base):
        # if 'monthly' in dirs:
        #     dirs.remove('monthly')
        filelist.extend([os.path.join(root, f) for f in fnmatch.filter(files, '*.bin')])
    return sorted(filelist)
'''

script = jedi.Script(encoding='utf-8', line=10, column=31, path='/vagrant/source/seaicedata/tmp.py', source=source)
script.call_signatures()
```

Backtrace:

```
Traceback (most recent call last):
  File "/home/vagrant/.emacs.d/.cask/24.5.1/elpa/elpy-20151101.401/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/iterable.py", line 90, in iter_content
    return f.get_return_types(check_yields=True)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/precedence.py", line 45, in calculate_children
    right = next(iterator)
StopIteration
```

**Comment by jorgenschaefer** [comment]
Originally reported as jorgenschaefer/elpy#711

**Comment by asvetlov** [comment]
I have the same error.

My reproduction code
Reproduction:

```Python
import jedi

source = '''\
import injections
import pytest

from model_mapper import ModelMapper


@pytest.mark.run_loop
def test_simple(rwdb, rodb):
    mapper = ModelMapper()
    mapper._random.seed(1234)
    inj = injections.Container()
    inj['rodb'] = rodb
    inj.inject(mapper)

    lock = yield from rwdb.acquire()
    try:
        pass
    finally:
        yield from lock.
'''

script = jedi.Script(encoding='utf-8', column=24, source=source, line=19, path='/home/andrew/projects/job_router/tests/test_model_mapper.py')
script.completions()
```

**Comment by davidhalter** [comment]
Probably, because yield from has not been implemented.
