### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'path'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#658]
Jedi 0.9.0, Python 3.5.0, so possibly another 3.5 issue. Originally reported as jorgenschaefer/elpy#739 (also includes a reproduction case I have not tested yet):

```
Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 217, in completions
    new = classes.Completion(self._evaluator, c, needs_dot, len(like))
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 369, in __init__
    super(Completion, self).__init__(evaluator, name)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 72, in __init__
    self.module_path = self._module.path
AttributeError: 'Node' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 217, in completions
    new = classes.Completion(self._evaluator, c, needs_dot, len(like))
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 369, in __init__
    super(Completion, self).__init__(evaluator, name)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 72, in __init__
    self.module_path = self._module.path
AttributeError: 'Node' object has no attribute 'path'

Jedi Debug Information

[N] dbg: While parsing '/home/bibek/Templates/python/reverseshell/server.py', line 7 slowed down the fast parser.
[N] dbg: Parsed /home/bibek/Templates/python/reverseshell/server.py, with 1 parsers in 2 splits.
[W] warning: No statement under the cursor.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
```

**Comment by Gnouc** [comment]
The same issue with `python 2.7.9`

**Comment by davidhalter** [comment]
The issue https://github.com/jorgenschaefer/elpy/issues/739 contains a few reproduction cases for possibly different issues. I have fixed all of them.

Only the second one seems to have still appeared, the others were fixed along the lines.
