### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#686]
Jedi 0.9.0, Python 2.7.8, but no reproduction steps, I'm afraid:

```
Traceback (most recent call last):
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/server.py", line 86, in rpc_get_calltip
    get_source(source), offset)
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 129, in rpc_get_calltip
    "index": call.index,
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/tree.py", line 1185, in name
    if is_node(self._tfpdef(), 'tfpdef'):
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/tree.py", line 1181, in _tfpdef
    return self.children[offset]
IndexError: list index out of range
```

Original reporter says:

> This one happened as I was editing a function signature to add a `*args` at the end -- I typed `*` and the traceback popped up.

Originally reported as jorgenschaefer/elpy#595

**Comment by davidhalter** [comment]
Hmm, I'm pretty sure this one is solved with the latest changes to the `*` operator in params.
