### ISSUE TITLE
AttributeError: 'NoneType' has no attribute 'get_parent_until'

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#688]
Jedi 0.9.0, Python 3.4.3. Originally reported as jorgenschaefer/elpy#745, but without reproduction steps, sadly.

```
Traceback (most recent call last):
  File "/Users/jmadden/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/jmadden/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/Users/jmadden/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/Users/jmadden/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/Users/jmadden/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in <listcomp>
    for proposal in proposals]
  File "/.../lib/python3.4/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/imports.py", line 231, in sys_path_with_modifications
    sys_path_mod = list(sys_path.sys_path_with_modifications(self._evaluator, self.module))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/sys_path.py", line 159, in sys_path_with_modifications
    result = _check_module(evaluator, module)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/sys_path.py", line 142, in _check_module
    sys_path.extend(_paths_from_assignment(evaluator, stmt))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/sys_path.py", line 95, in _paths_from_assignment
    for val in get_iterator_types(evaluator.eval_statement(expr_stmt)):
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 407, in get_iterator_types
    result += it.values()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 236, in values
    result = unite(self._evaluator.eval_element(v) for v in self._values())
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 38, in unite
    return list(chain.from_iterable(iterable))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 236, in <genexpr>
    result = unite(self._evaluator.eval_element(v) for v in self._values())
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 276, in _name_to_types
    types += _eval_param(evaluator, typ, scope)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 367, in _eval_param
    res_new += dynamic.search_params(evaluator, param)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/dynamic.py", line 63, in search_params
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/dynamic.py", line 63, in <genexpr>
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/.../lib/python3.4/site-packages/jedi/evaluate/param.py", line 174, in eval
    types += evaluator.eval_element(v)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 267, in eval_trailer
    new_types += get(self, node)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/representation.py", line 212, in get_index_types
    return self._evaluator.execute(method, [iterable.AlreadyEvaluated(indexes)])
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/.../lib/python3.4/site-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 267, in eval_trailer
    new_types += get(self, node)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 229, in get_index_types
    types += self.get_exact_index_types(index.obj)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 255, in get_exact_index_types
    return self._evaluator.eval_element(self._items()[mixed_index])
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/.../lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 577, in iter_content
    items += _check_array_additions(self._evaluator, self.instance, module, is_list)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 483, in _check_array_additions
    comp_arr_parent = get_execution_parent(compare_array)
  File "/.../lib/python3.4/site-packages/jedi/evaluate/iterable.py", line 477, in get_execution_parent
    return node.get_parent_until(er.FunctionExecution)
AttributeError: 'NoneType' object has no attribute 'get_parent_until'
```

**Comment by davidhalter** [comment]
I've tried to track down this issue for quite a long time. I cannot reproduce it. I could possibly fix it, but I won't until I have a reproducible test. Please post it again, once you have one!
