### ISSUE TITLE
IndexError when using defined_names() on a very empty function

### ISSUE THREAD

**Issue by MathieuDuponchelle** [davidhalter/jedi#697]
Reproduced with : 

```python
import jedi

source = '''
def lol():
    pass
'''

defs = jedi.names(source=source)
print defs[0].defined_names()
```

on the master branch, happens with the linter branch as well FWIW.

Expected output:

```shell
[]
```

Actual output:

```shell
(dev_env)[meh@meh-host hotdoc]$ python repro_issue.py 
Traceback (most recent call last):
  File "repro_issue.py", line 9, in <module>
    print defs[0].defined_names()
  File "/home/meh/devel/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/meh/devel/jedi/jedi/api/classes.py", line 603, in defined_names
    iterable = list(iterable)
  File "/home/meh/devel/jedi/jedi/api/classes.py", line 602, in <genexpr>
    iterable = (defined_names(self._evaluator, d) for d in defs)
  File "/home/meh/devel/jedi/jedi/api/classes.py", line 32, in defined_names
    names = filter_definition_names(names, scope)
  File "/home/meh/devel/jedi/jedi/evaluate/finder.py", line 62, in filter_definition_names
    stmt = names[0].get_definition()
IndexError: list index out of range
(dev_env)[meh@meh-host hotdoc]$
```

**Comment by MathieuDuponchelle** [comment]
\o/ well done :)
