### ISSUE TITLE
ValueError: Node(…) is not in list

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#704]
Jedi 0.9.0, Python 3.4.3:

```
Traceback (most recent call last):
  File "/home/joost/src/Python/Environments/Udemy/lib/python3.4/site-packages/jedi/api/classes.py", line 722, in full
    return self._name.doc
AttributeError: 'ExprStmt' object has no attribute 'doc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joost/.elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/joost/.elpa/elpy-20160131.118/elpy/server.py", line 107, in rpc_get_completion_docstring
    None, completion)
  File "/home/joost/.elpa/elpy-20160131.118/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/home/joost/.elpa/elpy-20160131.118/elpy/jedibackend.py", line 52, in rpc_get_completion_docstring
    return proposal.docstring(fast=False)
  File "/home/joost/src/Python/Environments/Udemy/lib/python3.4/site-packages/jedi/api/classes.py", line 457, in docstring
    return _Help(definition).full()
  File "/home/joost/src/Python/Environments/Udemy/lib/python3.4/site-packages/jedi/api/classes.py", line 724, in full
    return self.raw()
  File "/home/joost/src/Python/Environments/Udemy/lib/python3.4/site-packages/jedi/api/classes.py", line 733, in raw
    return self._name.raw_doc
  File "/home/joost/src/Python/Environments/Udemy/lib/python3.4/site-packages/jedi/parser/tree.py", line 75, in raw_doc
    index = c.index(simple_stmt)
ValueError: Node(simple_stmt, [<ExprStmt: locations = {0: "You are sitting in front of a computer learning Python",              1: "You are standing at the end of a road before a small brick building",              2: "You are at the top of a hill",              3: "You are inside a building, a well house for a small stream",              4: "You are in a valley beside a stream",              5: "You are in the forest"}@1,0>, <Whitespace: 
>]) is not in list
```

Sadly, I don't have a reproduction case here.

Originally reported as jorgenschaefer/elpy#820

**Comment by davidhalter** [comment]
Can you retry? A lot has changed.

**Comment by jorgenschaefer** [comment]
Tricky – I don't have a reproduction case, and the user does not have a way to reproduce it, either. Feel free to close this report if you believe it is fixed and you can't get anything out of the traceback there. :-)

**Comment by davidhalter** [comment]
Hmm. I think that logic has changed enough so that I cannot tell if it's still buggy. I'm closing and happy to get another report if it comes up again. :)
