### ISSUE TITLE
Instance <eInstance of …>: Don't touch this (is_class)!

### ISSUE THREAD

**Issue by jorgenschaefer** [davidhalter/jedi#706]
Jedi 0.9.0, Python 3.5.1. Originally reported as jorgenschaefer/elpy#830 (also includes reproduction steps using numpy, which I have not tried).

```
Traceback (most recent call last):
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20160131.118/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 267, in eval_trailer
    new_types += get(self, node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 212, in get_index_types
    return self._evaluator.execute(method, [iterable.AlreadyEvaluated(indexes)])
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 620, in get_return_types
    check = flow_analysis.break_check(self._evaluator, self, r)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 48, in break_check
    return _break_check(evaluator, stmt, base_scope, element_scope)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 65, in _break_check
    reachable = _check_if(evaluator, node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 79, in _check_if
    types = evaluator.eval_element(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 289, in execute
    return stdlib.execute(self, obj, arguments)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/stdlib.py", line 42, in execute
    return _implemented[module_name][obj_name](evaluator, obj, params)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/stdlib.py", line 81, in wrapper
    lst = list(arguments.eval_argument_clinic(clinic_args))
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/param.py", line 135, in eval_argument_clinic
    for el in va_values))
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/param.py", line 135, in <genexpr>
    for el in va_values))
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 620, in get_return_types
    check = flow_analysis.break_check(self._evaluator, self, r)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 48, in break_check
    return _break_check(evaluator, stmt, base_scope, element_scope)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 65, in _break_check
    reachable = _check_if(evaluator, node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 79, in _check_if
    types = evaluator.eval_element(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 620, in get_return_types
    check = flow_analysis.break_check(self._evaluator, self, r)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 48, in break_check
    return _break_check(evaluator, stmt, base_scope, element_scope)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 65, in _break_check
    reachable = _check_if(evaluator, node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/flow_analysis.py", line 79, in _check_if
    types = evaluator.eval_element(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 289, in execute
    return stdlib.execute(self, obj, arguments)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/stdlib.py", line 42, in execute
    return _implemented[module_name][obj_name](evaluator, obj, params)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/stdlib.py", line 90, in wrapper
    return func(evaluator, *lst, **kwargs)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/stdlib.py", line 179, in builtins_isinstance
    if cls_or_tup.is_class():
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 224, in __getattr__
    % (self, name))
AttributeError: Instance <eInstance of <eClass of <Class: _ABCGeneric@106-112>>(<Arguments: Node(arglist, [<String: "ABCGeneric">, <Operator: ,>, Node(power, [<Name: tuple@112,39>, Node(trailer, [<Operator: (>, <Operator: )>])]), <Operator: ,>, Node(atom, [<Operator: {>, <Operator: }>])])>)>: Don't touch this (is_class)!
```

**Comment by davidhalter** [comment]
It doesn't seem to be reproducible and I really cannot find the issue. Therefore I'm closing.
