### ISSUE TITLE
[linter] AttributeError: 'Node' object has no attribute 'value' with Node(star_expr)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#707]
When calling `jedi#goto()` I get this:

    Traceback (most recent call last):
      File "…/vim/neobundles/jedi/jedi/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '_user_stmt'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "…/vim/neobundles/jedi/jedi/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '__parser'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "…/vim/neobundles/jedi/jedi_vim.py", line 118, in wrapper
        return func(*args, **kwargs)
      File "…/vim/neobundles/jedi/jedi_vim.py", line 230, in goto
        definitions = [x for x in script.goto_definitions()
      File "…/vim/neobundles/jedi/jedi/jedi/api/__init__.py", line 375, in goto_definitions
        user_stmt = self._parser.user_stmt()
      File "…/vim/neobundles/jedi/jedi/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/user_context.py", line 293, in user_stmt
        module = self.module()
      File "…/vim/neobundles/jedi/jedi/jedi/parser/user_context.py", line 338, in module
        return self._parser().module
      File "…/vim/neobundles/jedi/jedi/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/user_context.py", line 283, in _parser
        parser = FastParser(self._grammar, self._source, self._path)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/fast.py", line 107, in __call__
        p = super(CachedFastParser, self).__call__(grammar, source, module_path)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/fast.py", line 244, in __init__
        self.update(source)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/fast.py", line 258, in update
        self._parse(source)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/fast.py", line 384, in _parse
        line_offset, nodes)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/fast.py", line 436, in _get_node
        p = ParserWithRecovery(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/__init__.py", line 304, in __init__
        super(ParserWithRecovery, self).__init__(grammar, source, 'file_input', tokenizer)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/__init__.py", line 145, in __init__
        self._parsed = p.parse(self._tokenize(tokenizer))
      File "…/vim/neobundles/jedi/jedi/jedi/parser/pgen2/parse.py", line 108, in parse
        if self.addtoken(type, value, prefix, start_pos):
      File "…/vim/neobundles/jedi/jedi/jedi/parser/pgen2/parse.py", line 166, in addtoken
        self.pop()
      File "…/vim/neobundles/jedi/jedi/jedi/parser/pgen2/parse.py", line 198, in pop
        newnode = self.convert_node(self.grammar, type, children)
      File "…/vim/neobundles/jedi/jedi/jedi/parser/__init__.py", line 207, in convert_node
        self._scope_names_stack[-1][n.value].remove(n)
    AttributeError: 'Node' object has no attribute 'value'

This happens for:

    Node(star_expr, [<Operator: *>, <Name: values@9,25>]) ['_IGNORE_EXECUTE_NODES',
    '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__',
    '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__',
    '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__',
    '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__',
    '__subclasshook__', 'assignment_indexes', 'children', 'end_pos',
    'first_leaf', 'get_code', 'get_definition',
    'get_following_comment_same_line', 'get_parent_scope', 'get_parent_until',
    'get_statement_for_position', 'is_scope', 'isinstance', 'last_leaf',
    'move', 'name_for_position', 'nodes_to_execute', 'parent', 'start_pos', 'type']

TEST CASE:

    from .foo import bar
    print([x for a, *x in [(1,2,3), (4,5,6)]])

Then try to goto `bar`.

https://www.python.org/dev/peps/pep-3132/

**Comment by DamnWidget** [comment]
Confirmed, some anaconda users got this error recently using a similar comprehension list syntax.

**Comment by davidhalter** [comment]
Reproduction:

    jedi.Script('from .foo import bar\nprint([x for a, *x in [(1,2,3), (4,5,6)]])', line=1).goto_assignments()

It seems like I have fixed the error. However this does not mean that we support PEP 3132 unpacking, yet.
