### ISSUE TITLE
raise AttributeError: 'NoneType' object has no attribute 'get_parent_until'

### ISSUE THREAD

**Issue by needle-wang** [davidhalter/jedi#712]
when i use gevent:
\#gevent is a package actually~
import gevent
gevent.\<trigger>
raise:
` File "~/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/iterable.py", line 478, in get_execution_parent`
`    return `**node**`.get_parent_until(er.FunctionExecution)`
`AttributeError: 'NoneType' object has no attribute 'get_parent_until'`

in this case, the process goes to:
line 475 : `node = list(element.var_args.argument_node[0])[0].var_args.trailer`
then I find:
`list(element.var_args.argument_node[0])[0].var_args` is
`<class 'jedi.evaluate.param.Arguments'>`

and in class jedi.evaluate.param.Arguments:
`self.trailer = trailer  # Can be None, e.g. in a class definition.`

but I don't know how to fix it.

**Comment by davidhalter** [comment]
Can you try this with the linter branch?

**Comment by needle-wang** [comment]
i just tried a few minutes ago.
raise the same exception at the same code but different line.

![jedi](https://cloud.githubusercontent.com/assets/5860291/14204308/fbb3b2b0-f835-11e5-920c-1e8d67b91268.png)

**Comment by davidhalter** [comment]
Can somebody reproduce this?

**Comment by bstaint** [comment]
reproduce:
```
import jedi
source = '''import gevent

gevent.'''
script = jedi.Script(source, 3, 7, 'test.py', 'utf-8')
completions = script.completions()

for c in completions:
    print c, c.description
```
traceback:
```
<Completion: absolute_import> instance: __future__.absolute_import
<Completion: ares> module: ares
<Completion: backdoor> module: backdoor
<Completion: baseserver> module: baseserver
<Completion: builtins> module: builtins
<Completion: core> module: core
<Completion: corecext> module: corecext
<Completion: corecffi> module: corecffi
<Completion: coros> module: coros
<Completion: event> module: event
<Completion: fileobject> module: fileobject
<Completion: fork> function: gevent.os.fork
<Completion: get_hub> function: gevent.hub.get_hub
<Completion: getcurrent>
Traceback (most recent call last):
  File "1.py", line 9, in <module>
    print c, c.description
  File "/srv/http/jedi/api/classes.py", line 425, in description
    t = self.type
  File "/srv/http/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/srv/http/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/srv/http/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/srv/http/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/srv/http/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/imports.py", line 231, in sys_path_with_modifications
    sys_path_mod = list(sys_path.sys_path_with_modifications(self._evaluator, self.module))
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/sys_path.py", line 159, in sys_path_with_modifications
    result = _check_module(evaluator, module)
  File "/srv/http/jedi/evaluate/sys_path.py", line 142, in _check_module
    sys_path.extend(_paths_from_assignment(evaluator, stmt))
  File "/srv/http/jedi/evaluate/sys_path.py", line 95, in _paths_from_assignment
    for val in get_iterator_types(evaluator.eval_statement(expr_stmt)):
  File "/srv/http/jedi/evaluate/iterable.py", line 407, in get_iterator_types
    result += it.values()
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/iterable.py", line 236, in values
    result = unite(self._evaluator.eval_element(v) for v in self._values())
  File "/srv/http/jedi/evaluate/iterable.py", line 38, in unite
    return list(chain.from_iterable(iterable))
  File "/srv/http/jedi/evaluate/iterable.py", line 236, in <genexpr>
    result = unite(self._evaluator.eval_element(v) for v in self._values())
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/srv/http/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/srv/http/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/srv/http/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/srv/http/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/srv/http/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/srv/http/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/srv/http/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/srv/http/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/srv/http/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/srv/http/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 276, in _name_to_types
    types += _eval_param(evaluator, typ, scope)
  File "/srv/http/jedi/evaluate/finder.py", line 367, in _eval_param
    res_new += dynamic.search_params(evaluator, param)
  File "/srv/http/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/dynamic.py", line 63, in search_params
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/srv/http/jedi/evaluate/dynamic.py", line 63, in <genexpr>
    result = list(chain.from_iterable(n.parent.eval(evaluator) for n in names))
  File "/srv/http/jedi/evaluate/param.py", line 174, in eval
    types += evaluator.eval_element(v)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/srv/http/jedi/evaluate/__init__.py", line 267, in eval_trailer
    new_types += get(self, node)
  File "/srv/http/jedi/evaluate/representation.py", line 212, in get_index_types
    return self._evaluator.execute(method, [iterable.AlreadyEvaluated(indexes)])
  File "/srv/http/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/srv/http/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/srv/http/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/srv/http/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/srv/http/jedi/evaluate/__init__.py", line 267, in eval_trailer
    new_types += get(self, node)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/iterable.py", line 229, in get_index_types
    types += self.get_exact_index_types(index.obj)
  File "/srv/http/jedi/evaluate/iterable.py", line 255, in get_exact_index_types
    return self._evaluator.eval_element(self._items()[mixed_index])
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/srv/http/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/srv/http/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/srv/http/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/srv/http/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/srv/http/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/srv/http/jedi/evaluate/iterable.py", line 577, in iter_content
    items += _check_array_additions(self._evaluator, self.instance, module, is_list)
  File "/srv/http/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/srv/http/jedi/evaluate/iterable.py", line 483, in _check_array_additions
    comp_arr_parent = get_execution_parent(compare_array)
  File "/srv/http/jedi/evaluate/iterable.py", line 477, in get_execution_parent
    return node.get_parent_until(er.FunctionExecution)
AttributeError: 'NoneType' object has no attribute 'get_parent_until'
```

**Comment by needle-wang** [comment]
this bug disapears.
i think it can be closed.
