### ISSUE TITLE
AttributeError thrown when native _decimal module is not available

### ISSUE THREAD

**Issue by bradst** [davidhalter/jedi#716]
When importing the `decimal` module, Jedi throws an AttributeError if the native `_decimal` module is not available, instead of falling back to `_pydecimal` by following the ImportError except clause. The native module is only available if the external `mpdecimal` library is installed. I came across this when my auto-completer started throwing exceptions everywhere while editing a file that contained `from decimal import Decimal` at the top. :smile:

This is an example of what happens when the native module is not available:
```python
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.Script(source='from decimal import ').completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 150, in get_completions
    completion_names = i.completion_names(self._evaluator, only_modules)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 414, in completion_names
    for names_dict in scope.names_dicts(search_global=False):
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 720, in names_dicts
    yield star_module.names_dict
AttributeError: 'NoneType' object has no attribute 'names_dict'
>>> import _decimal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libmpdec.so.2: cannot open shared object file: No such file or directory
>>> import _pydecimal
>>>
```
With `mpdecimal` installed, everything works as expected. However, it's an optional dependency for `python` in Arch Linux, so this may affect a good amount of people.

**Comment by davidhalter** [comment]
Does it happen in the linter branch as well?

**Comment by bradst** [comment]
Yes, the same thing happens in the linter branch.

```python
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.Script(source='from decimal import ').completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brad/build/python-jedi-git/jedi/jedi/api/__init__.py", line 213, in completions
    completion_names = get_completions(user_stmt, self._evaluator.BUILTINS)
  File "/home/brad/build/python-jedi-git/jedi/jedi/api/__init__.py", line 172, in get_completions
    completion_names = i.completion_names(self._evaluator, only_modules)
  File "/home/brad/build/python-jedi-git/jedi/jedi/evaluate/imports.py", line 414, in completion_names
    for names_dict in scope.names_dicts(search_global=False):
  File "/home/brad/build/python-jedi-git/jedi/jedi/evaluate/representation.py", line 788, in names_dicts
    yield star_module.names_dict
AttributeError: 'NoneType' object has no attribute 'names_dict'
```

**Comment by davidhalter** [comment]
I have just tested this on the latest dev branch, I cannot reproduce it? Could you try again?

**Comment by bradst** [comment]
Same result with latest HEAD on dev branch:
```
~/build/python-jedi-git/jedi $ git branch
* dev
  linter
  master

~/build/python-jedi-git/jedi $ git rev-parse HEAD 
67ea9ab9f3a6b1f293da2ad13f03daa1e5cbde47

~/build/python-jedi-git/jedi $ python
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi
<module 'jedi' from '/home/brad/build/python-jedi-git/jedi/jedi/__init__.py'>
>>> jedi.Script(source='from decimal import ').completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brad/build/python-jedi-git/jedi/jedi/api/__init__.py", line 167, in completions
    completions = completion.completions()
  File "/home/brad/build/python-jedi-git/jedi/jedi/api/completion.py", line 89, in completions
    completion_names = self._get_context_completions()
  File "/home/brad/build/python-jedi-git/jedi/jedi/api/completion.py", line 152, in _get_context_completions
    only_modules
  File "/home/brad/build/python-jedi-git/jedi/jedi/api/completion.py", line 228, in _get_importer_names
    return i.completion_names(self._evaluator, only_modules=only_modules)
  File "/home/brad/build/python-jedi-git/jedi/jedi/evaluate/imports.py", line 414, in completion_names
    for names_dict in scope.names_dicts(search_global=False):
  File "/home/brad/build/python-jedi-git/jedi/jedi/evaluate/representation.py", line 799, in names_dicts
    yield star_module.names_dict
AttributeError: 'NoneType' object has no attribute 'names_dict'
>>> import _decimal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libmpdec.so.2: cannot open shared object file: No such file or directory
>>> import _pydecimal
>>> import decimal
>>> 
```

**Comment by davidhalter** [comment]
I think this is fixed (dev branch). You may try again!

**Comment by bradst** [comment]
Confirmed on my end. Thanks for the fix!
