### ISSUE TITLE
Crash with PySide object instance autocompletion

### ISSUE THREAD

**Issue by zwadar** [davidhalter/jedi#720]
Hi,
this small python script
[jedi_debug.txt](https://github.com/davidhalter/jedi/files/231998/jedi_debug.txt)
causes crash and produces following callstack
[jedi_callstack.txt](https://github.com/davidhalter/jedi/files/232002/jedi_callstack.txt)

**Comment by davidhalter** [comment]
```
import jedi

code = """from PySide import QtGui

class Foo(QtGui.QDialog):
    pass

bar = Foo()
bar."""


script = jedi.Script(code, 7, 4, None, "utf-8")
completions = script.completions()
```

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1\helpers\pydev\pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1\helpers\pydev\pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "J:/TechArt_WS/Tools/dev/python/lib/jedi_debug.py", line 13, in <module>
    completions = script.completions()
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\api\__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\api\__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\api\__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\api\__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\__init__.py", line 299, in execute
    types = func(self, arguments)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\representation.py", line 443, in py__call__
    return [Instance(evaluator, self, params)]
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\representation.py", line 93, in __init__
    method = self.get_subscope_by_name('__init__')
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\representation.py", line 168, in get_subscope_by_name
    sub = self.base.get_subscope_by_name(name)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\representation.py", line 466, in get_subscope_by_name
    for s in self.py__mro__(self._evaluator):
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\representation.py", line 429, in py__mro__
    for cls_new in mro_method(evaluator):
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\compiled\__init__.py", line 68, in py__mro__
    return tuple(create(evaluator, cls, self.parent) for cls in self.obj.__mro__)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\compiled\__init__.py", line 68, in <genexpr>
    return tuple(create(evaluator, cls, self.parent) for cls in self.obj.__mro__)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\compiled\__init__.py", line 505, in wrapper
    result = func(evaluator, obj, parent, module)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\compiled\__init__.py", line 520, in create
    faked = fake.get_faked(module and module.obj, obj)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\compiled\fake.py", line 102, in get_faked
    result = _faked(module, obj, name)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\compiled\fake.py", line 73, in _faked
    module = get_module(obj)
  File "J:\TechArt_WS\Tools\dev\python\packages\common\jedi\evaluate\compiled\fake.py", line 67, in get_module
    return __import__(imp_plz)
ImportError: No module named Shiboken
```

**Comment by davidhalter** [comment]
Does this happen with Jedi's linter branch as well?

**Comment by zwadar** [comment]
It seems it is not crashing there
