### ISSUE TITLE
type hints not working in Python 3.5

### ISSUE THREAD

**Issue by DonJayamanne** [davidhalter/jedi#742]
The following code returns no completions under Python 3.5, but works in Python 2.7.
It feels like I am doing something wrong, as it works in 2.7 and not in 3.5!

```python
import jedi
source = '''
def testing(wow: int) -> str:
    wow.
'''
script = jedi.Script(source, 3, len('    wow.'), 'example.py')
completions = script.completions()
completions
```

Under python 3.5.1 the result for completions is empty.
```
value for completions = []
```
Details of Python 3.5.1:
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

Details of Python 2.7:
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin

**Comment by davidhalter** [comment]
Jedi version?

**Comment by DonJayamanne** [comment]
Oops. version 0.9.0

**Comment by DonJayamanne** [comment]
Will try, I remember trying it earlier today and it used to crash on Python 2.7.
Will give it another go.

**Comment by DonJayamanne** [comment]
Yes, falls over in Python 2.7, will try 3.5 next:
Here's the trace for 2.7:

```python
>>> completions = script.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jedi/api/__init__.py", line 167, in completions
    completions = completion.completions()
  File "jedi/api/completion.py", line 89, in completions
    completion_names = self._get_context_completions()
  File "jedi/api/completion.py", line 161, in _get_context_completions
    completion_names += self._trailer_completions(atom_expr)
  File "jedi/api/completion.py", line 197, in _trailer_completions
    scopes = self._evaluator.eval_element(atom_expr)
  File "jedi/evaluate/__init__.py", line 262, in eval_element
    return self._eval_element_if_evaluated(element)
  File "jedi/evaluate/__init__.py", line 275, in _eval_element_if_evaluated
    return self._eval_element_cached(element)
  File "jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "jedi/evaluate/__init__.py", line 279, in _eval_element_cached
    return self._eval_element_not_cached(element)
  File "jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "jedi/evaluate/__init__.py", line 286, in _eval_element_not_cached
    types = self._eval_atom(element)
  File "jedi/evaluate/__init__.py", line 357, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "jedi/evaluate/__init__.py", line 142, in find_types
    return f.find(scopes, search_global)
  File "jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "jedi/evaluate/finder.py", line 97, in find
    types = self._names_to_types(names, search_global)
  File "jedi/evaluate/finder.py", line 286, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "jedi/evaluate/finder.py", line 332, in _name_to_types
    types = _eval_param(evaluator, typ, scope)
  File "jedi/evaluate/finder.py", line 427, in _eval_param
    res_new |= dynamic.search_params(evaluator, param)
  File "jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "jedi/evaluate/dynamic.py", line 60, in search_params
    names = [n for n in search_function_call(evaluator, func)
  File "jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "jedi/evaluate/dynamic.py", line 138, in search_function_call
    for mod in imports.get_modules_containing_name(evaluator, [current_module], func_name):
  File "jedi/evaluate/imports.py", line 501, in get_modules_containing_name
    for entry in os.listdir(d):
OSError: [Errno 2] No such file or directory: ''
```

**Comment by DonJayamanne** [comment]
works in Python 3.5

**Comment by DonJayamanne** [comment]
@davidhalter, I'm assuming resolving this issue could take a while. 
In the meantime, can i use the master branch just for Python 3.x and the official 0.9 release for other versions (2.x)?

**Comment by davidhalter** [comment]
You can do whatever you want :P Seriously what is the question?

**Comment by DonJayamanne** [comment]
Is the  master branch stable for use in python 3?

**Comment by davidhalter** [comment]
Well, what does stable really means. All the tests are running, yes (and there are a lot of them). But usually I don't run `sith.py` a lot on it and when I haven't done that, there might be issues.

Apart from that: If the master branch is stable for Python 3, it's also stable for Python 2.

**Comment by DonJayamanne** [comment]
Thanks for the response

**Comment by davidhalter** [comment]
It works for me now in the latest dev branch. Can you retry?

**Comment by DonJayamanne** [comment]
Nope still no good, same error (as mentioned earlier) under Python 2.7.
However it does work under Python 3.5
```
func_name):
  File "jedi/evaluate/imports.py", line 501, in get_modules_containing_name
    for entry in os.listdir(d):
OSError: [Errno 2] No such file or directory: ''
```

**Comment by davidhalter** [comment]
You don't seem to have the same line numbers as me, which makes me suspect you're not on the dev branch. Please pull again.

**Comment by DonJayamanne** [comment]
Oh boy, Yes this works in the dev branch under both versions of python, sorry for the confusion.
