### ISSUE TITLE
ValueError: Node(...) is not in list

### ISSUE THREAD

**Issue by micbou** [davidhalter/jedi#765]
Running the following script (the two completion lines are not a mistake):

``` python
import jedi

args = (
  '''import os
print( "{0}".format( os.
''',
  2,
  len('print( "{0}".format( os.'),
  'example.py'
)

jedi.Script(*args).completions()
jedi.Script(*args).completions()
```

results in this traceback:

```
Traceback (most recent call last):
  File "completions.py", line 17, in <module>
    jedi.Script(*args).completions()
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\api\__init__.py", line 169, in completions
    completions = completion.completions()
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\api\completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\api\completion.py", line 118, in _get_context_completions
    grammar, self._code_lines, self._module, self._position
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\api\helpers.py", line 140, in get_stack_at_position
    code = _get_code_for_stack(code_lines, module, pos)
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\api\helpers.py", line 81, in _get_code_for_stack
    leaf = module.get_leaf_for_position(position, include_prefixes=True)
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\parser\tree.py", line 551, in get_leaf_for_position
    return c.get_leaf_for_position(position, include_prefixes)
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\parser\tree.py", line 545, in get_leaf_for_position
    start_pos = c.get_start_pos_of_prefix()
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\parser\tree.py", line 299, in get_start_pos_of_prefix
    previous_leaf = previous_leaf.get_previous_leaf()
  File "C:\Users\micbou\tests\ycm-issue-2298\jedi\jedi\parser\tree.py", line 238, in get_previous_leaf
    i = c.index(node)
ValueError: Node(power, [<String: '"{0}"'>, Node(trailer, [<Operator: .>, <Name: format@2,13>])]) is not in list
```

Note that it does not happen when only one completion is done. However, all subsequent completions will raise the above exception.

Configuration:
- Windows 7 64-bit
- Jedi https://github.com/davidhalter/jedi/commit/be2a97cd36ce1b7d6f587ef122efc3433b1e8ae2
- Python 3.5.1

**Comment by micbou** [comment]
@davidhalter This issue does not occur with the dev branch so you may want to close the issue.

**Comment by davidhalter** [comment]
Yes, thanks for debugging  :)
