### ISSUE TITLE
RuntimeError when autocompleting Flask-SQLAlchemy queries

### ISSUE THREAD

**Issue by jpvanhal** [davidhalter/jedi#785]
We're using ptpython with Flask-Konch and noticed that the autocompletion crashes whenever ptpython tries to autocomplete Flask-SQLAlchemy queries. 

Below is the minimal code to reproduce the issue in ptpython shell:

``` python
>>> from flask import Flask
>>> from flask_sqlalchemy import SQLAlchemy
>>>
>>> app = Flask(__name__)
>>> db = SQLAlchemy()
>>> db.init_app(app)
>>>
>>> class User(db.Model):
...     __tablename__ = 'users'
...      id = db.Column(db.Integer, primary_key=True)
...      email = db.Column(db.Text)

>>> User.query.filter_by(eException in thread Thread-168:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 836, in run [F2] Menu - CPython 2.7.12
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/api/__init__.py", line 192, in completions
    for call_sig in self.call_signatures():
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 257, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 160, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 263, in __getitem__
    getattr(self._compiled_obj.obj, name)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 500, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 153, in __init__
    self.app = app = db.get_app()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
```

Is this a something that Jedi should be handling?

**Comment by davidhalter** [comment]
Ok. This sucks ass. I'm not sure why this error gets through.. At the moment we're catching `Exception` after the `getattr`. `RuntimeError` is a subclass of `Exception`.

Maybe you're just not using the master branch? Can you try on that?

**Comment by jpvanhal** [comment]
I tried master branch, but I'm not sure if it fixed this issue, because I'm now getting an `IndexError`:

```python
>>> from flask import Flask
... from flask_sqlalchemy import SQLAlchemy
... app = Flask(__name__)
... db = SQLAlchemy()
... db.init_app(app)
...
... class User(db.Model):
...     __tablename__ = 'users'
...     id = db.Column(db.Integer, primary_key=True)
...     email = db.Column(db.Text)

>>> UException in thread Thread-25:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 836, in run                                                   [F2] Menu - CPython 2.7.12
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/api/__init__.py", line 169, in completions
    completions = completion.completions()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/api/completion.py", line 95, in completions
    return sorted(completions, key=lambda x: (x.name.startswith('__'),
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/api/completion.py", line 38, in filter_names
    if isinstance(name.parent, (tree.Function, tree.Class)):
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/parser/utils.py", line 40, in wrapper
    result = func(self)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/evaluate/compiled/mixed.py", line 69, in parent
    return create(self._evaluator, getattr(self._compiled_obj.obj, self.name))
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/evaluate/compiled/__init__.py", line 516, in wrapper
    result = func(evaluator, obj)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/evaluate/compiled/mixed.py", line 154, in create
    name = find_syntax_node_name(evaluator, obj)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/src/jedi/jedi/evaluate/compiled/mixed.py", line 149, in find_syntax_node_name
    return names[-1]
IndexError: list index out of range
```

**Comment by bmbove** [comment]
chiming in because I'm having the originally reported error, using jedi==0.9.0 (along with ptpython==0.36). I haven't looked at how jedi is set up, but it looks like the thread doing the autocompletion doesn't have access to the Flask application context:

```
$ ./manage.py shell
>>> from shop.orders.models import Order

>>> o = Order.query.filter_by(uException in thread Thread-455:
Traceback (most recent call last):                                                                                                                                                                          
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/cache.py", line 158, in wrapper                                                                                 
    return dct[key]                                                                                                                                                                                         
KeyError: (('query',), frozenset())                                                                                                                                                                         
                                                                                                                                                                                                            
During handling of the above exception, another exception occurred:                                                                                                                                         
                                                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                          
  File "~/projects/shop/api/env/lib/python3.5/site-packages/sqlalchemy/util/_collections.py", line 988, in __call__                                                              
    return self.registry[key]
KeyError: 139778451445504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 840, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "~/projects/shop/api/env/lib/python3.5/site-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/api/__init__.py", line 192, in completions
    for call_sig in self.call_signatures():
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/common.py", line 90, in scale_speed_settings
    yield
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)ry [F6] Paste mode                                                                                                                                             [F2] Menu - CPython 3.5.2 
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 257, in eval_trailer
    new_types += self.find_types(typ, node)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/cache.py", line 160, in wrapper
    result = method(self, *args, **kwargs)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/jedi/evaluate/compiled/__init__.py", line 263, in __getitem__
    getattr(self._compiled_obj.obj, name)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 500, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "~/projects/shop/api/env/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "~/projects/shop/api/env/lib/python3.5/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "~/projects/shop/api/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "~/projects/shop/api/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 153, in __init__
    self.app = app = db.get_app()
  File "~/projects/shop/api/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 922, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context

```

I don't have the time at the moment, but someday I might get around to taking a deeper look at this, so I figured I'd post. If someone else starts digging, let me know if you need anymore info.

**Comment by davidhalter** [comment]
Can you rechek in the current master? I've reduced code executions by a lot for ipython users.

**Comment by jpvanhal** [comment]
I rechecked with jedi==0.11.0 and ptpython==0.41. It seems to work now, thanks!
