### ISSUE TITLE
KeyError exception in parser.clear_names

### ISSUE THREAD

**Issue by linnik** [davidhalter/jedi#795]
Hi. I encountered an error while using "go to definition" from anaconda-mode package with latest (0.9.0) jedi in emacs prelude.
This code triggers exception
```python

async def d():
    return map(lambda e: e['_id'], await smth)

```
and this one is not
```python
async def d():
    result = await smth
    return map(lambda e: e['_id'], result)

```
Exception
```python

Traceback (most recent call last):
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/service_factory-0.1.2-py3.5.egg/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/anaconda_mode-0.1.2-py3.5.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/anaconda_mode-0.1.2-py3.5.egg/anaconda_mode.py", line 51, in wrapper
    for definition in f(script)]
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/anaconda_mode-0.1.2-py3.5.egg/anaconda_mode.py", line 69, in goto_definitions
    return script.goto_definitions()
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/api/__init__.py", line 362, in goto_definitions
    definitions = set(self._prepare_goto(goto_path))
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/imports.py", line 347, in _do_import
    module = _load_module(self._evaluator, module_path, source, sys_path)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/imports.py", line 450, in _load_module
    module = load(source) if cached is None else cached.module
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/evaluate/imports.py", line 445, in load
    p = fast.FastParser(evaluator.grammar, common.source_to_unicode(source), p)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/fast.py", line 106, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/fast.py", line 243, in __init__
    self.update(source)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/jedi-0.9.0-py3.5.egg/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: 'e'

```

**Comment by davidhalter** [comment]
The scope_names_stack has been removed on latest dev I think. I'm closing. You're happy to try out there, again.
