### ISSUE TITLE
AttributeError exception in jedi 0.10 when using await keyword

### ISSUE THREAD

**Issue by linnik** [davidhalter/jedi#797]
jedi from dev branch (jedi-0.10.0-py3.5.egg-info),
installed today with `pip install git+git://github.com/davidhalter/jedi.git@dev`

module1.py 
```python
from module2 import TestClass

async def test():
    await TestClass.check()  # exception on goto-definition to 'check' method
    # TestClass.check()  # no exception without await 

```
module2.py
```python
class TestClass:

    @classmethod
    async def check(cls):
        print('check')

````

```python

Traceback (most recent call last):
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/service_factory-0.1.2-py3.5.egg/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/anaconda_mode-0.1.2-py3.5.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/anaconda_mode-0.1.2-py3.5.egg/anaconda_mode.py", line 51, in wrapper
    for definition in f(script)]
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.2/anaconda_mode-0.1.2-py3.5.egg/anaconda_mode.py", line 69, in goto_definitions
    return script.goto_definitions()
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/api/__init__.py", line 190, in goto_definitions
    definitions = helpers.evaluate_goto_definition(self._evaluator, leaf)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/api/helpers.py", line 211, in evaluate_goto_definition
    return evaluator.goto_definitions(leaf)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 461, in goto_definitions
    return self.eval_element(call)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 263, in eval_element
    return self._eval_element_if_evaluated(element)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 276, in _eval_element_if_evaluated
    return self._eval_element_cached(element)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 280, in _eval_element_cached
    return self._eval_element_not_cached(element)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 300, in _eval_element_not_cached
    types = self._eval_atom(element.children[0])
  File "/Users/slava/.virtualenvs/env/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 362, in _eval_atom
    c = atom.children
AttributeError: 'Keyword' object has no attribute 'children'

```

**Comment by linnik** [comment]
with latest HEAD from dev branch exception now is:
```
Traceback (most recent call last):
  File "/Users/slava/.virtualenvs/env/lib/python3.6/site-packages/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/anaconda_mode-0.1.6-py2.7.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/anaconda_mode-0.1.6-py2.7.egg/anaconda_mode.py", line 51, in wrapper
    for definition in f(script)]
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/anaconda_mode-0.1.6-py2.7.egg/anaconda_mode.py", line 69, in goto_definitions
    return script.goto_definitions()
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/jedi/api/__init__.py", line 198, in goto_definitions
    definitions = helpers.evaluate_goto_definition(self._evaluator, context, leaf)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/jedi/api/helpers.py", line 199, in evaluate_goto_definition
    return evaluator.goto_definitions(context, leaf)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/jedi/evaluate/__init__.py", line 448, in goto_definitions
    return helpers.evaluate_call_of_leaf(context, name)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/jedi/evaluate/helpers.py", line 104, in evaluate_call_of_leaf
    values = context.eval_trailer(values, trailer)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/jedi/_compatibility.py", line 182, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/jedi/evaluate/context.py", line 48, in eval_trailer
    return self.evaluator.eval_trailer(self, types, trailer)
  File "/Users/slava/.emacs.d/anaconda-mode/0.1.6/jedi/evaluate/__init__.py", line 382, in eval_trailer
    trailer_op, node = trailer.children[:2]
AttributeError: 'Name' object has no attribute 'children'
```

**Comment by davidhalter** [comment]
await/async is something we have simply not implemented, yet.

**Comment by davidhalter** [comment]
At least it doesn't raise an error anymore (dev branch).
