### ISSUE TITLE
KeyError for multiline strings using goto_definitions 

### ISSUE THREAD

**Issue by renfredxh** [davidhalter/jedi#803]
Running into an issue with multi-line strings when using the `goto_definition` API call. This looks similar to #681 but wasn't sure if it was exactly the same.

Reproduction steps:
```
>>> import jedi
>>> src = """words = (
...   "Hello"
...   "Big"
...   "String"
... )
...
... print(words)
... """
>>> script = jedi.api.Script(source=src, line=7, column=8)
>>> script.goto_definitions()
Traceback (most recent call last):
  File "<ipython-input-6-62143defa296>", line 1, in <module>
    script.goto_definitions()
  File "/usr/local/lib/python3.5/site-packages/jedi/api/__init__.py", line 362, in goto_definitions
    definitions = set(self._prepare_goto(goto_path))
  File "/usr/local/lib/python3.5/site-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/local/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 239, in _eval_atom
    return self.eval_element(c[1])
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 247, in _eval_atom
    return [iterable.Array(self, atom)]
  File "/usr/local/lib/python3.5/site-packages/jedi/evaluate/iterable.py", line 198, in __init__
    self.type = Array.mapping[atom.children[0]]
KeyError: <String: "Hello">
```

**Comment by davidhalter** [comment]
Some on Jedi master? I think it was fixed along the lines.
