### ISSUE TITLE
Memory error when importing large custom libraries

### ISSUE THREAD

**Issue by yRefl3x** [davidhalter/jedi#804]
Python version: 2.7.5
wxPython version: 2.9.4.0
PC: Windows 7, Intel Core i5-3320M, 8GB RAM
VSCode version: 1.7.1
pythonVSCode version: 0.5.1

Noticed that issue with wxPython. Intellisense is stuck at loading. I have checked if the paths are correct, all custom libraries are located in "Lib/site-packages/". All core libraries work flawlessly.

I also observed that when I "start" intellisense, the python instance that is started rapidly goes up to about 2GB of memory used before the memory error is thrown.

![intellisensebug](https://cloud.githubusercontent.com/assets/15350550/20175796/dbcbe99a-a744-11e6-96db-e73b6a5329be.png)

## Output from console window

```
extensionHost.ts:255 [Extension Host] ---------------------------I.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255 [Extension Host] stderr jediProxyI.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 404, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 395, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 175, in _serialize_completions
    completions = script.completions()
  File "preview\jedi\jedi\api\__init__.py", line 169, in completions
    completions = completion.completions()
  File "preview\jedi\jedi\api\completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview\jedi\jedi\api\completion.py", line 164, in _get_context_completions
    completion_names += self._trailer_completions(atom_expr)
  File "preview\jedi\jedi\api\completion.py", line 206, in _trailer_completions
    for names_dict in s.names_dicts(search_global=False):
  File "preview\jedi\jedi\evaluate\representation.py", line 824, in names_dicts
    for star_module in self.star_imports():
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\representation.py", line 840, in star_imports
    new = imports.ImportWrapper(self._evaluator, name).follow()
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\imports.py", line 89, in follow
    types = importer.follow()
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\imports.py", line 246, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "preview\jedi\jedi\evaluate\imports.py", line 336, in _do_import
    source = module_file.read()
MemoryError
```

**Comment by davidhalter** [comment]
Since you're using wx, this is definitely connected to https://github.com/davidhalter/jedi/issues/805.

I'm closing in favor of the other thread. I think that a MemoryError is definitely not what Jedi should catch, however Jedi should try it's best to not let the user run into such an error.
