### ISSUE TITLE
Minimal crashing of jedi parsing using Script/Interpreter

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#831]
Hi there, I'm re-working on integrating Jedi into IPython. 
Works great for now, I get both Jedi and IPython completion to cohabit nicely.

I did though managed to make Jedi fail to parse an input: 

` jedi.api.Script('"foo".capitalise().',line=1,column=19).completions()`

I try to have a look, but tired for now.

Here is the full session in case it has extra informations.

```
~/dev/jedi master $ git show HEAD
commit f05c0714c701ab784bd344aa063acd216fb45ec0
Merge: 2ba78ab7 65371ca5
Author: Dave Halter <davidhalter88@gmail.com>
Date:   Mon Jan 2 12:13:56 2017 +0100

    Merge pull request #823 from fsouza/grammar-3.6

    parser: add grammar3.6

 ~/dev/jedi master $ python
Python 3.5.2 | packaged by conda-forge | (default, Jul 26 2016, 01:37:38)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.api.Script('"foo".capitalise().',line=1,column=19).completions()
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/dev/jedi/jedi/api/__init__.py", line 169, in completions
    completions = completion.completions()
  File "~/dev/jedi/jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "~/dev/jedi/jedi/api/completion.py", line 170, in _get_context_completions
    call_signatures = self._call_signatures_method()
  File "~/dev/jedi/jedi/api/__init__.py", line 297, in call_signatures
    helpers.get_call_signature_details(self._get_module(), self._pos)
  File "~/dev/jedi/jedi/api/helpers.py", line 268, in get_call_signature_details
    leaf = module.get_leaf_for_position(position, include_prefixes=True)
  File "~/dev/jedi/jedi/parser/tree.py", line 545, in get_leaf_for_position
    start_pos = c.get_start_pos_of_prefix()
  File "~/dev/jedi/jedi/parser/tree.py", line 516, in get_start_pos_of_prefix
    return self.children[0].get_start_pos_of_prefix()
  File "~/dev/jedi/jedi/parser/tree.py", line 299, in get_start_pos_of_prefix
    previous_leaf = previous_leaf.get_previous_leaf()
  File "~/dev/jedi/jedi/parser/tree.py", line 238, in get_previous_leaf
    i = c.index(node)
ValueError: Node(power, [<String: '"foo"'>, Node(trailer, [<Operator: .>, <Name: capitalise@1,6>]), Node(trailer, [<Operator: (>, <Operator: )>])]) is not in list
```

**Comment by Carreau** [comment]
I'm stupid, and I should not code when I'm too tired. 

I forgot that `master` is stable and that I should try the `dev` branch, which is working fine. Thanks.
