### ISSUE TITLE
Crash if complete get_item on None-like with Interpreter (dev branch only)

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#836]
Here is a minimal crashing example: `a['`with `a=None` in the namespace.

```
jedi.Interpreter("a['",[{'a':None}], line=1, column=3).completions()
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/bussonniermatthias/dev/jedi/jedi/cache.py in wrapper(self, *args, **kwargs)
     86         try:
---> 87             return dct[key]
     88         except KeyError:

KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
<ipython-input-8-5d1090540ed3> in <module>()
----> 1 jedi.Interpreter("a['",[{'a':None}], line=1, column=3).completions()

/Users/bussonniermatthias/dev/jedi/jedi/api/__init__.py in completions(self)
    169         debug.speed('completions start')
    170         completion = Completion(
--> 171             self._evaluator, self._get_module(), self._code_lines,
    172             self._pos, self.call_signatures
    173         )

/Users/bussonniermatthias/dev/jedi/jedi/api/__init__.py in _get_module(self)
    394
    395     def _get_module(self):
--> 396         parser_module = super(Interpreter, self)._get_module_node()
    397         return interpreter.MixedModuleContext(
    398             self._evaluator,

/Users/bussonniermatthias/dev/jedi/jedi/cache.py in wrapper(self, *args, **kwargs)
     87             return dct[key]
     88         except KeyError:
---> 89             result = method(self, *args, **kwargs)
     90             dct[key] = result
     91             return result

/Users/bussonniermatthias/dev/jedi/jedi/api/__init__.py in _get_module_node(self)
    135     def _get_module_node(self):
    136         cache.invalidate_star_import_cache(self._path)
--> 137         parser = FastParser(self._grammar, self._source, self.path)
    138         save_parser(self.path, parser, pickling=False)
    139

/Users/bussonniermatthias/dev/jedi/jedi/parser/fast.py in __call__(self, grammar, source, module_path)
     29         d = DiffParser(parser)
     30         new_lines = splitlines(source, keepends=True)
---> 31         parser.module = parser._parsed = d.update(new_lines)
     32         return parser
     33

/Users/bussonniermatthias/dev/jedi/jedi/parser/fast.py in update(self, lines_new)
    192         self._old_module = self._new_module
    193
--> 194         assert self._new_module.end_pos[0] == line_length
    195
    196         return self._new_module

AssertionError:
```

**Comment by Carreau** [comment]
(affect only `dev`, not `master`)

**Comment by Carreau** [comment]
Hum, of course heisenbug , now that I'm trying to dig into it, I can't reproduce...

**Comment by Carreau** [comment]
So it's a bit more complicated, it seem that it need some action to happen before.

Is `Interpreter` statefull ?

**Comment by Carreau** [comment]
Ok, I got it I think, on latest dev:

```
 git describe; cat foo.py
fatal: No annotated tags can describe '1caa2ceafa7bc321a79dedc43d671bef8eec5d66'.
However, there were unannotated tags: try --tags.
import jedi
import sys

print(jedi.__file__, sys.version_info)
print('Going once...', end='')
jedi.Interpreter("a['",[{'a':None}, {}], line=1, column=3).completions()
print('ok')
print('Going twice', end='')
jedi.Interpreter("a['",[{'a':None}], line=1, column=3).completions()
print('ok')
print('done')
 ~/dev/jedi origin/dev $ python foo.py
/Users/bussonniermatthias/dev/jedi/jedi/__init__.py sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
Going once...ok
Going twiceTraceback (most recent call last):
  File "/Users/bussonniermatthias/dev/jedi/jedi/cache.py", line 87, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    jedi.Interpreter("a['",[{'a':None}], line=1, column=3).completions()
  File "/Users/bussonniermatthias/dev/jedi/jedi/api/__init__.py", line 171, in completions
    self._evaluator, self._get_module(), self._code_lines,
  File "/Users/bussonniermatthias/dev/jedi/jedi/api/__init__.py", line 396, in _get_module
    parser_module = super(Interpreter, self)._get_module_node()
  File "/Users/bussonniermatthias/dev/jedi/jedi/cache.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/bussonniermatthias/dev/jedi/jedi/api/__init__.py", line 137, in _get_module_node
    parser = FastParser(self._grammar, self._source, self.path)
  File "/Users/bussonniermatthias/dev/jedi/jedi/parser/diff.py", line 33, in __call__
    parser.module = parser._parsed = d.update(new_lines)
  File "/Users/bussonniermatthias/dev/jedi/jedi/parser/diff.py", line 187, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (2 != 1) with the diff parser. Please report:
---
+++
@@ -1,2 +1 @@
-a['
-+a['
```

**Comment by davidhalter** [comment]
Nice!!! Thanks for debugging this. I can really use that help. It's not that easy to find those (and especially reproduce them.

**Comment by Carreau** [comment]
> Nice!!! Thanks for debugging this. I can really use that help. It's not that easy to find those (and especially reproduce them.

No problem. Right now I have an IPython branch that uses jedi  in parallel, and "Complete your code to a bug report" if jedi fails:

![jedi debug](https://cloud.githubusercontent.com/assets/335567/22223221/eae39748-e16e-11e6-8e79-71f2249fa8ba.gif)

Plus it prints the completions that current IPython come with and jedi does not. I'm polishing the branches, and after will fait for the flow of bug report. 

I'll also add integration with the notebook in the following weeks. So we should likely get some more feedback.

**Comment by davidhalter** [comment]
Ok I think I have fixed it. Please let me know if you find others (especially the parser ones, they are really hard to find).

The IPython looks awesome! Let me know if you need more help with that.

**Comment by Carreau** [comment]
Good ! I'll try ! If you want to try the PR it is [here](https://github.com/ipython/ipython/pull/10182) ; A bit complicated still, I'm cleaning up and writing docs.
