### ISSUE TITLE
Crash on `__code__`  completion if trying to access `type`

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#844]
So minimal crashing example:

```
 ~/dev/jedi dfced867 $ cat foo.py
def foo():pass

 ~/dev/jedi dfced867 $ python
Python 3.5.2 | packaged by conda-forge | (default, Jul 26 2016, 01:37:38)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> from foo import foo; import jedi
>>> jedi.Interpreter("foo.__co", [{'foo':foo}], line=1, column=8).completions()[0].type
```

And the attached traceback.

```python
Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/jedi/jedi/parser/utils.py", line 38, in wrapper
    return getattr(self, name)
AttributeError: 'MixedName' object has no attribute '_infer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/jedi/jedi/evaluate/compiled/__init__.py", line 555, in wrapper
    return cache[key][0]
KeyError: (4330899328, 4365163320)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/dev/jedi/jedi/api/classes.py", line 148, in type
    return self._name.api_type
  File "~/dev/jedi/jedi/evaluate/compiled/mixed.py", line 103, in api_type
    return next(iter(self.infer())).api_type
  File "~/dev/jedi/jedi/parser/utils.py", line 40, in wrapper
    result = func(self)
  File "~/dev/jedi/jedi/evaluate/compiled/mixed.py", line 99, in infer
    return [create(self._evaluator, obj, parent_context=self.parent_context)]
  File "~/dev/jedi/jedi/evaluate/compiled/__init__.py", line 558, in wrapper
    result = func(evaluator, obj, parent_context, module, faked)
  File "~/dev/jedi/jedi/evaluate/compiled/mixed.py", line 188, in create
    tree_name = find_syntax_node_name(evaluator, obj)
  File "~/dev/jedi/jedi/evaluate/compiled/mixed.py", line 151, in find_syntax_node_name
    name_str = python_object.__name__
AttributeError: 'code' object has no attribute '__name__'
```

Strangely it does work if `foo` is defined interactively.

**Comment by davidhalter** [comment]
I think returning `None` at that point would be good. 

PS: Did I assign you? I definitely didn't do that intentionally. If so are you going to do this? It's not a big thing, I can do that as well.

**Comment by Carreau** [comment]
> PS: Did I assign you? I definitely didn't do that intentionally. If so are you going to do this? It's not a big thing, I can do that as well.

Hu, I was not even aware you could assign a non-committer. I can try to have a look, but If you know the fix, feel free to do it.
