### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_root_node'

### ISSUE THREAD

**Issue by balta2ar** [davidhalter/jedi#854]
Hello. I came from this issue: https://github.com/tweekmonster/impsort.vim/issues/13#issuecomment-277656500
I'm using adc0878. Here is the stacktrace:

```
[impsort] Traceback (most recent call last):
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/imports.py", line 47, in <module>
[impsort]     get_names(sys.argv[1], source)
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/imports.py", line 35, in get_names
[impsort]     print('%s,%s' % (c.name, c.type))
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/api/classes.py", line 470, in type
[impsort] 
[impsort]     followed = self.follow_definition()
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/evaluate/cache.py", line 41, in wrapper
[impsort]     rv = function(obj, *args, **kwargs)
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/api/classes.py", line 498, in follow_definition
[impsort]     defs = self._follow_statements_imports()
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/evaluate/cache.py", line 41, in wrapper
[impsort]     rv = function(obj, *args, **kwargs)
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/api/classes.py", line 485, in _follow_statements_imports
[impsort]     return i.follow()
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/evaluate/cache.py", line 41, in wrapper
[impsort]     rv = function(obj, *args, **kwargs)
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/evaluate/imports.py", line 103, in follow
[impsort]     for t in types))
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/evaluate/imports.py", line 103, in <genexpr>
[impsort]     for t in types))
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/evaluate/__init__.py", line 117, in find_types
[impsort]     scopes = f.scopes(search_global)
[impsort]   File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/bin/jedi/jedi/evaluate/finder.py", line 109, in scopes
[impsort]     return ((n, None) for n in self.scope.names_dicts(search_global))
[impsort] AttributeError: 'NoneType' object has no attribute 'names_dicts'
[impsort] 
Press ENTER or type command to continue
```

JediDebugInfo
```
#### Jedi-vim debug information
Using Python version: 2
 - sys.version: 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40), [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
 - site module: /home/ybochkarev/miniconda/lib/python2.7/site.pyc
Jedi path: /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/pymode/libs
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein
    - /home/ybochkarev/dev/cs/trunk
    - /home/ybochkarev/miniconda/lib/python27.zip
    - /home/ybochkarev/miniconda/lib/python2.7
    - /home/ybochkarev/miniconda/lib/python2.7/plat-linux2
    - /home/ybochkarev/miniconda/lib/python2.7/lib-tk
    - /home/ybochkarev/miniconda/lib/python2.7/lib-old
    - /home/ybochkarev/miniconda/lib/python2.7/lib-dynload
    - /home/ybochkarev/.local/lib/python2.7/site-packages
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages
    - _vim_path_
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/autoload/../python
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/pymode/libs/astroid/brain
jedi-vim git version: fatal: Not a git repository (or any of the parent directories): .git
jedi git submodule status: fatal: Not a git repository (or any of the parent directories): .git

##### Settings

g:force_py_version = '2' (default: 'auto')
g:popup_select_first = 0 (default: 1)
g:documentation_command = '<leader>jk' (default: 'K')
g:usages_command = '<leader>ju' (default: '<leader>n')
g:completions_command = '' (default: '<C-Space>')
g:popup_on_dot = 0 (default: 1)
g:rename_command = '<leader>jr' (default: '<leader>r')
g:auto_vim_configuration = 0 (default: 1)
g:goto_assignments_command = '<leader>ja' (default: '<leader>g')
g:show_call_signatures_delay = 0 (default: 500)
g:goto_definitions_command = '<leader>jd' (default: '')
g:show_call_signatures = '2' (default: 1)
g:completions_enabled = 0 (default: 1)

  omnifunc=pythoncomplete#Complete
        Last set from ~/rc.arch/bz/.vim/init.vim
  completeopt=longest,menuone
        Last set from ~/rc.arch/bz/.vim/init.vim
```

I can't provide a minimal reproducible code at the moment, unfortunately, but I can try to narrow it down if you tell me how. Could you please take a look, @blueyed @davidhalter?

Thanks!

**Comment by balta2ar** [comment]
While trying to narrow it down, I noticed that "metrics" module is the last one reported in my logs. When I do "GoToDefintion" on its import, I get this:
```
Traceback (most recent call last):
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 234, in goto
    definitions = [x for x in script.goto_definitions()
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/api/__init__.py", line 198, in goto_definitions
    definitions = helpers.evaluate_goto_definition(self._evaluator, context, leaf)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/api/helpers.py", line 200, in evaluate_goto_definition
    return evaluator.goto_definitions(context, leaf)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/__init__.py", line 457, in goto_definitions
    return imports.infer_import(context, name)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/imports.py", line 69, in infer_import
    ) for t in types
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/common.py", line 186, in unite
    return set(typ for types in iterable for typ in types)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/common.py", line 186, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/imports.py", line 69, in <genexpr>
    ) for t in types
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/_compatibility.py", line 185, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/context.py", line 54, in py__getattribute__
    self, name_or_str, name_context, position, search_global, is_goto)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/__init__.py", line 129, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/finder.py", line 55, in find
    names = self.filter_name(filters)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/finder.py", line 113, in filter_name
    for filter in filters:
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/representation.py", line 421, in get_filters
    origin_scope=origin_scope
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/filters.py", line 178, in __init__
    super(ParserTreeFilter, self).__init__(context, node_context.tree_node)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/filters.py", line 145, in __init__
    self._used_names = self._parser_scope.get_root_node().used_names
AttributeError: 'NoneType' object has no attribute 'get_root_node'

Press ENTER or type command to continue
```

**Comment by balta2ar** [comment]
Here is something closer to a minimal code. I took datetime.so from /usr/lib/python2.7/lib-dynload. Tree structure:
```
.
├── sub
│   ├── datetime.so
│   └── __init__.py (empty)
└── test.py

1 directory, 3 files
```

test.py:
``` python
import os
from sub import datetime
```

GoToDefinition displays this:
```
Traceback (most recent call last):
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 234, in goto
    definitions = [x for x in script.goto_definitions()
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/api/__init__.py", line 200, in goto_definitions
    names = [s.name for s in definitions]
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/evaluate/representation.py", line 454, in name
    return ContextName(self, self.tree_node.name)
AttributeError: 'NoneType' object has no attribute 'name'

Press ENTER or type command to continue
```

**Comment by davidhalter** [comment]
Hmm can you recheck if Jedi is really on the latest version? `names_dicts` doesn't exist as a string in the library.

**Comment by blueyed** [comment]
`JediDebugInfo` also said:

> jedi-vim git version: fatal: Not a git repository (or any of the parent directories): .git
jedi git submodule status: fatal: Not a git repository (or any of the parent directories): .git

**Comment by balta2ar** [comment]
> recheck if Jedi is really on the latest version

@davidhalter Yeah, this is kind of pain to do with dein plugin manager because of its unclear internal caching scheme... I've switched to vim-plug and redownloaded all the plugins from scratch. Now impsort displays this stack trace:

```
[impsort] Traceback (most recent call last):
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/imports.py", line 47, in <module>
[impsort]     get_names(sys.argv[1], source)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/imports.py", line 35, in get_names
[impsort]     print('%s,%s' % (c.name, c.type))
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/api/classes.py", line 146, in type
[impsort] 
[impsort]     for context in self._name.infer():
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/filters.py", line 82, in infer
[impsort]     return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 188, in _name_to_types
[impsort]     types = imports.infer_import(context, tree_name)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/cache.py", line 41, in wrapper
[impsort]     rv = function(obj, *args, **kwargs)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/imports.py", line 69, in infer_import
[impsort]     ) for t in types
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/common.py", line 186, in unite
[impsort]     return set(typ for types in iterable for typ in types)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/common.py", line 186, in <genexpr>
[impsort]     return set(typ for types in iterable for typ in types)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/imports.py", line 69, in <genexpr>
[impsort]     ) for t in types
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/_compatibility.py", line 185, in <lambda>
[impsort]     return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/context.py", line 54, in py__getattribute__
[impsort]     self, name_or_str, name_context, position, search_global, is_goto)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 129, in find_types
[impsort]     return f.find(filters, attribute_lookup=not search_global)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/debug.py", line 81, in wrapper
[impsort]     return func(*args, **kwargs)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 55, in find
[impsort]     names = self.filter_name(filters)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 113, in filter_name
[impsort]     for filter in filters:
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/representation.py", line 421, in get_filters
[impsort]     origin_scope=origin_scope
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/filters.py", line 178, in __init__
[impsort]     super(ParserTreeFilter, self).__init__(context, node_context.tree_node)
[impsort]   File "/home/ybochkarev/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi/jedi/evaluate/filters.py", line 145, in __init__
[impsort]     self._used_names = self._parser_scope.get_root_node().used_names
[impsort] AttributeError: 'NoneType' object has no attribute 'get_root_node'
[impsort] 
Press ENTER or type command to continue
```

According to this commit, it should be the latest version of jedi: https://github.com/tweekmonster/impsort.vim/commit/106c910cb8a4bb1064e1637e1de7312a28f0386c

@blueyed Here is `JediDebugInfo` after switching to vim-plug:
```
#### Jedi-vim debug information
Using Python version: 2
 - sys.version: 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40), [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
 - site module: /home/ybochkarev/miniconda/lib/python2.7/site.pyc
Jedi path: /home/ybochkarev/rc.arch/bz/.vim/plugged/jedi-vim/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/ybochkarev/rc.arch/bz/.vim/plugged/python-mode/pymode/libs
    - /home/ybochkarev/rc.arch/bz/.vim/plugged/python-mode
    - /home/ybochkarev/rc.arch/bz/.vim/plugged/jedi-vim
    - /home/ybochkarev/dev/cs/trunk
    - /home/ybochkarev/miniconda/lib/python27.zip
    - /home/ybochkarev/miniconda/lib/python2.7
    - /home/ybochkarev/miniconda/lib/python2.7/plat-linux2
    - /home/ybochkarev/miniconda/lib/python2.7/lib-tk
    - /home/ybochkarev/miniconda/lib/python2.7/lib-old
    - /home/ybochkarev/miniconda/lib/python2.7/lib-dynload
    - /home/ybochkarev/.local/lib/python2.7/site-packages
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages
    - _vim_path_
    - /home/ybochkarev/rc.arch/bz/.vim/plugged/MatchTagAlways/autoload/../python
    - /home/ybochkarev/rc.arch/bz/.vim/plugged/python-mode/pymode/libs/astroid/brain
jedi-vim git version: 0dea756
jedi git submodule status:  70200861661a921016563717487c1ced9993acdb jedi (v0.10.0)

##### Settings
g:force_py_version = '2' (default: 'auto')
g:popup_select_first = 0 (default: 1)
g:documentation_command = '<leader>jk' (default: 'K')
g:usages_command = '<leader>ju' (default: '<leader>n')
g:completions_command = '' (default: '<C-Space>')
g:popup_on_dot = 0 (default: 1)
g:rename_command = '<leader>jr' (default: '<leader>r')
g:auto_vim_configuration = 0 (default: 1)
g:goto_assignments_command = '<leader>ja' (default: '<leader>g')
g:show_call_signatures_delay = 0 (default: 500)
g:goto_definitions_command = '<leader>jd' (default: '')
g:show_call_signatures = '2' (default: 1)
g:completions_enabled = 0 (default: 1)

  omnifunc=pythoncomplete#Complete
        Last set from ~/rc.arch/bz/.vim/init.vim
  completeopt=longest,menuone
        Last set from ~/rc.arch/bz/.vim/init.vim
```

**Comment by davidhalter** [comment]
Could you provide a minimal example? Maybe I have not seen it, but without it it's going to be very hard to debug this.

**Comment by blueyed** [comment]
@davidhalter 
Minimal example: https://github.com/davidhalter/jedi/issues/854#issuecomment-277933693

@balta2ar 
It is better to go to the submodule directly, and update it, i.e. go to `~/rc.arch/bz/.vim/plugged/impsort.vim/bin/jedi`, and `git fetch origin`, then checkout origin/master, and origin/dev  - restarting Vim inbetween.
You can then checkout the pinned version later again: `cd ..; git checkout jedi`.

**Comment by davidhalter** [comment]
@balta2ar Well, I cannot reproduce this. Can you maybe try to write a test as a pull request so it fails on travis and I can then continue debugging this?

**Comment by balta2ar** [comment]
@davidhalter  I went to `~/.vim/plugged/jedi-vim/jedi` and manually checked out to 8bdf7e3, and I can't reproduce it anymore, so I'm closing this issue. Thank you for your hard work!

**Comment by blueyed** [comment]
@balta2ar 
So it's fixed in master then?

**Comment by balta2ar** [comment]
@blueyed Yes.
