### ISSUE TITLE
ERROR runnin tox : invocation failed

### ISSUE THREAD

**Issue by pr13905** [davidhalter/jedi#879]
```
ERROR: invocation failed (exit code 1), logfile: /home/pr13905/.vim/bundle/jedi-vim/.toxg
ERROR: actionid: tox
msg: packaging
cmdargs: ['/home/pr13905/anaconda2/bin/python', local('/home/pr13905/.vim/bundle/jedi-vi]
env: None

Traceback (most recent call last):
File "setup.py", line 13, in
readme = open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read()
IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'

ERROR: FAIL could not package project - v = InvocationError('/home/pr13905/anaconda2/bin)
```

Running `tox -e py27` I get the above error.
I have just tried to install Jedi using the Github repo.
Jedi doesn't seem to work so far.

**Comment by pr13905** [comment]
ERROR: invocation failed (exit code 1), logfile: /home/pr13905/.vim/bundle/jedi-vim/.toxg
ERROR: actionid: tox
msg: packaging
cmdargs: ['/home/pr13905/anaconda2/bin/python', local('/home/pr13905/.vim/bundle/jedi-vi]
env: None

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    readme = open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read()
IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'

ERROR: FAIL could not package project - v = InvocationError('/home/pr13905/anaconda2/bin)

**Comment by pr13905** [comment]
Uninstalled and installed again both anaconda and Jedi - Error does not persist.
