### ISSUE TITLE
Jedi fails on autocomplete in sublime text

### ISSUE THREAD

**Issue by rmerkushin** [davidhalter/jedi#896]
Jedi fails on autocomplete in sublime text for some cases.

Source example:
```python
import os

def x(y):
    print(y)

print(x)
f = open('1.txt', mode='r', encoding='utf-8'). # fail on dot

from datetime import d # fail on module import
```

I've got this error in both cases:
```python
...
  File "/Users/rmerkushin/Library/Application Support/Sublime Text 3/Packages/sublime-jedi/jedi/parser/__init__.py", line 267, in parse
    root_node = super(ParserWithRecovery, self).parse(self._tokenize(tokenizer))
  File "/Users/rmerkushin/Library/Application Support/Sublime Text 3/Packages/sublime-jedi/jedi/parser/__init__.py", line 146, in parse
    self.remove_last_newline()
  File "/Users/rmerkushin/Library/Application Support/Sublime Text 3/Packages/sublime-jedi/jedi/parser/__init__.py", line 227, in remove_last_newline
    assert newline.value.endswith('\n')
AssertionError
```

How to fix this issue?

P.S.: jedi version - 0.10.0, Sublime Text - 3126 (Python 3.3.6)

I'm also tried Jedi 0.9.0, but catching this error:
```python
...
File "/Users/rmerkushin/Library/Application Support/Sublime Text 3/Packages/sublime-jedi/jedi/_compatibility.py", line 40, in find_module_py33
    module_file = open(module_path, 'rb')
NotADirectoryError: [Errno 20] Not a directory: '/Applications/Sublime Text.app/Contents/MacOS/python3.3.zip/datetime.pyo'
```

I'm not sure about error reason, because in independent python interpreter this code example works fine :(

**Comment by davidhalter** [comment]
Can you reproduce it? Or did it happen only once?

**Comment by rmerkushin** [comment]
Yes, it's happens every time and on different OS (Mac OS and Windows 10).

My autocomplete plugin code:

```python
import jedi

import sublime
import sublime_plugin


COMPLITION_FLAGS = sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS


class Autocomplete(sublime_plugin.EventListener):

    def on_query_completions(self, view, prefix, locations):
        line, column = view.rowcol(locations[0])
        source = view.substr(sublime.Region(0, view.size()))
        script = jedi.Script(source, line + 1, column, path=view.file_name() or '')
        completions = [(c.name + '\t' + c.type, c.name) for c in script.completions()]
        return (completions, COMPLITION_FLAGS)
```

**Comment by rmerkushin** [comment]
I'm print self._parsed.children in remove_last_newline method and got this:
```python
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(power, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <ErrorNode: from datetime import@9,0>, <Newline: '\n'>, <EndMarker: >]

[<ErrorNode: PK@1,0>, <ErrorLeaf: errortoken:'\x03', (1, 2))>, <ErrorNode: O@2,0>, <ErrorLeaf: errortoken:'"nX���)��/��q��\n', (2, 1))>, <ErrorLeaf: colon:':', (3, 0))>, <ErrorLeaf: errortoken:'\x0e', (3, 1))>, <ErrorLeaf: errortoken:'\x04', (4, 0))>, <ErrorLeaf: errortoken:'\x01', (5, 0))>, <ErrorLeaf: errortoken:'�', (6, 0))>, <ErrorLeaf: errortoken:'�', (7, 0))>, <ErrorLeaf: errortoken:'�', (8, 0))>, <ErrorLeaf: errortoken:'�', (9, 0))>, <ErrorLeaf: errortoken:'�', (10, 0))>, <ErrorLeaf: errortoken:'�', (11, 0))>, <ErrorLeaf: errortoken:'�', (12, 0))>, <ErrorNode: C/B7Q@13,0>, <ErrorLeaf: errortoken:'�', (13, 5))>, <ErrorLeaf: errortoken:'�', (14, 0))>, <ErrorNode: z@15,0>, <ErrorLeaf: errortoken:'�', (15, 1))>, <ErrorLeaf: semi:';', (16, 0))>, <ErrorLeaf: errortoken:'�', (16, 1))>, <ErrorNode: -@17,0>, <ErrorLeaf: rpar:')', (17, 1))>, <ErrorLeaf: errortoken:'�', (17, 2))>, <ErrorLeaf: errortoken:'\x16', (18, 0))>, <ErrorNode: o@19,0>, <ErrorLeaf: errortoken:'\x05', (19, 1))>, <ErrorNode: "��Y� �D[�6o��U���j3��V�B�D\i�e���q�tO��[o�7'��72��-(������~��������׺��m~�e	8����d`���$��	�!��_��4!��ؑ�b�
```
I think the reason is in the symbol '�'.

**Comment by rmerkushin** [comment]
The "remove_last_window" method is not called if you run the example directly in the python interpreter directly. I don't understand anything... :(

![ ](https://img.fireden.net/vg/image/1435/15/1435158878046.png)

**Comment by davidhalter** [comment]
Haha :D Well thanks for looking into it. My guess is that you have to do it multiple times. In that case the caching is important. I think that the diff parser might screw up something here. So if you want to reproduce it, you might want to just run the same piece of code multiple times.

**Comment by rmerkushin** [comment]
I tried two ways and no one gave the result.

```python
import jedi

source = """
import os

def x(y):
    print(y)

print(x)
f = open('1.txt', mode='r', encoding='utf-8').

from datetime import
"""

script = jedi.Script(source, line=8, column=46)
for x in range(1000):
    a = [(c.name + '\t' + c.type, c.name) for c in script.completions()]

for y in range(1000):
    script = jedi.Script(source, line=8, column=46)
    b = [(c.name + '\t' + c.type, c.name) for c in script.completions()]
```

**Comment by davidhalter** [comment]
Have you tried deleting the cache in `~/.cache/jedi`?

**Comment by rmerkushin** [comment]
I have no ~/.cache/jedi but have ~/Library/Caches/Jedi  I deleted it, but it did not help me.

**Comment by rmerkushin** [comment]
These problems can occur because of multithreading or multiprocessing? I do not think that the on_query_completion method runs in parallel, but who knows? This assumption is from despair :D

**Comment by davidhalter** [comment]
Can you maybe log each time it runs and with which parameters it runs? (and maybe also which version?

Oh and another idea: In your pure Python example you do have a newline at the end. You might not have had one in your code (probably not). This is very important, try removing it.

**Comment by rmerkushin** [comment]
Alright. I created the same conditions for sublime plugin and code in pycharm. I saved code example into file and run test and got this:

sublime text:
```python
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(power, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <EndMarker: >]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[<ErrorNode: PK@1,0>, <ErrorLeaf: errortoken:'\x03', (1, 2))>, <ErrorNode: O@2,0>, <ErrorLeaf: errortoken:'"nX���)��/��q��\n', (2, 1))>, <ErrorLeaf: colon:':', (3, 0))>, <ErrorLeaf: errortoken:'\x0e', (3, 1))>, <ErrorLeaf: errortoken:'\x04', (4, 0))>, <ErrorLeaf: errortoken:'\x01', (5, 0))>, <ErrorLeaf: errortoken:'�', (6, 0))>, <ErrorLeaf: errortoken:'�', (7, 0))>, <ErrorLeaf: errortoken:'�', (8, 0))>, <ErrorLeaf: errortoken:'�', (9, 0))>, <ErrorLeaf: errortoken:'�', (10, 0))>, <ErrorLeaf: errortoken:'�', (11, 0))>, <ErrorLeaf: errortoken:'�', (12, 0))>, <ErrorNode: C/B7Q@13,0>, <ErrorLeaf: errortoken:'�', (13, 5))>, <ErrorLeaf: errortoken:'�', (14, 0))>, <ErrorNode: z@15,0>, <ErrorLeaf: errortoken:'�', (15, 1))>, <ErrorLeaf: semi:';', (16, 0))>, <ErrorLeaf: errortoken:'�', (16, 1))>, <ErrorNode: -@17,0>, <ErrorLeaf: rpar:')', (17, 1))>, <ErrorLeaf: errortoken:'�', (17, 2))>, <ErrorLeaf: errortoken:'\x16', (18, 0))>, <ErrorNode: o@19,0>, <ErrorLeaf: errortoken:'\x05', (19, 1))>, <ErrorNode: "��Y� �D[�6o��U���j3��V�B�D\i�e���q�tO��[o�7'��72��-(������~��������׺��m~�e	8����d`���$��	�!��_��4!��ؑ�b�
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

pycharm:
```python
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(atom_expr, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <EndMarker: >]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by rmerkushin** [comment]
on_query_completions method run once. Parameters passed to Script (source, line, column) are the same and I still do not understand why the remove_last_window method is called twice

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
import os

def x(y):
    print(y)

print(x)
f = open('1.txt', mode='r', encoding='utf-8').
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
line: 7
column: 46
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by davidhalter** [comment]
Sorry now I'm totally confused. There's now suddenly pycharm in there. Did you try removing the new line I suggested in your Jedi example?

Also once you now what you call Jedi with, can you reproduce it with pure Jedi calls?

**Comment by rmerkushin** [comment]
I probably did not put it right (sorry for my bad english).

I created example source file with content:
```python
import os

def x(y):
    print(y)

print(x)
f = open('1.txt', mode='r', encoding='utf-8').
```
I used this example in sublime text (see plugin code above) and with pure Jedi calls (i'm use pycharm for run code):
```python
import jedi

source = open('atcmpl.py', mode='r', encoding='utf-8').read()

script = jedi.Script(source, line=7, column=46)
print([(c.name + '\t' + c.type, c.name) for c in script.completions()])
```

In both cases jedi called with same arguments, but in case 2 without fails. I remove new line as you can see in example. I can't reproduce fail in case 2 with pure Jedi calls.

**Comment by davidhalter** [comment]
Hmm but in your case above if you print a and b you get a result for `b`, but not for `a`. That's at least a starting point?!

**Comment by rmerkushin** [comment]
I did not quite understand you. Do you mean "print self._parsed.children"? If yes, then i just added "print self._parsed.children" in Jedi lib in remove_last_newline method at 206 line:
```python
    def remove_last_newline(self):
        endmarker = self._parsed.children[-1]
        print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
        print(self._parsed.children)
        print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
```
After that i executed autocomplete code with modified Jedi lib as i described in my previous post. In sublime case autocomplete method run once but remove_last_newline in Jedi lib execute twice and i don't understand why it happened :(

**Comment by davidhalter** [comment]
I mean this example: https://github.com/davidhalter/jedi/issues/896#issuecomment-287267055

Remove the newline.

**Comment by rmerkushin** [comment]
Ok, I removed last new lines and did the following:

debug.py (executed with pure jedi calls):

```python
import jedi

source = open('atcmpl.py', mode='r', encoding='utf-8').read()

script = jedi.Script(source, line=7, column=46)
for x in range(100):
    a = [(c.name + '\t' + c.type, c.name) for c in script.completions()]

print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')

for y in range(100):
    script = jedi.Script(source, line=7, column=46)
    b = [(c.name + '\t' + c.type, c.name) for c in script.completions()]
```

atcmpl.py content (no new line after dot, line 7, column 46):

```python
import os

def x(y):
    print(y)

print(x)
f = open('1.txt', mode='r', encoding='utf-8').
```

result:

```python
>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(atom_expr, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <EndMarker: >]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(atom_expr, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <EndMarker: >]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(atom_expr, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <EndMarker: >]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(atom_expr, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <EndMarker: >]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
....
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Node(simple_stmt, [<ImportName: import os@1,0>, <Newline: '\n'>]), <Function: x@3-5>, Node(simple_stmt, [Node(atom_expr, [<Name: print@6,0>, Node(trailer, [<Operator: (>, <Name: x@6,6>, <Operator: )>])]), <Newline: '\n'>]), <ErrorNode: f = open('1.txt', mode='r', encoding='utf-8').@7,0>, <Newline: '\n'>, <EndMarker: >]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

As you can see in the first for loop, print self._parsed.children executed once and in the second for loop it executed 100 times.

I'm on the right way?

Sorry, maybe I'm a bit on the slow side again :-D

**Comment by davidhalter** [comment]
I have no idea if you're on the right way. I suggest again that you start logging when and how you call Jedi. I'm 100% sure this issue is very reproducible if you log correctly.

As soon as you can create a case that triggers a bug with DIRECT Jedi calls, we can talk again. I don't have time to analyze what you're sending me here.

Sorry. I don't have infinite resources.

**Comment by jonathanslenders** [comment]
I get this one as well in ptpython:
```python
>>> Exception in thread Thread-12780:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/prompt_toolkit/interface.py", line 860, in run                                                                           [F2] Menu - CPython 3.7.0
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/jedi/api/completion.py", line 96, in completions
    completion_names = self._get_context_completions()
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/jedi/api/completion.py", line 124, in _get_context_completions
    grammar, self._code_lines, self._module_node, self._position
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/jedi/api/helpers.py", line 139, in get_stack_at_position
    p.parse(tokenizer=tokenize_without_endmarker(code))
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/jedi/parser/__init__.py", line 267, in parse
    root_node = super(ParserWithRecovery, self).parse(self._tokenize(tokenizer))
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/jedi/parser/__init__.py", line 146, in parse
    self.remove_last_newline()
  File "/root/.virtualenvs/ipython/lib/python3.7/site-packages/jedi/parser/__init__.py", line 227, in remove_last_newline
    assert newline.value.endswith('\n')
AssertionError
```
Not sure how to reproduce it right now.

**Comment by davidhalter** [comment]
Please check again with the latest 0.10.2 release!

**Comment by rmerkushin** [comment]
Uhhh... it's really funny. With Jedi 0.10.2 i have no errors in log anymore.... and completion variants too :-D But pure jedi works well

![](http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2014/03/1394332737Go-Deeper-Inception-Movie.jpg)

**Comment by davidhalter** [comment]
I suppose this one is fixed. Let me know if not.
