### ISSUE TITLE
AC exception: 'NoneType' object has no attribute 'argument_node'

### ISSUE THREAD

**Issue by TobiasRzepka** [davidhalter/jedi#969]
Hello David,
I've found another bug. This time, the stack trace is different and (maybe) not possible to squeeze it into a line. I've attached all as files. This time I've tested with 0.10.2 on Windows.
> Traceback (most recent call last):
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\jedi_test_exceptions.py", line 10, in <module>
    jedi.Script(source, 166, 14, "cmd").completions()
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\jedi\api\__init__.py", line 179, in completions
    completions = completion.completions()
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\jedi\api\completion.py", line 96, in completions
    completion_names = self._get_context_completions()
...
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\jedi\evaluate\param.py", line 302, in get_params
    for node in var_args.get_calling_nodes():
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\jedi\evaluate\instance.py", line 425, in get_calling_nodes
    return self._get_var_args().get_calling_nodes()
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\jedi\evaluate\param.py", line 191, in get_calling_nodes
    return [arguments.argument_node or arguments.trailer]
  File "D:\eric6\eric6_plugins\Plugin_Completion_Jedi\CompletionJedi\jedi\evaluate\instance.py", line 428, in __getattr__
    return getattr(self._var_args, name)
AttributeError: 'NoneType' object has no attribute 'argument_node'

If you execute jedi_test_exceptions.py you should get it directly.
Tobias
[stack trace line 166, 14.txt](https://github.com/davidhalter/jedi/files/1392446/stack.trace.line.166.14.txt)
[jedi_test_exceptions.py.txt](https://github.com/davidhalter/jedi/files/1392456/jedi_test_exceptions.py.txt)
[JediCompleter line 166, 14.py.txt](https://github.com/davidhalter/jedi/files/1392457/JediCompleter.line.166.14.py.txt)

**Comment by davidhalter** [comment]
This should have been fixed by @micbou in a recent commit. Please check.
