### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by TobiasRzepka** [davidhalter/jedi#970]
Hello David,
this one is a little special. If you run it on Py 2.7 you got a normal stack trace. But on Py 3.5 you got additionally the "During handling of the above exception, another exception occurred:" message. I know, it doesn't make it easier.
Tobias
[jedi_test_exceptions.py.txt](https://github.com/davidhalter/jedi/files/1392548/jedi_test_exceptions.py.txt)
[JediCompleter.py.txt](https://github.com/davidhalter/jedi/files/1392549/JediCompleter.py.txt)
[stack trace 141, 40, Py35.txt](https://github.com/davidhalter/jedi/files/1392550/stack.trace.141.40.Py35.txt)

**Comment by davidhalter** [comment]
The 3.5 part is just exception chaining of Python 3. That makes it actually easier, because it's easier to see what led to the error. But for people that are not used to them, this might be confusing.

Can you please just paste the files inside ``` quotes? It's easier for me to just work with that instead of downloading them. Especially if we want to gain a quick overview of what's the bug about. Thanks for the report!

**Comment by NiyongaboEric** [comment]
@TobiasRzepka
## #############################Similar Exception ################
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\stochastic_gradient.py", line 157, in _get_penalty_type
    return PENALTY_TYPES[penalty]
KeyError: 'i2'

****During handling of the above exception, another exception occurred**:**

Traceback (most recent call last):
  File "C:\Users\User\Documents\Python Future\Practice\BusinessComputing\dataScience\challengeOneA.py", line 5, in <module>
    clf = SGDClassifier(loss="hinge", penalty="i2")
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\stochastic_gradient.py", line 789, in __init__
    average=average, n_iter=n_iter)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\stochastic_gradient.py", line 357, in __init__
    n_iter=n_iter)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\stochastic_gradient.py", line 74, in __init__
    self._validate_params(set_max_iter=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\stochastic_gradient.py", line 104, in _validate_params
    self._get_penalty_type(self.penalty)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\linear_model\stochastic_gradient.py", line 159, in _get_penalty_type
    raise ValueError("Penalty %s is not supported. " % penalty)
ValueError: Penalty i2 is not supported. 
[Finished in 1.0s]

##############################################
i am learning Scikit-library specically Stochastic Gradient Descent classification. i was able to solve the error by simply modifying "I2" to  **"l2"**
below is run code 

from **sklearn.linear_mode**l import **SGDClassifier**
x = [[0.,0.], [1.,1.]]
y = [0, 1]
clf = **SGDClassifier**(loss="hinge", penalty="**l2**")
clf.fit(x, y)

i hope this will help you

**Comment by davidhalter** [comment]
This one was recently fixed. Please check if I'm right.
