### ISSUE TITLE
Can not load 'pyc' in archive. (Windows embeddable zip file)

### ISSUE THREAD

**Issue by Milly** [davidhalter/jedi#975]
Using python embeddable zip file in Windows.
(from: https://www.python.org/downloads/windows/)
(file: https://www.python.org/ftp/python/3.5.4/python-3.5.4-embed-amd64.zip)

Exception raised in completion.
```python
import os
os.
```

## values
```python
sys.path  # => ['C:\\tools\\python35\\python35.zip']

# File "jedi/_compatibility.py", in find_module_py33
loader.archive  # => 'C:\\tools\\python35\\python35.zip'
loader.get_filename('os')  # => 'C:\\tools\\python35\\python35.zip\\os.pyc'
```

## traceback
```
Traceback (most recent call last):
  File "C:/jedi-vim\pythonx\jedi_vim.py", line 194, in completions
    completions = script.completions()
  File "C:/jedi-vim\pythonx\jedi\jedi\api\__init__.py", line 157, in completions
    completions = completion.completions()
  File "C:/jedi-vim\pythonx\jedi\jedi\api\completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "C:/jedi-vim\pythonx\jedi\jedi\api\completion.py", line 198, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "C:/jedi-vim\pythonx\jedi\jedi\api\completion.py", line 233, in _trailer_completions
    contexts = evaluate_call_of_leaf(evaluation_context, previous_leaf)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\helpers.py", line 68, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\context.py", line 47, in eval_node
    return self.evaluator.eval_element(self, node)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 282, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 294, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 298, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "C:/jedi-vim\pythonx\jedi\jedi\debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 107, in wrapper
    return func(evaluator, context, *args, **kwargs)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 307, in _eval_element_not_cached
    types = self.eval_atom(context, element)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 378, in eval_atom
    search_global=True
  File "C:/jedi-vim\pythonx\jedi\jedi\_compatibility.py", line 212, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\context.py", line 63, in py__getattribute__
    analysis_errors)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 159, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "C:/jedi-vim\pythonx\jedi\jedi\debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\finder.py", line 68, in find
    types = self._names_to_types(names, attribute_lookup)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\finder.py", line 163, in _names_to_types
    types = unite(name.infer() for name in names)
  File "C:/jedi-vim\pythonx\jedi\jedi\common.py", line 105, in unite
    return set(typ for types in iterable for typ in types)
  File "C:/jedi-vim\pythonx\jedi\jedi\common.py", line 105, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\finder.py", line 163, in <genexpr>
    types = unite(name.infer() for name in names)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\filters.py", line 97, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\finder.py", line 231, in _name_to_types
    types = imports.infer_import(context, tree_name)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\imports.py", line 60, in infer_import
    types = importer.follow()
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\imports.py", line 274, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\imports.py", line 381, in _do_import
    module = _load_module(self._evaluator, module_path, code, sys_path, parent_module)
  File "C:/jedi-vim\pythonx\jedi\jedi\evaluate\imports.py", line 486, in _load_module
    cache_path=settings.cache_directory)
  File "C:/jedi-vim\pythonx\parso\parso\grammar.py", line 77, in parse
    return self._parse(code=code, **kwargs)
  File "C:/jedi-vim\pythonx\parso\parso\grammar.py", line 109, in _parse
    code = python_bytes_to_unicode(code)
  File "C:/jedi-vim\pythonx\parso\parso\utils.py", line 89, in python_bytes_to_unicode
    return unicode(source, encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 17: invalid continuation byte
```

**Comment by davidhalter** [comment]
I have fixed #1003 and I'm 99% sure that this one is the exact same thing. You may test it on the master branch :)
